// Code generated by scripts/gen_device_types.py; DO NOT EDIT.
package devices

import (
	"encoding/json"
	"fmt"

	"github.com/tyandl/homelink/pkg/yolink/controller"
	"github.com/tyandl/homelink/pkg/yolink/types"
)

type CellularHub struct{ *controller.Device }

func init() {
	controller.RegisterDeviceFactory("CellularHub", func(device *controller.Device) controller.DeviceController {
		return &CellularHub{Device: device}
	})
}

type CellularHubGetStateResponseWifi struct {
	Enable  bool   `json:"enable"`  // Is WiFi connected
	Ssid    string `json:"ssid"`    // Current WiFi SSID
	Ip      string `json:"ip"`      // WiFi IP
	Gateway string `json:"gateway"` // WiFi gateway
	Mask    string `json:"mask"`    // WiFi subnet mask
}

func (r CellularHubGetStateResponseWifi) String() string {
	return fmt.Sprintf("{Enable:%v Ssid:%v Ip:%v Gateway:%v Mask:%v}", r.Enable, r.Ssid, r.Ip, r.Gateway, r.Mask)
}

type CellularHubGetStateResponseEth struct {
	Enable  bool   `json:"enable"`  // Is Ethernet connected
	Ip      string `json:"ip"`      // Ethernet IP
	Gateway string `json:"gateway"` // Ethernet gateway
	Mask    string `json:"mask"`    // Ethernet subnet mask
}

func (r CellularHubGetStateResponseEth) String() string {
	return fmt.Sprintf("{Enable:%v Ip:%v Gateway:%v Mask:%v}", r.Enable, r.Ip, r.Gateway, r.Mask)
}

type CellularHubGetStateResponseCellularModule struct {
	Enable bool    `json:"enable"`          // Is cellular module running
	Mfr    *string `json:"mfr,omitempty"`   // Cellular module manufacturer
	Model  *string `json:"model,omitempty"` // Cellular module model
	Ver    *string `json:"ver,omitempty"`   // Cellular module firmware version
	Imei   *string `json:"imei,omitempty"`  // Cellular module IMEI
}

func (r CellularHubGetStateResponseCellularModule) String() string {
	var ptr0 any = "<nil>"
	if r.Mfr != nil {
		ptr0 = fmt.Sprint(*r.Mfr)
	}
	var ptr1 any = "<nil>"
	if r.Model != nil {
		ptr1 = fmt.Sprint(*r.Model)
	}
	var ptr2 any = "<nil>"
	if r.Ver != nil {
		ptr2 = fmt.Sprint(*r.Ver)
	}
	var ptr3 any = "<nil>"
	if r.Imei != nil {
		ptr3 = fmt.Sprint(*r.Imei)
	}
	return fmt.Sprintf("{Enable:%v Mfr:%v Model:%v Ver:%v Imei:%v}", r.Enable, ptr0, ptr1, ptr2, ptr3)
}

type CellularHubGetStateResponseCellular struct {
	Enable       bool                                      `json:"enable"` // Is cellular network connected
	Module       CellularHubGetStateResponseCellularModule `json:"module"`
	Iccid        string                                    `json:"iccid"`        // Current SIM card ICCID; empty = no SIM
	Apn          string                                    `json:"apn"`          // Current APN; empty = no APN used
	RegState     types.CellularRegState                    `json:"regState"`     // Registration state ['none','registered','registering','denied','roaming','error']
	RegStateCode int                                       `json:"regStateCode"` // Raw registration code from cellular module
	Rssi         int                                       `json:"rssi"`         // RSSI; 99=unknown or undetectable
}

func (r CellularHubGetStateResponseCellular) String() string {
	return fmt.Sprintf("{Enable:%v Module:%v Iccid:%v Apn:%v RegState:%v RegStateCode:%v Rssi:%v}", r.Enable, r.Module, r.Iccid, r.Apn, r.RegState, r.RegStateCode, r.Rssi)
}

type CellularHubGetStateResponseOtherPower struct {
	Dc           bool               `json:"dc"`           // DC power supply connected
	Battery      bool               `json:"battery"`      // Battery connected
	BatteryState types.BatteryState `json:"batteryState"` // Battery state: 0=none,1=powering,2=charging,3=standby,4=maintenance
}

func (r CellularHubGetStateResponseOtherPower) String() string {
	return fmt.Sprintf("{Dc:%v Battery:%v BatteryState:%v}", r.Dc, r.Battery, r.BatteryState)
}

type CellularHubGetStateResponseOther struct {
	Power CellularHubGetStateResponseOtherPower `json:"power"`
}

func (r CellularHubGetStateResponseOther) String() string {
	return fmt.Sprintf("{Power:%v}", r.Power)
}

type CellularHubGetStateResponse struct {
	Version  string                              `json:"version"` // Hub version
	Wifi     CellularHubGetStateResponseWifi     `json:"wifi"`
	Eth      CellularHubGetStateResponseEth      `json:"eth"`
	Cellular CellularHubGetStateResponseCellular `json:"cellular"`
	Other    CellularHubGetStateResponseOther    `json:"other"`
}

func (r CellularHubGetStateResponse) String() string {
	return fmt.Sprintf("{Version:%v Wifi:%v Eth:%v Cellular:%v Other:%v}", r.Version, r.Wifi, r.Eth, r.Cellular, r.Other)
}

// GetState Get Hub's State including WiFi, Ethernet, and cellular network info
func (device *CellularHub) GetState() (CellularHubGetStateResponse, error) {
	var response CellularHubGetStateResponse
	err := device.Call("CellularHub.getState", nil, &response)
	return response, err
}

func (device *CellularHub) GetStateAsync() <-chan controller.AsyncResult[CellularHubGetStateResponse] {
	return controller.DecodeAsync[CellularHubGetStateResponse](device.CallAsync("CellularHub.getState", nil))
}

type CellularHubScanWiFiListResponseWifiListItem struct {
	Ssid       string               `json:"ssid"`       // AP ESSID
	Rssi       string               `json:"rssi"`       // AP RSSI
	Encryption types.WiFiEncryption `json:"encryption"` // Encryption type ['none','wep','psk','psk2','psk-mixed','unknown']
}

func (r CellularHubScanWiFiListResponseWifiListItem) String() string {
	return fmt.Sprintf("{Ssid:%v Rssi:%v Encryption:%v}", r.Ssid, r.Rssi, r.Encryption)
}

type CellularHubScanWiFiListResponse struct {
	WifiList []CellularHubScanWiFiListResponseWifiListItem `json:"wifiList"`
}

func (r CellularHubScanWiFiListResponse) String() string {
	return fmt.Sprintf("{WifiList:%v}", r.WifiList)
}

// ScanWiFiList Search for available WiFi APs. Use a timeout >8 seconds when calling.
func (device *CellularHub) ScanWiFiList() (CellularHubScanWiFiListResponse, error) {
	var response CellularHubScanWiFiListResponse
	err := device.Call("CellularHub.scanWiFiList", nil, &response)
	return response, err
}

func (device *CellularHub) ScanWiFiListAsync() <-chan controller.AsyncResult[CellularHubScanWiFiListResponse] {
	return controller.DecodeAsync[CellularHubScanWiFiListResponse](device.CallAsync("CellularHub.scanWiFiList", nil))
}

type CellularHubSetWiFiParams struct {
	Ssid       string `json:"ssid"`       // WiFi SSID
	Password   string `json:"password"`   // WiFi password
	Encryption string `json:"encryption"` // Encryption type
}

func (r CellularHubSetWiFiParams) String() string {
	return fmt.Sprintf("{Ssid:%v Password:%v Encryption:%v}", r.Ssid, r.Password, r.Encryption)
}

// SetWiFi Set hub's WiFi info (when online)
func (device *CellularHub) SetWiFi(params CellularHubSetWiFiParams) error {
	return device.Call("CellularHub.setWiFi", params, nil)
}

func (device *CellularHub) SetWiFiAsync(params CellularHubSetWiFiParams) <-chan controller.AsyncResult[any] {
	return controller.DecodeAsync[any](device.CallAsync("CellularHub.setWiFi", params))
}

// ResetCellular Reset cellular module
func (device *CellularHub) ResetCellular() error {
	return device.Call("CellularHub.resetCellular", nil, nil)
}

func (device *CellularHub) ResetCellularAsync() <-chan controller.AsyncResult[any] {
	return controller.DecodeAsync[any](device.CallAsync("CellularHub.resetCellular", nil))
}

type CellularHubReportResponseWifi struct {
	Enable  bool   `json:"enable"`  // Is WiFi connected
	Ssid    string `json:"ssid"`    // Current WiFi SSID
	Ip      string `json:"ip"`      // WiFi IP
	Gateway string `json:"gateway"` // WiFi gateway
	Mask    string `json:"mask"`    // WiFi subnet mask
}

func (r CellularHubReportResponseWifi) String() string {
	return fmt.Sprintf("{Enable:%v Ssid:%v Ip:%v Gateway:%v Mask:%v}", r.Enable, r.Ssid, r.Ip, r.Gateway, r.Mask)
}

type CellularHubReportResponseEth struct {
	Enable  bool   `json:"enable"`  // Is Ethernet connected
	Ip      string `json:"ip"`      // Ethernet IP
	Gateway string `json:"gateway"` // Ethernet gateway
	Mask    string `json:"mask"`    // Ethernet subnet mask
}

func (r CellularHubReportResponseEth) String() string {
	return fmt.Sprintf("{Enable:%v Ip:%v Gateway:%v Mask:%v}", r.Enable, r.Ip, r.Gateway, r.Mask)
}

type CellularHubReportResponseCellularModule struct {
	Enable bool    `json:"enable"`          // Is cellular module running
	Mfr    *string `json:"mfr,omitempty"`   // Cellular module manufacturer
	Model  *string `json:"model,omitempty"` // Cellular module model
	Ver    *string `json:"ver,omitempty"`   // Cellular module firmware version
	Imei   *string `json:"imei,omitempty"`  // Cellular module IMEI
}

func (r CellularHubReportResponseCellularModule) String() string {
	var ptr0 any = "<nil>"
	if r.Mfr != nil {
		ptr0 = fmt.Sprint(*r.Mfr)
	}
	var ptr1 any = "<nil>"
	if r.Model != nil {
		ptr1 = fmt.Sprint(*r.Model)
	}
	var ptr2 any = "<nil>"
	if r.Ver != nil {
		ptr2 = fmt.Sprint(*r.Ver)
	}
	var ptr3 any = "<nil>"
	if r.Imei != nil {
		ptr3 = fmt.Sprint(*r.Imei)
	}
	return fmt.Sprintf("{Enable:%v Mfr:%v Model:%v Ver:%v Imei:%v}", r.Enable, ptr0, ptr1, ptr2, ptr3)
}

type CellularHubReportResponseCellular struct {
	Enable       bool                                    `json:"enable"` // Is cellular network connected
	Module       CellularHubReportResponseCellularModule `json:"module"`
	Iccid        string                                  `json:"iccid"`        // Current SIM card ICCID; empty = no SIM
	Apn          string                                  `json:"apn"`          // Current APN; empty = no APN used
	RegState     types.CellularRegState                  `json:"regState"`     // Registration state ['none','registered','registering','denied','roaming','error']
	RegStateCode int                                     `json:"regStateCode"` // Raw registration code from cellular module
	Rssi         int                                     `json:"rssi"`         // RSSI; 99=unknown or undetectable
}

func (r CellularHubReportResponseCellular) String() string {
	return fmt.Sprintf("{Enable:%v Module:%v Iccid:%v Apn:%v RegState:%v RegStateCode:%v Rssi:%v}", r.Enable, r.Module, r.Iccid, r.Apn, r.RegState, r.RegStateCode, r.Rssi)
}

type CellularHubReportResponseOtherPower struct {
	Dc           bool               `json:"dc"`           // DC power supply connected
	Battery      bool               `json:"battery"`      // Battery connected
	BatteryState types.BatteryState `json:"batteryState"` // Battery state: 0=none,1=powering,2=charging,3=standby,4=maintenance
}

func (r CellularHubReportResponseOtherPower) String() string {
	return fmt.Sprintf("{Dc:%v Battery:%v BatteryState:%v}", r.Dc, r.Battery, r.BatteryState)
}

type CellularHubReportResponseOther struct {
	Power CellularHubReportResponseOtherPower `json:"power"`
}

func (r CellularHubReportResponseOther) String() string {
	return fmt.Sprintf("{Power:%v}", r.Power)
}

type CellularHubReportResponse struct {
	Version  string                            `json:"version"` // Hub version
	Wifi     CellularHubReportResponseWifi     `json:"wifi"`
	Eth      CellularHubReportResponseEth      `json:"eth"`
	Cellular CellularHubReportResponseCellular `json:"cellular"`
	Other    CellularHubReportResponseOther    `json:"other"`
	LoraInfo *types.LoraInfo                   `json:"loraInfo,omitempty"`
}

func (r CellularHubReportResponse) String() string {
	var ptr0 any = "<nil>"
	if r.LoraInfo != nil {
		ptr0 = fmt.Sprint(*r.LoraInfo)
	}
	return fmt.Sprintf("{Version:%v Wifi:%v Eth:%v Cellular:%v Other:%v LoraInfo:%v}", r.Version, r.Wifi, r.Eth, r.Cellular, r.Other, ptr0)
}

type CellularHubAlertResponseWifi struct {
	Enable  bool   `json:"enable"`  // Is WiFi connected
	Ssid    string `json:"ssid"`    // Current WiFi SSID
	Ip      string `json:"ip"`      // WiFi IP
	Gateway string `json:"gateway"` // WiFi gateway
	Mask    string `json:"mask"`    // WiFi subnet mask
}

func (r CellularHubAlertResponseWifi) String() string {
	return fmt.Sprintf("{Enable:%v Ssid:%v Ip:%v Gateway:%v Mask:%v}", r.Enable, r.Ssid, r.Ip, r.Gateway, r.Mask)
}

type CellularHubAlertResponseEth struct {
	Enable  bool   `json:"enable"`  // Is Ethernet connected
	Ip      string `json:"ip"`      // Ethernet IP
	Gateway string `json:"gateway"` // Ethernet gateway
	Mask    string `json:"mask"`    // Ethernet subnet mask
}

func (r CellularHubAlertResponseEth) String() string {
	return fmt.Sprintf("{Enable:%v Ip:%v Gateway:%v Mask:%v}", r.Enable, r.Ip, r.Gateway, r.Mask)
}

type CellularHubAlertResponseCellularModule struct {
	Enable bool    `json:"enable"`          // Is cellular module running
	Mfr    *string `json:"mfr,omitempty"`   // Cellular module manufacturer
	Model  *string `json:"model,omitempty"` // Cellular module model
	Ver    *string `json:"ver,omitempty"`   // Cellular module firmware version
	Imei   *string `json:"imei,omitempty"`  // Cellular module IMEI
}

func (r CellularHubAlertResponseCellularModule) String() string {
	var ptr0 any = "<nil>"
	if r.Mfr != nil {
		ptr0 = fmt.Sprint(*r.Mfr)
	}
	var ptr1 any = "<nil>"
	if r.Model != nil {
		ptr1 = fmt.Sprint(*r.Model)
	}
	var ptr2 any = "<nil>"
	if r.Ver != nil {
		ptr2 = fmt.Sprint(*r.Ver)
	}
	var ptr3 any = "<nil>"
	if r.Imei != nil {
		ptr3 = fmt.Sprint(*r.Imei)
	}
	return fmt.Sprintf("{Enable:%v Mfr:%v Model:%v Ver:%v Imei:%v}", r.Enable, ptr0, ptr1, ptr2, ptr3)
}

type CellularHubAlertResponseCellular struct {
	Enable       bool                                   `json:"enable"` // Is cellular network connected
	Module       CellularHubAlertResponseCellularModule `json:"module"`
	Iccid        string                                 `json:"iccid"`        // Current SIM card ICCID; empty = no SIM
	Apn          string                                 `json:"apn"`          // Current APN; empty = no APN used
	RegState     types.CellularRegState                 `json:"regState"`     // Registration state ['none','registered','registering','denied','roaming','error']
	RegStateCode int                                    `json:"regStateCode"` // Raw registration code from cellular module
	Rssi         int                                    `json:"rssi"`         // RSSI; 99=unknown or undetectable
}

func (r CellularHubAlertResponseCellular) String() string {
	return fmt.Sprintf("{Enable:%v Module:%v Iccid:%v Apn:%v RegState:%v RegStateCode:%v Rssi:%v}", r.Enable, r.Module, r.Iccid, r.Apn, r.RegState, r.RegStateCode, r.Rssi)
}

type CellularHubAlertResponseOtherPower struct {
	Dc           bool               `json:"dc"`           // DC power supply connected
	Battery      bool               `json:"battery"`      // Battery connected
	BatteryState types.BatteryState `json:"batteryState"` // Battery state: 0=none,1=powering,2=charging,3=standby,4=maintenance
}

func (r CellularHubAlertResponseOtherPower) String() string {
	return fmt.Sprintf("{Dc:%v Battery:%v BatteryState:%v}", r.Dc, r.Battery, r.BatteryState)
}

type CellularHubAlertResponseOther struct {
	Power CellularHubAlertResponseOtherPower `json:"power"`
}

func (r CellularHubAlertResponseOther) String() string {
	return fmt.Sprintf("{Power:%v}", r.Power)
}

type CellularHubAlertResponse struct {
	Version        string                           `json:"version"` // Hub version
	Wifi           CellularHubAlertResponseWifi     `json:"wifi"`
	Eth            CellularHubAlertResponseEth      `json:"eth"`
	Cellular       CellularHubAlertResponseCellular `json:"cellular"`
	Other          CellularHubAlertResponseOther    `json:"other"`
	LoraInfo       *types.LoraInfo                  `json:"loraInfo,omitempty"`
	StateChangedAt *types.Timestamp                 `json:"stateChangedAt,omitempty"`
}

func (r CellularHubAlertResponse) String() string {
	var ptr0 any = "<nil>"
	if r.LoraInfo != nil {
		ptr0 = fmt.Sprint(*r.LoraInfo)
	}
	var ptr1 any = "<nil>"
	if r.StateChangedAt != nil {
		ptr1 = fmt.Sprint(*r.StateChangedAt)
	}
	return fmt.Sprintf("{Version:%v Wifi:%v Eth:%v Cellular:%v Other:%v LoraInfo:%v StateChangedAt:%v}", r.Version, r.Wifi, r.Eth, r.Cellular, r.Other, ptr0, ptr1)
}

func (device *CellularHub) ParseEvent(message controller.MqttMessage) (controller.Report, bool) {
	report, ok := device.Device.ParseEvent(message) // base impl decodes event + raw data
	if !ok {
		return report, false
	}
	report.Device = device                        // attribute the report to this concrete device
	data := report.Data.(controller.Unknown).Json // raw payload, re-typed below
	switch report.Event {
	case "CellularHub.getState":
		var response CellularHubGetStateResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "CellularHub.scanWiFiList":
		var response CellularHubScanWiFiListResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "CellularHub.Report":
		var response CellularHubReportResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "CellularHub.Alert":
		var response CellularHubAlertResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	}
	return report, true
}
