// Code generated by scripts/gen_device_types.py; DO NOT EDIT.
package devices

import (
	"encoding/json"
	"fmt"
	"time"

	"github.com/tyandl/homelink/pkg/yolink/controller"
	"github.com/tyandl/homelink/pkg/yolink/types"
)

type COSmokeSensor struct{ *controller.Device }

func init() {
	controller.RegisterDeviceFactory("COSmokeSensor", func(device *controller.Device) controller.DeviceController {
		return &COSmokeSensor{Device: device}
	})
}

type COSmokeSensorGetStateResponseStateState struct {
	Unexpected    bool `json:"unexpected"`    // Unexpected error detected
	SLowBattery   bool `json:"sLowBattery"`   // Battery of sensor is low
	SmokeAlarm    bool `json:"smokeAlarm"`    // Smoke detected
	GasAlarm      bool `json:"gasAlarm"`      // CO detected
	HighTempAlarm bool `json:"highTempAlarm"` // High temperature (over 57C) detected
	Silence       bool `json:"silence"`       // Reserve
}

func (r COSmokeSensorGetStateResponseStateState) String() string {
	return fmt.Sprintf("{Unexpected:%v SLowBattery:%v SmokeAlarm:%v GasAlarm:%v HighTempAlarm:%v Silence:%v}", r.Unexpected, r.SLowBattery, r.SmokeAlarm, r.GasAlarm, r.HighTempAlarm, r.Silence)
}

type COSmokeSensorGetStateResponseStateMetadata struct {
	Inspect *bool `json:"inspect,omitempty"` // Self-check result
}

func (r COSmokeSensorGetStateResponseStateMetadata) String() string {
	var ptr0 any = "<nil>"
	if r.Inspect != nil {
		ptr0 = fmt.Sprint(*r.Inspect)
	}
	return fmt.Sprintf("{Inspect:%v}", ptr0)
}

type COSmokeSensorGetStateResponseStateSche struct {
	Type types.ScheduleType `json:"type"` // Schedule type ['disable','weekly','monthly']
	Day  int                `json:"day"`  // Active day of schedule
	Time string             `json:"time"` // Time of schedule, HH:MM
}

func (r COSmokeSensorGetStateResponseStateSche) String() string {
	return fmt.Sprintf("{Type:%v Day:%v Time:%v}", r.Type, r.Day, r.Time)
}

type COSmokeSensorGetStateResponseState struct {
	Online         bool                                       `json:"online"` // Is device online
	State          COSmokeSensorGetStateResponseStateState    `json:"state"`
	Battery        types.BatteryLevel                         `json:"battery"`            // Base battery level 0-4
	Interval       *int                                       `json:"interval,omitempty"` // Interval of Continuous Alert
	Metadata       COSmokeSensorGetStateResponseStateMetadata `json:"metadata"`
	DevTemperature int                                        `json:"devTemperature"` // Current temperature
	Sche           COSmokeSensorGetStateResponseStateSche     `json:"sche"`
	Version        string                                     `json:"version"` // Firmware version
}

func (r COSmokeSensorGetStateResponseState) String() string {
	var ptr0 any = "<nil>"
	if r.Interval != nil {
		ptr0 = fmt.Sprint(*r.Interval)
	}
	return fmt.Sprintf("{Online:%v State:%v Battery:%v Interval:%v Metadata:%v DevTemperature:%v Sche:%v Version:%v}", r.Online, r.State, r.Battery, ptr0, r.Metadata, r.DevTemperature, r.Sche, r.Version)
}

type COSmokeSensorGetStateResponse struct {
	State    COSmokeSensorGetStateResponseState `json:"state"`
	ReportAt time.Time                          `json:"reportAt"` // Report time
	DeviceId string                             `json:"deviceId"` // Device EUI
}

func (r COSmokeSensorGetStateResponse) String() string {
	return fmt.Sprintf("{State:%v ReportAt:%v DeviceId:%v}", r.State, r.ReportAt, r.DeviceId)
}

// GetState Get CO & Smoke Sensor's State
func (device *COSmokeSensor) GetState() (COSmokeSensorGetStateResponse, error) {
	var response COSmokeSensorGetStateResponse
	err := device.Call("COSmokeSensor.getState", nil, &response)
	return response, err
}

func (device *COSmokeSensor) GetStateAsync() <-chan controller.AsyncResult[COSmokeSensorGetStateResponse] {
	return controller.DecodeAsync[COSmokeSensorGetStateResponse](device.CallAsync("COSmokeSensor.getState", nil))
}

type COSmokeSensorSetStateParams struct {
	Inspect bool `json:"inspect"` // Start self-checking
}

func (r COSmokeSensorSetStateParams) String() string {
	return fmt.Sprintf("{Inspect:%v}", r.Inspect)
}

// SetState Trigger device self-checking
func (device *COSmokeSensor) SetState(params COSmokeSensorSetStateParams) error {
	return device.Call("COSmokeSensor.setState", params, nil)
}

func (device *COSmokeSensor) SetStateAsync(params COSmokeSensorSetStateParams) <-chan controller.AsyncResult[any] {
	return controller.DecodeAsync[any](device.CallAsync("COSmokeSensor.setState", params))
}

type COSmokeSensorSetScheduleParams struct {
	Type types.ScheduleType `json:"type"` // ['disable','weekly','monthly']
	Day  int                `json:"day"`  // Day of schedule
	Time string             `json:"time"` // Time HH:mm
}

func (r COSmokeSensorSetScheduleParams) String() string {
	return fmt.Sprintf("{Type:%v Day:%v Time:%v}", r.Type, r.Day, r.Time)
}

// SetSchedule Set the scheduled self-checking
func (device *COSmokeSensor) SetSchedule(params COSmokeSensorSetScheduleParams) error {
	return device.Call("COSmokeSensor.setSchedule", params, nil)
}

func (device *COSmokeSensor) SetScheduleAsync(params COSmokeSensorSetScheduleParams) <-chan controller.AsyncResult[any] {
	return controller.DecodeAsync[any](device.CallAsync("COSmokeSensor.setSchedule", params))
}

type COSmokeSensorReportResponseState struct {
	Unexpected    bool `json:"unexpected"`    // Unexpected error detected
	SLowBattery   bool `json:"sLowBattery"`   // Battery of sensor is low
	SmokeAlarm    bool `json:"smokeAlarm"`    // Smoke detected
	GasAlarm      bool `json:"gasAlarm"`      // CO detected
	HighTempAlarm bool `json:"highTempAlarm"` // High temperature (over 57C) detected
	Silence       bool `json:"silence"`       // Reserve
}

func (r COSmokeSensorReportResponseState) String() string {
	return fmt.Sprintf("{Unexpected:%v SLowBattery:%v SmokeAlarm:%v GasAlarm:%v HighTempAlarm:%v Silence:%v}", r.Unexpected, r.SLowBattery, r.SmokeAlarm, r.GasAlarm, r.HighTempAlarm, r.Silence)
}

type COSmokeSensorReportResponseMetadata struct {
	Inspect *bool `json:"inspect,omitempty"` // Self-check result
}

func (r COSmokeSensorReportResponseMetadata) String() string {
	var ptr0 any = "<nil>"
	if r.Inspect != nil {
		ptr0 = fmt.Sprint(*r.Inspect)
	}
	return fmt.Sprintf("{Inspect:%v}", ptr0)
}

type COSmokeSensorReportResponseSche struct {
	Type types.ScheduleType `json:"type"` // Schedule type ['disable','weekly','monthly']
	Day  int                `json:"day"`  // Active day of schedule
	Time string             `json:"time"` // Time of schedule, HH:MM
}

func (r COSmokeSensorReportResponseSche) String() string {
	return fmt.Sprintf("{Type:%v Day:%v Time:%v}", r.Type, r.Day, r.Time)
}

type COSmokeSensorReportResponse struct {
	Online         bool                                `json:"online"` // Is device online
	State          COSmokeSensorReportResponseState    `json:"state"`
	Battery        types.BatteryLevel                  `json:"battery"`            // Base battery level 0-4
	Interval       *int                                `json:"interval,omitempty"` // Interval of Continuous Alert
	Metadata       COSmokeSensorReportResponseMetadata `json:"metadata"`
	DevTemperature int                                 `json:"devTemperature"` // Current temperature
	Sche           COSmokeSensorReportResponseSche     `json:"sche"`
	Version        string                              `json:"version"` // Firmware version
	LoraInfo       *types.LoraInfo                     `json:"loraInfo,omitempty"`
}

func (r COSmokeSensorReportResponse) String() string {
	var ptr0 any = "<nil>"
	if r.Interval != nil {
		ptr0 = fmt.Sprint(*r.Interval)
	}
	var ptr1 any = "<nil>"
	if r.LoraInfo != nil {
		ptr1 = fmt.Sprint(*r.LoraInfo)
	}
	return fmt.Sprintf("{Online:%v State:%v Battery:%v Interval:%v Metadata:%v DevTemperature:%v Sche:%v Version:%v LoraInfo:%v}", r.Online, r.State, r.Battery, ptr0, r.Metadata, r.DevTemperature, r.Sche, r.Version, ptr1)
}

type COSmokeSensorAlertResponseState struct {
	Unexpected    bool `json:"unexpected"`    // Unexpected error detected
	SLowBattery   bool `json:"sLowBattery"`   // Battery of sensor is low
	SmokeAlarm    bool `json:"smokeAlarm"`    // Smoke detected
	GasAlarm      bool `json:"gasAlarm"`      // CO detected
	HighTempAlarm bool `json:"highTempAlarm"` // High temperature (over 57C) detected
	Silence       bool `json:"silence"`       // Reserve
}

func (r COSmokeSensorAlertResponseState) String() string {
	return fmt.Sprintf("{Unexpected:%v SLowBattery:%v SmokeAlarm:%v GasAlarm:%v HighTempAlarm:%v Silence:%v}", r.Unexpected, r.SLowBattery, r.SmokeAlarm, r.GasAlarm, r.HighTempAlarm, r.Silence)
}

type COSmokeSensorAlertResponseMetadata struct {
	Inspect *bool `json:"inspect,omitempty"` // Self-check result
}

func (r COSmokeSensorAlertResponseMetadata) String() string {
	var ptr0 any = "<nil>"
	if r.Inspect != nil {
		ptr0 = fmt.Sprint(*r.Inspect)
	}
	return fmt.Sprintf("{Inspect:%v}", ptr0)
}

type COSmokeSensorAlertResponseSche struct {
	Type types.ScheduleType `json:"type"` // Schedule type ['disable','weekly','monthly']
	Day  int                `json:"day"`  // Active day of schedule
	Time string             `json:"time"` // Time of schedule, HH:MM
}

func (r COSmokeSensorAlertResponseSche) String() string {
	return fmt.Sprintf("{Type:%v Day:%v Time:%v}", r.Type, r.Day, r.Time)
}

type COSmokeSensorAlertResponse struct {
	Online         bool                               `json:"online"` // Is device online
	State          COSmokeSensorAlertResponseState    `json:"state"`
	Battery        types.BatteryLevel                 `json:"battery"`            // Base battery level 0-4
	Interval       *int                               `json:"interval,omitempty"` // Interval of Continuous Alert
	Metadata       COSmokeSensorAlertResponseMetadata `json:"metadata"`
	DevTemperature int                                `json:"devTemperature"` // Current temperature
	Sche           COSmokeSensorAlertResponseSche     `json:"sche"`
	Version        string                             `json:"version"` // Firmware version
	LoraInfo       *types.LoraInfo                    `json:"loraInfo,omitempty"`
	StateChangedAt *types.Timestamp                   `json:"stateChangedAt,omitempty"`
}

func (r COSmokeSensorAlertResponse) String() string {
	var ptr0 any = "<nil>"
	if r.Interval != nil {
		ptr0 = fmt.Sprint(*r.Interval)
	}
	var ptr1 any = "<nil>"
	if r.LoraInfo != nil {
		ptr1 = fmt.Sprint(*r.LoraInfo)
	}
	var ptr2 any = "<nil>"
	if r.StateChangedAt != nil {
		ptr2 = fmt.Sprint(*r.StateChangedAt)
	}
	return fmt.Sprintf("{Online:%v State:%v Battery:%v Interval:%v Metadata:%v DevTemperature:%v Sche:%v Version:%v LoraInfo:%v StateChangedAt:%v}", r.Online, r.State, r.Battery, ptr0, r.Metadata, r.DevTemperature, r.Sche, r.Version, ptr1, ptr2)
}

func (device *COSmokeSensor) ParseEvent(message controller.MqttMessage) (controller.Report, bool) {
	report, ok := device.Device.ParseEvent(message) // base impl decodes event + raw data
	if !ok {
		return report, false
	}
	report.Device = device                        // attribute the report to this concrete device
	data := report.Data.(controller.Unknown).Json // raw payload, re-typed below
	switch report.Event {
	case "COSmokeSensor.getState":
		var response COSmokeSensorGetStateResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "COSmokeSensor.Report":
		var response COSmokeSensorReportResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "COSmokeSensor.Alert":
		var response COSmokeSensorAlertResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	}
	return report, true
}
