// Code generated by scripts/gen_device_types.py; DO NOT EDIT.
package devices

import "github.com/tyandl/homelink/pkg/yolink/controller"

type CSDevice struct{ *controller.Device }

func init() {
	controller.RegisterDeviceFactory("CSDevice", func(device *controller.Device) controller.DeviceController {
		return &CSDevice{Device: device}
	})
}

// Send Send data to device, wait for response (default timeout 4s)
func (device *CSDevice) Send() error {
	return device.Call("CSDevice.send", nil, nil)
}

func (device *CSDevice) SendAsync() <-chan controller.AsyncResult[any] {
	return controller.DecodeAsync[any](device.CallAsync("CSDevice.send", nil))
}

// SendNoWait Send data to device, don't wait for response
func (device *CSDevice) SendNoWait() error {
	return device.Call("CSDevice.sendNoWait", nil, nil)
}

func (device *CSDevice) SendNoWaitAsync() <-chan controller.AsyncResult[any] {
	return controller.DecodeAsync[any](device.CallAsync("CSDevice.sendNoWait", nil))
}

func (device *CSDevice) ParseEvent(message controller.MqttMessage) (controller.Report, bool) {
	report, ok := device.Device.ParseEvent(message) // base impl decodes event + raw data
	if !ok {
		return report, false
	}
	report.Device = device // attribute the report to this concrete device
	return report, true
}
