// Code generated by scripts/gen_device_types.py; DO NOT EDIT.
package devices

import (
	"encoding/json"
	"fmt"

	"github.com/tyandl/homelink/pkg/yolink/controller"
)

type Debugger struct{ *controller.Device }

func init() {
	controller.RegisterDeviceFactory("Debugger", func(device *controller.Device) controller.DeviceController {
		return &Debugger{Device: device}
	})
}

type DebuggerCreateAccessTokenParams struct {
	Scope  string `json:"scope"`  // Fixed: 'device/raw_stream'
	Expire int    `json:"expire"` // Token validity in seconds
}

func (r DebuggerCreateAccessTokenParams) String() string {
	return fmt.Sprintf("{Scope:%v Expire:%v}", r.Scope, r.Expire)
}

type DebuggerCreateAccessTokenResponseAccessToken struct {
	AccessToken string `json:"access_token"` // Access token
}

func (r DebuggerCreateAccessTokenResponseAccessToken) String() string {
	return fmt.Sprintf("{AccessToken:%v}", r.AccessToken)
}

type DebuggerCreateAccessTokenResponse struct {
	AccessToken DebuggerCreateAccessTokenResponseAccessToken `json:"access_token"`
	TokenType   string                                       `json:"token_type"` // Token type
	ExpiresIn   string                                       `json:"expires_in"` // Token expiry
	Scope       []string                                     `json:"scope"`      // Token scopes
}

func (r DebuggerCreateAccessTokenResponse) String() string {
	return fmt.Sprintf("{AccessToken:%v TokenType:%v ExpiresIn:%v Scope:%v}", r.AccessToken, r.TokenType, r.ExpiresIn, r.Scope)
}

// CreateAccessToken Create access token for device debug
func (device *Debugger) CreateAccessToken(params DebuggerCreateAccessTokenParams) (DebuggerCreateAccessTokenResponse, error) {
	var response DebuggerCreateAccessTokenResponse
	err := device.Call("Debugger.createAccessToken", params, &response)
	return response, err
}

func (device *Debugger) CreateAccessTokenAsync(params DebuggerCreateAccessTokenParams) <-chan controller.AsyncResult[DebuggerCreateAccessTokenResponse] {
	return controller.DecodeAsync[DebuggerCreateAccessTokenResponse](device.CallAsync("Debugger.createAccessToken", params))
}

func (device *Debugger) ParseEvent(message controller.MqttMessage) (controller.Report, bool) {
	report, ok := device.Device.ParseEvent(message) // base impl decodes event + raw data
	if !ok {
		return report, false
	}
	report.Device = device                        // attribute the report to this concrete device
	data := report.Data.(controller.Unknown).Json // raw payload, re-typed below
	switch report.Event {
	case "Debugger.createAccessToken":
		var response DebuggerCreateAccessTokenResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	}
	return report, true
}
