// Code generated by scripts/gen_device_types.py; DO NOT EDIT.
package devices

import (
	"encoding/json"
	"fmt"
	"time"

	"github.com/tyandl/homelink/pkg/yolink/controller"
	"github.com/tyandl/homelink/pkg/yolink/types"
)

type Dimmer struct{ *controller.Device }

func init() {
	controller.RegisterDeviceFactory("Dimmer", func(device *controller.Device) controller.DeviceController {
		return &Dimmer{Device: device}
	})
}

type DimmerGetStateResponseDelay struct {
	On  int `json:"on"`  // Remain Delay ON minutes
	Off int `json:"off"` // Remain Delay OFF minutes
}

func (r DimmerGetStateResponseDelay) String() string {
	return fmt.Sprintf("{On:%v Off:%v}", r.On, r.Off)
}

type DimmerGetStateResponse struct {
	State      types.SwitchState           `json:"state"`      // ['closed','open']
	Brightness int                         `json:"brightness"` // Brightness 1-100
	Delay      DimmerGetStateResponseDelay `json:"delay"`
	Version    string                      `json:"version"` // Firmware version
	Tz         int                         `json:"tz"`      // Timezone -12~12
}

func (r DimmerGetStateResponse) String() string {
	return fmt.Sprintf("{State:%v Brightness:%v Delay:%v Version:%v Tz:%v}", r.State, r.Brightness, r.Delay, r.Version, r.Tz)
}

// GetState Get Current State
func (device *Dimmer) GetState() (DimmerGetStateResponse, error) {
	var response DimmerGetStateResponse
	err := device.Call("Dimmer.getState", nil, &response)
	return response, err
}

func (device *Dimmer) GetStateAsync() <-chan controller.AsyncResult[DimmerGetStateResponse] {
	return controller.DecodeAsync[DimmerGetStateResponse](device.CallAsync("Dimmer.getState", nil))
}

type DimmerSetStateParams struct {
	State      types.SwitchCommand `json:"state"`                // ['close','open']
	Brightness *int                `json:"brightness,omitempty"` // Brightness 1-100
}

func (r DimmerSetStateParams) String() string {
	var ptr0 any = "<nil>"
	if r.Brightness != nil {
		ptr0 = fmt.Sprint(*r.Brightness)
	}
	return fmt.Sprintf("{State:%v Brightness:%v}", r.State, ptr0)
}

type DimmerSetStateResponse struct {
	State types.SwitchState `json:"state"` // ['closed','open']
}

func (r DimmerSetStateResponse) String() string {
	return fmt.Sprintf("{State:%v}", r.State)
}

// SetState Set Dimmer's State
func (device *Dimmer) SetState(params DimmerSetStateParams) (DimmerSetStateResponse, error) {
	var response DimmerSetStateResponse
	err := device.Call("Dimmer.setState", params, &response)
	return response, err
}

func (device *Dimmer) SetStateAsync(params DimmerSetStateParams) <-chan controller.AsyncResult[DimmerSetStateResponse] {
	return controller.DecodeAsync[DimmerSetStateResponse](device.CallAsync("Dimmer.setState", params))
}

type DimmerSetDelayParams struct {
	DelayOn  *int `json:"delayOn,omitempty"`  // Delay ON minutes; 0=cancel
	DelayOff *int `json:"delayOff,omitempty"` // Delay OFF minutes; 0=cancel
}

func (r DimmerSetDelayParams) String() string {
	var ptr0 any = "<nil>"
	if r.DelayOn != nil {
		ptr0 = fmt.Sprint(*r.DelayOn)
	}
	var ptr1 any = "<nil>"
	if r.DelayOff != nil {
		ptr1 = fmt.Sprint(*r.DelayOff)
	}
	return fmt.Sprintf("{DelayOn:%v DelayOff:%v}", ptr0, ptr1)
}

type DimmerSetDelayResponseDelay struct {
	On  int `json:"on"`  // Remain Delay ON minutes
	Off int `json:"off"` // Remain Delay OFF minutes
}

func (r DimmerSetDelayResponseDelay) String() string {
	return fmt.Sprintf("{On:%v Off:%v}", r.On, r.Off)
}

type DimmerSetDelayResponse struct {
	Delay DimmerSetDelayResponseDelay `json:"delay"`
}

func (r DimmerSetDelayResponse) String() string {
	return fmt.Sprintf("{Delay:%v}", r.Delay)
}

// SetDelay Set delay to turn on/off Dimmer
func (device *Dimmer) SetDelay(params DimmerSetDelayParams) (DimmerSetDelayResponse, error) {
	var response DimmerSetDelayResponse
	err := device.Call("Dimmer.setDelay", params, &response)
	return response, err
}

func (device *Dimmer) SetDelayAsync(params DimmerSetDelayParams) <-chan controller.AsyncResult[DimmerSetDelayResponse] {
	return controller.DecodeAsync[DimmerSetDelayResponse](device.CallAsync("Dimmer.setDelay", params))
}

type DimmerGetSchedulesResponse = []struct {
	IsValid bool    `json:"isValid"`       // Enabled/Disabled
	Index   int     `json:"index"`         // Index of record
	On      *string `json:"on,omitempty"`  // Time to turn on HH:mm
	Off     *string `json:"off,omitempty"` // Time to turn off HH:mm
	Week    int     `json:"week"`          // Weekday mask Sunday-Saturday
}

// GetSchedules Get Schedule List
func (device *Dimmer) GetSchedules() (DimmerGetSchedulesResponse, error) {
	var response DimmerGetSchedulesResponse
	err := device.Call("Dimmer.getSchedules", nil, &response)
	return response, err
}

func (device *Dimmer) GetSchedulesAsync() <-chan controller.AsyncResult[DimmerGetSchedulesResponse] {
	return controller.DecodeAsync[DimmerGetSchedulesResponse](device.CallAsync("Dimmer.getSchedules", nil))
}

type DimmerSetSchedulesParamsSchesItem struct {
	IsValid bool   `json:"isValid"` // Enabled/Disabled
	Index   int    `json:"index"`   // Index 0-5
	On      string `json:"on"`      // Time to turn on HH:mm
	Off     string `json:"off"`     // Time to turn off HH:mm
	Week    int    `json:"week"`    // Weekday mask
}

func (r DimmerSetSchedulesParamsSchesItem) String() string {
	return fmt.Sprintf("{IsValid:%v Index:%v On:%v Off:%v Week:%v}", r.IsValid, r.Index, r.On, r.Off, r.Week)
}

type DimmerSetSchedulesParams struct {
	Sches []DimmerSetSchedulesParamsSchesItem `json:"sches"`
}

func (r DimmerSetSchedulesParams) String() string {
	return fmt.Sprintf("{Sches:%v}", r.Sches)
}

type DimmerSetSchedulesResponse = []struct {
	IsValid bool    `json:"isValid"`       // Enabled/Disabled
	Index   int     `json:"index"`         // Index of record
	On      *string `json:"on,omitempty"`  // Time to turn on HH:mm
	Off     *string `json:"off,omitempty"` // Time to turn off HH:mm
	Week    int     `json:"week"`          // Weekday mask Sunday-Saturday
}

// SetSchedules Set Schedule
func (device *Dimmer) SetSchedules(params DimmerSetSchedulesParams) (DimmerSetSchedulesResponse, error) {
	var response DimmerSetSchedulesResponse
	err := device.Call("Dimmer.setSchedules", params, &response)
	return response, err
}

func (device *Dimmer) SetSchedulesAsync(params DimmerSetSchedulesParams) <-chan controller.AsyncResult[DimmerSetSchedulesResponse] {
	return controller.DecodeAsync[DimmerSetSchedulesResponse](device.CallAsync("Dimmer.setSchedules", params))
}

type DimmerGetVersionResponseNewVersion struct {
	VersionId   *string `json:"versionId,omitempty"`   // Newest version ID
	VersionCode *string `json:"versionCode,omitempty"` // Newest version code
	FileSize    *string `json:"fileSize,omitempty"`    // Newest version file size
}

func (r DimmerGetVersionResponseNewVersion) String() string {
	var ptr0 any = "<nil>"
	if r.VersionId != nil {
		ptr0 = fmt.Sprint(*r.VersionId)
	}
	var ptr1 any = "<nil>"
	if r.VersionCode != nil {
		ptr1 = fmt.Sprint(*r.VersionCode)
	}
	var ptr2 any = "<nil>"
	if r.FileSize != nil {
		ptr2 = fmt.Sprint(*r.FileSize)
	}
	return fmt.Sprintf("{VersionId:%v VersionCode:%v FileSize:%v}", ptr0, ptr1, ptr2)
}

type DimmerGetVersionResponse struct {
	Version    string                             `json:"version"` // Current version
	NewVersion DimmerGetVersionResponseNewVersion `json:"newVersion"`
}

func (r DimmerGetVersionResponse) String() string {
	return fmt.Sprintf("{Version:%v NewVersion:%v}", r.Version, r.NewVersion)
}

// GetVersion Get firmware info
func (device *Dimmer) GetVersion() (DimmerGetVersionResponse, error) {
	var response DimmerGetVersionResponse
	err := device.Call("Dimmer.getVersion", nil, &response)
	return response, err
}

func (device *Dimmer) GetVersionAsync() <-chan controller.AsyncResult[DimmerGetVersionResponse] {
	return controller.DecodeAsync[DimmerGetVersionResponse](device.CallAsync("Dimmer.getVersion", nil))
}

type DimmerSetDeviceAttributesParamsLed struct {
	Status *string `json:"status,omitempty"` // Status LED ['on','off']
	Level  *string `json:"level,omitempty"`  // Brightness LED ['on','off']
}

func (r DimmerSetDeviceAttributesParamsLed) String() string {
	var ptr0 any = "<nil>"
	if r.Status != nil {
		ptr0 = fmt.Sprint(*r.Status)
	}
	var ptr1 any = "<nil>"
	if r.Level != nil {
		ptr1 = fmt.Sprint(*r.Level)
	}
	return fmt.Sprintf("{Status:%v Level:%v}", ptr0, ptr1)
}

type DimmerSetDeviceAttributesParamsGradient struct {
	On  *int `json:"on,omitempty"`  // Gentle on seconds 0-20
	Off *int `json:"off,omitempty"` // Gentle off seconds 0-20
}

func (r DimmerSetDeviceAttributesParamsGradient) String() string {
	var ptr0 any = "<nil>"
	if r.On != nil {
		ptr0 = fmt.Sprint(*r.On)
	}
	var ptr1 any = "<nil>"
	if r.Off != nil {
		ptr1 = fmt.Sprint(*r.Off)
	}
	return fmt.Sprintf("{On:%v Off:%v}", ptr0, ptr1)
}

type DimmerSetDeviceAttributesParams struct {
	Led             DimmerSetDeviceAttributesParamsLed      `json:"led"`
	Gradient        DimmerSetDeviceAttributesParamsGradient `json:"gradient"`
	Calibration     *int                                    `json:"calibration,omitempty"`     // Dimming calibration low 0-99
	CalibrationHigh *int                                    `json:"calibrationHigh,omitempty"` // Dimming calibration high 0-99
}

func (r DimmerSetDeviceAttributesParams) String() string {
	var ptr0 any = "<nil>"
	if r.Calibration != nil {
		ptr0 = fmt.Sprint(*r.Calibration)
	}
	var ptr1 any = "<nil>"
	if r.CalibrationHigh != nil {
		ptr1 = fmt.Sprint(*r.CalibrationHigh)
	}
	return fmt.Sprintf("{Led:%v Gradient:%v Calibration:%v CalibrationHigh:%v}", r.Led, r.Gradient, ptr0, ptr1)
}

type DimmerSetDeviceAttributesResponseDeviceAttributesLed struct {
	Status string `json:"status"`
	Level  string `json:"level"`
}

func (r DimmerSetDeviceAttributesResponseDeviceAttributesLed) String() string {
	return fmt.Sprintf("{Status:%v Level:%v}", r.Status, r.Level)
}

type DimmerSetDeviceAttributesResponseDeviceAttributesGradient struct {
	On  int `json:"on"`
	Off int `json:"off"`
}

func (r DimmerSetDeviceAttributesResponseDeviceAttributesGradient) String() string {
	return fmt.Sprintf("{On:%v Off:%v}", r.On, r.Off)
}

type DimmerSetDeviceAttributesResponseDeviceAttributes struct {
	Led             DimmerSetDeviceAttributesResponseDeviceAttributesLed      `json:"led"`
	Gradient        DimmerSetDeviceAttributesResponseDeviceAttributesGradient `json:"gradient"`
	Calibration     int                                                       `json:"calibration"`
	CalibrationHigh int                                                       `json:"calibrationHigh"`
}

func (r DimmerSetDeviceAttributesResponseDeviceAttributes) String() string {
	return fmt.Sprintf("{Led:%v Gradient:%v Calibration:%v CalibrationHigh:%v}", r.Led, r.Gradient, r.Calibration, r.CalibrationHigh)
}

type DimmerSetDeviceAttributesResponse struct {
	DeviceAttributes DimmerSetDeviceAttributesResponseDeviceAttributes `json:"deviceAttributes"`
}

func (r DimmerSetDeviceAttributesResponse) String() string {
	return fmt.Sprintf("{DeviceAttributes:%v}", r.DeviceAttributes)
}

// SetDeviceAttributes Set dimmer's attributes
func (device *Dimmer) SetDeviceAttributes(params DimmerSetDeviceAttributesParams) (DimmerSetDeviceAttributesResponse, error) {
	var response DimmerSetDeviceAttributesResponse
	err := device.Call("Dimmer.setDeviceAttributes", params, &response)
	return response, err
}

func (device *Dimmer) SetDeviceAttributesAsync(params DimmerSetDeviceAttributesParams) <-chan controller.AsyncResult[DimmerSetDeviceAttributesResponse] {
	return controller.DecodeAsync[DimmerSetDeviceAttributesResponse](device.CallAsync("Dimmer.setDeviceAttributes", params))
}

type DimmerStartUpgradeParams struct {
	VersionId string `json:"versionId"` // Version ID to upgrade to
}

func (r DimmerStartUpgradeParams) String() string {
	return fmt.Sprintf("{VersionId:%v}", r.VersionId)
}

type DimmerStartUpgradeResponse struct {
	IsStarted bool `json:"isStarted"` // Is upgrading started
}

func (r DimmerStartUpgradeResponse) String() string {
	return fmt.Sprintf("{IsStarted:%v}", r.IsStarted)
}

// StartUpgrade Start firmware upgrade
func (device *Dimmer) StartUpgrade(params DimmerStartUpgradeParams) (DimmerStartUpgradeResponse, error) {
	var response DimmerStartUpgradeResponse
	err := device.Call("Dimmer.startUpgrade", params, &response)
	return response, err
}

func (device *Dimmer) StartUpgradeAsync(params DimmerStartUpgradeParams) <-chan controller.AsyncResult[DimmerStartUpgradeResponse] {
	return controller.DecodeAsync[DimmerStartUpgradeResponse](device.CallAsync("Dimmer.startUpgrade", params))
}

type DimmerGetActivityLogsParamsSearch struct {
	StartDate *string `json:"startDate,omitempty"` // YYYY-MM-DD
	EndDate   *string `json:"endDate,omitempty"`   // YYYY-MM-DD
}

func (r DimmerGetActivityLogsParamsSearch) String() string {
	var ptr0 any = "<nil>"
	if r.StartDate != nil {
		ptr0 = fmt.Sprint(*r.StartDate)
	}
	var ptr1 any = "<nil>"
	if r.EndDate != nil {
		ptr1 = fmt.Sprint(*r.EndDate)
	}
	return fmt.Sprintf("{StartDate:%v EndDate:%v}", ptr0, ptr1)
}

type DimmerGetActivityLogsParams struct {
	Search       DimmerGetActivityLogsParamsSearch `json:"search"`
	RetrievalKey *string                           `json:"retrievalKey,omitempty"` // Retrieval key for pagination
}

func (r DimmerGetActivityLogsParams) String() string {
	var ptr0 any = "<nil>"
	if r.RetrievalKey != nil {
		ptr0 = fmt.Sprint(*r.RetrievalKey)
	}
	return fmt.Sprintf("{Search:%v RetrievalKey:%v}", r.Search, ptr0)
}

type DimmerGetActivityLogsResponseLogsItem struct {
	Id   string      `json:"id"`   // Record ID
	Time time.Time   `json:"time"` // Record time
	Data interface{} `json:"data"` // Record data
}

func (r DimmerGetActivityLogsResponseLogsItem) String() string {
	return fmt.Sprintf("{Id:%v Time:%v Data:%v}", r.Id, r.Time, r.Data)
}

type DimmerGetActivityLogsResponseRetrievalKeys struct {
	Next *interface{} `json:"next,omitempty"` // Key for more results
}

func (r DimmerGetActivityLogsResponseRetrievalKeys) String() string {
	var ptr0 any = "<nil>"
	if r.Next != nil {
		ptr0 = fmt.Sprint(*r.Next)
	}
	return fmt.Sprintf("{Next:%v}", ptr0)
}

type DimmerGetActivityLogsResponse struct {
	Logs          []DimmerGetActivityLogsResponseLogsItem    `json:"logs"`
	RetrievalKeys DimmerGetActivityLogsResponseRetrievalKeys `json:"retrievalKeys"`
}

func (r DimmerGetActivityLogsResponse) String() string {
	return fmt.Sprintf("{Logs:%v RetrievalKeys:%v}", r.Logs, r.RetrievalKeys)
}

// GetActivityLogs Retrieve device activity records. Requires DEVICE.HISTORICAL_DATA.READ permission.
func (device *Dimmer) GetActivityLogs(params DimmerGetActivityLogsParams) (DimmerGetActivityLogsResponse, error) {
	var response DimmerGetActivityLogsResponse
	err := device.Call("Dimmer.getActivityLogs", params, &response)
	return response, err
}

func (device *Dimmer) GetActivityLogsAsync(params DimmerGetActivityLogsParams) <-chan controller.AsyncResult[DimmerGetActivityLogsResponse] {
	return controller.DecodeAsync[DimmerGetActivityLogsResponse](device.CallAsync("Dimmer.getActivityLogs", params))
}

type DimmerReportResponseDelay struct {
	On  int `json:"on"`  // Remain Delay ON minutes
	Off int `json:"off"` // Remain Delay OFF minutes
}

func (r DimmerReportResponseDelay) String() string {
	return fmt.Sprintf("{On:%v Off:%v}", r.On, r.Off)
}

type DimmerReportResponse struct {
	State      types.SwitchState         `json:"state"`      // ['closed','open']
	Brightness int                       `json:"brightness"` // Brightness 1-100
	Delay      DimmerReportResponseDelay `json:"delay"`
	Version    string                    `json:"version"` // Firmware version
	Tz         int                       `json:"tz"`      // Timezone -12~12
	LoraInfo   *types.LoraInfo           `json:"loraInfo,omitempty"`
}

func (r DimmerReportResponse) String() string {
	var ptr0 any = "<nil>"
	if r.LoraInfo != nil {
		ptr0 = fmt.Sprint(*r.LoraInfo)
	}
	return fmt.Sprintf("{State:%v Brightness:%v Delay:%v Version:%v Tz:%v LoraInfo:%v}", r.State, r.Brightness, r.Delay, r.Version, r.Tz, ptr0)
}

type DimmerAlertResponseDelay struct {
	On  int `json:"on"`  // Remain Delay ON minutes
	Off int `json:"off"` // Remain Delay OFF minutes
}

func (r DimmerAlertResponseDelay) String() string {
	return fmt.Sprintf("{On:%v Off:%v}", r.On, r.Off)
}

type DimmerAlertResponse struct {
	State          types.SwitchState        `json:"state"`      // ['closed','open']
	Brightness     int                      `json:"brightness"` // Brightness 1-100
	Delay          DimmerAlertResponseDelay `json:"delay"`
	Version        string                   `json:"version"` // Firmware version
	Tz             int                      `json:"tz"`      // Timezone -12~12
	LoraInfo       *types.LoraInfo          `json:"loraInfo,omitempty"`
	StateChangedAt *types.Timestamp         `json:"stateChangedAt,omitempty"`
}

func (r DimmerAlertResponse) String() string {
	var ptr0 any = "<nil>"
	if r.LoraInfo != nil {
		ptr0 = fmt.Sprint(*r.LoraInfo)
	}
	var ptr1 any = "<nil>"
	if r.StateChangedAt != nil {
		ptr1 = fmt.Sprint(*r.StateChangedAt)
	}
	return fmt.Sprintf("{State:%v Brightness:%v Delay:%v Version:%v Tz:%v LoraInfo:%v StateChangedAt:%v}", r.State, r.Brightness, r.Delay, r.Version, r.Tz, ptr0, ptr1)
}

func (device *Dimmer) ParseEvent(message controller.MqttMessage) (controller.Report, bool) {
	report, ok := device.Device.ParseEvent(message) // base impl decodes event + raw data
	if !ok {
		return report, false
	}
	report.Device = device                        // attribute the report to this concrete device
	data := report.Data.(controller.Unknown).Json // raw payload, re-typed below
	switch report.Event {
	case "Dimmer.getState":
		var response DimmerGetStateResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "Dimmer.setState":
		var response DimmerSetStateResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "Dimmer.setDelay":
		var response DimmerSetDelayResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "Dimmer.getSchedules":
		var response DimmerGetSchedulesResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "Dimmer.setSchedules":
		var response DimmerSetSchedulesResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "Dimmer.getVersion":
		var response DimmerGetVersionResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "Dimmer.setDeviceAttributes":
		var response DimmerSetDeviceAttributesResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "Dimmer.startUpgrade":
		var response DimmerStartUpgradeResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "Dimmer.getActivityLogs":
		var response DimmerGetActivityLogsResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "Dimmer.Report":
		var response DimmerReportResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "Dimmer.Alert":
		var response DimmerAlertResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	}
	return report, true
}
