// Code generated by scripts/gen_device_types.py; DO NOT EDIT.
package devices

import (
	"encoding/json"
	"fmt"
	"time"

	"github.com/tyandl/homelink/pkg/yolink/controller"
	"github.com/tyandl/homelink/pkg/yolink/types"
)

type DoorSensor struct{ *controller.Device }

func init() {
	controller.RegisterDeviceFactory("DoorSensor", func(device *controller.Device) controller.DeviceController {
		return &DoorSensor{Device: device}
	})
}

type DoorSensorGetStateResponseState struct {
	State           types.DoorState    `json:"state"`                     // ['closed','open','error']
	Battery         types.BatteryLevel `json:"battery"`                   // Battery level 0-4
	OpenRemindDelay *int               `json:"openRemindDelay,omitempty"` // Open remind delay seconds
	AlertInterval   *int               `json:"alertInterval,omitempty"`   // Continuous alert interval
	Delay           int                `json:"delay"`                     // Delay time
	Version         string             `json:"version"`                   // Firmware version
	StateChangedAt  types.Timestamp    `json:"stateChangedAt"`            // Last state change time
}

func (r DoorSensorGetStateResponseState) String() string {
	var ptr0 any = "<nil>"
	if r.OpenRemindDelay != nil {
		ptr0 = fmt.Sprint(*r.OpenRemindDelay)
	}
	var ptr1 any = "<nil>"
	if r.AlertInterval != nil {
		ptr1 = fmt.Sprint(*r.AlertInterval)
	}
	return fmt.Sprintf("{State:%v Battery:%v OpenRemindDelay:%v AlertInterval:%v Delay:%v Version:%v StateChangedAt:%v}", r.State, r.Battery, ptr0, ptr1, r.Delay, r.Version, r.StateChangedAt)
}

type DoorSensorGetStateResponse struct {
	Online   bool                            `json:"online"` // Is device online
	State    DoorSensorGetStateResponseState `json:"state"`
	ReportAt time.Time                       `json:"reportAt"` // Report time
	DeviceId string                          `json:"deviceId"` // Device ID
}

func (r DoorSensorGetStateResponse) String() string {
	return fmt.Sprintf("{Online:%v State:%v ReportAt:%v DeviceId:%v}", r.Online, r.State, r.ReportAt, r.DeviceId)
}

// GetState Get Door Sensor's State
func (device *DoorSensor) GetState() (DoorSensorGetStateResponse, error) {
	var response DoorSensorGetStateResponse
	err := device.Call("DoorSensor.getState", nil, &response)
	return response, err
}

func (device *DoorSensor) GetStateAsync() <-chan controller.AsyncResult[DoorSensorGetStateResponse] {
	return controller.DecodeAsync[DoorSensorGetStateResponse](device.CallAsync("DoorSensor.getState", nil))
}

type DoorSensorGetActivityLogsParamsSearch struct {
	StartDate *string `json:"startDate,omitempty"` // YYYY-MM-DD
	EndDate   *string `json:"endDate,omitempty"`   // YYYY-MM-DD
}

func (r DoorSensorGetActivityLogsParamsSearch) String() string {
	var ptr0 any = "<nil>"
	if r.StartDate != nil {
		ptr0 = fmt.Sprint(*r.StartDate)
	}
	var ptr1 any = "<nil>"
	if r.EndDate != nil {
		ptr1 = fmt.Sprint(*r.EndDate)
	}
	return fmt.Sprintf("{StartDate:%v EndDate:%v}", ptr0, ptr1)
}

type DoorSensorGetActivityLogsParams struct {
	Search       DoorSensorGetActivityLogsParamsSearch `json:"search"`
	RetrievalKey *string                               `json:"retrievalKey,omitempty"` // Retrieval key
}

func (r DoorSensorGetActivityLogsParams) String() string {
	var ptr0 any = "<nil>"
	if r.RetrievalKey != nil {
		ptr0 = fmt.Sprint(*r.RetrievalKey)
	}
	return fmt.Sprintf("{Search:%v RetrievalKey:%v}", r.Search, ptr0)
}

type DoorSensorGetActivityLogsResponseLogsItem struct {
	Id   string      `json:"id"`   // Record ID
	Time time.Time   `json:"time"` // Record time
	Data interface{} `json:"data"` // Record data
}

func (r DoorSensorGetActivityLogsResponseLogsItem) String() string {
	return fmt.Sprintf("{Id:%v Time:%v Data:%v}", r.Id, r.Time, r.Data)
}

type DoorSensorGetActivityLogsResponseRetrievalKeys struct {
	Next *interface{} `json:"next,omitempty"` // Key for more results
}

func (r DoorSensorGetActivityLogsResponseRetrievalKeys) String() string {
	var ptr0 any = "<nil>"
	if r.Next != nil {
		ptr0 = fmt.Sprint(*r.Next)
	}
	return fmt.Sprintf("{Next:%v}", ptr0)
}

type DoorSensorGetActivityLogsResponse struct {
	Logs          []DoorSensorGetActivityLogsResponseLogsItem    `json:"logs"`
	RetrievalKeys DoorSensorGetActivityLogsResponseRetrievalKeys `json:"retrievalKeys"`
}

func (r DoorSensorGetActivityLogsResponse) String() string {
	return fmt.Sprintf("{Logs:%v RetrievalKeys:%v}", r.Logs, r.RetrievalKeys)
}

// GetActivityLogs Retrieve device activity records. Requires DEVICE.HISTORICAL_DATA.READ permission.
func (device *DoorSensor) GetActivityLogs(params DoorSensorGetActivityLogsParams) (DoorSensorGetActivityLogsResponse, error) {
	var response DoorSensorGetActivityLogsResponse
	err := device.Call("DoorSensor.getActivityLogs", params, &response)
	return response, err
}

func (device *DoorSensor) GetActivityLogsAsync(params DoorSensorGetActivityLogsParams) <-chan controller.AsyncResult[DoorSensorGetActivityLogsResponse] {
	return controller.DecodeAsync[DoorSensorGetActivityLogsResponse](device.CallAsync("DoorSensor.getActivityLogs", params))
}

type DoorSensorSetAttributesParams struct {
	OpenRemindDelay *int `json:"openRemindDelay,omitempty"` // Open remind seconds 10-64800
	AlertInterval   *int `json:"alertInterval,omitempty"`   // Alert interval minutes 0-120
}

func (r DoorSensorSetAttributesParams) String() string {
	var ptr0 any = "<nil>"
	if r.OpenRemindDelay != nil {
		ptr0 = fmt.Sprint(*r.OpenRemindDelay)
	}
	var ptr1 any = "<nil>"
	if r.AlertInterval != nil {
		ptr1 = fmt.Sprint(*r.AlertInterval)
	}
	return fmt.Sprintf("{OpenRemindDelay:%v AlertInterval:%v}", ptr0, ptr1)
}

type DoorSensorSetAttributesResponse struct {
	OpenRemindDelay int `json:"openRemindDelay"`
	AlertInterval   int `json:"alertInterval"`
}

func (r DoorSensorSetAttributesResponse) String() string {
	return fmt.Sprintf("{OpenRemindDelay:%v AlertInterval:%v}", r.OpenRemindDelay, r.AlertInterval)
}

// SetAttributes Set device's attributes
func (device *DoorSensor) SetAttributes(params DoorSensorSetAttributesParams) (DoorSensorSetAttributesResponse, error) {
	var response DoorSensorSetAttributesResponse
	err := device.Call("DoorSensor.setAttributes", params, &response)
	return response, err
}

func (device *DoorSensor) SetAttributesAsync(params DoorSensorSetAttributesParams) <-chan controller.AsyncResult[DoorSensorSetAttributesResponse] {
	return controller.DecodeAsync[DoorSensorSetAttributesResponse](device.CallAsync("DoorSensor.setAttributes", params))
}

type DoorSensorAlertResponse struct {
	State          types.DoorState    `json:"state"`
	AlertType      string             `json:"alertType"` // normal | openRemind
	Battery        types.BatteryLevel `json:"battery"`
	Version        string             `json:"version"`
	LoraInfo       *types.LoraInfo    `json:"loraInfo,omitempty"`
	StateChangedAt types.Timestamp    `json:"stateChangedAt"`
}

func (r DoorSensorAlertResponse) String() string {
	var ptr0 any = "<nil>"
	if r.LoraInfo != nil {
		ptr0 = fmt.Sprint(*r.LoraInfo)
	}
	return fmt.Sprintf("{State:%v AlertType:%v Battery:%v Version:%v LoraInfo:%v StateChangedAt:%v}", r.State, r.AlertType, r.Battery, r.Version, ptr0, r.StateChangedAt)
}

type DoorSensorReportResponse struct {
	State           types.DoorState    `json:"state"`
	AlertType       string             `json:"alertType"` // normal | openRemind
	Battery         types.BatteryLevel `json:"battery"`
	Delay           int                `json:"delay"`
	Version         string             `json:"version"`
	OpenRemindDelay *int               `json:"openRemindDelay,omitempty"`
	AlertInterval   *int               `json:"alertInterval,omitempty"`
	LoraInfo        *types.LoraInfo    `json:"loraInfo,omitempty"`
}

func (r DoorSensorReportResponse) String() string {
	var ptr0 any = "<nil>"
	if r.OpenRemindDelay != nil {
		ptr0 = fmt.Sprint(*r.OpenRemindDelay)
	}
	var ptr1 any = "<nil>"
	if r.AlertInterval != nil {
		ptr1 = fmt.Sprint(*r.AlertInterval)
	}
	var ptr2 any = "<nil>"
	if r.LoraInfo != nil {
		ptr2 = fmt.Sprint(*r.LoraInfo)
	}
	return fmt.Sprintf("{State:%v AlertType:%v Battery:%v Delay:%v Version:%v OpenRemindDelay:%v AlertInterval:%v LoraInfo:%v}", r.State, r.AlertType, r.Battery, r.Delay, r.Version, ptr0, ptr1, ptr2)
}

func (device *DoorSensor) ParseEvent(message controller.MqttMessage) (controller.Report, bool) {
	report, ok := device.Device.ParseEvent(message) // base impl decodes event + raw data
	if !ok {
		return report, false
	}
	report.Device = device                        // attribute the report to this concrete device
	data := report.Data.(controller.Unknown).Json // raw payload, re-typed below
	switch report.Event {
	case "DoorSensor.getState":
		var response DoorSensorGetStateResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "DoorSensor.getActivityLogs":
		var response DoorSensorGetActivityLogsResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "DoorSensor.setAttributes":
		var response DoorSensorSetAttributesResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "DoorSensor.Alert":
		var response DoorSensorAlertResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "DoorSensor.Report":
		var response DoorSensorReportResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	}
	return report, true
}
