// Code generated by scripts/gen_device_types.py; DO NOT EDIT.
package devices

import "github.com/tyandl/homelink/pkg/yolink/controller"

type Finger struct{ *controller.Device }

func init() {
	controller.RegisterDeviceFactory("Finger", func(device *controller.Device) controller.DeviceController {
		return &Finger{Device: device}
	})
}

// Toggle Let finger press once. Check DoorSensor state first before calling.
func (device *Finger) Toggle() error {
	return device.Call("Finger.toggle", nil, nil)
}

func (device *Finger) ToggleAsync() <-chan controller.AsyncResult[any] {
	return controller.DecodeAsync[any](device.CallAsync("Finger.toggle", nil))
}

func (device *Finger) ParseEvent(message controller.MqttMessage) (controller.Report, bool) {
	report, ok := device.Device.ParseEvent(message) // base impl decodes event + raw data
	if !ok {
		return report, false
	}
	report.Device = device // attribute the report to this concrete device
	return report, true
}
