// Code generated by scripts/gen_device_types.py; DO NOT EDIT.
package devices

import (
	"encoding/json"
	"fmt"

	"github.com/tyandl/homelink/pkg/yolink/controller"
	"github.com/tyandl/homelink/pkg/yolink/types"
)

type Hub struct{ *controller.Device }

func init() {
	controller.RegisterDeviceFactory("Hub", func(device *controller.Device) controller.DeviceController {
		return &Hub{Device: device}
	})
}

type HubGetStateResponseWifi struct {
	Enable  bool   `json:"enable"`  // Is WiFi connected
	Ssid    string `json:"ssid"`    // Current WiFi SSID
	Ip      string `json:"ip"`      // WiFi IP
	Gateway string `json:"gateway"` // WiFi gateway
	Mask    string `json:"mask"`    // WiFi subnet mask
}

func (r HubGetStateResponseWifi) String() string {
	return fmt.Sprintf("{Enable:%v Ssid:%v Ip:%v Gateway:%v Mask:%v}", r.Enable, r.Ssid, r.Ip, r.Gateway, r.Mask)
}

type HubGetStateResponseEth struct {
	Enable  bool   `json:"enable"`  // Is Ethernet connected
	Ip      string `json:"ip"`      // Ethernet IP
	Gateway string `json:"gateway"` // Ethernet gateway
	Mask    string `json:"mask"`    // Ethernet subnet mask
}

func (r HubGetStateResponseEth) String() string {
	return fmt.Sprintf("{Enable:%v Ip:%v Gateway:%v Mask:%v}", r.Enable, r.Ip, r.Gateway, r.Mask)
}

type HubGetStateResponse struct {
	Version string                  `json:"version"` // Hub version
	Wifi    HubGetStateResponseWifi `json:"wifi"`
	Eth     HubGetStateResponseEth  `json:"eth"`
}

func (r HubGetStateResponse) String() string {
	return fmt.Sprintf("{Version:%v Wifi:%v Eth:%v}", r.Version, r.Wifi, r.Eth)
}

// GetState Get Hub's State
func (device *Hub) GetState() (HubGetStateResponse, error) {
	var response HubGetStateResponse
	err := device.Call("Hub.getState", nil, &response)
	return response, err
}

func (device *Hub) GetStateAsync() <-chan controller.AsyncResult[HubGetStateResponse] {
	return controller.DecodeAsync[HubGetStateResponse](device.CallAsync("Hub.getState", nil))
}

type HubSetWiFiParams struct {
	Ssid     string `json:"ssid"`     // WiFi SSID
	Password string `json:"password"` // WiFi password
}

func (r HubSetWiFiParams) String() string {
	return fmt.Sprintf("{Ssid:%v Password:%v}", r.Ssid, r.Password)
}

// SetWiFi Set hub's WiFi info (when online)
func (device *Hub) SetWiFi(params HubSetWiFiParams) error {
	return device.Call("Hub.setWiFi", params, nil)
}

func (device *Hub) SetWiFiAsync(params HubSetWiFiParams) <-chan controller.AsyncResult[any] {
	return controller.DecodeAsync[any](device.CallAsync("Hub.setWiFi", params))
}

type HubReportResponseWifi struct {
	Enable  bool   `json:"enable"`  // Is WiFi connected
	Ssid    string `json:"ssid"`    // Current WiFi SSID
	Ip      string `json:"ip"`      // WiFi IP
	Gateway string `json:"gateway"` // WiFi gateway
	Mask    string `json:"mask"`    // WiFi subnet mask
}

func (r HubReportResponseWifi) String() string {
	return fmt.Sprintf("{Enable:%v Ssid:%v Ip:%v Gateway:%v Mask:%v}", r.Enable, r.Ssid, r.Ip, r.Gateway, r.Mask)
}

type HubReportResponseEth struct {
	Enable  bool   `json:"enable"`  // Is Ethernet connected
	Ip      string `json:"ip"`      // Ethernet IP
	Gateway string `json:"gateway"` // Ethernet gateway
	Mask    string `json:"mask"`    // Ethernet subnet mask
}

func (r HubReportResponseEth) String() string {
	return fmt.Sprintf("{Enable:%v Ip:%v Gateway:%v Mask:%v}", r.Enable, r.Ip, r.Gateway, r.Mask)
}

type HubReportResponse struct {
	Version  string                `json:"version"` // Hub version
	Wifi     HubReportResponseWifi `json:"wifi"`
	Eth      HubReportResponseEth  `json:"eth"`
	LoraInfo *types.LoraInfo       `json:"loraInfo,omitempty"`
}

func (r HubReportResponse) String() string {
	var ptr0 any = "<nil>"
	if r.LoraInfo != nil {
		ptr0 = fmt.Sprint(*r.LoraInfo)
	}
	return fmt.Sprintf("{Version:%v Wifi:%v Eth:%v LoraInfo:%v}", r.Version, r.Wifi, r.Eth, ptr0)
}

type HubAlertResponseWifi struct {
	Enable  bool   `json:"enable"`  // Is WiFi connected
	Ssid    string `json:"ssid"`    // Current WiFi SSID
	Ip      string `json:"ip"`      // WiFi IP
	Gateway string `json:"gateway"` // WiFi gateway
	Mask    string `json:"mask"`    // WiFi subnet mask
}

func (r HubAlertResponseWifi) String() string {
	return fmt.Sprintf("{Enable:%v Ssid:%v Ip:%v Gateway:%v Mask:%v}", r.Enable, r.Ssid, r.Ip, r.Gateway, r.Mask)
}

type HubAlertResponseEth struct {
	Enable  bool   `json:"enable"`  // Is Ethernet connected
	Ip      string `json:"ip"`      // Ethernet IP
	Gateway string `json:"gateway"` // Ethernet gateway
	Mask    string `json:"mask"`    // Ethernet subnet mask
}

func (r HubAlertResponseEth) String() string {
	return fmt.Sprintf("{Enable:%v Ip:%v Gateway:%v Mask:%v}", r.Enable, r.Ip, r.Gateway, r.Mask)
}

type HubAlertResponse struct {
	Version        string               `json:"version"` // Hub version
	Wifi           HubAlertResponseWifi `json:"wifi"`
	Eth            HubAlertResponseEth  `json:"eth"`
	LoraInfo       *types.LoraInfo      `json:"loraInfo,omitempty"`
	StateChangedAt *types.Timestamp     `json:"stateChangedAt,omitempty"`
}

func (r HubAlertResponse) String() string {
	var ptr0 any = "<nil>"
	if r.LoraInfo != nil {
		ptr0 = fmt.Sprint(*r.LoraInfo)
	}
	var ptr1 any = "<nil>"
	if r.StateChangedAt != nil {
		ptr1 = fmt.Sprint(*r.StateChangedAt)
	}
	return fmt.Sprintf("{Version:%v Wifi:%v Eth:%v LoraInfo:%v StateChangedAt:%v}", r.Version, r.Wifi, r.Eth, ptr0, ptr1)
}

func (device *Hub) ParseEvent(message controller.MqttMessage) (controller.Report, bool) {
	report, ok := device.Device.ParseEvent(message) // base impl decodes event + raw data
	if !ok {
		return report, false
	}
	report.Device = device                        // attribute the report to this concrete device
	data := report.Data.(controller.Unknown).Json // raw payload, re-typed below
	switch report.Event {
	case "Hub.getState":
		var response HubGetStateResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "Hub.Report":
		var response HubReportResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "Hub.Alert":
		var response HubAlertResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	}
	return report, true
}
