// Code generated by scripts/gen_device_types.py; DO NOT EDIT.
package devices

import (
	"encoding/json"
	"fmt"
	"time"

	"github.com/tyandl/homelink/pkg/yolink/controller"
	"github.com/tyandl/homelink/pkg/yolink/types"
)

type InfraredRemoter struct{ *controller.Device }

func init() {
	controller.RegisterDeviceFactory("InfraredRemoter", func(device *controller.Device) controller.DeviceController {
		return &InfraredRemoter{Device: device}
	})
}

type InfraredRemoterGetStateResponse struct {
	Battery types.BatteryLevel `json:"battery"`        // Battery level 1-4
	Keys    []bool             `json:"keys"`           // 64 keys; true=learned
	Version string             `json:"version"`        // Firmware version
	Tz      int                `json:"tz"`             // Timezone
	Time    *time.Time         `json:"time,omitempty"` // Last activity timestamp
}

func (r InfraredRemoterGetStateResponse) String() string {
	var ptr0 any = "<nil>"
	if r.Time != nil {
		ptr0 = fmt.Sprint(*r.Time)
	}
	return fmt.Sprintf("{Battery:%v Keys:%v Version:%v Tz:%v Time:%v}", r.Battery, r.Keys, r.Version, r.Tz, ptr0)
}

// GetState Get Current InfraredRemoter State
func (device *InfraredRemoter) GetState() (InfraredRemoterGetStateResponse, error) {
	var response InfraredRemoterGetStateResponse
	err := device.Call("InfraredRemoter.getState", nil, &response)
	return response, err
}

func (device *InfraredRemoter) GetStateAsync() <-chan controller.AsyncResult[InfraredRemoterGetStateResponse] {
	return controller.DecodeAsync[InfraredRemoterGetStateResponse](device.CallAsync("InfraredRemoter.getState", nil))
}

type InfraredRemoterLearnParams struct {
	Key int `json:"key"` // Key index [0-63]
}

func (r InfraredRemoterLearnParams) String() string {
	return fmt.Sprintf("{Key:%v}", r.Key)
}

type InfraredRemoterLearnResponse struct {
	Success   bool    `json:"success"`             // Learning result
	ErrorCode *string `json:"errorCode,omitempty"` // 'error'|'keyError'|'started'|'timeout'
}

func (r InfraredRemoterLearnResponse) String() string {
	var ptr0 any = "<nil>"
	if r.ErrorCode != nil {
		ptr0 = fmt.Sprint(*r.ErrorCode)
	}
	return fmt.Sprintf("{Success:%v ErrorCode:%v}", r.Success, ptr0)
}

// Learn Learn IR code for a key
func (device *InfraredRemoter) Learn(params InfraredRemoterLearnParams) (InfraredRemoterLearnResponse, error) {
	var response InfraredRemoterLearnResponse
	err := device.Call("InfraredRemoter.learn", params, &response)
	return response, err
}

func (device *InfraredRemoter) LearnAsync(params InfraredRemoterLearnParams) <-chan controller.AsyncResult[InfraredRemoterLearnResponse] {
	return controller.DecodeAsync[InfraredRemoterLearnResponse](device.CallAsync("InfraredRemoter.learn", params))
}

type InfraredRemoterSendParams struct {
	Key int `json:"key"` // Key index [0-63]
}

func (r InfraredRemoterSendParams) String() string {
	return fmt.Sprintf("{Key:%v}", r.Key)
}

type InfraredRemoterSendResponse struct {
	Success   bool    `json:"success"`
	ErrorCode *string `json:"errorCode,omitempty"` // 'notLearn'|'keyError'
}

func (r InfraredRemoterSendResponse) String() string {
	var ptr0 any = "<nil>"
	if r.ErrorCode != nil {
		ptr0 = fmt.Sprint(*r.ErrorCode)
	}
	return fmt.Sprintf("{Success:%v ErrorCode:%v}", r.Success, ptr0)
}

// Send Send a learned IR code
func (device *InfraredRemoter) Send(params InfraredRemoterSendParams) (InfraredRemoterSendResponse, error) {
	var response InfraredRemoterSendResponse
	err := device.Call("InfraredRemoter.send", params, &response)
	return response, err
}

func (device *InfraredRemoter) SendAsync(params InfraredRemoterSendParams) <-chan controller.AsyncResult[InfraredRemoterSendResponse] {
	return controller.DecodeAsync[InfraredRemoterSendResponse](device.CallAsync("InfraredRemoter.send", params))
}

type InfraredRemoterSetTimeZoneParams struct {
	Tz int `json:"tz"` // Timezone -12~+12
}

func (r InfraredRemoterSetTimeZoneParams) String() string {
	return fmt.Sprintf("{Tz:%v}", r.Tz)
}

type InfraredRemoterSetTimeZoneResponse struct {
	Success   bool    `json:"success"`
	ErrorCode *string `json:"errorCode,omitempty"`
}

func (r InfraredRemoterSetTimeZoneResponse) String() string {
	var ptr0 any = "<nil>"
	if r.ErrorCode != nil {
		ptr0 = fmt.Sprint(*r.ErrorCode)
	}
	return fmt.Sprintf("{Success:%v ErrorCode:%v}", r.Success, ptr0)
}

// SetTimeZone Set device timezone
func (device *InfraredRemoter) SetTimeZone(params InfraredRemoterSetTimeZoneParams) (InfraredRemoterSetTimeZoneResponse, error) {
	var response InfraredRemoterSetTimeZoneResponse
	err := device.Call("InfraredRemoter.setTimeZone", params, &response)
	return response, err
}

func (device *InfraredRemoter) SetTimeZoneAsync(params InfraredRemoterSetTimeZoneParams) <-chan controller.AsyncResult[InfraredRemoterSetTimeZoneResponse] {
	return controller.DecodeAsync[InfraredRemoterSetTimeZoneResponse](device.CallAsync("InfraredRemoter.setTimeZone", params))
}

type InfraredRemoterSetScheduleParamsSchesItem struct {
	IsValid bool   `json:"isValid"` // Schedule enabled
	Week    int    `json:"week"`    // Weekday bitmask; bit 0-6 = Sun-Sat
	Time    string `json:"time"`    // HH:mm
	Key     int    `json:"key"`     // Key to trigger [0-63]
}

func (r InfraredRemoterSetScheduleParamsSchesItem) String() string {
	return fmt.Sprintf("{IsValid:%v Week:%v Time:%v Key:%v}", r.IsValid, r.Week, r.Time, r.Key)
}

type InfraredRemoterSetScheduleParams struct {
	Sches []InfraredRemoterSetScheduleParamsSchesItem `json:"sches"`
}

func (r InfraredRemoterSetScheduleParams) String() string {
	return fmt.Sprintf("{Sches:%v}", r.Sches)
}

type InfraredRemoterSetScheduleResponseSchesItem struct {
	IsValid bool   `json:"isValid"`
	Week    int    `json:"week"`
	Time    string `json:"time"`
	Key     int    `json:"key"`
}

func (r InfraredRemoterSetScheduleResponseSchesItem) String() string {
	return fmt.Sprintf("{IsValid:%v Week:%v Time:%v Key:%v}", r.IsValid, r.Week, r.Time, r.Key)
}

type InfraredRemoterSetScheduleResponse struct {
	Sches []InfraredRemoterSetScheduleResponseSchesItem `json:"sches"`
}

func (r InfraredRemoterSetScheduleResponse) String() string {
	return fmt.Sprintf("{Sches:%v}", r.Sches)
}

// SetSchedule Create or update schedules (up to 10)
func (device *InfraredRemoter) SetSchedule(params InfraredRemoterSetScheduleParams) (InfraredRemoterSetScheduleResponse, error) {
	var response InfraredRemoterSetScheduleResponse
	err := device.Call("InfraredRemoter.setSchedule", params, &response)
	return response, err
}

func (device *InfraredRemoter) SetScheduleAsync(params InfraredRemoterSetScheduleParams) <-chan controller.AsyncResult[InfraredRemoterSetScheduleResponse] {
	return controller.DecodeAsync[InfraredRemoterSetScheduleResponse](device.CallAsync("InfraredRemoter.setSchedule", params))
}

type InfraredRemoterGetSchedulesResponseSchesItem struct {
	IsValid bool   `json:"isValid"`
	Week    int    `json:"week"`
	Time    string `json:"time"`
	Key     int    `json:"key"`
}

func (r InfraredRemoterGetSchedulesResponseSchesItem) String() string {
	return fmt.Sprintf("{IsValid:%v Week:%v Time:%v Key:%v}", r.IsValid, r.Week, r.Time, r.Key)
}

type InfraredRemoterGetSchedulesResponse struct {
	Sches []InfraredRemoterGetSchedulesResponseSchesItem `json:"sches"`
}

func (r InfraredRemoterGetSchedulesResponse) String() string {
	return fmt.Sprintf("{Sches:%v}", r.Sches)
}

// GetSchedules Get schedules
func (device *InfraredRemoter) GetSchedules() (InfraredRemoterGetSchedulesResponse, error) {
	var response InfraredRemoterGetSchedulesResponse
	err := device.Call("InfraredRemoter.getSchedules", nil, &response)
	return response, err
}

func (device *InfraredRemoter) GetSchedulesAsync() <-chan controller.AsyncResult[InfraredRemoterGetSchedulesResponse] {
	return controller.DecodeAsync[InfraredRemoterGetSchedulesResponse](device.CallAsync("InfraredRemoter.getSchedules", nil))
}

type InfraredRemoterReportResponse struct {
	Battery  types.BatteryLevel `json:"battery"`
	Keys     []bool             `json:"keys"` // 64-element array indicating which keys are programmed
	Version  string             `json:"version"`
	Time     *string            `json:"time,omitempty"` // ISO 8601 datetime
	Tz       *int               `json:"tz,omitempty"`
	LoraInfo *types.LoraInfo    `json:"loraInfo,omitempty"`
}

func (r InfraredRemoterReportResponse) String() string {
	var ptr0 any = "<nil>"
	if r.Time != nil {
		ptr0 = fmt.Sprint(*r.Time)
	}
	var ptr1 any = "<nil>"
	if r.Tz != nil {
		ptr1 = fmt.Sprint(*r.Tz)
	}
	var ptr2 any = "<nil>"
	if r.LoraInfo != nil {
		ptr2 = fmt.Sprint(*r.LoraInfo)
	}
	return fmt.Sprintf("{Battery:%v Keys:%v Version:%v Time:%v Tz:%v LoraInfo:%v}", r.Battery, r.Keys, r.Version, ptr0, ptr1, ptr2)
}

type InfraredRemoterAlertResponse struct {
	Battery        types.BatteryLevel `json:"battery"`        // Battery level 1-4
	Keys           []bool             `json:"keys"`           // 64 keys; true=learned
	Version        string             `json:"version"`        // Firmware version
	Tz             int                `json:"tz"`             // Timezone
	Time           *time.Time         `json:"time,omitempty"` // Last activity timestamp
	LoraInfo       *types.LoraInfo    `json:"loraInfo,omitempty"`
	StateChangedAt *types.Timestamp   `json:"stateChangedAt,omitempty"`
}

func (r InfraredRemoterAlertResponse) String() string {
	var ptr0 any = "<nil>"
	if r.Time != nil {
		ptr0 = fmt.Sprint(*r.Time)
	}
	var ptr1 any = "<nil>"
	if r.LoraInfo != nil {
		ptr1 = fmt.Sprint(*r.LoraInfo)
	}
	var ptr2 any = "<nil>"
	if r.StateChangedAt != nil {
		ptr2 = fmt.Sprint(*r.StateChangedAt)
	}
	return fmt.Sprintf("{Battery:%v Keys:%v Version:%v Tz:%v Time:%v LoraInfo:%v StateChangedAt:%v}", r.Battery, r.Keys, r.Version, r.Tz, ptr0, ptr1, ptr2)
}

func (device *InfraredRemoter) ParseEvent(message controller.MqttMessage) (controller.Report, bool) {
	report, ok := device.Device.ParseEvent(message) // base impl decodes event + raw data
	if !ok {
		return report, false
	}
	report.Device = device                        // attribute the report to this concrete device
	data := report.Data.(controller.Unknown).Json // raw payload, re-typed below
	switch report.Event {
	case "InfraredRemoter.getState":
		var response InfraredRemoterGetStateResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "InfraredRemoter.learn":
		var response InfraredRemoterLearnResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "InfraredRemoter.send":
		var response InfraredRemoterSendResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "InfraredRemoter.setTimeZone":
		var response InfraredRemoterSetTimeZoneResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "InfraredRemoter.setSchedule":
		var response InfraredRemoterSetScheduleResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "InfraredRemoter.getSchedules":
		var response InfraredRemoterGetSchedulesResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "InfraredRemoter.Report":
		var response InfraredRemoterReportResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "InfraredRemoter.Alert":
		var response InfraredRemoterAlertResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	}
	return report, true
}
