// Code generated by scripts/gen_device_types.py; DO NOT EDIT.
package devices

import (
	"encoding/json"
	"fmt"

	"github.com/tyandl/homelink/pkg/yolink/controller"
	"github.com/tyandl/homelink/pkg/yolink/types"
)

type IPCamera struct{ *controller.Device }

func init() {
	controller.RegisterDeviceFactory("IPCamera", func(device *controller.Device) controller.DeviceController {
		return &IPCamera{Device: device}
	})
}

type IPCameraGetStateResponseWifi struct {
	Enable  bool    `json:"enable"`            // Is WiFi connected
	Ip      string  `json:"ip"`                // WiFi IP
	Mask    string  `json:"mask"`              // WiFi subnet mask
	Gateway *string `json:"gateway,omitempty"` // WiFi gateway
	Mac     *string `json:"mac,omitempty"`     // WiFi MAC address
	Rssi    int     `json:"rssi"`              // WiFi RSSI
}

func (r IPCameraGetStateResponseWifi) String() string {
	var ptr0 any = "<nil>"
	if r.Gateway != nil {
		ptr0 = fmt.Sprint(*r.Gateway)
	}
	var ptr1 any = "<nil>"
	if r.Mac != nil {
		ptr1 = fmt.Sprint(*r.Mac)
	}
	return fmt.Sprintf("{Enable:%v Ip:%v Mask:%v Gateway:%v Mac:%v Rssi:%v}", r.Enable, r.Ip, r.Mask, ptr0, ptr1, r.Rssi)
}

type IPCameraGetStateResponseSoundDetection struct {
	Enable bool `json:"enable"` // Sound detection enabled
	Level  int  `json:"level"`  // Sound detection sensitivity [0-5]
}

func (r IPCameraGetStateResponseSoundDetection) String() string {
	return fmt.Sprintf("{Enable:%v Level:%v}", r.Enable, r.Level)
}

type IPCameraGetStateResponseMotionDetection struct {
	Enable bool `json:"enable"` // Motion detection enabled
	Level  int  `json:"level"`  // Motion detection sensitivity [0-4]
}

func (r IPCameraGetStateResponseMotionDetection) String() string {
	return fmt.Sprintf("{Enable:%v Level:%v}", r.Enable, r.Level)
}

type IPCameraGetStateResponseStorage struct {
	Total    int    `json:"total"`    // SD card total capacity (MB)
	Free     int    `json:"free"`     // SD card free capacity (MB)
	SdFormat string `json:"sdFormat"` // SD card format
	RwMode   string `json:"rwMode"`   // SD card read-write mode
}

func (r IPCameraGetStateResponseStorage) String() string {
	return fmt.Sprintf("{Total:%v Free:%v SdFormat:%v RwMode:%v}", r.Total, r.Free, r.SdFormat, r.RwMode)
}

type IPCameraGetStateResponse struct {
	Online              bool                                    `json:"online"` // Is device online
	Wifi                IPCameraGetStateResponseWifi            `json:"wifi"`
	Volume              int                                     `json:"volume"`              // Speaker volume [0-5]
	RecordMode          types.RecordMode                        `json:"recordMode"`          // ['full-time','alarm','off']
	IndicatorLight      string                                  `json:"indicatorLight"`      // ['on','off']
	VoicePrompts        string                                  `json:"voicePrompts"`        // ['on','off']
	MaxManualRecordTime int                                     `json:"maxManualRecordTime"` // Max manual recording time in minutes
	NightVision         types.NightVision                       `json:"nightVision"`         // ['on','off','auto']
	SoundDetection      IPCameraGetStateResponseSoundDetection  `json:"soundDetection"`
	MotionDetection     IPCameraGetStateResponseMotionDetection `json:"motionDetection"`
	Storage             IPCameraGetStateResponseStorage         `json:"storage"`
	SoundEnable         bool                                    `json:"soundEnable"` // Sound enabled
	PrivacyMode         string                                  `json:"privacyMode"` // ['on','off']
	Version             string                                  `json:"version"`     // Firmware version
	Tz                  int                                     `json:"tz"`          // Timezone
}

func (r IPCameraGetStateResponse) String() string {
	return fmt.Sprintf("{Online:%v Wifi:%v Volume:%v RecordMode:%v IndicatorLight:%v VoicePrompts:%v MaxManualRecordTime:%v NightVision:%v SoundDetection:%v MotionDetection:%v Storage:%v SoundEnable:%v PrivacyMode:%v Version:%v Tz:%v}", r.Online, r.Wifi, r.Volume, r.RecordMode, r.IndicatorLight, r.VoicePrompts, r.MaxManualRecordTime, r.NightVision, r.SoundDetection, r.MotionDetection, r.Storage, r.SoundEnable, r.PrivacyMode, r.Version, r.Tz)
}

// GetState Get Current State
func (device *IPCamera) GetState() (IPCameraGetStateResponse, error) {
	var response IPCameraGetStateResponse
	err := device.Call("IPCamera.getState", nil, &response)
	return response, err
}

func (device *IPCamera) GetStateAsync() <-chan controller.AsyncResult[IPCameraGetStateResponse] {
	return controller.DecodeAsync[IPCameraGetStateResponse](device.CallAsync("IPCamera.getState", nil))
}

type IPCameraSetPropertiesParamsSoundDetection struct {
	Enable *bool `json:"enable,omitempty"`
	Level  *int  `json:"level,omitempty"` // [0-5]
}

func (r IPCameraSetPropertiesParamsSoundDetection) String() string {
	var ptr0 any = "<nil>"
	if r.Enable != nil {
		ptr0 = fmt.Sprint(*r.Enable)
	}
	var ptr1 any = "<nil>"
	if r.Level != nil {
		ptr1 = fmt.Sprint(*r.Level)
	}
	return fmt.Sprintf("{Enable:%v Level:%v}", ptr0, ptr1)
}

type IPCameraSetPropertiesParamsMotionDetection struct {
	Enable *bool `json:"enable,omitempty"`
	Level  *int  `json:"level,omitempty"` // [0-4]
}

func (r IPCameraSetPropertiesParamsMotionDetection) String() string {
	var ptr0 any = "<nil>"
	if r.Enable != nil {
		ptr0 = fmt.Sprint(*r.Enable)
	}
	var ptr1 any = "<nil>"
	if r.Level != nil {
		ptr1 = fmt.Sprint(*r.Level)
	}
	return fmt.Sprintf("{Enable:%v Level:%v}", ptr0, ptr1)
}

type IPCameraSetPropertiesParams struct {
	Volume              *int                                       `json:"volume,omitempty"`              // Speaker volume [0-5]
	IndicatorLight      *string                                    `json:"indicatorLight,omitempty"`      // ['on','off']
	VoicePrompts        *string                                    `json:"voicePrompts,omitempty"`        // ['on','off']
	MaxManualRecordTime *int                                       `json:"maxManualRecordTime,omitempty"` // Max manual recording time in minutes
	NightVision         *types.NightVision                         `json:"nightVision,omitempty"`         // ['on','off','auto']
	SoundDetection      IPCameraSetPropertiesParamsSoundDetection  `json:"soundDetection"`
	MotionDetection     IPCameraSetPropertiesParamsMotionDetection `json:"motionDetection"`
	SoundEnable         *bool                                      `json:"soundEnable,omitempty"`
}

func (r IPCameraSetPropertiesParams) String() string {
	var ptr0 any = "<nil>"
	if r.Volume != nil {
		ptr0 = fmt.Sprint(*r.Volume)
	}
	var ptr1 any = "<nil>"
	if r.IndicatorLight != nil {
		ptr1 = fmt.Sprint(*r.IndicatorLight)
	}
	var ptr2 any = "<nil>"
	if r.VoicePrompts != nil {
		ptr2 = fmt.Sprint(*r.VoicePrompts)
	}
	var ptr3 any = "<nil>"
	if r.MaxManualRecordTime != nil {
		ptr3 = fmt.Sprint(*r.MaxManualRecordTime)
	}
	var ptr4 any = "<nil>"
	if r.NightVision != nil {
		ptr4 = fmt.Sprint(*r.NightVision)
	}
	var ptr5 any = "<nil>"
	if r.SoundEnable != nil {
		ptr5 = fmt.Sprint(*r.SoundEnable)
	}
	return fmt.Sprintf("{Volume:%v IndicatorLight:%v VoicePrompts:%v MaxManualRecordTime:%v NightVision:%v SoundDetection:%v MotionDetection:%v SoundEnable:%v}", ptr0, ptr1, ptr2, ptr3, ptr4, r.SoundDetection, r.MotionDetection, ptr5)
}

type IPCameraSetPropertiesResponse struct {
	Success bool `json:"success"`
	Code    int  `json:"code"` // 200=success
}

func (r IPCameraSetPropertiesResponse) String() string {
	return fmt.Sprintf("{Success:%v Code:%v}", r.Success, r.Code)
}

// SetProperties Set device's properties
func (device *IPCamera) SetProperties(params IPCameraSetPropertiesParams) (IPCameraSetPropertiesResponse, error) {
	var response IPCameraSetPropertiesResponse
	err := device.Call("IPCamera.setProperties", params, &response)
	return response, err
}

func (device *IPCamera) SetPropertiesAsync(params IPCameraSetPropertiesParams) <-chan controller.AsyncResult[IPCameraSetPropertiesResponse] {
	return controller.DecodeAsync[IPCameraSetPropertiesResponse](device.CallAsync("IPCamera.setProperties", params))
}

type IPCameraStartRecordingParams struct {
	AudioEnable *bool `json:"audioEnable,omitempty"` // Record audio; default true
	Duration    *int  `json:"duration,omitempty"`    // Recording duration in minutes
}

func (r IPCameraStartRecordingParams) String() string {
	var ptr0 any = "<nil>"
	if r.AudioEnable != nil {
		ptr0 = fmt.Sprint(*r.AudioEnable)
	}
	var ptr1 any = "<nil>"
	if r.Duration != nil {
		ptr1 = fmt.Sprint(*r.Duration)
	}
	return fmt.Sprintf("{AudioEnable:%v Duration:%v}", ptr0, ptr1)
}

type IPCameraStartRecordingResponse struct {
	Success bool `json:"success"`
	Code    int  `json:"code"` // 200=started
}

func (r IPCameraStartRecordingResponse) String() string {
	return fmt.Sprintf("{Success:%v Code:%v}", r.Success, r.Code)
}

// StartRecording Start local video recording
func (device *IPCamera) StartRecording(params IPCameraStartRecordingParams) (IPCameraStartRecordingResponse, error) {
	var response IPCameraStartRecordingResponse
	err := device.Call("IPCamera.startRecording", params, &response)
	return response, err
}

func (device *IPCamera) StartRecordingAsync(params IPCameraStartRecordingParams) <-chan controller.AsyncResult[IPCameraStartRecordingResponse] {
	return controller.DecodeAsync[IPCameraStartRecordingResponse](device.CallAsync("IPCamera.startRecording", params))
}

type IPCameraStopRecordingResponse struct {
	Success bool `json:"success"`
	Code    int  `json:"code"` // 200=stopped
}

func (r IPCameraStopRecordingResponse) String() string {
	return fmt.Sprintf("{Success:%v Code:%v}", r.Success, r.Code)
}

// StopRecording Stop local recording
func (device *IPCamera) StopRecording() (IPCameraStopRecordingResponse, error) {
	var response IPCameraStopRecordingResponse
	err := device.Call("IPCamera.stopRecording", nil, &response)
	return response, err
}

func (device *IPCamera) StopRecordingAsync() <-chan controller.AsyncResult[IPCameraStopRecordingResponse] {
	return controller.DecodeAsync[IPCameraStopRecordingResponse](device.CallAsync("IPCamera.stopRecording", nil))
}

type IPCameraReportResponseWifi struct {
	Enable  bool    `json:"enable"`            // Is WiFi connected
	Ip      string  `json:"ip"`                // WiFi IP
	Mask    string  `json:"mask"`              // WiFi subnet mask
	Gateway *string `json:"gateway,omitempty"` // WiFi gateway
	Mac     *string `json:"mac,omitempty"`     // WiFi MAC address
	Rssi    int     `json:"rssi"`              // WiFi RSSI
}

func (r IPCameraReportResponseWifi) String() string {
	var ptr0 any = "<nil>"
	if r.Gateway != nil {
		ptr0 = fmt.Sprint(*r.Gateway)
	}
	var ptr1 any = "<nil>"
	if r.Mac != nil {
		ptr1 = fmt.Sprint(*r.Mac)
	}
	return fmt.Sprintf("{Enable:%v Ip:%v Mask:%v Gateway:%v Mac:%v Rssi:%v}", r.Enable, r.Ip, r.Mask, ptr0, ptr1, r.Rssi)
}

type IPCameraReportResponseSoundDetection struct {
	Enable bool `json:"enable"` // Sound detection enabled
	Level  int  `json:"level"`  // Sound detection sensitivity [0-5]
}

func (r IPCameraReportResponseSoundDetection) String() string {
	return fmt.Sprintf("{Enable:%v Level:%v}", r.Enable, r.Level)
}

type IPCameraReportResponseMotionDetection struct {
	Enable bool `json:"enable"` // Motion detection enabled
	Level  int  `json:"level"`  // Motion detection sensitivity [0-4]
}

func (r IPCameraReportResponseMotionDetection) String() string {
	return fmt.Sprintf("{Enable:%v Level:%v}", r.Enable, r.Level)
}

type IPCameraReportResponseStorage struct {
	Total    int    `json:"total"`    // SD card total capacity (MB)
	Free     int    `json:"free"`     // SD card free capacity (MB)
	SdFormat string `json:"sdFormat"` // SD card format
	RwMode   string `json:"rwMode"`   // SD card read-write mode
}

func (r IPCameraReportResponseStorage) String() string {
	return fmt.Sprintf("{Total:%v Free:%v SdFormat:%v RwMode:%v}", r.Total, r.Free, r.SdFormat, r.RwMode)
}

type IPCameraReportResponse struct {
	Wifi                IPCameraReportResponseWifi            `json:"wifi"`
	Volume              int                                   `json:"volume"`              // Speaker volume [0-5]
	RecordMode          types.RecordMode                      `json:"recordMode"`          // ['full-time','alarm','off']
	IndicatorLight      string                                `json:"indicatorLight"`      // ['on','off']
	VoicePrompts        string                                `json:"voicePrompts"`        // ['on','off']
	MaxManualRecordTime int                                   `json:"maxManualRecordTime"` // Max manual recording time in minutes
	NightVision         types.NightVision                     `json:"nightVision"`         // ['on','off','auto']
	SoundDetection      IPCameraReportResponseSoundDetection  `json:"soundDetection"`
	MotionDetection     IPCameraReportResponseMotionDetection `json:"motionDetection"`
	Storage             IPCameraReportResponseStorage         `json:"storage"`
	SoundEnable         bool                                  `json:"soundEnable"` // Sound enabled
	PrivacyMode         string                                `json:"privacyMode"` // ['on','off']
	Version             string                                `json:"version"`     // Firmware version
	Tz                  int                                   `json:"tz"`          // Timezone
	LoraInfo            *types.LoraInfo                       `json:"loraInfo,omitempty"`
}

func (r IPCameraReportResponse) String() string {
	var ptr0 any = "<nil>"
	if r.LoraInfo != nil {
		ptr0 = fmt.Sprint(*r.LoraInfo)
	}
	return fmt.Sprintf("{Wifi:%v Volume:%v RecordMode:%v IndicatorLight:%v VoicePrompts:%v MaxManualRecordTime:%v NightVision:%v SoundDetection:%v MotionDetection:%v Storage:%v SoundEnable:%v PrivacyMode:%v Version:%v Tz:%v LoraInfo:%v}", r.Wifi, r.Volume, r.RecordMode, r.IndicatorLight, r.VoicePrompts, r.MaxManualRecordTime, r.NightVision, r.SoundDetection, r.MotionDetection, r.Storage, r.SoundEnable, r.PrivacyMode, r.Version, r.Tz, ptr0)
}

type IPCameraAlertResponseWifi struct {
	Enable  bool    `json:"enable"`            // Is WiFi connected
	Ip      string  `json:"ip"`                // WiFi IP
	Mask    string  `json:"mask"`              // WiFi subnet mask
	Gateway *string `json:"gateway,omitempty"` // WiFi gateway
	Mac     *string `json:"mac,omitempty"`     // WiFi MAC address
	Rssi    int     `json:"rssi"`              // WiFi RSSI
}

func (r IPCameraAlertResponseWifi) String() string {
	var ptr0 any = "<nil>"
	if r.Gateway != nil {
		ptr0 = fmt.Sprint(*r.Gateway)
	}
	var ptr1 any = "<nil>"
	if r.Mac != nil {
		ptr1 = fmt.Sprint(*r.Mac)
	}
	return fmt.Sprintf("{Enable:%v Ip:%v Mask:%v Gateway:%v Mac:%v Rssi:%v}", r.Enable, r.Ip, r.Mask, ptr0, ptr1, r.Rssi)
}

type IPCameraAlertResponseSoundDetection struct {
	Enable bool `json:"enable"` // Sound detection enabled
	Level  int  `json:"level"`  // Sound detection sensitivity [0-5]
}

func (r IPCameraAlertResponseSoundDetection) String() string {
	return fmt.Sprintf("{Enable:%v Level:%v}", r.Enable, r.Level)
}

type IPCameraAlertResponseMotionDetection struct {
	Enable bool `json:"enable"` // Motion detection enabled
	Level  int  `json:"level"`  // Motion detection sensitivity [0-4]
}

func (r IPCameraAlertResponseMotionDetection) String() string {
	return fmt.Sprintf("{Enable:%v Level:%v}", r.Enable, r.Level)
}

type IPCameraAlertResponseStorage struct {
	Total    int    `json:"total"`    // SD card total capacity (MB)
	Free     int    `json:"free"`     // SD card free capacity (MB)
	SdFormat string `json:"sdFormat"` // SD card format
	RwMode   string `json:"rwMode"`   // SD card read-write mode
}

func (r IPCameraAlertResponseStorage) String() string {
	return fmt.Sprintf("{Total:%v Free:%v SdFormat:%v RwMode:%v}", r.Total, r.Free, r.SdFormat, r.RwMode)
}

type IPCameraAlertResponse struct {
	Wifi                IPCameraAlertResponseWifi            `json:"wifi"`
	Volume              int                                  `json:"volume"`              // Speaker volume [0-5]
	RecordMode          types.RecordMode                     `json:"recordMode"`          // ['full-time','alarm','off']
	IndicatorLight      string                               `json:"indicatorLight"`      // ['on','off']
	VoicePrompts        string                               `json:"voicePrompts"`        // ['on','off']
	MaxManualRecordTime int                                  `json:"maxManualRecordTime"` // Max manual recording time in minutes
	NightVision         types.NightVision                    `json:"nightVision"`         // ['on','off','auto']
	SoundDetection      IPCameraAlertResponseSoundDetection  `json:"soundDetection"`
	MotionDetection     IPCameraAlertResponseMotionDetection `json:"motionDetection"`
	Storage             IPCameraAlertResponseStorage         `json:"storage"`
	SoundEnable         bool                                 `json:"soundEnable"` // Sound enabled
	PrivacyMode         string                               `json:"privacyMode"` // ['on','off']
	Version             string                               `json:"version"`     // Firmware version
	Tz                  int                                  `json:"tz"`          // Timezone
	LoraInfo            *types.LoraInfo                      `json:"loraInfo,omitempty"`
	StateChangedAt      *types.Timestamp                     `json:"stateChangedAt,omitempty"`
}

func (r IPCameraAlertResponse) String() string {
	var ptr0 any = "<nil>"
	if r.LoraInfo != nil {
		ptr0 = fmt.Sprint(*r.LoraInfo)
	}
	var ptr1 any = "<nil>"
	if r.StateChangedAt != nil {
		ptr1 = fmt.Sprint(*r.StateChangedAt)
	}
	return fmt.Sprintf("{Wifi:%v Volume:%v RecordMode:%v IndicatorLight:%v VoicePrompts:%v MaxManualRecordTime:%v NightVision:%v SoundDetection:%v MotionDetection:%v Storage:%v SoundEnable:%v PrivacyMode:%v Version:%v Tz:%v LoraInfo:%v StateChangedAt:%v}", r.Wifi, r.Volume, r.RecordMode, r.IndicatorLight, r.VoicePrompts, r.MaxManualRecordTime, r.NightVision, r.SoundDetection, r.MotionDetection, r.Storage, r.SoundEnable, r.PrivacyMode, r.Version, r.Tz, ptr0, ptr1)
}

func (device *IPCamera) ParseEvent(message controller.MqttMessage) (controller.Report, bool) {
	report, ok := device.Device.ParseEvent(message) // base impl decodes event + raw data
	if !ok {
		return report, false
	}
	report.Device = device                        // attribute the report to this concrete device
	data := report.Data.(controller.Unknown).Json // raw payload, re-typed below
	switch report.Event {
	case "IPCamera.getState":
		var response IPCameraGetStateResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "IPCamera.setProperties":
		var response IPCameraSetPropertiesResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "IPCamera.startRecording":
		var response IPCameraStartRecordingResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "IPCamera.stopRecording":
		var response IPCameraStopRecordingResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "IPCamera.Report":
		var response IPCameraReportResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "IPCamera.Alert":
		var response IPCameraAlertResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	}
	return report, true
}
