// Code generated by scripts/gen_device_types.py; DO NOT EDIT.
package devices

import (
	"encoding/json"
	"fmt"
	"time"

	"github.com/tyandl/homelink/pkg/yolink/controller"
	"github.com/tyandl/homelink/pkg/yolink/types"
)

type LeakSensor struct{ *controller.Device }

func init() {
	controller.RegisterDeviceFactory("LeakSensor", func(device *controller.Device) controller.DeviceController {
		return &LeakSensor{Device: device}
	})
}

type LeakSensorGetStateResponseStateAlarmState struct {
	StayError     bool `json:"stayError"`
	DetectorError bool `json:"detectorError"`
	FreezeError   bool `json:"freezeError"`
	Reminder      bool `json:"reminder"`
}

func (r LeakSensorGetStateResponseStateAlarmState) String() string {
	return fmt.Sprintf("{StayError:%v DetectorError:%v FreezeError:%v Reminder:%v}", r.StayError, r.DetectorError, r.FreezeError, r.Reminder)
}

type LeakSensorGetStateResponseState struct {
	State             types.AlarmState                          `json:"state"`              // ['normal','alert']
	Battery           types.BatteryLevel                        `json:"battery"`            // Battery level 0-4
	Beep              bool                                      `json:"beep"`               // Is sounding alarm
	DevTemperature    int                                       `json:"devTemperature"`     // Device temperature
	Interval          *int                                      `json:"interval,omitempty"` // Continuous alert interval
	Sensitivity       types.LeakSensorSensitivity               `json:"sensitivity"`        // Sensitivity level
	SensorMode        types.LeakSensorMode                      `json:"sensorMode"`         // Operating mode
	StateChangedAt    types.Timestamp                           `json:"stateChangedAt"`     // Last state change time
	SupportChangeMode bool                                      `json:"supportChangeMode"`  // Supports mode change
	Version           string                                    `json:"version"`            // Firmware version
	AlarmState        LeakSensorGetStateResponseStateAlarmState `json:"alarmState"`
}

func (r LeakSensorGetStateResponseState) String() string {
	var ptr0 any = "<nil>"
	if r.Interval != nil {
		ptr0 = fmt.Sprint(*r.Interval)
	}
	return fmt.Sprintf("{State:%v Battery:%v Beep:%v DevTemperature:%v Interval:%v Sensitivity:%v SensorMode:%v StateChangedAt:%v SupportChangeMode:%v Version:%v AlarmState:%v}", r.State, r.Battery, r.Beep, r.DevTemperature, ptr0, r.Sensitivity, r.SensorMode, r.StateChangedAt, r.SupportChangeMode, r.Version, r.AlarmState)
}

type LeakSensorGetStateResponse struct {
	Online   bool                            `json:"online"` // Is device online
	State    LeakSensorGetStateResponseState `json:"state"`
	ReportAt time.Time                       `json:"reportAt"` // Report time
	DeviceId string                          `json:"deviceId"` // Device ID
}

func (r LeakSensorGetStateResponse) String() string {
	return fmt.Sprintf("{Online:%v State:%v ReportAt:%v DeviceId:%v}", r.Online, r.State, r.ReportAt, r.DeviceId)
}

// GetState Get Leak Sensor's State
func (device *LeakSensor) GetState() (LeakSensorGetStateResponse, error) {
	var response LeakSensorGetStateResponse
	err := device.Call("LeakSensor.getState", nil, &response)
	return response, err
}

func (device *LeakSensor) GetStateAsync() <-chan controller.AsyncResult[LeakSensorGetStateResponse] {
	return controller.DecodeAsync[LeakSensorGetStateResponse](device.CallAsync("LeakSensor.getState", nil))
}

type LeakSensorSetSettingsParams struct {
	Interval    *int                         `json:"interval,omitempty"`    // Continuous alarm interval minutes
	Beep        *bool                        `json:"beep,omitempty"`        // Enable beep on alert
	SensorMode  *types.LeakSensorMode        `json:"sensorMode,omitempty"`  // Work mode ['WaterPeak','WaterLeak']
	Sensitivity *types.LeakSensorSensitivity `json:"sensitivity,omitempty"` // ['low','high']
}

func (r LeakSensorSetSettingsParams) String() string {
	var ptr0 any = "<nil>"
	if r.Interval != nil {
		ptr0 = fmt.Sprint(*r.Interval)
	}
	var ptr1 any = "<nil>"
	if r.Beep != nil {
		ptr1 = fmt.Sprint(*r.Beep)
	}
	var ptr2 any = "<nil>"
	if r.SensorMode != nil {
		ptr2 = fmt.Sprint(*r.SensorMode)
	}
	var ptr3 any = "<nil>"
	if r.Sensitivity != nil {
		ptr3 = fmt.Sprint(*r.Sensitivity)
	}
	return fmt.Sprintf("{Interval:%v Beep:%v SensorMode:%v Sensitivity:%v}", ptr0, ptr1, ptr2, ptr3)
}

// SetSettings Set settings for leak sensor
func (device *LeakSensor) SetSettings(params LeakSensorSetSettingsParams) error {
	return device.Call("LeakSensor.setSettings", params, nil)
}

func (device *LeakSensor) SetSettingsAsync(params LeakSensorSetSettingsParams) <-chan controller.AsyncResult[any] {
	return controller.DecodeAsync[any](device.CallAsync("LeakSensor.setSettings", params))
}

type LeakSensorGetActivityLogsParamsSearch struct {
	StartDate *string `json:"startDate,omitempty"` // YYYY-MM-DD
	EndDate   *string `json:"endDate,omitempty"`   // YYYY-MM-DD
}

func (r LeakSensorGetActivityLogsParamsSearch) String() string {
	var ptr0 any = "<nil>"
	if r.StartDate != nil {
		ptr0 = fmt.Sprint(*r.StartDate)
	}
	var ptr1 any = "<nil>"
	if r.EndDate != nil {
		ptr1 = fmt.Sprint(*r.EndDate)
	}
	return fmt.Sprintf("{StartDate:%v EndDate:%v}", ptr0, ptr1)
}

type LeakSensorGetActivityLogsParams struct {
	Search       LeakSensorGetActivityLogsParamsSearch `json:"search"`
	RetrievalKey *string                               `json:"retrievalKey,omitempty"` // Retrieval key
}

func (r LeakSensorGetActivityLogsParams) String() string {
	var ptr0 any = "<nil>"
	if r.RetrievalKey != nil {
		ptr0 = fmt.Sprint(*r.RetrievalKey)
	}
	return fmt.Sprintf("{Search:%v RetrievalKey:%v}", r.Search, ptr0)
}

type LeakSensorGetActivityLogsResponseLogsItem struct {
	Id   string      `json:"id"`
	Time time.Time   `json:"time"`
	Data interface{} `json:"data"`
}

func (r LeakSensorGetActivityLogsResponseLogsItem) String() string {
	return fmt.Sprintf("{Id:%v Time:%v Data:%v}", r.Id, r.Time, r.Data)
}

type LeakSensorGetActivityLogsResponseRetrievalKeys struct {
	Next *interface{} `json:"next,omitempty"`
}

func (r LeakSensorGetActivityLogsResponseRetrievalKeys) String() string {
	var ptr0 any = "<nil>"
	if r.Next != nil {
		ptr0 = fmt.Sprint(*r.Next)
	}
	return fmt.Sprintf("{Next:%v}", ptr0)
}

type LeakSensorGetActivityLogsResponse struct {
	Logs          []LeakSensorGetActivityLogsResponseLogsItem    `json:"logs"`
	RetrievalKeys LeakSensorGetActivityLogsResponseRetrievalKeys `json:"retrievalKeys"`
}

func (r LeakSensorGetActivityLogsResponse) String() string {
	return fmt.Sprintf("{Logs:%v RetrievalKeys:%v}", r.Logs, r.RetrievalKeys)
}

// GetActivityLogs Retrieve device activity records. Requires DEVICE.HISTORICAL_DATA.READ permission.
func (device *LeakSensor) GetActivityLogs(params LeakSensorGetActivityLogsParams) (LeakSensorGetActivityLogsResponse, error) {
	var response LeakSensorGetActivityLogsResponse
	err := device.Call("LeakSensor.getActivityLogs", params, &response)
	return response, err
}

func (device *LeakSensor) GetActivityLogsAsync(params LeakSensorGetActivityLogsParams) <-chan controller.AsyncResult[LeakSensorGetActivityLogsResponse] {
	return controller.DecodeAsync[LeakSensorGetActivityLogsResponse](device.CallAsync("LeakSensor.getActivityLogs", params))
}

type LeakSensorReportResponseAlarmState struct {
	StayError     bool `json:"stayError"`
	DetectorError bool `json:"detectorError"`
	FreezeError   bool `json:"freezeError"`
	Reminder      bool `json:"reminder"`
}

func (r LeakSensorReportResponseAlarmState) String() string {
	return fmt.Sprintf("{StayError:%v DetectorError:%v FreezeError:%v Reminder:%v}", r.StayError, r.DetectorError, r.FreezeError, r.Reminder)
}

type LeakSensorReportResponse struct {
	SensorMode        string                             `json:"sensorMode"` // WaterLeak | ...
	SupportChangeMode bool                               `json:"supportChangeMode"`
	State             types.AlarmState                   `json:"state"`
	AlarmState        LeakSensorReportResponseAlarmState `json:"alarmState"`
	Battery           types.BatteryLevel                 `json:"battery"`
	Interval          int                                `json:"interval"`
	Version           string                             `json:"version"`
	DevTemperature    *int                               `json:"devTemperature,omitempty"`
	LoraInfo          *types.LoraInfo                    `json:"loraInfo,omitempty"`
	StateChangedAt    types.Timestamp                    `json:"stateChangedAt"`
}

func (r LeakSensorReportResponse) String() string {
	var ptr0 any = "<nil>"
	if r.DevTemperature != nil {
		ptr0 = fmt.Sprint(*r.DevTemperature)
	}
	var ptr1 any = "<nil>"
	if r.LoraInfo != nil {
		ptr1 = fmt.Sprint(*r.LoraInfo)
	}
	return fmt.Sprintf("{SensorMode:%v SupportChangeMode:%v State:%v AlarmState:%v Battery:%v Interval:%v Version:%v DevTemperature:%v LoraInfo:%v StateChangedAt:%v}", r.SensorMode, r.SupportChangeMode, r.State, r.AlarmState, r.Battery, r.Interval, r.Version, ptr0, ptr1, r.StateChangedAt)
}

type LeakSensorAlertResponseAlarmState struct {
	StayError     bool `json:"stayError"`
	DetectorError bool `json:"detectorError"`
	FreezeError   bool `json:"freezeError"`
	Reminder      bool `json:"reminder"`
}

func (r LeakSensorAlertResponseAlarmState) String() string {
	return fmt.Sprintf("{StayError:%v DetectorError:%v FreezeError:%v Reminder:%v}", r.StayError, r.DetectorError, r.FreezeError, r.Reminder)
}

type LeakSensorAlertResponse struct {
	State             types.AlarmState                  `json:"state"`              // ['normal','alert']
	Battery           types.BatteryLevel                `json:"battery"`            // Battery level 0-4
	Beep              bool                              `json:"beep"`               // Is sounding alarm
	DevTemperature    int                               `json:"devTemperature"`     // Device temperature
	Interval          *int                              `json:"interval,omitempty"` // Continuous alert interval
	Sensitivity       types.LeakSensorSensitivity       `json:"sensitivity"`        // Sensitivity level
	SensorMode        types.LeakSensorMode              `json:"sensorMode"`         // Operating mode
	StateChangedAt    *types.Timestamp                  `json:"stateChangedAt,omitempty"`
	SupportChangeMode bool                              `json:"supportChangeMode"` // Supports mode change
	Version           string                            `json:"version"`           // Firmware version
	AlarmState        LeakSensorAlertResponseAlarmState `json:"alarmState"`
	LoraInfo          *types.LoraInfo                   `json:"loraInfo,omitempty"`
}

func (r LeakSensorAlertResponse) String() string {
	var ptr0 any = "<nil>"
	if r.Interval != nil {
		ptr0 = fmt.Sprint(*r.Interval)
	}
	var ptr1 any = "<nil>"
	if r.StateChangedAt != nil {
		ptr1 = fmt.Sprint(*r.StateChangedAt)
	}
	var ptr2 any = "<nil>"
	if r.LoraInfo != nil {
		ptr2 = fmt.Sprint(*r.LoraInfo)
	}
	return fmt.Sprintf("{State:%v Battery:%v Beep:%v DevTemperature:%v Interval:%v Sensitivity:%v SensorMode:%v StateChangedAt:%v SupportChangeMode:%v Version:%v AlarmState:%v LoraInfo:%v}", r.State, r.Battery, r.Beep, r.DevTemperature, ptr0, r.Sensitivity, r.SensorMode, ptr1, r.SupportChangeMode, r.Version, r.AlarmState, ptr2)
}

type LeakSensorStatusChangeResponseAlarmState struct {
	StayError     bool `json:"stayError"`
	DetectorError bool `json:"detectorError"`
	FreezeError   bool `json:"freezeError"`
	Reminder      bool `json:"reminder"`
}

func (r LeakSensorStatusChangeResponseAlarmState) String() string {
	return fmt.Sprintf("{StayError:%v DetectorError:%v FreezeError:%v Reminder:%v}", r.StayError, r.DetectorError, r.FreezeError, r.Reminder)
}

type LeakSensorStatusChangeResponse struct {
	SensorMode     string                                   `json:"sensorMode"` // WaterLeak | ...
	State          types.AlarmState                         `json:"state"`
	AlarmState     LeakSensorStatusChangeResponseAlarmState `json:"alarmState"`
	Battery        types.BatteryLevel                       `json:"battery"`
	Version        string                                   `json:"version"`
	DevTemperature *int                                     `json:"devTemperature,omitempty"`
	LoraInfo       *types.LoraInfo                          `json:"loraInfo,omitempty"`
	StateChangedAt types.Timestamp                          `json:"stateChangedAt"`
}

func (r LeakSensorStatusChangeResponse) String() string {
	var ptr0 any = "<nil>"
	if r.DevTemperature != nil {
		ptr0 = fmt.Sprint(*r.DevTemperature)
	}
	var ptr1 any = "<nil>"
	if r.LoraInfo != nil {
		ptr1 = fmt.Sprint(*r.LoraInfo)
	}
	return fmt.Sprintf("{SensorMode:%v State:%v AlarmState:%v Battery:%v Version:%v DevTemperature:%v LoraInfo:%v StateChangedAt:%v}", r.SensorMode, r.State, r.AlarmState, r.Battery, r.Version, ptr0, ptr1, r.StateChangedAt)
}

func (device *LeakSensor) ParseEvent(message controller.MqttMessage) (controller.Report, bool) {
	report, ok := device.Device.ParseEvent(message) // base impl decodes event + raw data
	if !ok {
		return report, false
	}
	report.Device = device                        // attribute the report to this concrete device
	data := report.Data.(controller.Unknown).Json // raw payload, re-typed below
	switch report.Event {
	case "LeakSensor.getState":
		var response LeakSensorGetStateResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "LeakSensor.getActivityLogs":
		var response LeakSensorGetActivityLogsResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "LeakSensor.Report":
		var response LeakSensorReportResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "LeakSensor.Alert":
		var response LeakSensorAlertResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "LeakSensor.StatusChange":
		var response LeakSensorStatusChangeResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	}
	return report, true
}
