// Code generated by scripts/gen_device_types.py; DO NOT EDIT.
package devices

import (
	"encoding/json"
	"fmt"
	"time"

	"github.com/tyandl/homelink/pkg/yolink/controller"
	"github.com/tyandl/homelink/pkg/yolink/types"
)

type Lock struct{ *controller.Device }

func init() {
	controller.RegisterDeviceFactory("Lock", func(device *controller.Device) controller.DeviceController {
		return &Lock{Device: device}
	})
}

type LockFetchStateResponseState struct {
	State   types.LockState    `json:"state"`   // ['locked','unlocked']
	Battery types.BatteryLevel `json:"battery"` // Battery level 0-4
}

func (r LockFetchStateResponseState) String() string {
	return fmt.Sprintf("{State:%v Battery:%v}", r.State, r.Battery)
}

type LockFetchStateResponse struct {
	State   LockFetchStateResponseState `json:"state"`
	Version string                      `json:"version"` // Firmware version
	Tz      int                         `json:"tz"`      // Timezone -12~12
}

func (r LockFetchStateResponse) String() string {
	return fmt.Sprintf("{State:%v Version:%v Tz:%v}", r.State, r.Version, r.Tz)
}

// FetchState Fetch current status from cache
func (device *Lock) FetchState() (LockFetchStateResponse, error) {
	var response LockFetchStateResponse
	err := device.Call("Lock.fetchState", nil, &response)
	return response, err
}

func (device *Lock) FetchStateAsync() <-chan controller.AsyncResult[LockFetchStateResponse] {
	return controller.DecodeAsync[LockFetchStateResponse](device.CallAsync("Lock.fetchState", nil))
}

type LockGetStateResponse struct {
	State    types.LockState    `json:"state"`           // ['locked','unlocked']
	Battery  types.BatteryLevel `json:"battery"`         // Battery level 0-4
	RlSet    *types.LatchSide   `json:"rlSet,omitempty"` // Latch orientation ['left','right']
	LoraInfo *types.LoraInfo    `json:"loraInfo,omitempty"`
}

func (r LockGetStateResponse) String() string {
	var ptr0 any = "<nil>"
	if r.RlSet != nil {
		ptr0 = fmt.Sprint(*r.RlSet)
	}
	var ptr1 any = "<nil>"
	if r.LoraInfo != nil {
		ptr1 = fmt.Sprint(*r.LoraInfo)
	}
	return fmt.Sprintf("{State:%v Battery:%v RlSet:%v LoraInfo:%v}", r.State, r.Battery, ptr0, ptr1)
}

// GetState Get current status from device
func (device *Lock) GetState() (LockGetStateResponse, error) {
	var response LockGetStateResponse
	err := device.Call("Lock.getState", nil, &response)
	return response, err
}

func (device *Lock) GetStateAsync() <-chan controller.AsyncResult[LockGetStateResponse] {
	return controller.DecodeAsync[LockGetStateResponse](device.CallAsync("Lock.getState", nil))
}

type LockSetStateParams struct {
	State types.LockState `json:"state"` // ['locked','unlocked']
}

func (r LockSetStateParams) String() string {
	return fmt.Sprintf("{State:%v}", r.State)
}

type LockSetStateResponse struct {
	State    types.LockState `json:"state"` // ['locked','unlocked']
	LoraInfo *types.LoraInfo `json:"loraInfo,omitempty"`
	Source   *string         `json:"source,omitempty"` // Origin of the change, e.g. 'app'
}

func (r LockSetStateResponse) String() string {
	var ptr0 any = "<nil>"
	if r.LoraInfo != nil {
		ptr0 = fmt.Sprint(*r.LoraInfo)
	}
	var ptr1 any = "<nil>"
	if r.Source != nil {
		ptr1 = fmt.Sprint(*r.Source)
	}
	return fmt.Sprintf("{State:%v LoraInfo:%v Source:%v}", r.State, ptr0, ptr1)
}

// SetState Lock or unlock the door (INFERRED: not officially part of the YoLink API; modeled after LockV2.setState and the observed Lock.setState report)
func (device *Lock) SetState(params LockSetStateParams) (LockSetStateResponse, error) {
	var response LockSetStateResponse
	err := device.Call("Lock.setState", params, &response)
	return response, err
}

func (device *Lock) SetStateAsync(params LockSetStateParams) <-chan controller.AsyncResult[LockSetStateResponse] {
	return controller.DecodeAsync[LockSetStateResponse](device.CallAsync("Lock.setState", params))
}

type LockListPasswordsParams struct {
	Limit  int  `json:"limit"`            // List size max 10
	Offset *int `json:"offset,omitempty"` // List offset default 0
}

func (r LockListPasswordsParams) String() string {
	var ptr0 any = "<nil>"
	if r.Offset != nil {
		ptr0 = fmt.Sprint(*r.Offset)
	}
	return fmt.Sprintf("{Limit:%v Offset:%v}", r.Limit, ptr0)
}

type LockListPasswordsResponseItemsItem struct {
	Index int       `json:"index"` // Password index
	Start time.Time `json:"start"` // Active from
	End   time.Time `json:"end"`   // Expires at
	Pwd   string    `json:"pwd"`   // Password
}

func (r LockListPasswordsResponseItemsItem) String() string {
	return fmt.Sprintf("{Index:%v Start:%v End:%v Pwd:%v}", r.Index, r.Start, r.End, r.Pwd)
}

type LockListPasswordsResponse struct {
	Offset int                                  `json:"offset"`
	Limit  int                                  `json:"limit"`
	Total  int                                  `json:"total"`
	Items  []LockListPasswordsResponseItemsItem `json:"items"`
}

func (r LockListPasswordsResponse) String() string {
	return fmt.Sprintf("{Offset:%v Limit:%v Total:%v Items:%v}", r.Offset, r.Limit, r.Total, r.Items)
}

// ListPasswords Get the list of passwords from the device
func (device *Lock) ListPasswords(params LockListPasswordsParams) (LockListPasswordsResponse, error) {
	var response LockListPasswordsResponse
	err := device.Call("Lock.listPasswords", params, &response)
	return response, err
}

func (device *Lock) ListPasswordsAsync(params LockListPasswordsParams) <-chan controller.AsyncResult[LockListPasswordsResponse] {
	return controller.DecodeAsync[LockListPasswordsResponse](device.CallAsync("Lock.listPasswords", params))
}

type LockGenerateOTPParams struct {
	Pwd *string `json:"pwd,omitempty"` // 4-digit OTP matching /^\d{4}$/
}

func (r LockGenerateOTPParams) String() string {
	var ptr0 any = "<nil>"
	if r.Pwd != nil {
		ptr0 = fmt.Sprint(*r.Pwd)
	}
	return fmt.Sprintf("{Pwd:%v}", ptr0)
}

type LockGenerateOTPResponse struct {
	Success bool `json:"success"`
}

func (r LockGenerateOTPResponse) String() string {
	return fmt.Sprintf("{Success:%v}", r.Success)
}

// GenerateOTP Set a One Time Password
func (device *Lock) GenerateOTP(params LockGenerateOTPParams) (LockGenerateOTPResponse, error) {
	var response LockGenerateOTPResponse
	err := device.Call("Lock.generateOTP", params, &response)
	return response, err
}

func (device *Lock) GenerateOTPAsync(params LockGenerateOTPParams) <-chan controller.AsyncResult[LockGenerateOTPResponse] {
	return controller.DecodeAsync[LockGenerateOTPResponse](device.CallAsync("Lock.generateOTP", params))
}

type LockAddPasswordParams struct {
	Pwd   string          `json:"pwd"`   // 4-8 digit password
	Start types.Timestamp `json:"start"` // Active from (ms)
	End   types.Timestamp `json:"end"`   // Expires at (ms)
}

func (r LockAddPasswordParams) String() string {
	return fmt.Sprintf("{Pwd:%v Start:%v End:%v}", r.Pwd, r.Start, r.End)
}

type LockAddPasswordResponse struct {
	Success bool `json:"success"`
}

func (r LockAddPasswordResponse) String() string {
	return fmt.Sprintf("{Success:%v}", r.Success)
}

// AddPassword Set a new password to device
func (device *Lock) AddPassword(params LockAddPasswordParams) (LockAddPasswordResponse, error) {
	var response LockAddPasswordResponse
	err := device.Call("Lock.addPassword", params, &response)
	return response, err
}

func (device *Lock) AddPasswordAsync(params LockAddPasswordParams) <-chan controller.AsyncResult[LockAddPasswordResponse] {
	return controller.DecodeAsync[LockAddPasswordResponse](device.CallAsync("Lock.addPassword", params))
}

type LockUpdatePasswordParams struct {
	OldPwd interface{}     `json:"oldPwd"` // Password or index to update
	Pwd    string          `json:"pwd"`    // New 4-8 digit password
	Start  types.Timestamp `json:"start"`  // New active from (ms)
	End    types.Timestamp `json:"end"`    // New expires at (ms)
}

func (r LockUpdatePasswordParams) String() string {
	return fmt.Sprintf("{OldPwd:%v Pwd:%v Start:%v End:%v}", r.OldPwd, r.Pwd, r.Start, r.End)
}

type LockUpdatePasswordResponse struct {
	Success bool `json:"success"`
}

func (r LockUpdatePasswordResponse) String() string {
	return fmt.Sprintf("{Success:%v}", r.Success)
}

// UpdatePassword Update an existing password in device
func (device *Lock) UpdatePassword(params LockUpdatePasswordParams) (LockUpdatePasswordResponse, error) {
	var response LockUpdatePasswordResponse
	err := device.Call("Lock.updatePassword", params, &response)
	return response, err
}

func (device *Lock) UpdatePasswordAsync(params LockUpdatePasswordParams) <-chan controller.AsyncResult[LockUpdatePasswordResponse] {
	return controller.DecodeAsync[LockUpdatePasswordResponse](device.CallAsync("Lock.updatePassword", params))
}

type LockDelPasswordParams struct {
	Pwd interface{} `json:"pwd"` // Password or index to delete
}

func (r LockDelPasswordParams) String() string {
	return fmt.Sprintf("{Pwd:%v}", r.Pwd)
}

type LockDelPasswordResponse struct {
	Success bool `json:"success"`
}

func (r LockDelPasswordResponse) String() string {
	return fmt.Sprintf("{Success:%v}", r.Success)
}

// DelPassword Delete an existing password in device
func (device *Lock) DelPassword(params LockDelPasswordParams) (LockDelPasswordResponse, error) {
	var response LockDelPasswordResponse
	err := device.Call("Lock.delPassword", params, &response)
	return response, err
}

func (device *Lock) DelPasswordAsync(params LockDelPasswordParams) <-chan controller.AsyncResult[LockDelPasswordResponse] {
	return controller.DecodeAsync[LockDelPasswordResponse](device.CallAsync("Lock.delPassword", params))
}

type LockClearPasswordResponse struct {
	Success bool `json:"success"`
}

func (r LockClearPasswordResponse) String() string {
	return fmt.Sprintf("{Success:%v}", r.Success)
}

// ClearPassword Clear all passwords in device
func (device *Lock) ClearPassword() (LockClearPasswordResponse, error) {
	var response LockClearPasswordResponse
	err := device.Call("Lock.clearPassword", nil, &response)
	return response, err
}

func (device *Lock) ClearPasswordAsync() <-chan controller.AsyncResult[LockClearPasswordResponse] {
	return controller.DecodeAsync[LockClearPasswordResponse](device.CallAsync("Lock.clearPassword", nil))
}

type LockGetVersionResponseNewVersion struct {
	VersionId   *string `json:"versionId,omitempty"`
	VersionCode *string `json:"versionCode,omitempty"`
	FileSize    *string `json:"fileSize,omitempty"`
}

func (r LockGetVersionResponseNewVersion) String() string {
	var ptr0 any = "<nil>"
	if r.VersionId != nil {
		ptr0 = fmt.Sprint(*r.VersionId)
	}
	var ptr1 any = "<nil>"
	if r.VersionCode != nil {
		ptr1 = fmt.Sprint(*r.VersionCode)
	}
	var ptr2 any = "<nil>"
	if r.FileSize != nil {
		ptr2 = fmt.Sprint(*r.FileSize)
	}
	return fmt.Sprintf("{VersionId:%v VersionCode:%v FileSize:%v}", ptr0, ptr1, ptr2)
}

type LockGetVersionResponse struct {
	Version    string                           `json:"version"` // Current version
	NewVersion LockGetVersionResponseNewVersion `json:"newVersion"`
}

func (r LockGetVersionResponse) String() string {
	return fmt.Sprintf("{Version:%v NewVersion:%v}", r.Version, r.NewVersion)
}

// GetVersion Get firmware info
func (device *Lock) GetVersion() (LockGetVersionResponse, error) {
	var response LockGetVersionResponse
	err := device.Call("Lock.getVersion", nil, &response)
	return response, err
}

func (device *Lock) GetVersionAsync() <-chan controller.AsyncResult[LockGetVersionResponse] {
	return controller.DecodeAsync[LockGetVersionResponse](device.CallAsync("Lock.getVersion", nil))
}

type LockStartUpgradeParams struct {
	VersionId string `json:"versionId"` // Version ID
}

func (r LockStartUpgradeParams) String() string {
	return fmt.Sprintf("{VersionId:%v}", r.VersionId)
}

type LockStartUpgradeResponse struct {
	IsStarted bool `json:"isStarted"`
}

func (r LockStartUpgradeResponse) String() string {
	return fmt.Sprintf("{IsStarted:%v}", r.IsStarted)
}

// StartUpgrade Start firmware upgrade
func (device *Lock) StartUpgrade(params LockStartUpgradeParams) (LockStartUpgradeResponse, error) {
	var response LockStartUpgradeResponse
	err := device.Call("Lock.startUpgrade", params, &response)
	return response, err
}

func (device *Lock) StartUpgradeAsync(params LockStartUpgradeParams) <-chan controller.AsyncResult[LockStartUpgradeResponse] {
	return controller.DecodeAsync[LockStartUpgradeResponse](device.CallAsync("Lock.startUpgrade", params))
}

type LockStatusChangeResponse struct {
	State    types.LockState    `json:"state"`
	Battery  types.BatteryLevel `json:"battery"`
	RlSet    *string            `json:"rlSet,omitempty"` // right | left
	LoraInfo *types.LoraInfo    `json:"loraInfo,omitempty"`
}

func (r LockStatusChangeResponse) String() string {
	var ptr0 any = "<nil>"
	if r.RlSet != nil {
		ptr0 = fmt.Sprint(*r.RlSet)
	}
	var ptr1 any = "<nil>"
	if r.LoraInfo != nil {
		ptr1 = fmt.Sprint(*r.LoraInfo)
	}
	return fmt.Sprintf("{State:%v Battery:%v RlSet:%v LoraInfo:%v}", r.State, r.Battery, ptr0, ptr1)
}

type LockReportResponse struct {
	State    types.LockState    `json:"state"`
	Battery  types.BatteryLevel `json:"battery"`
	RlSet    *string            `json:"rlSet,omitempty"` // right | left
	Tz       *int               `json:"tz,omitempty"`
	Version  string             `json:"version"`
	LoraInfo *types.LoraInfo    `json:"loraInfo,omitempty"`
}

func (r LockReportResponse) String() string {
	var ptr0 any = "<nil>"
	if r.RlSet != nil {
		ptr0 = fmt.Sprint(*r.RlSet)
	}
	var ptr1 any = "<nil>"
	if r.Tz != nil {
		ptr1 = fmt.Sprint(*r.Tz)
	}
	var ptr2 any = "<nil>"
	if r.LoraInfo != nil {
		ptr2 = fmt.Sprint(*r.LoraInfo)
	}
	return fmt.Sprintf("{State:%v Battery:%v RlSet:%v Tz:%v Version:%v LoraInfo:%v}", r.State, r.Battery, ptr0, ptr1, r.Version, ptr2)
}

type LockAlertResponse struct {
	State          types.LockState    `json:"state"`           // ['locked','unlocked']
	Battery        types.BatteryLevel `json:"battery"`         // Battery level 0-4
	RlSet          *types.LatchSide   `json:"rlSet,omitempty"` // Latch orientation ['left','right']
	LoraInfo       *types.LoraInfo    `json:"loraInfo,omitempty"`
	StateChangedAt *types.Timestamp   `json:"stateChangedAt,omitempty"`
}

func (r LockAlertResponse) String() string {
	var ptr0 any = "<nil>"
	if r.RlSet != nil {
		ptr0 = fmt.Sprint(*r.RlSet)
	}
	var ptr1 any = "<nil>"
	if r.LoraInfo != nil {
		ptr1 = fmt.Sprint(*r.LoraInfo)
	}
	var ptr2 any = "<nil>"
	if r.StateChangedAt != nil {
		ptr2 = fmt.Sprint(*r.StateChangedAt)
	}
	return fmt.Sprintf("{State:%v Battery:%v RlSet:%v LoraInfo:%v StateChangedAt:%v}", r.State, r.Battery, ptr0, ptr1, ptr2)
}

func (device *Lock) ParseEvent(message controller.MqttMessage) (controller.Report, bool) {
	report, ok := device.Device.ParseEvent(message) // base impl decodes event + raw data
	if !ok {
		return report, false
	}
	report.Device = device                        // attribute the report to this concrete device
	data := report.Data.(controller.Unknown).Json // raw payload, re-typed below
	switch report.Event {
	case "Lock.fetchState":
		var response LockFetchStateResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "Lock.getState":
		var response LockGetStateResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "Lock.setState":
		var response LockSetStateResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "Lock.listPasswords":
		var response LockListPasswordsResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "Lock.generateOTP":
		var response LockGenerateOTPResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "Lock.addPassword":
		var response LockAddPasswordResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "Lock.updatePassword":
		var response LockUpdatePasswordResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "Lock.delPassword":
		var response LockDelPasswordResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "Lock.clearPassword":
		var response LockClearPasswordResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "Lock.getVersion":
		var response LockGetVersionResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "Lock.startUpgrade":
		var response LockStartUpgradeResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "Lock.StatusChange":
		var response LockStatusChangeResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "Lock.Report":
		var response LockReportResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "Lock.Alert":
		var response LockAlertResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	}
	return report, true
}
