// Code generated by scripts/gen_device_types.py; DO NOT EDIT.
package devices

import (
	"encoding/json"
	"fmt"

	"github.com/tyandl/homelink/pkg/yolink/controller"
	"github.com/tyandl/homelink/pkg/yolink/types"
)

type LockV2 struct{ *controller.Device }

func init() {
	controller.RegisterDeviceFactory("LockV2", func(device *controller.Device) controller.DeviceController {
		return &LockV2{Device: device}
	})
}

type LockV2FetchStateResponseStateState struct {
	Lock types.LockState `json:"lock"` // ['locked','unlocked']
}

func (r LockV2FetchStateResponseStateState) String() string {
	return fmt.Sprintf("{Lock:%v}", r.Lock)
}

type LockV2FetchStateResponseStateAttributes struct {
	AutoLock        int                  `json:"autoLock"` // Auto lock duration seconds; 0=disable
	EnableSetButton bool                 `json:"enableSetButton"`
	RlSet           types.LatchSide      `json:"rlSet"`      // ['left','right']
	SoundLevel      types.LockSoundLevel `json:"soundLevel"` // [0-3] mute/low/medium/high
}

func (r LockV2FetchStateResponseStateAttributes) String() string {
	return fmt.Sprintf("{AutoLock:%v EnableSetButton:%v RlSet:%v SoundLevel:%v}", r.AutoLock, r.EnableSetButton, r.RlSet, r.SoundLevel)
}

type LockV2FetchStateResponseState struct {
	State      LockV2FetchStateResponseStateState      `json:"state"`
	Attributes LockV2FetchStateResponseStateAttributes `json:"attributes"`
	Battery    types.BatteryLevel                      `json:"battery"` // 0-4
}

func (r LockV2FetchStateResponseState) String() string {
	return fmt.Sprintf("{State:%v Attributes:%v Battery:%v}", r.State, r.Attributes, r.Battery)
}

type LockV2FetchStateResponse struct {
	State     LockV2FetchStateResponseState `json:"state"`
	HwVersion string                        `json:"hwVersion"` // Hardware version
	Version   string                        `json:"version"`   // Firmware version
	Tz        int                           `json:"tz"`
}

func (r LockV2FetchStateResponse) String() string {
	return fmt.Sprintf("{State:%v HwVersion:%v Version:%v Tz:%v}", r.State, r.HwVersion, r.Version, r.Tz)
}

// FetchState Fetch current status from cache
func (device *LockV2) FetchState() (LockV2FetchStateResponse, error) {
	var response LockV2FetchStateResponse
	err := device.Call("LockV2.fetchState", nil, &response)
	return response, err
}

func (device *LockV2) FetchStateAsync() <-chan controller.AsyncResult[LockV2FetchStateResponse] {
	return controller.DecodeAsync[LockV2FetchStateResponse](device.CallAsync("LockV2.fetchState", nil))
}

type LockV2GetStateResponseState struct {
	Lock types.LockState `json:"lock"` // ['locked','unlocked']
}

func (r LockV2GetStateResponseState) String() string {
	return fmt.Sprintf("{Lock:%v}", r.Lock)
}

type LockV2GetStateResponseAttributes struct {
	AutoLock        int                  `json:"autoLock"`
	EnableSetButton bool                 `json:"enableSetButton"`
	RlSet           types.LatchSide      `json:"rlSet"`      // ['left','right']
	SoundLevel      types.LockSoundLevel `json:"soundLevel"` // [0-3]
}

func (r LockV2GetStateResponseAttributes) String() string {
	return fmt.Sprintf("{AutoLock:%v EnableSetButton:%v RlSet:%v SoundLevel:%v}", r.AutoLock, r.EnableSetButton, r.RlSet, r.SoundLevel)
}

type LockV2GetStateResponse struct {
	State      LockV2GetStateResponseState      `json:"state"`
	Attributes LockV2GetStateResponseAttributes `json:"attributes"`
	Battery    types.BatteryLevel               `json:"battery"`
	HwVersion  string                           `json:"hwVersion"`
	Version    string                           `json:"version"`
	Tz         int                              `json:"tz"`
}

func (r LockV2GetStateResponse) String() string {
	return fmt.Sprintf("{State:%v Attributes:%v Battery:%v HwVersion:%v Version:%v Tz:%v}", r.State, r.Attributes, r.Battery, r.HwVersion, r.Version, r.Tz)
}

// GetState Get current status from device
func (device *LockV2) GetState() (LockV2GetStateResponse, error) {
	var response LockV2GetStateResponse
	err := device.Call("LockV2.getState", nil, &response)
	return response, err
}

func (device *LockV2) GetStateAsync() <-chan controller.AsyncResult[LockV2GetStateResponse] {
	return controller.DecodeAsync[LockV2GetStateResponse](device.CallAsync("LockV2.getState", nil))
}

type LockV2SetStateParamsState struct {
	Lock types.LockState `json:"lock"` // ['locked','unlocked']
}

func (r LockV2SetStateParamsState) String() string {
	return fmt.Sprintf("{Lock:%v}", r.Lock)
}

type LockV2SetStateParams struct {
	State LockV2SetStateParamsState `json:"state"`
}

func (r LockV2SetStateParams) String() string {
	return fmt.Sprintf("{State:%v}", r.State)
}

type LockV2SetStateResponseState struct {
	Lock types.LockState `json:"lock"`
}

func (r LockV2SetStateResponseState) String() string {
	return fmt.Sprintf("{Lock:%v}", r.Lock)
}

type LockV2SetStateResponse struct {
	State LockV2SetStateResponseState `json:"state"`
}

func (r LockV2SetStateResponse) String() string {
	return fmt.Sprintf("{State:%v}", r.State)
}

// SetState Lock or Unlock the door
func (device *LockV2) SetState(params LockV2SetStateParams) (LockV2SetStateResponse, error) {
	var response LockV2SetStateResponse
	err := device.Call("LockV2.setState", params, &response)
	return response, err
}

func (device *LockV2) SetStateAsync(params LockV2SetStateParams) <-chan controller.AsyncResult[LockV2SetStateResponse] {
	return controller.DecodeAsync[LockV2SetStateResponse](device.CallAsync("LockV2.setState", params))
}

type LockV2SetAttributesParams struct {
	AutoLock        *int                  `json:"autoLock,omitempty"`   // Auto lock seconds; 0=disable
	RlSet           *types.LatchSide      `json:"rlSet,omitempty"`      // ['left','right']
	SoundLevel      *types.LockSoundLevel `json:"soundLevel,omitempty"` // [0-3]
	EnableSetButton *bool                 `json:"enableSetButton,omitempty"`
}

func (r LockV2SetAttributesParams) String() string {
	var ptr0 any = "<nil>"
	if r.AutoLock != nil {
		ptr0 = fmt.Sprint(*r.AutoLock)
	}
	var ptr1 any = "<nil>"
	if r.RlSet != nil {
		ptr1 = fmt.Sprint(*r.RlSet)
	}
	var ptr2 any = "<nil>"
	if r.SoundLevel != nil {
		ptr2 = fmt.Sprint(*r.SoundLevel)
	}
	var ptr3 any = "<nil>"
	if r.EnableSetButton != nil {
		ptr3 = fmt.Sprint(*r.EnableSetButton)
	}
	return fmt.Sprintf("{AutoLock:%v RlSet:%v SoundLevel:%v EnableSetButton:%v}", ptr0, ptr1, ptr2, ptr3)
}

type LockV2SetAttributesResponse struct {
	AutoLock        int                  `json:"autoLock"`
	RlSet           types.LatchSide      `json:"rlSet"`
	SoundLevel      types.LockSoundLevel `json:"soundLevel"`
	EnableSetButton bool                 `json:"enableSetButton"`
}

func (r LockV2SetAttributesResponse) String() string {
	return fmt.Sprintf("{AutoLock:%v RlSet:%v SoundLevel:%v EnableSetButton:%v}", r.AutoLock, r.RlSet, r.SoundLevel, r.EnableSetButton)
}

// SetAttributes Set lock attributes
func (device *LockV2) SetAttributes(params LockV2SetAttributesParams) (LockV2SetAttributesResponse, error) {
	var response LockV2SetAttributesResponse
	err := device.Call("LockV2.setAttributes", params, &response)
	return response, err
}

func (device *LockV2) SetAttributesAsync(params LockV2SetAttributesParams) <-chan controller.AsyncResult[LockV2SetAttributesResponse] {
	return controller.DecodeAsync[LockV2SetAttributesResponse](device.CallAsync("LockV2.setAttributes", params))
}

// UserManagement User and credential management. Use params.command to specify the operation.
func (device *LockV2) UserManagement() error {
	return device.Call("LockV2.userManagement", nil, nil)
}

func (device *LockV2) UserManagementAsync() <-chan controller.AsyncResult[any] {
	return controller.DecodeAsync[any](device.CallAsync("LockV2.userManagement", nil))
}

type LockV2ReportResponse struct {
	Lock     types.LockState `json:"lock"` // ['locked','unlocked']
	LoraInfo *types.LoraInfo `json:"loraInfo,omitempty"`
}

func (r LockV2ReportResponse) String() string {
	var ptr0 any = "<nil>"
	if r.LoraInfo != nil {
		ptr0 = fmt.Sprint(*r.LoraInfo)
	}
	return fmt.Sprintf("{Lock:%v LoraInfo:%v}", r.Lock, ptr0)
}

type LockV2AlertResponse struct {
	Lock           types.LockState  `json:"lock"` // ['locked','unlocked']
	LoraInfo       *types.LoraInfo  `json:"loraInfo,omitempty"`
	StateChangedAt *types.Timestamp `json:"stateChangedAt,omitempty"`
}

func (r LockV2AlertResponse) String() string {
	var ptr0 any = "<nil>"
	if r.LoraInfo != nil {
		ptr0 = fmt.Sprint(*r.LoraInfo)
	}
	var ptr1 any = "<nil>"
	if r.StateChangedAt != nil {
		ptr1 = fmt.Sprint(*r.StateChangedAt)
	}
	return fmt.Sprintf("{Lock:%v LoraInfo:%v StateChangedAt:%v}", r.Lock, ptr0, ptr1)
}

func (device *LockV2) ParseEvent(message controller.MqttMessage) (controller.Report, bool) {
	report, ok := device.Device.ParseEvent(message) // base impl decodes event + raw data
	if !ok {
		return report, false
	}
	report.Device = device                        // attribute the report to this concrete device
	data := report.Data.(controller.Unknown).Json // raw payload, re-typed below
	switch report.Event {
	case "LockV2.fetchState":
		var response LockV2FetchStateResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "LockV2.getState":
		var response LockV2GetStateResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "LockV2.setState":
		var response LockV2SetStateResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "LockV2.setAttributes":
		var response LockV2SetAttributesResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "LockV2.Report":
		var response LockV2ReportResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "LockV2.Alert":
		var response LockV2AlertResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	}
	return report, true
}
