// Code generated by scripts/gen_device_types.py; DO NOT EDIT.
package devices

import (
	"encoding/json"
	"fmt"
	"time"

	"github.com/tyandl/homelink/pkg/yolink/controller"
	"github.com/tyandl/homelink/pkg/yolink/types"
)

type Manipulator struct{ *controller.Device }

func init() {
	controller.RegisterDeviceFactory("Manipulator", func(device *controller.Device) controller.DeviceController {
		return &Manipulator{Device: device}
	})
}

type ManipulatorGetStateResponseDelay struct {
	On  *int `json:"on,omitempty"`  // Remain Delay ON minutes
	Off *int `json:"off,omitempty"` // Remain Delay OFF minutes
}

func (r ManipulatorGetStateResponseDelay) String() string {
	var ptr0 any = "<nil>"
	if r.On != nil {
		ptr0 = fmt.Sprint(*r.On)
	}
	var ptr1 any = "<nil>"
	if r.Off != nil {
		ptr1 = fmt.Sprint(*r.Off)
	}
	return fmt.Sprintf("{On:%v Off:%v}", ptr0, ptr1)
}

type ManipulatorGetStateResponse struct {
	State      types.SwitchState                `json:"state"` // ['closed','open']
	Delay      ManipulatorGetStateResponseDelay `json:"delay"`
	OpenRemind *int                             `json:"openRemind,omitempty"` // Open remind time; 0=disabled
	Version    string                           `json:"version"`              // Firmware version
	Tz         int                              `json:"tz"`                   // Timezone -12~12
}

func (r ManipulatorGetStateResponse) String() string {
	var ptr0 any = "<nil>"
	if r.OpenRemind != nil {
		ptr0 = fmt.Sprint(*r.OpenRemind)
	}
	return fmt.Sprintf("{State:%v Delay:%v OpenRemind:%v Version:%v Tz:%v}", r.State, r.Delay, ptr0, r.Version, r.Tz)
}

// GetState Get Current State
func (device *Manipulator) GetState() (ManipulatorGetStateResponse, error) {
	var response ManipulatorGetStateResponse
	err := device.Call("Manipulator.getState", nil, &response)
	return response, err
}

func (device *Manipulator) GetStateAsync() <-chan controller.AsyncResult[ManipulatorGetStateResponse] {
	return controller.DecodeAsync[ManipulatorGetStateResponse](device.CallAsync("Manipulator.getState", nil))
}

type ManipulatorSetStateParams struct {
	State types.SwitchCommand `json:"state"` // ['close','open']
}

func (r ManipulatorSetStateParams) String() string {
	return fmt.Sprintf("{State:%v}", r.State)
}

type ManipulatorSetStateResponse struct {
	State types.SwitchState `json:"state"` // ['closed','open']
}

func (r ManipulatorSetStateResponse) String() string {
	return fmt.Sprintf("{State:%v}", r.State)
}

// SetState Set Manipulator's State
func (device *Manipulator) SetState(params ManipulatorSetStateParams) (ManipulatorSetStateResponse, error) {
	var response ManipulatorSetStateResponse
	err := device.Call("Manipulator.setState", params, &response)
	return response, err
}

func (device *Manipulator) SetStateAsync(params ManipulatorSetStateParams) <-chan controller.AsyncResult[ManipulatorSetStateResponse] {
	return controller.DecodeAsync[ManipulatorSetStateResponse](device.CallAsync("Manipulator.setState", params))
}

type ManipulatorSetDelayParams struct {
	DelayOn  *int `json:"delayOn,omitempty"`  // Delay ON minutes; 0=cancel
	DelayOff *int `json:"delayOff,omitempty"` // Delay OFF minutes; 0=cancel
}

func (r ManipulatorSetDelayParams) String() string {
	var ptr0 any = "<nil>"
	if r.DelayOn != nil {
		ptr0 = fmt.Sprint(*r.DelayOn)
	}
	var ptr1 any = "<nil>"
	if r.DelayOff != nil {
		ptr1 = fmt.Sprint(*r.DelayOff)
	}
	return fmt.Sprintf("{DelayOn:%v DelayOff:%v}", ptr0, ptr1)
}

type ManipulatorSetDelayResponseDelay struct {
	On  *int `json:"on,omitempty"`
	Off *int `json:"off,omitempty"`
}

func (r ManipulatorSetDelayResponseDelay) String() string {
	var ptr0 any = "<nil>"
	if r.On != nil {
		ptr0 = fmt.Sprint(*r.On)
	}
	var ptr1 any = "<nil>"
	if r.Off != nil {
		ptr1 = fmt.Sprint(*r.Off)
	}
	return fmt.Sprintf("{On:%v Off:%v}", ptr0, ptr1)
}

type ManipulatorSetDelayResponse struct {
	Delay ManipulatorSetDelayResponseDelay `json:"delay"`
}

func (r ManipulatorSetDelayResponse) String() string {
	return fmt.Sprintf("{Delay:%v}", r.Delay)
}

// SetDelay Set delay to turn on/off Manipulator
func (device *Manipulator) SetDelay(params ManipulatorSetDelayParams) (ManipulatorSetDelayResponse, error) {
	var response ManipulatorSetDelayResponse
	err := device.Call("Manipulator.setDelay", params, &response)
	return response, err
}

func (device *Manipulator) SetDelayAsync(params ManipulatorSetDelayParams) <-chan controller.AsyncResult[ManipulatorSetDelayResponse] {
	return controller.DecodeAsync[ManipulatorSetDelayResponse](device.CallAsync("Manipulator.setDelay", params))
}

type ManipulatorGetSchedulesResponse = []struct {
	IsValid bool    `json:"isValid"`
	Index   int     `json:"index"`
	On      *string `json:"on,omitempty"`  // HH:mm
	Off     *string `json:"off,omitempty"` // HH:mm
	Week    int     `json:"week"`          // Weekday mask
}

// GetSchedules Get Schedule List
func (device *Manipulator) GetSchedules() (ManipulatorGetSchedulesResponse, error) {
	var response ManipulatorGetSchedulesResponse
	err := device.Call("Manipulator.getSchedules", nil, &response)
	return response, err
}

func (device *Manipulator) GetSchedulesAsync() <-chan controller.AsyncResult[ManipulatorGetSchedulesResponse] {
	return controller.DecodeAsync[ManipulatorGetSchedulesResponse](device.CallAsync("Manipulator.getSchedules", nil))
}

type ManipulatorSetSchedulesParamsSchesItem struct {
	IsValid bool   `json:"isValid"`
	Index   int    `json:"index"`
	On      string `json:"on"`   // HH:mm
	Off     string `json:"off"`  // HH:mm
	Week    int    `json:"week"` // Weekday mask
}

func (r ManipulatorSetSchedulesParamsSchesItem) String() string {
	return fmt.Sprintf("{IsValid:%v Index:%v On:%v Off:%v Week:%v}", r.IsValid, r.Index, r.On, r.Off, r.Week)
}

type ManipulatorSetSchedulesParams struct {
	Sches []ManipulatorSetSchedulesParamsSchesItem `json:"sches"`
}

func (r ManipulatorSetSchedulesParams) String() string {
	return fmt.Sprintf("{Sches:%v}", r.Sches)
}

type ManipulatorSetSchedulesResponse = []struct {
	IsValid bool    `json:"isValid"`
	Index   int     `json:"index"`
	On      *string `json:"on,omitempty"`  // HH:mm
	Off     *string `json:"off,omitempty"` // HH:mm
	Week    int     `json:"week"`          // Weekday mask
}

// SetSchedules Set Schedule (index 0-5)
func (device *Manipulator) SetSchedules(params ManipulatorSetSchedulesParams) (ManipulatorSetSchedulesResponse, error) {
	var response ManipulatorSetSchedulesResponse
	err := device.Call("Manipulator.setSchedules", params, &response)
	return response, err
}

func (device *Manipulator) SetSchedulesAsync(params ManipulatorSetSchedulesParams) <-chan controller.AsyncResult[ManipulatorSetSchedulesResponse] {
	return controller.DecodeAsync[ManipulatorSetSchedulesResponse](device.CallAsync("Manipulator.setSchedules", params))
}

type ManipulatorGetVersionResponseNewVersion struct {
	VersionId   *string `json:"versionId,omitempty"`
	VersionCode *string `json:"versionCode,omitempty"`
	FileSize    *string `json:"fileSize,omitempty"`
}

func (r ManipulatorGetVersionResponseNewVersion) String() string {
	var ptr0 any = "<nil>"
	if r.VersionId != nil {
		ptr0 = fmt.Sprint(*r.VersionId)
	}
	var ptr1 any = "<nil>"
	if r.VersionCode != nil {
		ptr1 = fmt.Sprint(*r.VersionCode)
	}
	var ptr2 any = "<nil>"
	if r.FileSize != nil {
		ptr2 = fmt.Sprint(*r.FileSize)
	}
	return fmt.Sprintf("{VersionId:%v VersionCode:%v FileSize:%v}", ptr0, ptr1, ptr2)
}

type ManipulatorGetVersionResponse struct {
	Version    string                                  `json:"version"`
	NewVersion ManipulatorGetVersionResponseNewVersion `json:"newVersion"`
}

func (r ManipulatorGetVersionResponse) String() string {
	return fmt.Sprintf("{Version:%v NewVersion:%v}", r.Version, r.NewVersion)
}

// GetVersion Get firmware info
func (device *Manipulator) GetVersion() (ManipulatorGetVersionResponse, error) {
	var response ManipulatorGetVersionResponse
	err := device.Call("Manipulator.getVersion", nil, &response)
	return response, err
}

func (device *Manipulator) GetVersionAsync() <-chan controller.AsyncResult[ManipulatorGetVersionResponse] {
	return controller.DecodeAsync[ManipulatorGetVersionResponse](device.CallAsync("Manipulator.getVersion", nil))
}

type ManipulatorStartUpgradeParams struct {
	VersionId string `json:"versionId"`
}

func (r ManipulatorStartUpgradeParams) String() string {
	return fmt.Sprintf("{VersionId:%v}", r.VersionId)
}

type ManipulatorStartUpgradeResponse struct {
	IsStarted bool `json:"isStarted"`
}

func (r ManipulatorStartUpgradeResponse) String() string {
	return fmt.Sprintf("{IsStarted:%v}", r.IsStarted)
}

// StartUpgrade Start firmware upgrade
func (device *Manipulator) StartUpgrade(params ManipulatorStartUpgradeParams) (ManipulatorStartUpgradeResponse, error) {
	var response ManipulatorStartUpgradeResponse
	err := device.Call("Manipulator.startUpgrade", params, &response)
	return response, err
}

func (device *Manipulator) StartUpgradeAsync(params ManipulatorStartUpgradeParams) <-chan controller.AsyncResult[ManipulatorStartUpgradeResponse] {
	return controller.DecodeAsync[ManipulatorStartUpgradeResponse](device.CallAsync("Manipulator.startUpgrade", params))
}

type ManipulatorGetActivityLogsParamsSearch struct {
	StartDate *string `json:"startDate,omitempty"` // YYYY-MM-DD
	EndDate   *string `json:"endDate,omitempty"`   // YYYY-MM-DD
}

func (r ManipulatorGetActivityLogsParamsSearch) String() string {
	var ptr0 any = "<nil>"
	if r.StartDate != nil {
		ptr0 = fmt.Sprint(*r.StartDate)
	}
	var ptr1 any = "<nil>"
	if r.EndDate != nil {
		ptr1 = fmt.Sprint(*r.EndDate)
	}
	return fmt.Sprintf("{StartDate:%v EndDate:%v}", ptr0, ptr1)
}

type ManipulatorGetActivityLogsParams struct {
	Search       ManipulatorGetActivityLogsParamsSearch `json:"search"`
	RetrievalKey *string                                `json:"retrievalKey,omitempty"`
}

func (r ManipulatorGetActivityLogsParams) String() string {
	var ptr0 any = "<nil>"
	if r.RetrievalKey != nil {
		ptr0 = fmt.Sprint(*r.RetrievalKey)
	}
	return fmt.Sprintf("{Search:%v RetrievalKey:%v}", r.Search, ptr0)
}

type ManipulatorGetActivityLogsResponseLogsItem struct {
	Id   string      `json:"id"`
	Time time.Time   `json:"time"`
	Data interface{} `json:"data"`
}

func (r ManipulatorGetActivityLogsResponseLogsItem) String() string {
	return fmt.Sprintf("{Id:%v Time:%v Data:%v}", r.Id, r.Time, r.Data)
}

type ManipulatorGetActivityLogsResponseRetrievalKeys struct {
	Next *interface{} `json:"next,omitempty"`
}

func (r ManipulatorGetActivityLogsResponseRetrievalKeys) String() string {
	var ptr0 any = "<nil>"
	if r.Next != nil {
		ptr0 = fmt.Sprint(*r.Next)
	}
	return fmt.Sprintf("{Next:%v}", ptr0)
}

type ManipulatorGetActivityLogsResponse struct {
	Logs          []ManipulatorGetActivityLogsResponseLogsItem    `json:"logs"`
	RetrievalKeys ManipulatorGetActivityLogsResponseRetrievalKeys `json:"retrievalKeys"`
}

func (r ManipulatorGetActivityLogsResponse) String() string {
	return fmt.Sprintf("{Logs:%v RetrievalKeys:%v}", r.Logs, r.RetrievalKeys)
}

// GetActivityLogs Retrieve device activity records. Requires DEVICE.HISTORICAL_DATA.READ permission.
func (device *Manipulator) GetActivityLogs(params ManipulatorGetActivityLogsParams) (ManipulatorGetActivityLogsResponse, error) {
	var response ManipulatorGetActivityLogsResponse
	err := device.Call("Manipulator.getActivityLogs", params, &response)
	return response, err
}

func (device *Manipulator) GetActivityLogsAsync(params ManipulatorGetActivityLogsParams) <-chan controller.AsyncResult[ManipulatorGetActivityLogsResponse] {
	return controller.DecodeAsync[ManipulatorGetActivityLogsResponse](device.CallAsync("Manipulator.getActivityLogs", params))
}

type ManipulatorReportResponseDelay struct {
	On  *int `json:"on,omitempty"`  // Remain Delay ON minutes
	Off *int `json:"off,omitempty"` // Remain Delay OFF minutes
}

func (r ManipulatorReportResponseDelay) String() string {
	var ptr0 any = "<nil>"
	if r.On != nil {
		ptr0 = fmt.Sprint(*r.On)
	}
	var ptr1 any = "<nil>"
	if r.Off != nil {
		ptr1 = fmt.Sprint(*r.Off)
	}
	return fmt.Sprintf("{On:%v Off:%v}", ptr0, ptr1)
}

type ManipulatorReportResponse struct {
	State      types.SwitchState              `json:"state"` // ['closed','open']
	Delay      ManipulatorReportResponseDelay `json:"delay"`
	OpenRemind *int                           `json:"openRemind,omitempty"` // Open remind time; 0=disabled
	Version    string                         `json:"version"`              // Firmware version
	Tz         int                            `json:"tz"`                   // Timezone -12~12
	LoraInfo   *types.LoraInfo                `json:"loraInfo,omitempty"`
}

func (r ManipulatorReportResponse) String() string {
	var ptr0 any = "<nil>"
	if r.OpenRemind != nil {
		ptr0 = fmt.Sprint(*r.OpenRemind)
	}
	var ptr1 any = "<nil>"
	if r.LoraInfo != nil {
		ptr1 = fmt.Sprint(*r.LoraInfo)
	}
	return fmt.Sprintf("{State:%v Delay:%v OpenRemind:%v Version:%v Tz:%v LoraInfo:%v}", r.State, r.Delay, ptr0, r.Version, r.Tz, ptr1)
}

type ManipulatorAlertResponseDelay struct {
	On  *int `json:"on,omitempty"`  // Remain Delay ON minutes
	Off *int `json:"off,omitempty"` // Remain Delay OFF minutes
}

func (r ManipulatorAlertResponseDelay) String() string {
	var ptr0 any = "<nil>"
	if r.On != nil {
		ptr0 = fmt.Sprint(*r.On)
	}
	var ptr1 any = "<nil>"
	if r.Off != nil {
		ptr1 = fmt.Sprint(*r.Off)
	}
	return fmt.Sprintf("{On:%v Off:%v}", ptr0, ptr1)
}

type ManipulatorAlertResponse struct {
	State          types.SwitchState             `json:"state"` // ['closed','open']
	Delay          ManipulatorAlertResponseDelay `json:"delay"`
	OpenRemind     *int                          `json:"openRemind,omitempty"` // Open remind time; 0=disabled
	Version        string                        `json:"version"`              // Firmware version
	Tz             int                           `json:"tz"`                   // Timezone -12~12
	LoraInfo       *types.LoraInfo               `json:"loraInfo,omitempty"`
	StateChangedAt *types.Timestamp              `json:"stateChangedAt,omitempty"`
}

func (r ManipulatorAlertResponse) String() string {
	var ptr0 any = "<nil>"
	if r.OpenRemind != nil {
		ptr0 = fmt.Sprint(*r.OpenRemind)
	}
	var ptr1 any = "<nil>"
	if r.LoraInfo != nil {
		ptr1 = fmt.Sprint(*r.LoraInfo)
	}
	var ptr2 any = "<nil>"
	if r.StateChangedAt != nil {
		ptr2 = fmt.Sprint(*r.StateChangedAt)
	}
	return fmt.Sprintf("{State:%v Delay:%v OpenRemind:%v Version:%v Tz:%v LoraInfo:%v StateChangedAt:%v}", r.State, r.Delay, ptr0, r.Version, r.Tz, ptr1, ptr2)
}

func (device *Manipulator) ParseEvent(message controller.MqttMessage) (controller.Report, bool) {
	report, ok := device.Device.ParseEvent(message) // base impl decodes event + raw data
	if !ok {
		return report, false
	}
	report.Device = device                        // attribute the report to this concrete device
	data := report.Data.(controller.Unknown).Json // raw payload, re-typed below
	switch report.Event {
	case "Manipulator.getState":
		var response ManipulatorGetStateResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "Manipulator.setState":
		var response ManipulatorSetStateResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "Manipulator.setDelay":
		var response ManipulatorSetDelayResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "Manipulator.getSchedules":
		var response ManipulatorGetSchedulesResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "Manipulator.setSchedules":
		var response ManipulatorSetSchedulesResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "Manipulator.getVersion":
		var response ManipulatorGetVersionResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "Manipulator.startUpgrade":
		var response ManipulatorStartUpgradeResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "Manipulator.getActivityLogs":
		var response ManipulatorGetActivityLogsResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "Manipulator.Report":
		var response ManipulatorReportResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "Manipulator.Alert":
		var response ManipulatorAlertResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	}
	return report, true
}
