// Code generated by scripts/gen_device_types.py; DO NOT EDIT.
package devices

import (
	"encoding/json"
	"fmt"
	"time"

	"github.com/tyandl/homelink/pkg/yolink/controller"
	"github.com/tyandl/homelink/pkg/yolink/types"
)

type MotionSensor struct{ *controller.Device }

func init() {
	controller.RegisterDeviceFactory("MotionSensor", func(device *controller.Device) controller.DeviceController {
		return &MotionSensor{Device: device}
	})
}

type MotionSensorGetStateResponseStateAlarmState struct {
	StayError     bool `json:"stayError"`
	DetectorError bool `json:"detectorError"`
	FreezeError   bool `json:"freezeError"`
	Reminder      bool `json:"reminder"`
}

func (r MotionSensorGetStateResponseStateAlarmState) String() string {
	return fmt.Sprintf("{StayError:%v DetectorError:%v FreezeError:%v Reminder:%v}", r.StayError, r.DetectorError, r.FreezeError, r.Reminder)
}

type MotionSensorGetStateResponseState struct {
	State             types.AlarmState                            `json:"state"`   // ['normal','alert']
	Battery           types.BatteryLevel                          `json:"battery"` // Battery level 0-4
	Beep              bool                                        `json:"beep"`
	DevTemperature    int                                         `json:"devTemperature"`
	Sensitivity       int                                         `json:"sensitivity"`
	SensorMode        string                                      `json:"sensorMode"`
	StateChangedAt    types.Timestamp                             `json:"stateChangedAt"`
	SupportChangeMode bool                                        `json:"supportChangeMode"`
	Version           string                                      `json:"version"`
	AlarmState        MotionSensorGetStateResponseStateAlarmState `json:"alarmState"`
	AlertInterval     *int                                        `json:"alertInterval,omitempty"`
	LedAlarm          *bool                                       `json:"ledAlarm,omitempty"`
	BatteryType       *string                                     `json:"batteryType,omitempty"`
	NomotionDelay     *int                                        `json:"nomotionDelay,omitempty"`
}

func (r MotionSensorGetStateResponseState) String() string {
	var ptr0 any = "<nil>"
	if r.AlertInterval != nil {
		ptr0 = fmt.Sprint(*r.AlertInterval)
	}
	var ptr1 any = "<nil>"
	if r.LedAlarm != nil {
		ptr1 = fmt.Sprint(*r.LedAlarm)
	}
	var ptr2 any = "<nil>"
	if r.BatteryType != nil {
		ptr2 = fmt.Sprint(*r.BatteryType)
	}
	var ptr3 any = "<nil>"
	if r.NomotionDelay != nil {
		ptr3 = fmt.Sprint(*r.NomotionDelay)
	}
	return fmt.Sprintf("{State:%v Battery:%v Beep:%v DevTemperature:%v Sensitivity:%v SensorMode:%v StateChangedAt:%v SupportChangeMode:%v Version:%v AlarmState:%v AlertInterval:%v LedAlarm:%v BatteryType:%v NomotionDelay:%v}", r.State, r.Battery, r.Beep, r.DevTemperature, r.Sensitivity, r.SensorMode, r.StateChangedAt, r.SupportChangeMode, r.Version, r.AlarmState, ptr0, ptr1, ptr2, ptr3)
}

type MotionSensorGetStateResponse struct {
	Online   bool                              `json:"online"` // Is device online
	State    MotionSensorGetStateResponseState `json:"state"`
	ReportAt time.Time                         `json:"reportAt"`
	DeviceId string                            `json:"deviceId"`
}

func (r MotionSensorGetStateResponse) String() string {
	return fmt.Sprintf("{Online:%v State:%v ReportAt:%v DeviceId:%v}", r.Online, r.State, r.ReportAt, r.DeviceId)
}

// GetState Get Motion Sensor's State
func (device *MotionSensor) GetState() (MotionSensorGetStateResponse, error) {
	var response MotionSensorGetStateResponse
	err := device.Call("MotionSensor.getState", nil, &response)
	return response, err
}

func (device *MotionSensor) GetStateAsync() <-chan controller.AsyncResult[MotionSensorGetStateResponse] {
	return controller.DecodeAsync[MotionSensorGetStateResponse](device.CallAsync("MotionSensor.getState", nil))
}

type MotionSensorGetActivityLogsParamsSearch struct {
	StartDate *string `json:"startDate,omitempty"` // YYYY-MM-DD
	EndDate   *string `json:"endDate,omitempty"`   // YYYY-MM-DD
}

func (r MotionSensorGetActivityLogsParamsSearch) String() string {
	var ptr0 any = "<nil>"
	if r.StartDate != nil {
		ptr0 = fmt.Sprint(*r.StartDate)
	}
	var ptr1 any = "<nil>"
	if r.EndDate != nil {
		ptr1 = fmt.Sprint(*r.EndDate)
	}
	return fmt.Sprintf("{StartDate:%v EndDate:%v}", ptr0, ptr1)
}

type MotionSensorGetActivityLogsParams struct {
	Search       MotionSensorGetActivityLogsParamsSearch `json:"search"`
	RetrievalKey *string                                 `json:"retrievalKey,omitempty"`
}

func (r MotionSensorGetActivityLogsParams) String() string {
	var ptr0 any = "<nil>"
	if r.RetrievalKey != nil {
		ptr0 = fmt.Sprint(*r.RetrievalKey)
	}
	return fmt.Sprintf("{Search:%v RetrievalKey:%v}", r.Search, ptr0)
}

type MotionSensorGetActivityLogsResponseLogsItem struct {
	Id   string      `json:"id"`
	Time time.Time   `json:"time"`
	Data interface{} `json:"data"`
}

func (r MotionSensorGetActivityLogsResponseLogsItem) String() string {
	return fmt.Sprintf("{Id:%v Time:%v Data:%v}", r.Id, r.Time, r.Data)
}

type MotionSensorGetActivityLogsResponseRetrievalKeys struct {
	Next *interface{} `json:"next,omitempty"`
}

func (r MotionSensorGetActivityLogsResponseRetrievalKeys) String() string {
	var ptr0 any = "<nil>"
	if r.Next != nil {
		ptr0 = fmt.Sprint(*r.Next)
	}
	return fmt.Sprintf("{Next:%v}", ptr0)
}

type MotionSensorGetActivityLogsResponse struct {
	Logs          []MotionSensorGetActivityLogsResponseLogsItem    `json:"logs"`
	RetrievalKeys MotionSensorGetActivityLogsResponseRetrievalKeys `json:"retrievalKeys"`
}

func (r MotionSensorGetActivityLogsResponse) String() string {
	return fmt.Sprintf("{Logs:%v RetrievalKeys:%v}", r.Logs, r.RetrievalKeys)
}

// GetActivityLogs Retrieve device activity records. Requires DEVICE.HISTORICAL_DATA.READ permission.
func (device *MotionSensor) GetActivityLogs(params MotionSensorGetActivityLogsParams) (MotionSensorGetActivityLogsResponse, error) {
	var response MotionSensorGetActivityLogsResponse
	err := device.Call("MotionSensor.getActivityLogs", params, &response)
	return response, err
}

func (device *MotionSensor) GetActivityLogsAsync(params MotionSensorGetActivityLogsParams) <-chan controller.AsyncResult[MotionSensorGetActivityLogsResponse] {
	return controller.DecodeAsync[MotionSensorGetActivityLogsResponse](device.CallAsync("MotionSensor.getActivityLogs", params))
}

type MotionSensorSetAttributesParams struct {
	AlertInterval *int  `json:"alertInterval,omitempty"` // Alert interval minutes
	LedAlarm      *bool `json:"ledAlarm,omitempty"`      // Alarm LED status
	NomotionDelay *int  `json:"nomotionDelay,omitempty"` // Motion delay minutes 0-120
	Sensitivity   *int  `json:"sensitivity,omitempty"`   // Sensitivity 1-3
}

func (r MotionSensorSetAttributesParams) String() string {
	var ptr0 any = "<nil>"
	if r.AlertInterval != nil {
		ptr0 = fmt.Sprint(*r.AlertInterval)
	}
	var ptr1 any = "<nil>"
	if r.LedAlarm != nil {
		ptr1 = fmt.Sprint(*r.LedAlarm)
	}
	var ptr2 any = "<nil>"
	if r.NomotionDelay != nil {
		ptr2 = fmt.Sprint(*r.NomotionDelay)
	}
	var ptr3 any = "<nil>"
	if r.Sensitivity != nil {
		ptr3 = fmt.Sprint(*r.Sensitivity)
	}
	return fmt.Sprintf("{AlertInterval:%v LedAlarm:%v NomotionDelay:%v Sensitivity:%v}", ptr0, ptr1, ptr2, ptr3)
}

type MotionSensorSetAttributesResponse struct {
	AlertInterval int  `json:"alertInterval"`
	LedAlarm      bool `json:"ledAlarm"`
	NomotionDelay int  `json:"nomotionDelay"`
	Sensitivity   int  `json:"sensitivity"`
}

func (r MotionSensorSetAttributesResponse) String() string {
	return fmt.Sprintf("{AlertInterval:%v LedAlarm:%v NomotionDelay:%v Sensitivity:%v}", r.AlertInterval, r.LedAlarm, r.NomotionDelay, r.Sensitivity)
}

// SetAttributes Set device's attributes
func (device *MotionSensor) SetAttributes(params MotionSensorSetAttributesParams) (MotionSensorSetAttributesResponse, error) {
	var response MotionSensorSetAttributesResponse
	err := device.Call("MotionSensor.setAttributes", params, &response)
	return response, err
}

func (device *MotionSensor) SetAttributesAsync(params MotionSensorSetAttributesParams) <-chan controller.AsyncResult[MotionSensorSetAttributesResponse] {
	return controller.DecodeAsync[MotionSensorSetAttributesResponse](device.CallAsync("MotionSensor.setAttributes", params))
}

type MotionSensorAlertResponse struct {
	State          types.AlertState   `json:"state"` // alert | normal
	Battery        types.BatteryLevel `json:"battery"`
	Version        string             `json:"version"`
	LedAlarm       bool               `json:"ledAlarm"`
	AlertInterval  int                `json:"alertInterval"`
	NomotionDelay  int                `json:"nomotionDelay"`
	Sensitivity    int                `json:"sensitivity"`
	LoraInfo       *types.LoraInfo    `json:"loraInfo,omitempty"`
	StateChangedAt types.Timestamp    `json:"stateChangedAt"`
}

func (r MotionSensorAlertResponse) String() string {
	var ptr0 any = "<nil>"
	if r.LoraInfo != nil {
		ptr0 = fmt.Sprint(*r.LoraInfo)
	}
	return fmt.Sprintf("{State:%v Battery:%v Version:%v LedAlarm:%v AlertInterval:%v NomotionDelay:%v Sensitivity:%v LoraInfo:%v StateChangedAt:%v}", r.State, r.Battery, r.Version, r.LedAlarm, r.AlertInterval, r.NomotionDelay, r.Sensitivity, ptr0, r.StateChangedAt)
}

type MotionSensorReportResponse struct {
	State          types.AlertState   `json:"state"` // alert | normal
	Battery        types.BatteryLevel `json:"battery"`
	Version        string             `json:"version"`
	LedAlarm       bool               `json:"ledAlarm"`
	AlertInterval  int                `json:"alertInterval"`
	NomotionDelay  int                `json:"nomotionDelay"`
	Sensitivity    int                `json:"sensitivity"`
	DevTemperature *int               `json:"devTemperature,omitempty"`
	BatteryType    *string            `json:"batteryType,omitempty"`
	LoraInfo       *types.LoraInfo    `json:"loraInfo,omitempty"`
}

func (r MotionSensorReportResponse) String() string {
	var ptr0 any = "<nil>"
	if r.DevTemperature != nil {
		ptr0 = fmt.Sprint(*r.DevTemperature)
	}
	var ptr1 any = "<nil>"
	if r.BatteryType != nil {
		ptr1 = fmt.Sprint(*r.BatteryType)
	}
	var ptr2 any = "<nil>"
	if r.LoraInfo != nil {
		ptr2 = fmt.Sprint(*r.LoraInfo)
	}
	return fmt.Sprintf("{State:%v Battery:%v Version:%v LedAlarm:%v AlertInterval:%v NomotionDelay:%v Sensitivity:%v DevTemperature:%v BatteryType:%v LoraInfo:%v}", r.State, r.Battery, r.Version, r.LedAlarm, r.AlertInterval, r.NomotionDelay, r.Sensitivity, ptr0, ptr1, ptr2)
}

func (device *MotionSensor) ParseEvent(message controller.MqttMessage) (controller.Report, bool) {
	report, ok := device.Device.ParseEvent(message) // base impl decodes event + raw data
	if !ok {
		return report, false
	}
	report.Device = device                        // attribute the report to this concrete device
	data := report.Data.(controller.Unknown).Json // raw payload, re-typed below
	switch report.Event {
	case "MotionSensor.getState":
		var response MotionSensorGetStateResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "MotionSensor.getActivityLogs":
		var response MotionSensorGetActivityLogsResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "MotionSensor.setAttributes":
		var response MotionSensorSetAttributesResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "MotionSensor.Alert":
		var response MotionSensorAlertResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "MotionSensor.Report":
		var response MotionSensorReportResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	}
	return report, true
}
