// Code generated by scripts/gen_device_types.py; DO NOT EDIT.
package devices

import (
	"encoding/json"
	"fmt"

	"github.com/tyandl/homelink/pkg/yolink/controller"
	"github.com/tyandl/homelink/pkg/yolink/types"
)

type MultiOutlet struct{ *controller.Device }

func init() {
	controller.RegisterDeviceFactory("MultiOutlet", func(device *controller.Device) controller.DeviceController {
		return &MultiOutlet{Device: device}
	})
}

type MultiOutletGetStateResponseDelaysItem struct {
	On  int `json:"on"`  // Remain Delay ON minutes
	Off int `json:"off"` // Remain Delay OFF minutes
}

func (r MultiOutletGetStateResponseDelaysItem) String() string {
	return fmt.Sprintf("{On:%v Off:%v}", r.On, r.Off)
}

type MultiOutletGetStateResponse struct {
	State   []string                                `json:"state"`
	Delays  []MultiOutletGetStateResponseDelaysItem `json:"delays"`
	Version string                                  `json:"version"`
	Tz      int                                     `json:"tz"`
}

func (r MultiOutletGetStateResponse) String() string {
	return fmt.Sprintf("{State:%v Delays:%v Version:%v Tz:%v}", r.State, r.Delays, r.Version, r.Tz)
}

// GetState Get Current State
func (device *MultiOutlet) GetState() (MultiOutletGetStateResponse, error) {
	var response MultiOutletGetStateResponse
	err := device.Call("MultiOutlet.getState", nil, &response)
	return response, err
}

func (device *MultiOutlet) GetStateAsync() <-chan controller.AsyncResult[MultiOutletGetStateResponse] {
	return controller.DecodeAsync[MultiOutletGetStateResponse](device.CallAsync("MultiOutlet.getState", nil))
}

type MultiOutletSetStateParams struct {
	Chs   int                 `json:"chs"`   // Socket bitmask 0x01-0xFF
	State types.SwitchCommand `json:"state"` // ['close','open']
}

func (r MultiOutletSetStateParams) String() string {
	return fmt.Sprintf("{Chs:%v State:%v}", r.Chs, r.State)
}

type MultiOutletSetStateResponse struct {
	State []string `json:"state"`
}

func (r MultiOutletSetStateResponse) String() string {
	return fmt.Sprintf("{State:%v}", r.State)
}

// SetState Set MultiOutlet's State
func (device *MultiOutlet) SetState(params MultiOutletSetStateParams) (MultiOutletSetStateResponse, error) {
	var response MultiOutletSetStateResponse
	err := device.Call("MultiOutlet.setState", params, &response)
	return response, err
}

func (device *MultiOutlet) SetStateAsync(params MultiOutletSetStateParams) <-chan controller.AsyncResult[MultiOutletSetStateResponse] {
	return controller.DecodeAsync[MultiOutletSetStateResponse](device.CallAsync("MultiOutlet.setState", params))
}

type MultiOutletSetDelayParamsDelaysItem struct {
	Ch  *int `json:"ch,omitempty"`  // Socket index
	On  *int `json:"on,omitempty"`  // Delay ON minutes; 0=cancel
	Off *int `json:"off,omitempty"` // Delay OFF minutes; 0=cancel
}

func (r MultiOutletSetDelayParamsDelaysItem) String() string {
	var ptr0 any = "<nil>"
	if r.Ch != nil {
		ptr0 = fmt.Sprint(*r.Ch)
	}
	var ptr1 any = "<nil>"
	if r.On != nil {
		ptr1 = fmt.Sprint(*r.On)
	}
	var ptr2 any = "<nil>"
	if r.Off != nil {
		ptr2 = fmt.Sprint(*r.Off)
	}
	return fmt.Sprintf("{Ch:%v On:%v Off:%v}", ptr0, ptr1, ptr2)
}

type MultiOutletSetDelayParams struct {
	Delays []MultiOutletSetDelayParamsDelaysItem `json:"delays"`
}

func (r MultiOutletSetDelayParams) String() string {
	return fmt.Sprintf("{Delays:%v}", r.Delays)
}

type MultiOutletSetDelayResponseDelaysItem struct {
	On  int `json:"on"`
	Off int `json:"off"`
}

func (r MultiOutletSetDelayResponseDelaysItem) String() string {
	return fmt.Sprintf("{On:%v Off:%v}", r.On, r.Off)
}

type MultiOutletSetDelayResponse struct {
	Delays []MultiOutletSetDelayResponseDelaysItem `json:"delays"`
}

func (r MultiOutletSetDelayResponse) String() string {
	return fmt.Sprintf("{Delays:%v}", r.Delays)
}

// SetDelay Set delay for outlets
func (device *MultiOutlet) SetDelay(params MultiOutletSetDelayParams) (MultiOutletSetDelayResponse, error) {
	var response MultiOutletSetDelayResponse
	err := device.Call("MultiOutlet.setDelay", params, &response)
	return response, err
}

func (device *MultiOutlet) SetDelayAsync(params MultiOutletSetDelayParams) <-chan controller.AsyncResult[MultiOutletSetDelayResponse] {
	return controller.DecodeAsync[MultiOutletSetDelayResponse](device.CallAsync("MultiOutlet.setDelay", params))
}

type MultiOutletGetSchedulesResponse = []struct {
	Ch      int     `json:"ch"` // Socket index
	IsValid bool    `json:"isValid"`
	Index   int     `json:"index"`
	On      *string `json:"on,omitempty"`  // HH:mm
	Off     *string `json:"off,omitempty"` // HH:mm
	Week    int     `json:"week"`          // Weekday mask
}

// GetSchedules Get Schedule List
func (device *MultiOutlet) GetSchedules() (MultiOutletGetSchedulesResponse, error) {
	var response MultiOutletGetSchedulesResponse
	err := device.Call("MultiOutlet.getSchedules", nil, &response)
	return response, err
}

func (device *MultiOutlet) GetSchedulesAsync() <-chan controller.AsyncResult[MultiOutletGetSchedulesResponse] {
	return controller.DecodeAsync[MultiOutletGetSchedulesResponse](device.CallAsync("MultiOutlet.getSchedules", nil))
}

type MultiOutletSetSchedulesParamsSchesItem struct {
	Ch      int    `json:"ch"` // Socket index
	IsValid bool   `json:"isValid"`
	Index   int    `json:"index"`
	On      string `json:"on"`   // HH:mm
	Off     string `json:"off"`  // HH:mm
	Week    int    `json:"week"` // Weekday mask
}

func (r MultiOutletSetSchedulesParamsSchesItem) String() string {
	return fmt.Sprintf("{Ch:%v IsValid:%v Index:%v On:%v Off:%v Week:%v}", r.Ch, r.IsValid, r.Index, r.On, r.Off, r.Week)
}

type MultiOutletSetSchedulesParams struct {
	Sches []MultiOutletSetSchedulesParamsSchesItem `json:"sches"`
}

func (r MultiOutletSetSchedulesParams) String() string {
	return fmt.Sprintf("{Sches:%v}", r.Sches)
}

type MultiOutletSetSchedulesResponse = []struct {
	Ch      int     `json:"ch"` // Socket index
	IsValid bool    `json:"isValid"`
	Index   int     `json:"index"`
	On      *string `json:"on,omitempty"`  // HH:mm
	Off     *string `json:"off,omitempty"` // HH:mm
	Week    int     `json:"week"`          // Weekday mask
}

// SetSchedules Set Schedule (index 0-9)
func (device *MultiOutlet) SetSchedules(params MultiOutletSetSchedulesParams) (MultiOutletSetSchedulesResponse, error) {
	var response MultiOutletSetSchedulesResponse
	err := device.Call("MultiOutlet.setSchedules", params, &response)
	return response, err
}

func (device *MultiOutlet) SetSchedulesAsync(params MultiOutletSetSchedulesParams) <-chan controller.AsyncResult[MultiOutletSetSchedulesResponse] {
	return controller.DecodeAsync[MultiOutletSetSchedulesResponse](device.CallAsync("MultiOutlet.setSchedules", params))
}

type MultiOutletGetVersionResponseNewVersion struct {
	VersionId   *string `json:"versionId,omitempty"`
	VersionCode *string `json:"versionCode,omitempty"`
	FileSize    *string `json:"fileSize,omitempty"`
}

func (r MultiOutletGetVersionResponseNewVersion) String() string {
	var ptr0 any = "<nil>"
	if r.VersionId != nil {
		ptr0 = fmt.Sprint(*r.VersionId)
	}
	var ptr1 any = "<nil>"
	if r.VersionCode != nil {
		ptr1 = fmt.Sprint(*r.VersionCode)
	}
	var ptr2 any = "<nil>"
	if r.FileSize != nil {
		ptr2 = fmt.Sprint(*r.FileSize)
	}
	return fmt.Sprintf("{VersionId:%v VersionCode:%v FileSize:%v}", ptr0, ptr1, ptr2)
}

type MultiOutletGetVersionResponse struct {
	Version    string                                  `json:"version"`
	NewVersion MultiOutletGetVersionResponseNewVersion `json:"newVersion"`
}

func (r MultiOutletGetVersionResponse) String() string {
	return fmt.Sprintf("{Version:%v NewVersion:%v}", r.Version, r.NewVersion)
}

// GetVersion Get firmware info
func (device *MultiOutlet) GetVersion() (MultiOutletGetVersionResponse, error) {
	var response MultiOutletGetVersionResponse
	err := device.Call("MultiOutlet.getVersion", nil, &response)
	return response, err
}

func (device *MultiOutlet) GetVersionAsync() <-chan controller.AsyncResult[MultiOutletGetVersionResponse] {
	return controller.DecodeAsync[MultiOutletGetVersionResponse](device.CallAsync("MultiOutlet.getVersion", nil))
}

type MultiOutletStartUpgradeParams struct {
	VersionId string `json:"versionId"`
}

func (r MultiOutletStartUpgradeParams) String() string {
	return fmt.Sprintf("{VersionId:%v}", r.VersionId)
}

type MultiOutletStartUpgradeResponse struct {
	IsStarted bool `json:"isStarted"`
}

func (r MultiOutletStartUpgradeResponse) String() string {
	return fmt.Sprintf("{IsStarted:%v}", r.IsStarted)
}

// StartUpgrade Start firmware upgrade
func (device *MultiOutlet) StartUpgrade(params MultiOutletStartUpgradeParams) (MultiOutletStartUpgradeResponse, error) {
	var response MultiOutletStartUpgradeResponse
	err := device.Call("MultiOutlet.startUpgrade", params, &response)
	return response, err
}

func (device *MultiOutlet) StartUpgradeAsync(params MultiOutletStartUpgradeParams) <-chan controller.AsyncResult[MultiOutletStartUpgradeResponse] {
	return controller.DecodeAsync[MultiOutletStartUpgradeResponse](device.CallAsync("MultiOutlet.startUpgrade", params))
}

type MultiOutletReportResponseDelaysItem struct {
	On  int `json:"on"`  // Remain Delay ON minutes
	Off int `json:"off"` // Remain Delay OFF minutes
}

func (r MultiOutletReportResponseDelaysItem) String() string {
	return fmt.Sprintf("{On:%v Off:%v}", r.On, r.Off)
}

type MultiOutletReportResponse struct {
	State    []string                              `json:"state"`
	Delays   []MultiOutletReportResponseDelaysItem `json:"delays"`
	Version  string                                `json:"version"`
	Tz       int                                   `json:"tz"`
	LoraInfo *types.LoraInfo                       `json:"loraInfo,omitempty"`
}

func (r MultiOutletReportResponse) String() string {
	var ptr0 any = "<nil>"
	if r.LoraInfo != nil {
		ptr0 = fmt.Sprint(*r.LoraInfo)
	}
	return fmt.Sprintf("{State:%v Delays:%v Version:%v Tz:%v LoraInfo:%v}", r.State, r.Delays, r.Version, r.Tz, ptr0)
}

type MultiOutletAlertResponseDelaysItem struct {
	On  int `json:"on"`  // Remain Delay ON minutes
	Off int `json:"off"` // Remain Delay OFF minutes
}

func (r MultiOutletAlertResponseDelaysItem) String() string {
	return fmt.Sprintf("{On:%v Off:%v}", r.On, r.Off)
}

type MultiOutletAlertResponse struct {
	State          []string                             `json:"state"`
	Delays         []MultiOutletAlertResponseDelaysItem `json:"delays"`
	Version        string                               `json:"version"`
	Tz             int                                  `json:"tz"`
	LoraInfo       *types.LoraInfo                      `json:"loraInfo,omitempty"`
	StateChangedAt *types.Timestamp                     `json:"stateChangedAt,omitempty"`
}

func (r MultiOutletAlertResponse) String() string {
	var ptr0 any = "<nil>"
	if r.LoraInfo != nil {
		ptr0 = fmt.Sprint(*r.LoraInfo)
	}
	var ptr1 any = "<nil>"
	if r.StateChangedAt != nil {
		ptr1 = fmt.Sprint(*r.StateChangedAt)
	}
	return fmt.Sprintf("{State:%v Delays:%v Version:%v Tz:%v LoraInfo:%v StateChangedAt:%v}", r.State, r.Delays, r.Version, r.Tz, ptr0, ptr1)
}

func (device *MultiOutlet) ParseEvent(message controller.MqttMessage) (controller.Report, bool) {
	report, ok := device.Device.ParseEvent(message) // base impl decodes event + raw data
	if !ok {
		return report, false
	}
	report.Device = device                        // attribute the report to this concrete device
	data := report.Data.(controller.Unknown).Json // raw payload, re-typed below
	switch report.Event {
	case "MultiOutlet.getState":
		var response MultiOutletGetStateResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "MultiOutlet.setState":
		var response MultiOutletSetStateResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "MultiOutlet.setDelay":
		var response MultiOutletSetDelayResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "MultiOutlet.getSchedules":
		var response MultiOutletGetSchedulesResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "MultiOutlet.setSchedules":
		var response MultiOutletSetSchedulesResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "MultiOutlet.getVersion":
		var response MultiOutletGetVersionResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "MultiOutlet.startUpgrade":
		var response MultiOutletStartUpgradeResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "MultiOutlet.Report":
		var response MultiOutletReportResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "MultiOutlet.Alert":
		var response MultiOutletAlertResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	}
	return report, true
}
