// Code generated by scripts/gen_device_types.py; DO NOT EDIT.
package devices

import (
	"encoding/json"
	"fmt"
	"time"

	"github.com/tyandl/homelink/pkg/yolink/controller"
	"github.com/tyandl/homelink/pkg/yolink/types"
)

type Outlet struct{ *controller.Device }

func init() {
	controller.RegisterDeviceFactory("Outlet", func(device *controller.Device) controller.DeviceController {
		return &Outlet{Device: device}
	})
}

type OutletGetStateResponseDelay struct {
	On  int `json:"on"`  // Remain Delay ON minutes
	Off int `json:"off"` // Remain Delay OFF minutes
}

func (r OutletGetStateResponseDelay) String() string {
	return fmt.Sprintf("{On:%v Off:%v}", r.On, r.Off)
}

type OutletGetStateResponse struct {
	State   types.SwitchState           `json:"state"` // ['closed','open']
	Delay   OutletGetStateResponseDelay `json:"delay"`
	Power   *int                        `json:"power,omitempty"` // Current power (0 if unsupported)
	Version string                      `json:"version"`
	Tz      int                         `json:"tz"`
}

func (r OutletGetStateResponse) String() string {
	var ptr0 any = "<nil>"
	if r.Power != nil {
		ptr0 = fmt.Sprint(*r.Power)
	}
	return fmt.Sprintf("{State:%v Delay:%v Power:%v Version:%v Tz:%v}", r.State, r.Delay, ptr0, r.Version, r.Tz)
}

// GetState Get Current State
func (device *Outlet) GetState() (OutletGetStateResponse, error) {
	var response OutletGetStateResponse
	err := device.Call("Outlet.getState", nil, &response)
	return response, err
}

func (device *Outlet) GetStateAsync() <-chan controller.AsyncResult[OutletGetStateResponse] {
	return controller.DecodeAsync[OutletGetStateResponse](device.CallAsync("Outlet.getState", nil))
}

type OutletSetStateParams struct {
	State types.SwitchCommand `json:"state"` // ['close','open']
}

func (r OutletSetStateParams) String() string {
	return fmt.Sprintf("{State:%v}", r.State)
}

type OutletSetStateResponse struct {
	State types.SwitchState `json:"state"` // ['closed','open']
}

func (r OutletSetStateResponse) String() string {
	return fmt.Sprintf("{State:%v}", r.State)
}

// SetState Set Outlet's State
func (device *Outlet) SetState(params OutletSetStateParams) (OutletSetStateResponse, error) {
	var response OutletSetStateResponse
	err := device.Call("Outlet.setState", params, &response)
	return response, err
}

func (device *Outlet) SetStateAsync(params OutletSetStateParams) <-chan controller.AsyncResult[OutletSetStateResponse] {
	return controller.DecodeAsync[OutletSetStateResponse](device.CallAsync("Outlet.setState", params))
}

type OutletSetDelayParams struct {
	DelayOn  *int `json:"delayOn,omitempty"`  // Delay ON minutes; 0=cancel
	DelayOff *int `json:"delayOff,omitempty"` // Delay OFF minutes; 0=cancel
}

func (r OutletSetDelayParams) String() string {
	var ptr0 any = "<nil>"
	if r.DelayOn != nil {
		ptr0 = fmt.Sprint(*r.DelayOn)
	}
	var ptr1 any = "<nil>"
	if r.DelayOff != nil {
		ptr1 = fmt.Sprint(*r.DelayOff)
	}
	return fmt.Sprintf("{DelayOn:%v DelayOff:%v}", ptr0, ptr1)
}

type OutletSetDelayResponseDelay struct {
	On  int `json:"on"`
	Off int `json:"off"`
}

func (r OutletSetDelayResponseDelay) String() string {
	return fmt.Sprintf("{On:%v Off:%v}", r.On, r.Off)
}

type OutletSetDelayResponse struct {
	Delay OutletSetDelayResponseDelay `json:"delay"`
}

func (r OutletSetDelayResponse) String() string {
	return fmt.Sprintf("{Delay:%v}", r.Delay)
}

// SetDelay Delay to turn on/off outlet
func (device *Outlet) SetDelay(params OutletSetDelayParams) (OutletSetDelayResponse, error) {
	var response OutletSetDelayResponse
	err := device.Call("Outlet.setDelay", params, &response)
	return response, err
}

func (device *Outlet) SetDelayAsync(params OutletSetDelayParams) <-chan controller.AsyncResult[OutletSetDelayResponse] {
	return controller.DecodeAsync[OutletSetDelayResponse](device.CallAsync("Outlet.setDelay", params))
}

type OutletGetSchedulesResponse = []struct {
	IsValid bool    `json:"isValid"`
	Index   int     `json:"index"`
	On      *string `json:"on,omitempty"`  // HH:mm
	Off     *string `json:"off,omitempty"` // HH:mm
	Week    int     `json:"week"`          // Weekday mask
}

// GetSchedules Get Schedule List
func (device *Outlet) GetSchedules() (OutletGetSchedulesResponse, error) {
	var response OutletGetSchedulesResponse
	err := device.Call("Outlet.getSchedules", nil, &response)
	return response, err
}

func (device *Outlet) GetSchedulesAsync() <-chan controller.AsyncResult[OutletGetSchedulesResponse] {
	return controller.DecodeAsync[OutletGetSchedulesResponse](device.CallAsync("Outlet.getSchedules", nil))
}

type OutletSetSchedulesParamsSchesItem struct {
	IsValid bool   `json:"isValid"`
	Index   int    `json:"index"`
	On      string `json:"on"`   // HH:mm
	Off     string `json:"off"`  // HH:mm
	Week    int    `json:"week"` // Weekday mask
}

func (r OutletSetSchedulesParamsSchesItem) String() string {
	return fmt.Sprintf("{IsValid:%v Index:%v On:%v Off:%v Week:%v}", r.IsValid, r.Index, r.On, r.Off, r.Week)
}

type OutletSetSchedulesParams struct {
	Sches []OutletSetSchedulesParamsSchesItem `json:"sches"`
}

func (r OutletSetSchedulesParams) String() string {
	return fmt.Sprintf("{Sches:%v}", r.Sches)
}

type OutletSetSchedulesResponse = []struct {
	IsValid bool    `json:"isValid"`
	Index   int     `json:"index"`
	On      *string `json:"on,omitempty"`  // HH:mm
	Off     *string `json:"off,omitempty"` // HH:mm
	Week    int     `json:"week"`          // Weekday mask
}

// SetSchedules Set Schedule (index 0-5)
func (device *Outlet) SetSchedules(params OutletSetSchedulesParams) (OutletSetSchedulesResponse, error) {
	var response OutletSetSchedulesResponse
	err := device.Call("Outlet.setSchedules", params, &response)
	return response, err
}

func (device *Outlet) SetSchedulesAsync(params OutletSetSchedulesParams) <-chan controller.AsyncResult[OutletSetSchedulesResponse] {
	return controller.DecodeAsync[OutletSetSchedulesResponse](device.CallAsync("Outlet.setSchedules", params))
}

type OutletGetVersionResponseNewVersion struct {
	VersionId   *string `json:"versionId,omitempty"`
	VersionCode *string `json:"versionCode,omitempty"`
	FileSize    *string `json:"fileSize,omitempty"`
}

func (r OutletGetVersionResponseNewVersion) String() string {
	var ptr0 any = "<nil>"
	if r.VersionId != nil {
		ptr0 = fmt.Sprint(*r.VersionId)
	}
	var ptr1 any = "<nil>"
	if r.VersionCode != nil {
		ptr1 = fmt.Sprint(*r.VersionCode)
	}
	var ptr2 any = "<nil>"
	if r.FileSize != nil {
		ptr2 = fmt.Sprint(*r.FileSize)
	}
	return fmt.Sprintf("{VersionId:%v VersionCode:%v FileSize:%v}", ptr0, ptr1, ptr2)
}

type OutletGetVersionResponse struct {
	Version    string                             `json:"version"`
	NewVersion OutletGetVersionResponseNewVersion `json:"newVersion"`
}

func (r OutletGetVersionResponse) String() string {
	return fmt.Sprintf("{Version:%v NewVersion:%v}", r.Version, r.NewVersion)
}

// GetVersion Get firmware info
func (device *Outlet) GetVersion() (OutletGetVersionResponse, error) {
	var response OutletGetVersionResponse
	err := device.Call("Outlet.getVersion", nil, &response)
	return response, err
}

func (device *Outlet) GetVersionAsync() <-chan controller.AsyncResult[OutletGetVersionResponse] {
	return controller.DecodeAsync[OutletGetVersionResponse](device.CallAsync("Outlet.getVersion", nil))
}

type OutletStartUpgradeParams struct {
	VersionId string `json:"versionId"`
}

func (r OutletStartUpgradeParams) String() string {
	return fmt.Sprintf("{VersionId:%v}", r.VersionId)
}

type OutletStartUpgradeResponse struct {
	IsStarted bool `json:"isStarted"`
}

func (r OutletStartUpgradeResponse) String() string {
	return fmt.Sprintf("{IsStarted:%v}", r.IsStarted)
}

// StartUpgrade Start firmware upgrade
func (device *Outlet) StartUpgrade(params OutletStartUpgradeParams) (OutletStartUpgradeResponse, error) {
	var response OutletStartUpgradeResponse
	err := device.Call("Outlet.startUpgrade", params, &response)
	return response, err
}

func (device *Outlet) StartUpgradeAsync(params OutletStartUpgradeParams) <-chan controller.AsyncResult[OutletStartUpgradeResponse] {
	return controller.DecodeAsync[OutletStartUpgradeResponse](device.CallAsync("Outlet.startUpgrade", params))
}

type OutletGetActivityLogsParamsSearch struct {
	StartDate *string `json:"startDate,omitempty"` // YYYY-MM-DD
	EndDate   *string `json:"endDate,omitempty"`   // YYYY-MM-DD
}

func (r OutletGetActivityLogsParamsSearch) String() string {
	var ptr0 any = "<nil>"
	if r.StartDate != nil {
		ptr0 = fmt.Sprint(*r.StartDate)
	}
	var ptr1 any = "<nil>"
	if r.EndDate != nil {
		ptr1 = fmt.Sprint(*r.EndDate)
	}
	return fmt.Sprintf("{StartDate:%v EndDate:%v}", ptr0, ptr1)
}

type OutletGetActivityLogsParams struct {
	Search       OutletGetActivityLogsParamsSearch `json:"search"`
	RetrievalKey *string                           `json:"retrievalKey,omitempty"`
}

func (r OutletGetActivityLogsParams) String() string {
	var ptr0 any = "<nil>"
	if r.RetrievalKey != nil {
		ptr0 = fmt.Sprint(*r.RetrievalKey)
	}
	return fmt.Sprintf("{Search:%v RetrievalKey:%v}", r.Search, ptr0)
}

type OutletGetActivityLogsResponseLogsItem struct {
	Id   string      `json:"id"`
	Time time.Time   `json:"time"`
	Data interface{} `json:"data"`
}

func (r OutletGetActivityLogsResponseLogsItem) String() string {
	return fmt.Sprintf("{Id:%v Time:%v Data:%v}", r.Id, r.Time, r.Data)
}

type OutletGetActivityLogsResponseRetrievalKeys struct {
	Next *interface{} `json:"next,omitempty"`
}

func (r OutletGetActivityLogsResponseRetrievalKeys) String() string {
	var ptr0 any = "<nil>"
	if r.Next != nil {
		ptr0 = fmt.Sprint(*r.Next)
	}
	return fmt.Sprintf("{Next:%v}", ptr0)
}

type OutletGetActivityLogsResponse struct {
	Logs          []OutletGetActivityLogsResponseLogsItem    `json:"logs"`
	RetrievalKeys OutletGetActivityLogsResponseRetrievalKeys `json:"retrievalKeys"`
}

func (r OutletGetActivityLogsResponse) String() string {
	return fmt.Sprintf("{Logs:%v RetrievalKeys:%v}", r.Logs, r.RetrievalKeys)
}

// GetActivityLogs Retrieve device activity records. Requires DEVICE.HISTORICAL_DATA.READ permission.
func (device *Outlet) GetActivityLogs(params OutletGetActivityLogsParams) (OutletGetActivityLogsResponse, error) {
	var response OutletGetActivityLogsResponse
	err := device.Call("Outlet.getActivityLogs", params, &response)
	return response, err
}

func (device *Outlet) GetActivityLogsAsync(params OutletGetActivityLogsParams) <-chan controller.AsyncResult[OutletGetActivityLogsResponse] {
	return controller.DecodeAsync[OutletGetActivityLogsResponse](device.CallAsync("Outlet.getActivityLogs", params))
}

type OutletReportResponseDelay struct {
	On  int `json:"on"`  // Remain Delay ON minutes
	Off int `json:"off"` // Remain Delay OFF minutes
}

func (r OutletReportResponseDelay) String() string {
	return fmt.Sprintf("{On:%v Off:%v}", r.On, r.Off)
}

type OutletReportResponse struct {
	State    types.SwitchState         `json:"state"` // ['closed','open']
	Delay    OutletReportResponseDelay `json:"delay"`
	Power    *int                      `json:"power,omitempty"` // Current power (0 if unsupported)
	Version  string                    `json:"version"`
	Tz       int                       `json:"tz"`
	LoraInfo *types.LoraInfo           `json:"loraInfo,omitempty"`
}

func (r OutletReportResponse) String() string {
	var ptr0 any = "<nil>"
	if r.Power != nil {
		ptr0 = fmt.Sprint(*r.Power)
	}
	var ptr1 any = "<nil>"
	if r.LoraInfo != nil {
		ptr1 = fmt.Sprint(*r.LoraInfo)
	}
	return fmt.Sprintf("{State:%v Delay:%v Power:%v Version:%v Tz:%v LoraInfo:%v}", r.State, r.Delay, ptr0, r.Version, r.Tz, ptr1)
}

type OutletAlertResponseDelay struct {
	On  int `json:"on"`  // Remain Delay ON minutes
	Off int `json:"off"` // Remain Delay OFF minutes
}

func (r OutletAlertResponseDelay) String() string {
	return fmt.Sprintf("{On:%v Off:%v}", r.On, r.Off)
}

type OutletAlertResponse struct {
	State          types.SwitchState        `json:"state"` // ['closed','open']
	Delay          OutletAlertResponseDelay `json:"delay"`
	Power          *int                     `json:"power,omitempty"` // Current power (0 if unsupported)
	Version        string                   `json:"version"`
	Tz             int                      `json:"tz"`
	LoraInfo       *types.LoraInfo          `json:"loraInfo,omitempty"`
	StateChangedAt *types.Timestamp         `json:"stateChangedAt,omitempty"`
}

func (r OutletAlertResponse) String() string {
	var ptr0 any = "<nil>"
	if r.Power != nil {
		ptr0 = fmt.Sprint(*r.Power)
	}
	var ptr1 any = "<nil>"
	if r.LoraInfo != nil {
		ptr1 = fmt.Sprint(*r.LoraInfo)
	}
	var ptr2 any = "<nil>"
	if r.StateChangedAt != nil {
		ptr2 = fmt.Sprint(*r.StateChangedAt)
	}
	return fmt.Sprintf("{State:%v Delay:%v Power:%v Version:%v Tz:%v LoraInfo:%v StateChangedAt:%v}", r.State, r.Delay, ptr0, r.Version, r.Tz, ptr1, ptr2)
}

func (device *Outlet) ParseEvent(message controller.MqttMessage) (controller.Report, bool) {
	report, ok := device.Device.ParseEvent(message) // base impl decodes event + raw data
	if !ok {
		return report, false
	}
	report.Device = device                        // attribute the report to this concrete device
	data := report.Data.(controller.Unknown).Json // raw payload, re-typed below
	switch report.Event {
	case "Outlet.getState":
		var response OutletGetStateResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "Outlet.setState":
		var response OutletSetStateResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "Outlet.setDelay":
		var response OutletSetDelayResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "Outlet.getSchedules":
		var response OutletGetSchedulesResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "Outlet.setSchedules":
		var response OutletSetSchedulesResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "Outlet.getVersion":
		var response OutletGetVersionResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "Outlet.startUpgrade":
		var response OutletStartUpgradeResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "Outlet.getActivityLogs":
		var response OutletGetActivityLogsResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "Outlet.Report":
		var response OutletReportResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "Outlet.Alert":
		var response OutletAlertResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	}
	return report, true
}
