// Code generated by scripts/gen_device_types.py; DO NOT EDIT.
package devices

import (
	"encoding/json"
	"fmt"
	"time"

	"github.com/tyandl/homelink/pkg/yolink/controller"
	"github.com/tyandl/homelink/pkg/yolink/types"
)

type PowerFailureAlarm struct{ *controller.Device }

func init() {
	controller.RegisterDeviceFactory("PowerFailureAlarm", func(device *controller.Device) controller.DeviceController {
		return &PowerFailureAlarm{Device: device}
	})
}

type PowerFailureAlarmGetStateResponseState struct {
	State       *types.AlarmState  `json:"state,omitempty"`     // ['normal','alert','off']
	AlertType   *string            `json:"alertType,omitempty"` // Alert type
	Sound       int                `json:"sound"`               // Sound level
	Battery     types.BatteryLevel `json:"battery"`             // Battery level 0-4
	PowerSupply bool               `json:"powerSupply"`         // Is power supply connected
	Beep        bool               `json:"beep"`                // Beep enabled
	Mute        bool               `json:"mute"`                // Is in mute mode
	Version     string             `json:"version"`             // Firmware version
}

func (r PowerFailureAlarmGetStateResponseState) String() string {
	var ptr0 any = "<nil>"
	if r.State != nil {
		ptr0 = fmt.Sprint(*r.State)
	}
	var ptr1 any = "<nil>"
	if r.AlertType != nil {
		ptr1 = fmt.Sprint(*r.AlertType)
	}
	return fmt.Sprintf("{State:%v AlertType:%v Sound:%v Battery:%v PowerSupply:%v Beep:%v Mute:%v Version:%v}", ptr0, ptr1, r.Sound, r.Battery, r.PowerSupply, r.Beep, r.Mute, r.Version)
}

type PowerFailureAlarmGetStateResponse struct {
	State    PowerFailureAlarmGetStateResponseState `json:"state"`
	ReportAt time.Time                              `json:"reportAt"`
	DeviceId string                                 `json:"deviceId"`
}

func (r PowerFailureAlarmGetStateResponse) String() string {
	return fmt.Sprintf("{State:%v ReportAt:%v DeviceId:%v}", r.State, r.ReportAt, r.DeviceId)
}

// GetState Get last reported state of Power Failure Alarm
func (device *PowerFailureAlarm) GetState() (PowerFailureAlarmGetStateResponse, error) {
	var response PowerFailureAlarmGetStateResponse
	err := device.Call("PowerFailureAlarm.getState", nil, &response)
	return response, err
}

func (device *PowerFailureAlarm) GetStateAsync() <-chan controller.AsyncResult[PowerFailureAlarmGetStateResponse] {
	return controller.DecodeAsync[PowerFailureAlarmGetStateResponse](device.CallAsync("PowerFailureAlarm.getState", nil))
}

type PowerFailureAlarmReportResponse struct {
	State         types.AlarmState   `json:"state"`
	Sound         int                `json:"sound"`
	Battery       types.BatteryLevel `json:"battery"`
	PowerSupply   bool               `json:"powerSupply"` // true = AC power present
	AlertDuration int                `json:"alertDuration"`
	AlertInterval int                `json:"alertInterval"`
	Version       string             `json:"version"`
	Mute          bool               `json:"mute"`
	LoraP2PHash   *int               `json:"loraP2PHash,omitempty"`
	LoraInfo      *types.LoraInfo    `json:"loraInfo,omitempty"`
}

func (r PowerFailureAlarmReportResponse) String() string {
	var ptr0 any = "<nil>"
	if r.LoraP2PHash != nil {
		ptr0 = fmt.Sprint(*r.LoraP2PHash)
	}
	var ptr1 any = "<nil>"
	if r.LoraInfo != nil {
		ptr1 = fmt.Sprint(*r.LoraInfo)
	}
	return fmt.Sprintf("{State:%v Sound:%v Battery:%v PowerSupply:%v AlertDuration:%v AlertInterval:%v Version:%v Mute:%v LoraP2PHash:%v LoraInfo:%v}", r.State, r.Sound, r.Battery, r.PowerSupply, r.AlertDuration, r.AlertInterval, r.Version, r.Mute, ptr0, ptr1)
}

type PowerFailureAlarmStatusChangeResponse struct {
	State         types.AlarmState   `json:"state"`
	Sound         int                `json:"sound"`
	Battery       types.BatteryLevel `json:"battery"`
	PowerSupply   bool               `json:"powerSupply"` // true = AC power present
	AlertDuration int                `json:"alertDuration"`
	AlertInterval int                `json:"alertInterval"`
	Version       string             `json:"version"`
	Mute          bool               `json:"mute"`
	LoraInfo      *types.LoraInfo    `json:"loraInfo,omitempty"`
}

func (r PowerFailureAlarmStatusChangeResponse) String() string {
	var ptr0 any = "<nil>"
	if r.LoraInfo != nil {
		ptr0 = fmt.Sprint(*r.LoraInfo)
	}
	return fmt.Sprintf("{State:%v Sound:%v Battery:%v PowerSupply:%v AlertDuration:%v AlertInterval:%v Version:%v Mute:%v LoraInfo:%v}", r.State, r.Sound, r.Battery, r.PowerSupply, r.AlertDuration, r.AlertInterval, r.Version, r.Mute, ptr0)
}

type PowerFailureAlarmAlertResponse struct {
	State          *types.AlarmState  `json:"state,omitempty"`     // ['normal','alert','off']
	AlertType      *string            `json:"alertType,omitempty"` // Alert type
	Sound          int                `json:"sound"`               // Sound level
	Battery        types.BatteryLevel `json:"battery"`             // Battery level 0-4
	PowerSupply    bool               `json:"powerSupply"`         // Is power supply connected
	Beep           bool               `json:"beep"`                // Beep enabled
	Mute           bool               `json:"mute"`                // Is in mute mode
	Version        string             `json:"version"`             // Firmware version
	LoraInfo       *types.LoraInfo    `json:"loraInfo,omitempty"`
	StateChangedAt *types.Timestamp   `json:"stateChangedAt,omitempty"`
}

func (r PowerFailureAlarmAlertResponse) String() string {
	var ptr0 any = "<nil>"
	if r.State != nil {
		ptr0 = fmt.Sprint(*r.State)
	}
	var ptr1 any = "<nil>"
	if r.AlertType != nil {
		ptr1 = fmt.Sprint(*r.AlertType)
	}
	var ptr2 any = "<nil>"
	if r.LoraInfo != nil {
		ptr2 = fmt.Sprint(*r.LoraInfo)
	}
	var ptr3 any = "<nil>"
	if r.StateChangedAt != nil {
		ptr3 = fmt.Sprint(*r.StateChangedAt)
	}
	return fmt.Sprintf("{State:%v AlertType:%v Sound:%v Battery:%v PowerSupply:%v Beep:%v Mute:%v Version:%v LoraInfo:%v StateChangedAt:%v}", ptr0, ptr1, r.Sound, r.Battery, r.PowerSupply, r.Beep, r.Mute, r.Version, ptr2, ptr3)
}

func (device *PowerFailureAlarm) ParseEvent(message controller.MqttMessage) (controller.Report, bool) {
	report, ok := device.Device.ParseEvent(message) // base impl decodes event + raw data
	if !ok {
		return report, false
	}
	report.Device = device                        // attribute the report to this concrete device
	data := report.Data.(controller.Unknown).Json // raw payload, re-typed below
	switch report.Event {
	case "PowerFailureAlarm.getState":
		var response PowerFailureAlarmGetStateResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "PowerFailureAlarm.Report":
		var response PowerFailureAlarmReportResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "PowerFailureAlarm.StatusChange":
		var response PowerFailureAlarmStatusChangeResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "PowerFailureAlarm.Alert":
		var response PowerFailureAlarmAlertResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	}
	return report, true
}
