// Code generated by scripts/gen_device_types.py; DO NOT EDIT.
package devices

import (
	"encoding/json"
	"fmt"

	"github.com/tyandl/homelink/pkg/yolink/controller"
	"github.com/tyandl/homelink/pkg/yolink/types"
)

type Siren struct{ *controller.Device }

func init() {
	controller.RegisterDeviceFactory("Siren", func(device *controller.Device) controller.DeviceController {
		return &Siren{Device: device}
	})
}

type SirenGetStateResponse struct {
	State         types.AlarmState   `json:"state"`         // ['normal','alert','off']
	SoundLevel    int                `json:"soundLevel"`    // Volume
	Battery       types.BatteryLevel `json:"battery"`       // Battery level
	PowerSupply   types.PowerSupply  `json:"powerSupply"`   // ['battery','usb']
	AlarmDuation  int                `json:"alarmDuation"`  // Alert duration
	Mute          bool               `json:"mute"`          // Muted
	MuteDuration  int                `json:"muteDuration"`  // Mute duration seconds
	MuteRemaining int                `json:"muteRemaining"` // Seconds remaining in mute
	Tz            int                `json:"tz"`            // Timezone -12~12
	Version       string             `json:"version"`       // Firmware version
	LoraInfo      *types.LoraInfo    `json:"loraInfo,omitempty"`
}

func (r SirenGetStateResponse) String() string {
	var ptr0 any = "<nil>"
	if r.LoraInfo != nil {
		ptr0 = fmt.Sprint(*r.LoraInfo)
	}
	return fmt.Sprintf("{State:%v SoundLevel:%v Battery:%v PowerSupply:%v AlarmDuation:%v Mute:%v MuteDuration:%v MuteRemaining:%v Tz:%v Version:%v LoraInfo:%v}", r.State, r.SoundLevel, r.Battery, r.PowerSupply, r.AlarmDuation, r.Mute, r.MuteDuration, r.MuteRemaining, r.Tz, r.Version, ptr0)
}

// GetState Get the state of siren
func (device *Siren) GetState() (SirenGetStateResponse, error) {
	var response SirenGetStateResponse
	err := device.Call("Siren.getState", nil, &response)
	return response, err
}

func (device *Siren) GetStateAsync() <-chan controller.AsyncResult[SirenGetStateResponse] {
	return controller.DecodeAsync[SirenGetStateResponse](device.CallAsync("Siren.getState", nil))
}

type SirenSetStateParamsState struct {
	Alarm bool `json:"alarm"` // true=start alert, false=stop alert
}

func (r SirenSetStateParamsState) String() string {
	return fmt.Sprintf("{Alarm:%v}", r.Alarm)
}

type SirenSetStateParams struct {
	State SirenSetStateParamsState `json:"state"`
}

func (r SirenSetStateParams) String() string {
	return fmt.Sprintf("{State:%v}", r.State)
}

type SirenSetStateResponse struct {
	State types.AlarmState `json:"state"` // ['normal','alert','off']
}

func (r SirenSetStateResponse) String() string {
	return fmt.Sprintf("{State:%v}", r.State)
}

// SetState Set the state of siren
func (device *Siren) SetState(params SirenSetStateParams) (SirenSetStateResponse, error) {
	var response SirenSetStateResponse
	err := device.Call("Siren.setState", params, &response)
	return response, err
}

func (device *Siren) SetStateAsync(params SirenSetStateParams) <-chan controller.AsyncResult[SirenSetStateResponse] {
	return controller.DecodeAsync[SirenSetStateResponse](device.CallAsync("Siren.setState", params))
}

type SirenReportResponse struct {
	State         types.AlarmState   `json:"state"`
	SoundLevel    int                `json:"soundLevel"`
	Mute          bool               `json:"mute"`
	Battery       types.BatteryLevel `json:"battery"`
	PowerSupply   string             `json:"powerSupply"`  // usb | battery
	AlarmDuation  int                `json:"alarmDuation"` // Alarm duration seconds (sic)
	Version       string             `json:"version"`
	MuteDuration  int                `json:"muteDuration"`
	MuteRemaining int                `json:"muteRemaining"`
	Tz            int                `json:"tz"`
	LoraInfo      *types.LoraInfo    `json:"loraInfo,omitempty"`
}

func (r SirenReportResponse) String() string {
	var ptr0 any = "<nil>"
	if r.LoraInfo != nil {
		ptr0 = fmt.Sprint(*r.LoraInfo)
	}
	return fmt.Sprintf("{State:%v SoundLevel:%v Mute:%v Battery:%v PowerSupply:%v AlarmDuation:%v Version:%v MuteDuration:%v MuteRemaining:%v Tz:%v LoraInfo:%v}", r.State, r.SoundLevel, r.Mute, r.Battery, r.PowerSupply, r.AlarmDuation, r.Version, r.MuteDuration, r.MuteRemaining, r.Tz, ptr0)
}

type SirenStatusChangeResponse struct {
	State        types.AlarmState   `json:"state"`
	SoundLevel   int                `json:"soundLevel"`
	Mute         bool               `json:"mute"`
	Battery      types.BatteryLevel `json:"battery"`
	PowerSupply  string             `json:"powerSupply"`  // usb | battery
	AlarmDuation int                `json:"alarmDuation"` // Alarm duration seconds (sic)
	Version      string             `json:"version"`
	LoraInfo     *types.LoraInfo    `json:"loraInfo,omitempty"`
}

func (r SirenStatusChangeResponse) String() string {
	var ptr0 any = "<nil>"
	if r.LoraInfo != nil {
		ptr0 = fmt.Sprint(*r.LoraInfo)
	}
	return fmt.Sprintf("{State:%v SoundLevel:%v Mute:%v Battery:%v PowerSupply:%v AlarmDuation:%v Version:%v LoraInfo:%v}", r.State, r.SoundLevel, r.Mute, r.Battery, r.PowerSupply, r.AlarmDuation, r.Version, ptr0)
}

type SirenAlertResponse struct {
	State          types.AlarmState   `json:"state"`         // ['normal','alert','off']
	SoundLevel     int                `json:"soundLevel"`    // Volume
	Battery        types.BatteryLevel `json:"battery"`       // Battery level
	PowerSupply    types.PowerSupply  `json:"powerSupply"`   // ['battery','usb']
	AlarmDuation   int                `json:"alarmDuation"`  // Alert duration
	Mute           bool               `json:"mute"`          // Muted
	MuteDuration   int                `json:"muteDuration"`  // Mute duration seconds
	MuteRemaining  int                `json:"muteRemaining"` // Seconds remaining in mute
	Tz             int                `json:"tz"`            // Timezone -12~12
	Version        string             `json:"version"`       // Firmware version
	LoraInfo       *types.LoraInfo    `json:"loraInfo,omitempty"`
	StateChangedAt *types.Timestamp   `json:"stateChangedAt,omitempty"`
}

func (r SirenAlertResponse) String() string {
	var ptr0 any = "<nil>"
	if r.LoraInfo != nil {
		ptr0 = fmt.Sprint(*r.LoraInfo)
	}
	var ptr1 any = "<nil>"
	if r.StateChangedAt != nil {
		ptr1 = fmt.Sprint(*r.StateChangedAt)
	}
	return fmt.Sprintf("{State:%v SoundLevel:%v Battery:%v PowerSupply:%v AlarmDuation:%v Mute:%v MuteDuration:%v MuteRemaining:%v Tz:%v Version:%v LoraInfo:%v StateChangedAt:%v}", r.State, r.SoundLevel, r.Battery, r.PowerSupply, r.AlarmDuation, r.Mute, r.MuteDuration, r.MuteRemaining, r.Tz, r.Version, ptr0, ptr1)
}

func (device *Siren) ParseEvent(message controller.MqttMessage) (controller.Report, bool) {
	report, ok := device.Device.ParseEvent(message) // base impl decodes event + raw data
	if !ok {
		return report, false
	}
	report.Device = device                        // attribute the report to this concrete device
	data := report.Data.(controller.Unknown).Json // raw payload, re-typed below
	switch report.Event {
	case "Siren.getState":
		var response SirenGetStateResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "Siren.setState":
		var response SirenSetStateResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "Siren.Report":
		var response SirenReportResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "Siren.StatusChange":
		var response SirenStatusChangeResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "Siren.Alert":
		var response SirenAlertResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	}
	return report, true
}
