// Code generated by scripts/gen_device_types.py; DO NOT EDIT.
package devices

import (
	"encoding/json"
	"fmt"
	"time"

	"github.com/tyandl/homelink/pkg/yolink/controller"
	"github.com/tyandl/homelink/pkg/yolink/types"
)

type SmartRemoter struct{ *controller.Device }

func init() {
	controller.RegisterDeviceFactory("SmartRemoter", func(device *controller.Device) controller.DeviceController {
		return &SmartRemoter{Device: device}
	})
}

type SmartRemoterGetStateResponseStateEvent struct {
	KeyMask *int                         `json:"keyMask,omitempty"` // Triggered keys bitmask (bits 0-7)
	Type    *types.SmartRemoterEventType `json:"type,omitempty"`    // ['Press','LongPress']
}

func (r SmartRemoterGetStateResponseStateEvent) String() string {
	var ptr0 any = "<nil>"
	if r.KeyMask != nil {
		ptr0 = fmt.Sprint(*r.KeyMask)
	}
	var ptr1 any = "<nil>"
	if r.Type != nil {
		ptr1 = fmt.Sprint(*r.Type)
	}
	return fmt.Sprintf("{KeyMask:%v Type:%v}", ptr0, ptr1)
}

type SmartRemoterGetStateResponseState struct {
	Event          SmartRemoterGetStateResponseStateEvent `json:"event"`
	Battery        types.BatteryLevel                     `json:"battery"`        // Battery level 0-4
	Version        string                                 `json:"version"`        // Firmware version
	DevTemperature int                                    `json:"devTemperature"` // Device temperature
	Beep           bool                                   `json:"beep"`
}

func (r SmartRemoterGetStateResponseState) String() string {
	return fmt.Sprintf("{Event:%v Battery:%v Version:%v DevTemperature:%v Beep:%v}", r.Event, r.Battery, r.Version, r.DevTemperature, r.Beep)
}

type SmartRemoterGetStateResponse struct {
	Online   bool                              `json:"online"` // Is device online
	State    SmartRemoterGetStateResponseState `json:"state"`
	ReportAt time.Time                         `json:"reportAt"`
	DeviceId string                            `json:"deviceId"`
}

func (r SmartRemoterGetStateResponse) String() string {
	return fmt.Sprintf("{Online:%v State:%v ReportAt:%v DeviceId:%v}", r.Online, r.State, r.ReportAt, r.DeviceId)
}

// GetState Get last reported state of Smart Remoter
func (device *SmartRemoter) GetState() (SmartRemoterGetStateResponse, error) {
	var response SmartRemoterGetStateResponse
	err := device.Call("SmartRemoter.getState", nil, &response)
	return response, err
}

func (device *SmartRemoter) GetStateAsync() <-chan controller.AsyncResult[SmartRemoterGetStateResponse] {
	return controller.DecodeAsync[SmartRemoterGetStateResponse](device.CallAsync("SmartRemoter.getState", nil))
}

type SmartRemoterReportResponseEvent struct {
	KeyMask *int                         `json:"keyMask,omitempty"` // Triggered keys bitmask (bits 0-7)
	Type    *types.SmartRemoterEventType `json:"type,omitempty"`    // ['Press','LongPress']
}

func (r SmartRemoterReportResponseEvent) String() string {
	var ptr0 any = "<nil>"
	if r.KeyMask != nil {
		ptr0 = fmt.Sprint(*r.KeyMask)
	}
	var ptr1 any = "<nil>"
	if r.Type != nil {
		ptr1 = fmt.Sprint(*r.Type)
	}
	return fmt.Sprintf("{KeyMask:%v Type:%v}", ptr0, ptr1)
}

type SmartRemoterReportResponse struct {
	Event          SmartRemoterReportResponseEvent `json:"event"`
	Battery        types.BatteryLevel              `json:"battery"`        // Battery level 0-4
	Version        string                          `json:"version"`        // Firmware version
	DevTemperature int                             `json:"devTemperature"` // Device temperature
	Beep           bool                            `json:"beep"`
	LoraInfo       *types.LoraInfo                 `json:"loraInfo,omitempty"`
}

func (r SmartRemoterReportResponse) String() string {
	var ptr0 any = "<nil>"
	if r.LoraInfo != nil {
		ptr0 = fmt.Sprint(*r.LoraInfo)
	}
	return fmt.Sprintf("{Event:%v Battery:%v Version:%v DevTemperature:%v Beep:%v LoraInfo:%v}", r.Event, r.Battery, r.Version, r.DevTemperature, r.Beep, ptr0)
}

type SmartRemoterAlertResponseEvent struct {
	KeyMask *int                         `json:"keyMask,omitempty"` // Triggered keys bitmask (bits 0-7)
	Type    *types.SmartRemoterEventType `json:"type,omitempty"`    // ['Press','LongPress']
}

func (r SmartRemoterAlertResponseEvent) String() string {
	var ptr0 any = "<nil>"
	if r.KeyMask != nil {
		ptr0 = fmt.Sprint(*r.KeyMask)
	}
	var ptr1 any = "<nil>"
	if r.Type != nil {
		ptr1 = fmt.Sprint(*r.Type)
	}
	return fmt.Sprintf("{KeyMask:%v Type:%v}", ptr0, ptr1)
}

type SmartRemoterAlertResponse struct {
	Event          SmartRemoterAlertResponseEvent `json:"event"`
	Battery        types.BatteryLevel             `json:"battery"`        // Battery level 0-4
	Version        string                         `json:"version"`        // Firmware version
	DevTemperature int                            `json:"devTemperature"` // Device temperature
	Beep           bool                           `json:"beep"`
	LoraInfo       *types.LoraInfo                `json:"loraInfo,omitempty"`
	StateChangedAt *types.Timestamp               `json:"stateChangedAt,omitempty"`
}

func (r SmartRemoterAlertResponse) String() string {
	var ptr0 any = "<nil>"
	if r.LoraInfo != nil {
		ptr0 = fmt.Sprint(*r.LoraInfo)
	}
	var ptr1 any = "<nil>"
	if r.StateChangedAt != nil {
		ptr1 = fmt.Sprint(*r.StateChangedAt)
	}
	return fmt.Sprintf("{Event:%v Battery:%v Version:%v DevTemperature:%v Beep:%v LoraInfo:%v StateChangedAt:%v}", r.Event, r.Battery, r.Version, r.DevTemperature, r.Beep, ptr0, ptr1)
}

func (device *SmartRemoter) ParseEvent(message controller.MqttMessage) (controller.Report, bool) {
	report, ok := device.Device.ParseEvent(message) // base impl decodes event + raw data
	if !ok {
		return report, false
	}
	report.Device = device                        // attribute the report to this concrete device
	data := report.Data.(controller.Unknown).Json // raw payload, re-typed below
	switch report.Event {
	case "SmartRemoter.getState":
		var response SmartRemoterGetStateResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "SmartRemoter.Report":
		var response SmartRemoterReportResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "SmartRemoter.Alert":
		var response SmartRemoterAlertResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	}
	return report, true
}
