// Code generated by scripts/gen_device_types.py; DO NOT EDIT.
package devices

import (
	"encoding/json"
	"fmt"
	"time"

	"github.com/tyandl/homelink/pkg/yolink/controller"
	"github.com/tyandl/homelink/pkg/yolink/types"
)

type SoilThcSensor struct{ *controller.Device }

func init() {
	controller.RegisterDeviceFactory("SoilThcSensor", func(device *controller.Device) controller.DeviceController {
		return &SoilThcSensor{Device: device}
	})
}

type SoilThcSensorGetStateResponseStateAlarm struct {
	LowTemp          bool `json:"lowTemp"`
	HighTemp         bool `json:"highTemp"`
	LowHumidity      bool `json:"lowHumidity"`
	HighHumidity     bool `json:"highHumidity"`
	LowConductivity  bool `json:"lowConductivity"`
	HighConductivity bool `json:"highConductivity"`
	Period           bool `json:"period"`
}

func (r SoilThcSensorGetStateResponseStateAlarm) String() string {
	return fmt.Sprintf("{LowTemp:%v HighTemp:%v LowHumidity:%v HighHumidity:%v LowConductivity:%v HighConductivity:%v Period:%v}", r.LowTemp, r.HighTemp, r.LowHumidity, r.HighHumidity, r.LowConductivity, r.HighConductivity, r.Period)
}

type SoilThcSensorGetStateResponseStateState struct {
	Temperature  types.Temperature `json:"temperature"`  // Current temperature
	Humidity     float32           `json:"humidity"`     // Current humidity
	Conductivity float32           `json:"conductivity"` // Current conductivity µS/cm
}

func (r SoilThcSensorGetStateResponseStateState) String() string {
	return fmt.Sprintf("{Temperature:%v Humidity:%v Conductivity:%v}", r.Temperature, r.Humidity, r.Conductivity)
}

type SoilThcSensorGetStateResponseStateAttributesTempLimit struct {
	Max float32 `json:"max"`
	Min float32 `json:"min"`
}

func (r SoilThcSensorGetStateResponseStateAttributesTempLimit) String() string {
	return fmt.Sprintf("{Max:%v Min:%v}", r.Max, r.Min)
}

type SoilThcSensorGetStateResponseStateAttributesHumidityLimit struct {
	Max float32 `json:"max"`
	Min float32 `json:"min"`
}

func (r SoilThcSensorGetStateResponseStateAttributesHumidityLimit) String() string {
	return fmt.Sprintf("{Max:%v Min:%v}", r.Max, r.Min)
}

type SoilThcSensorGetStateResponseStateAttributesConductivityLimit struct {
	Max float32 `json:"max"`
	Min float32 `json:"min"`
}

func (r SoilThcSensorGetStateResponseStateAttributesConductivityLimit) String() string {
	return fmt.Sprintf("{Max:%v Min:%v}", r.Max, r.Min)
}

type SoilThcSensorGetStateResponseStateAttributes struct {
	AlertInterval     int                                                           `json:"alertInterval"`
	ReportInterval    int                                                           `json:"reportInterval"`
	TempLimit         SoilThcSensorGetStateResponseStateAttributesTempLimit         `json:"tempLimit"`
	HumidityLimit     SoilThcSensorGetStateResponseStateAttributesHumidityLimit     `json:"humidityLimit"`
	ConductivityLimit SoilThcSensorGetStateResponseStateAttributesConductivityLimit `json:"conductivityLimit"`
}

func (r SoilThcSensorGetStateResponseStateAttributes) String() string {
	return fmt.Sprintf("{AlertInterval:%v ReportInterval:%v TempLimit:%v HumidityLimit:%v ConductivityLimit:%v}", r.AlertInterval, r.ReportInterval, r.TempLimit, r.HumidityLimit, r.ConductivityLimit)
}

type SoilThcSensorGetStateResponseState struct {
	Alarm      SoilThcSensorGetStateResponseStateAlarm      `json:"alarm"`
	State      SoilThcSensorGetStateResponseStateState      `json:"state"`
	Attributes SoilThcSensorGetStateResponseStateAttributes `json:"attributes"`
	Tz         int                                          `json:"tz"`
	Battery    types.BatteryLevel                           `json:"battery"` // 0-4
	Version    string                                       `json:"version"`
}

func (r SoilThcSensorGetStateResponseState) String() string {
	return fmt.Sprintf("{Alarm:%v State:%v Attributes:%v Tz:%v Battery:%v Version:%v}", r.Alarm, r.State, r.Attributes, r.Tz, r.Battery, r.Version)
}

type SoilThcSensorGetStateResponse struct {
	Online   bool                               `json:"online"`
	State    SoilThcSensorGetStateResponseState `json:"state"`
	ReportAt time.Time                          `json:"reportAt"`
	DeviceId string                             `json:"deviceId"`
}

func (r SoilThcSensorGetStateResponse) String() string {
	return fmt.Sprintf("{Online:%v State:%v ReportAt:%v DeviceId:%v}", r.Online, r.State, r.ReportAt, r.DeviceId)
}

// GetState Get Soil Temperature, Humidity & Conductivity Sensor's State
func (device *SoilThcSensor) GetState() (SoilThcSensorGetStateResponse, error) {
	var response SoilThcSensorGetStateResponse
	err := device.Call("SoilThcSensor.getState", nil, &response)
	return response, err
}

func (device *SoilThcSensor) GetStateAsync() <-chan controller.AsyncResult[SoilThcSensorGetStateResponse] {
	return controller.DecodeAsync[SoilThcSensorGetStateResponse](device.CallAsync("SoilThcSensor.getState", nil))
}

type SoilThcSensorGetActivityLogsParamsSearch struct {
	StartDate *string `json:"startDate,omitempty"` // YYYY-MM-DD
	EndDate   *string `json:"endDate,omitempty"`   // YYYY-MM-DD
}

func (r SoilThcSensorGetActivityLogsParamsSearch) String() string {
	var ptr0 any = "<nil>"
	if r.StartDate != nil {
		ptr0 = fmt.Sprint(*r.StartDate)
	}
	var ptr1 any = "<nil>"
	if r.EndDate != nil {
		ptr1 = fmt.Sprint(*r.EndDate)
	}
	return fmt.Sprintf("{StartDate:%v EndDate:%v}", ptr0, ptr1)
}

type SoilThcSensorGetActivityLogsParams struct {
	Search       SoilThcSensorGetActivityLogsParamsSearch `json:"search"`
	RetrievalKey *string                                  `json:"retrievalKey,omitempty"`
}

func (r SoilThcSensorGetActivityLogsParams) String() string {
	var ptr0 any = "<nil>"
	if r.RetrievalKey != nil {
		ptr0 = fmt.Sprint(*r.RetrievalKey)
	}
	return fmt.Sprintf("{Search:%v RetrievalKey:%v}", r.Search, ptr0)
}

type SoilThcSensorGetActivityLogsResponseLogsItem struct {
	Id   string      `json:"id"`
	Time time.Time   `json:"time"`
	Data interface{} `json:"data"`
}

func (r SoilThcSensorGetActivityLogsResponseLogsItem) String() string {
	return fmt.Sprintf("{Id:%v Time:%v Data:%v}", r.Id, r.Time, r.Data)
}

type SoilThcSensorGetActivityLogsResponseRetrievalKeys struct {
	Next *interface{} `json:"next,omitempty"`
}

func (r SoilThcSensorGetActivityLogsResponseRetrievalKeys) String() string {
	var ptr0 any = "<nil>"
	if r.Next != nil {
		ptr0 = fmt.Sprint(*r.Next)
	}
	return fmt.Sprintf("{Next:%v}", ptr0)
}

type SoilThcSensorGetActivityLogsResponse struct {
	Logs          []SoilThcSensorGetActivityLogsResponseLogsItem    `json:"logs"`
	RetrievalKeys SoilThcSensorGetActivityLogsResponseRetrievalKeys `json:"retrievalKeys"`
}

func (r SoilThcSensorGetActivityLogsResponse) String() string {
	return fmt.Sprintf("{Logs:%v RetrievalKeys:%v}", r.Logs, r.RetrievalKeys)
}

// GetActivityLogs Retrieve device activity records. Requires DEVICE.HISTORICAL_DATA.READ permission.
func (device *SoilThcSensor) GetActivityLogs(params SoilThcSensorGetActivityLogsParams) (SoilThcSensorGetActivityLogsResponse, error) {
	var response SoilThcSensorGetActivityLogsResponse
	err := device.Call("SoilThcSensor.getActivityLogs", params, &response)
	return response, err
}

func (device *SoilThcSensor) GetActivityLogsAsync(params SoilThcSensorGetActivityLogsParams) <-chan controller.AsyncResult[SoilThcSensorGetActivityLogsResponse] {
	return controller.DecodeAsync[SoilThcSensorGetActivityLogsResponse](device.CallAsync("SoilThcSensor.getActivityLogs", params))
}

type SoilThcSensorGetMetricsLogsParamsSearch struct {
	StartDate *string `json:"startDate,omitempty"` // YYYY-MM-DD
	EndDate   *string `json:"endDate,omitempty"`   // YYYY-MM-DD
}

func (r SoilThcSensorGetMetricsLogsParamsSearch) String() string {
	var ptr0 any = "<nil>"
	if r.StartDate != nil {
		ptr0 = fmt.Sprint(*r.StartDate)
	}
	var ptr1 any = "<nil>"
	if r.EndDate != nil {
		ptr1 = fmt.Sprint(*r.EndDate)
	}
	return fmt.Sprintf("{StartDate:%v EndDate:%v}", ptr0, ptr1)
}

type SoilThcSensorGetMetricsLogsParams struct {
	Search SoilThcSensorGetMetricsLogsParamsSearch `json:"search"`
}

func (r SoilThcSensorGetMetricsLogsParams) String() string {
	return fmt.Sprintf("{Search:%v}", r.Search)
}

type SoilThcSensorGetMetricsLogsResponseLogsItem struct {
	Time time.Time `json:"time"`
}

func (r SoilThcSensorGetMetricsLogsResponseLogsItem) String() string {
	return fmt.Sprintf("{Time:%v}", r.Time)
}

type SoilThcSensorGetMetricsLogsResponse struct {
	Logs []SoilThcSensorGetMetricsLogsResponseLogsItem `json:"logs"`
}

func (r SoilThcSensorGetMetricsLogsResponse) String() string {
	return fmt.Sprintf("{Logs:%v}", r.Logs)
}

// GetMetricsLogs Retrieve device metrics logs. Requires DEVICE.HISTORICAL_DATA.READ permission.
func (device *SoilThcSensor) GetMetricsLogs(params SoilThcSensorGetMetricsLogsParams) (SoilThcSensorGetMetricsLogsResponse, error) {
	var response SoilThcSensorGetMetricsLogsResponse
	err := device.Call("SoilThcSensor.getMetricsLogs", params, &response)
	return response, err
}

func (device *SoilThcSensor) GetMetricsLogsAsync(params SoilThcSensorGetMetricsLogsParams) <-chan controller.AsyncResult[SoilThcSensorGetMetricsLogsResponse] {
	return controller.DecodeAsync[SoilThcSensorGetMetricsLogsResponse](device.CallAsync("SoilThcSensor.getMetricsLogs", params))
}

type SoilThcSensorReportResponseAlarm struct {
	LowTemp          bool `json:"lowTemp"`
	HighTemp         bool `json:"highTemp"`
	LowHumidity      bool `json:"lowHumidity"`
	HighHumidity     bool `json:"highHumidity"`
	LowConductivity  bool `json:"lowConductivity"`
	HighConductivity bool `json:"highConductivity"`
	Period           bool `json:"period"`
}

func (r SoilThcSensorReportResponseAlarm) String() string {
	return fmt.Sprintf("{LowTemp:%v HighTemp:%v LowHumidity:%v HighHumidity:%v LowConductivity:%v HighConductivity:%v Period:%v}", r.LowTemp, r.HighTemp, r.LowHumidity, r.HighHumidity, r.LowConductivity, r.HighConductivity, r.Period)
}

type SoilThcSensorReportResponseState struct {
	Temperature  types.Temperature `json:"temperature"`  // Current temperature
	Humidity     float32           `json:"humidity"`     // Current humidity
	Conductivity float32           `json:"conductivity"` // Current conductivity µS/cm
}

func (r SoilThcSensorReportResponseState) String() string {
	return fmt.Sprintf("{Temperature:%v Humidity:%v Conductivity:%v}", r.Temperature, r.Humidity, r.Conductivity)
}

type SoilThcSensorReportResponseAttributesTempLimit struct {
	Max float32 `json:"max"`
	Min float32 `json:"min"`
}

func (r SoilThcSensorReportResponseAttributesTempLimit) String() string {
	return fmt.Sprintf("{Max:%v Min:%v}", r.Max, r.Min)
}

type SoilThcSensorReportResponseAttributesHumidityLimit struct {
	Max float32 `json:"max"`
	Min float32 `json:"min"`
}

func (r SoilThcSensorReportResponseAttributesHumidityLimit) String() string {
	return fmt.Sprintf("{Max:%v Min:%v}", r.Max, r.Min)
}

type SoilThcSensorReportResponseAttributesConductivityLimit struct {
	Max float32 `json:"max"`
	Min float32 `json:"min"`
}

func (r SoilThcSensorReportResponseAttributesConductivityLimit) String() string {
	return fmt.Sprintf("{Max:%v Min:%v}", r.Max, r.Min)
}

type SoilThcSensorReportResponseAttributes struct {
	AlertInterval     int                                                    `json:"alertInterval"`
	ReportInterval    int                                                    `json:"reportInterval"`
	TempLimit         SoilThcSensorReportResponseAttributesTempLimit         `json:"tempLimit"`
	HumidityLimit     SoilThcSensorReportResponseAttributesHumidityLimit     `json:"humidityLimit"`
	ConductivityLimit SoilThcSensorReportResponseAttributesConductivityLimit `json:"conductivityLimit"`
}

func (r SoilThcSensorReportResponseAttributes) String() string {
	return fmt.Sprintf("{AlertInterval:%v ReportInterval:%v TempLimit:%v HumidityLimit:%v ConductivityLimit:%v}", r.AlertInterval, r.ReportInterval, r.TempLimit, r.HumidityLimit, r.ConductivityLimit)
}

type SoilThcSensorReportResponse struct {
	Alarm      SoilThcSensorReportResponseAlarm      `json:"alarm"`
	State      SoilThcSensorReportResponseState      `json:"state"`
	Attributes SoilThcSensorReportResponseAttributes `json:"attributes"`
	Tz         int                                   `json:"tz"`
	Battery    types.BatteryLevel                    `json:"battery"` // 0-4
	Version    string                                `json:"version"`
	LoraInfo   *types.LoraInfo                       `json:"loraInfo,omitempty"`
}

func (r SoilThcSensorReportResponse) String() string {
	var ptr0 any = "<nil>"
	if r.LoraInfo != nil {
		ptr0 = fmt.Sprint(*r.LoraInfo)
	}
	return fmt.Sprintf("{Alarm:%v State:%v Attributes:%v Tz:%v Battery:%v Version:%v LoraInfo:%v}", r.Alarm, r.State, r.Attributes, r.Tz, r.Battery, r.Version, ptr0)
}

type SoilThcSensorAlertResponseAlarm struct {
	LowTemp          bool `json:"lowTemp"`
	HighTemp         bool `json:"highTemp"`
	LowHumidity      bool `json:"lowHumidity"`
	HighHumidity     bool `json:"highHumidity"`
	LowConductivity  bool `json:"lowConductivity"`
	HighConductivity bool `json:"highConductivity"`
	Period           bool `json:"period"`
}

func (r SoilThcSensorAlertResponseAlarm) String() string {
	return fmt.Sprintf("{LowTemp:%v HighTemp:%v LowHumidity:%v HighHumidity:%v LowConductivity:%v HighConductivity:%v Period:%v}", r.LowTemp, r.HighTemp, r.LowHumidity, r.HighHumidity, r.LowConductivity, r.HighConductivity, r.Period)
}

type SoilThcSensorAlertResponseState struct {
	Temperature  types.Temperature `json:"temperature"`  // Current temperature
	Humidity     float32           `json:"humidity"`     // Current humidity
	Conductivity float32           `json:"conductivity"` // Current conductivity µS/cm
}

func (r SoilThcSensorAlertResponseState) String() string {
	return fmt.Sprintf("{Temperature:%v Humidity:%v Conductivity:%v}", r.Temperature, r.Humidity, r.Conductivity)
}

type SoilThcSensorAlertResponseAttributesTempLimit struct {
	Max float32 `json:"max"`
	Min float32 `json:"min"`
}

func (r SoilThcSensorAlertResponseAttributesTempLimit) String() string {
	return fmt.Sprintf("{Max:%v Min:%v}", r.Max, r.Min)
}

type SoilThcSensorAlertResponseAttributesHumidityLimit struct {
	Max float32 `json:"max"`
	Min float32 `json:"min"`
}

func (r SoilThcSensorAlertResponseAttributesHumidityLimit) String() string {
	return fmt.Sprintf("{Max:%v Min:%v}", r.Max, r.Min)
}

type SoilThcSensorAlertResponseAttributesConductivityLimit struct {
	Max float32 `json:"max"`
	Min float32 `json:"min"`
}

func (r SoilThcSensorAlertResponseAttributesConductivityLimit) String() string {
	return fmt.Sprintf("{Max:%v Min:%v}", r.Max, r.Min)
}

type SoilThcSensorAlertResponseAttributes struct {
	AlertInterval     int                                                   `json:"alertInterval"`
	ReportInterval    int                                                   `json:"reportInterval"`
	TempLimit         SoilThcSensorAlertResponseAttributesTempLimit         `json:"tempLimit"`
	HumidityLimit     SoilThcSensorAlertResponseAttributesHumidityLimit     `json:"humidityLimit"`
	ConductivityLimit SoilThcSensorAlertResponseAttributesConductivityLimit `json:"conductivityLimit"`
}

func (r SoilThcSensorAlertResponseAttributes) String() string {
	return fmt.Sprintf("{AlertInterval:%v ReportInterval:%v TempLimit:%v HumidityLimit:%v ConductivityLimit:%v}", r.AlertInterval, r.ReportInterval, r.TempLimit, r.HumidityLimit, r.ConductivityLimit)
}

type SoilThcSensorAlertResponse struct {
	Alarm          SoilThcSensorAlertResponseAlarm      `json:"alarm"`
	State          SoilThcSensorAlertResponseState      `json:"state"`
	Attributes     SoilThcSensorAlertResponseAttributes `json:"attributes"`
	Tz             int                                  `json:"tz"`
	Battery        types.BatteryLevel                   `json:"battery"` // 0-4
	Version        string                               `json:"version"`
	LoraInfo       *types.LoraInfo                      `json:"loraInfo,omitempty"`
	StateChangedAt *types.Timestamp                     `json:"stateChangedAt,omitempty"`
}

func (r SoilThcSensorAlertResponse) String() string {
	var ptr0 any = "<nil>"
	if r.LoraInfo != nil {
		ptr0 = fmt.Sprint(*r.LoraInfo)
	}
	var ptr1 any = "<nil>"
	if r.StateChangedAt != nil {
		ptr1 = fmt.Sprint(*r.StateChangedAt)
	}
	return fmt.Sprintf("{Alarm:%v State:%v Attributes:%v Tz:%v Battery:%v Version:%v LoraInfo:%v StateChangedAt:%v}", r.Alarm, r.State, r.Attributes, r.Tz, r.Battery, r.Version, ptr0, ptr1)
}

func (device *SoilThcSensor) ParseEvent(message controller.MqttMessage) (controller.Report, bool) {
	report, ok := device.Device.ParseEvent(message) // base impl decodes event + raw data
	if !ok {
		return report, false
	}
	report.Device = device                        // attribute the report to this concrete device
	data := report.Data.(controller.Unknown).Json // raw payload, re-typed below
	switch report.Event {
	case "SoilThcSensor.getState":
		var response SoilThcSensorGetStateResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "SoilThcSensor.getActivityLogs":
		var response SoilThcSensorGetActivityLogsResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "SoilThcSensor.getMetricsLogs":
		var response SoilThcSensorGetMetricsLogsResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "SoilThcSensor.Report":
		var response SoilThcSensorReportResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "SoilThcSensor.Alert":
		var response SoilThcSensorAlertResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	}
	return report, true
}
