// Code generated by scripts/gen_device_types.py; DO NOT EDIT.
package devices

import (
	"encoding/json"
	"fmt"

	"github.com/tyandl/homelink/pkg/yolink/controller"
	"github.com/tyandl/homelink/pkg/yolink/types"
)

type SpeakerHub struct{ *controller.Device }

func init() {
	controller.RegisterDeviceFactory("SpeakerHub", func(device *controller.Device) controller.DeviceController {
		return &SpeakerHub{Device: device}
	})
}

type SpeakerHubGetStateResponseWifi struct {
	Enable  bool   `json:"enable"`
	Ssid    string `json:"ssid"`
	Ip      string `json:"ip"`
	Gateway string `json:"gateway"`
	Mask    string `json:"mask"`
}

func (r SpeakerHubGetStateResponseWifi) String() string {
	return fmt.Sprintf("{Enable:%v Ssid:%v Ip:%v Gateway:%v Mask:%v}", r.Enable, r.Ssid, r.Ip, r.Gateway, r.Mask)
}

type SpeakerHubGetStateResponseEth struct {
	Enable bool `json:"enable"`
}

func (r SpeakerHubGetStateResponseEth) String() string {
	return fmt.Sprintf("{Enable:%v}", r.Enable)
}

type SpeakerHubGetStateResponseOptions struct {
	Volume     int  `json:"volume"`     // Global volume
	EnableBeep bool `json:"enableBeep"` // Beep on actions
	Mute       bool `json:"mute"`       // Mute all sounds
}

func (r SpeakerHubGetStateResponseOptions) String() string {
	return fmt.Sprintf("{Volume:%v EnableBeep:%v Mute:%v}", r.Volume, r.EnableBeep, r.Mute)
}

type SpeakerHubGetStateResponse struct {
	Version string                            `json:"version"`
	Wifi    SpeakerHubGetStateResponseWifi    `json:"wifi"`
	Eth     SpeakerHubGetStateResponseEth     `json:"eth"`
	Options SpeakerHubGetStateResponseOptions `json:"options"`
}

func (r SpeakerHubGetStateResponse) String() string {
	return fmt.Sprintf("{Version:%v Wifi:%v Eth:%v Options:%v}", r.Version, r.Wifi, r.Eth, r.Options)
}

// GetState Get SpeakerHub's State
func (device *SpeakerHub) GetState() (SpeakerHubGetStateResponse, error) {
	var response SpeakerHubGetStateResponse
	err := device.Call("SpeakerHub.getState", nil, &response)
	return response, err
}

func (device *SpeakerHub) GetStateAsync() <-chan controller.AsyncResult[SpeakerHubGetStateResponse] {
	return controller.DecodeAsync[SpeakerHubGetStateResponse](device.CallAsync("SpeakerHub.getState", nil))
}

type SpeakerHubSetWiFiParams struct {
	Ssid     string `json:"ssid"`
	Password string `json:"password"`
}

func (r SpeakerHubSetWiFiParams) String() string {
	return fmt.Sprintf("{Ssid:%v Password:%v}", r.Ssid, r.Password)
}

// SetWiFi Set device's WiFi info
func (device *SpeakerHub) SetWiFi(params SpeakerHubSetWiFiParams) error {
	return device.Call("SpeakerHub.setWiFi", params, nil)
}

func (device *SpeakerHub) SetWiFiAsync(params SpeakerHubSetWiFiParams) <-chan controller.AsyncResult[any] {
	return controller.DecodeAsync[any](device.CallAsync("SpeakerHub.setWiFi", params))
}

type SpeakerHubPlayAudioParams struct {
	Tone    *types.SpeakerTone `json:"tone,omitempty"`    // ['Emergency','Alert','Warn','Tip']
	Message *string            `json:"message,omitempty"` // TTS message to play
	Volume  *int               `json:"volume,omitempty"`  // Override volume; uses global if not set
	Repeat  *int               `json:"repeat,omitempty"`  // Repeat count [0-10]; 0=no repeat
}

func (r SpeakerHubPlayAudioParams) String() string {
	var ptr0 any = "<nil>"
	if r.Tone != nil {
		ptr0 = fmt.Sprint(*r.Tone)
	}
	var ptr1 any = "<nil>"
	if r.Message != nil {
		ptr1 = fmt.Sprint(*r.Message)
	}
	var ptr2 any = "<nil>"
	if r.Volume != nil {
		ptr2 = fmt.Sprint(*r.Volume)
	}
	var ptr3 any = "<nil>"
	if r.Repeat != nil {
		ptr3 = fmt.Sprint(*r.Repeat)
	}
	return fmt.Sprintf("{Tone:%v Message:%v Volume:%v Repeat:%v}", ptr0, ptr1, ptr2, ptr3)
}

// PlayAudio Play audio immediately
func (device *SpeakerHub) PlayAudio(params SpeakerHubPlayAudioParams) error {
	return device.Call("SpeakerHub.playAudio", params, nil)
}

func (device *SpeakerHub) PlayAudioAsync(params SpeakerHubPlayAudioParams) <-chan controller.AsyncResult[any] {
	return controller.DecodeAsync[any](device.CallAsync("SpeakerHub.playAudio", params))
}

type SpeakerHubSetOptionParams struct {
	Volume     *int  `json:"volume,omitempty"` // Global volume
	EnableBeep *bool `json:"enableBeep,omitempty"`
	Mute       *bool `json:"mute,omitempty"`
}

func (r SpeakerHubSetOptionParams) String() string {
	var ptr0 any = "<nil>"
	if r.Volume != nil {
		ptr0 = fmt.Sprint(*r.Volume)
	}
	var ptr1 any = "<nil>"
	if r.EnableBeep != nil {
		ptr1 = fmt.Sprint(*r.EnableBeep)
	}
	var ptr2 any = "<nil>"
	if r.Mute != nil {
		ptr2 = fmt.Sprint(*r.Mute)
	}
	return fmt.Sprintf("{Volume:%v EnableBeep:%v Mute:%v}", ptr0, ptr1, ptr2)
}

// SetOption Modify device settings
func (device *SpeakerHub) SetOption(params SpeakerHubSetOptionParams) error {
	return device.Call("SpeakerHub.setOption", params, nil)
}

func (device *SpeakerHub) SetOptionAsync(params SpeakerHubSetOptionParams) <-chan controller.AsyncResult[any] {
	return controller.DecodeAsync[any](device.CallAsync("SpeakerHub.setOption", params))
}

type SpeakerHubReportResponseWifi struct {
	Enable  bool   `json:"enable"`
	Ssid    string `json:"ssid"`
	Ip      string `json:"ip"`
	Gateway string `json:"gateway"`
	Mask    string `json:"mask"`
}

func (r SpeakerHubReportResponseWifi) String() string {
	return fmt.Sprintf("{Enable:%v Ssid:%v Ip:%v Gateway:%v Mask:%v}", r.Enable, r.Ssid, r.Ip, r.Gateway, r.Mask)
}

type SpeakerHubReportResponseEth struct {
	Enable bool `json:"enable"`
}

func (r SpeakerHubReportResponseEth) String() string {
	return fmt.Sprintf("{Enable:%v}", r.Enable)
}

type SpeakerHubReportResponseOptions struct {
	Volume     int  `json:"volume"`     // Global volume
	EnableBeep bool `json:"enableBeep"` // Beep on actions
	Mute       bool `json:"mute"`       // Mute all sounds
}

func (r SpeakerHubReportResponseOptions) String() string {
	return fmt.Sprintf("{Volume:%v EnableBeep:%v Mute:%v}", r.Volume, r.EnableBeep, r.Mute)
}

type SpeakerHubReportResponse struct {
	Version  string                          `json:"version"`
	Wifi     SpeakerHubReportResponseWifi    `json:"wifi"`
	Eth      SpeakerHubReportResponseEth     `json:"eth"`
	Options  SpeakerHubReportResponseOptions `json:"options"`
	LoraInfo *types.LoraInfo                 `json:"loraInfo,omitempty"`
}

func (r SpeakerHubReportResponse) String() string {
	var ptr0 any = "<nil>"
	if r.LoraInfo != nil {
		ptr0 = fmt.Sprint(*r.LoraInfo)
	}
	return fmt.Sprintf("{Version:%v Wifi:%v Eth:%v Options:%v LoraInfo:%v}", r.Version, r.Wifi, r.Eth, r.Options, ptr0)
}

type SpeakerHubAlertResponseWifi struct {
	Enable  bool   `json:"enable"`
	Ssid    string `json:"ssid"`
	Ip      string `json:"ip"`
	Gateway string `json:"gateway"`
	Mask    string `json:"mask"`
}

func (r SpeakerHubAlertResponseWifi) String() string {
	return fmt.Sprintf("{Enable:%v Ssid:%v Ip:%v Gateway:%v Mask:%v}", r.Enable, r.Ssid, r.Ip, r.Gateway, r.Mask)
}

type SpeakerHubAlertResponseEth struct {
	Enable bool `json:"enable"`
}

func (r SpeakerHubAlertResponseEth) String() string {
	return fmt.Sprintf("{Enable:%v}", r.Enable)
}

type SpeakerHubAlertResponseOptions struct {
	Volume     int  `json:"volume"`     // Global volume
	EnableBeep bool `json:"enableBeep"` // Beep on actions
	Mute       bool `json:"mute"`       // Mute all sounds
}

func (r SpeakerHubAlertResponseOptions) String() string {
	return fmt.Sprintf("{Volume:%v EnableBeep:%v Mute:%v}", r.Volume, r.EnableBeep, r.Mute)
}

type SpeakerHubAlertResponse struct {
	Version        string                         `json:"version"`
	Wifi           SpeakerHubAlertResponseWifi    `json:"wifi"`
	Eth            SpeakerHubAlertResponseEth     `json:"eth"`
	Options        SpeakerHubAlertResponseOptions `json:"options"`
	LoraInfo       *types.LoraInfo                `json:"loraInfo,omitempty"`
	StateChangedAt *types.Timestamp               `json:"stateChangedAt,omitempty"`
}

func (r SpeakerHubAlertResponse) String() string {
	var ptr0 any = "<nil>"
	if r.LoraInfo != nil {
		ptr0 = fmt.Sprint(*r.LoraInfo)
	}
	var ptr1 any = "<nil>"
	if r.StateChangedAt != nil {
		ptr1 = fmt.Sprint(*r.StateChangedAt)
	}
	return fmt.Sprintf("{Version:%v Wifi:%v Eth:%v Options:%v LoraInfo:%v StateChangedAt:%v}", r.Version, r.Wifi, r.Eth, r.Options, ptr0, ptr1)
}

func (device *SpeakerHub) ParseEvent(message controller.MqttMessage) (controller.Report, bool) {
	report, ok := device.Device.ParseEvent(message) // base impl decodes event + raw data
	if !ok {
		return report, false
	}
	report.Device = device                        // attribute the report to this concrete device
	data := report.Data.(controller.Unknown).Json // raw payload, re-typed below
	switch report.Event {
	case "SpeakerHub.getState":
		var response SpeakerHubGetStateResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "SpeakerHub.Report":
		var response SpeakerHubReportResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "SpeakerHub.Alert":
		var response SpeakerHubAlertResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	}
	return report, true
}
