// Code generated by scripts/gen_device_types.py; DO NOT EDIT.
package devices

import (
	"encoding/json"
	"fmt"

	"github.com/tyandl/homelink/pkg/yolink/controller"
	"github.com/tyandl/homelink/pkg/yolink/types"
)

type Sprinkler struct{ *controller.Device }

func init() {
	controller.RegisterDeviceFactory("Sprinkler", func(device *controller.Device) controller.DeviceController {
		return &Sprinkler{Device: device}
	})
}

type SprinklerGetStateResponseStateWatering struct {
	Zone  *int `json:"zone,omitempty"`  // Current watering zone index
	Total *int `json:"total,omitempty"` // Total watering time minutes
	Left  *int `json:"left,omitempty"`  // Remaining watering time minutes
}

func (r SprinklerGetStateResponseStateWatering) String() string {
	var ptr0 any = "<nil>"
	if r.Zone != nil {
		ptr0 = fmt.Sprint(*r.Zone)
	}
	var ptr1 any = "<nil>"
	if r.Total != nil {
		ptr1 = fmt.Sprint(*r.Total)
	}
	var ptr2 any = "<nil>"
	if r.Left != nil {
		ptr2 = fmt.Sprint(*r.Left)
	}
	return fmt.Sprintf("{Zone:%v Total:%v Left:%v}", ptr0, ptr1, ptr2)
}

type SprinklerGetStateResponseState struct {
	Mode     types.SprinklerMode                    `json:"mode"`     // ['auto','manual','off']
	ZoneSize int                                    `json:"zoneSize"` // Number of zones
	Delay    int                                    `json:"delay"`    // Minutes to delay
	Watering SprinklerGetStateResponseStateWatering `json:"watering"`
}

func (r SprinklerGetStateResponseState) String() string {
	return fmt.Sprintf("{Mode:%v ZoneSize:%v Delay:%v Watering:%v}", r.Mode, r.ZoneSize, r.Delay, r.Watering)
}

type SprinklerGetStateResponseSetting struct {
	MaxWaterTime int   `json:"maxWaterTime"` // Max watering time
	ManualWater  []int `json:"manualWater"`
}

func (r SprinklerGetStateResponseSetting) String() string {
	return fmt.Sprintf("{MaxWaterTime:%v ManualWater:%v}", r.MaxWaterTime, r.ManualWater)
}

type SprinklerGetStateResponse struct {
	State   SprinklerGetStateResponseState   `json:"state"`
	Setting SprinklerGetStateResponseSetting `json:"setting"`
	Version string                           `json:"version"`
	Tz      int                              `json:"tz"`
}

func (r SprinklerGetStateResponse) String() string {
	return fmt.Sprintf("{State:%v Setting:%v Version:%v Tz:%v}", r.State, r.Setting, r.Version, r.Tz)
}

// GetState Get Current State
func (device *Sprinkler) GetState() (SprinklerGetStateResponse, error) {
	var response SprinklerGetStateResponse
	err := device.Call("Sprinkler.getState", nil, &response)
	return response, err
}

func (device *Sprinkler) GetStateAsync() <-chan controller.AsyncResult[SprinklerGetStateResponse] {
	return controller.DecodeAsync[SprinklerGetStateResponse](device.CallAsync("Sprinkler.getState", nil))
}

type SprinklerSetStateParamsState struct {
	Mode     *types.SprinklerMode `json:"mode,omitempty"` // ['auto','manual','off']
	ZoneSize *int                 `json:"zoneSize,omitempty"`
	Delay    *int                 `json:"delay,omitempty"`
}

func (r SprinklerSetStateParamsState) String() string {
	var ptr0 any = "<nil>"
	if r.Mode != nil {
		ptr0 = fmt.Sprint(*r.Mode)
	}
	var ptr1 any = "<nil>"
	if r.ZoneSize != nil {
		ptr1 = fmt.Sprint(*r.ZoneSize)
	}
	var ptr2 any = "<nil>"
	if r.Delay != nil {
		ptr2 = fmt.Sprint(*r.Delay)
	}
	return fmt.Sprintf("{Mode:%v ZoneSize:%v Delay:%v}", ptr0, ptr1, ptr2)
}

type SprinklerSetStateParamsSetting struct {
	ManualWater  []int `json:"manualWater"`
	MaxWaterTime *int  `json:"maxWaterTime,omitempty"`
}

func (r SprinklerSetStateParamsSetting) String() string {
	var ptr0 any = "<nil>"
	if r.MaxWaterTime != nil {
		ptr0 = fmt.Sprint(*r.MaxWaterTime)
	}
	return fmt.Sprintf("{ManualWater:%v MaxWaterTime:%v}", r.ManualWater, ptr0)
}

type SprinklerSetStateParams struct {
	State   SprinklerSetStateParamsState   `json:"state"`
	Setting SprinklerSetStateParamsSetting `json:"setting"`
}

func (r SprinklerSetStateParams) String() string {
	return fmt.Sprintf("{State:%v Setting:%v}", r.State, r.Setting)
}

type SprinklerSetStateResponseStateWatering struct {
	Zone  *int `json:"zone,omitempty"`  // Current watering zone index
	Total *int `json:"total,omitempty"` // Total watering time minutes
	Left  *int `json:"left,omitempty"`  // Remaining watering time minutes
}

func (r SprinklerSetStateResponseStateWatering) String() string {
	var ptr0 any = "<nil>"
	if r.Zone != nil {
		ptr0 = fmt.Sprint(*r.Zone)
	}
	var ptr1 any = "<nil>"
	if r.Total != nil {
		ptr1 = fmt.Sprint(*r.Total)
	}
	var ptr2 any = "<nil>"
	if r.Left != nil {
		ptr2 = fmt.Sprint(*r.Left)
	}
	return fmt.Sprintf("{Zone:%v Total:%v Left:%v}", ptr0, ptr1, ptr2)
}

type SprinklerSetStateResponseState struct {
	Mode     types.SprinklerMode                    `json:"mode"`     // ['auto','manual','off']
	ZoneSize int                                    `json:"zoneSize"` // Number of zones
	Delay    int                                    `json:"delay"`    // Minutes to delay
	Watering SprinklerSetStateResponseStateWatering `json:"watering"`
}

func (r SprinklerSetStateResponseState) String() string {
	return fmt.Sprintf("{Mode:%v ZoneSize:%v Delay:%v Watering:%v}", r.Mode, r.ZoneSize, r.Delay, r.Watering)
}

type SprinklerSetStateResponseSetting struct {
	MaxWaterTime int   `json:"maxWaterTime"` // Max watering time
	ManualWater  []int `json:"manualWater"`
}

func (r SprinklerSetStateResponseSetting) String() string {
	return fmt.Sprintf("{MaxWaterTime:%v ManualWater:%v}", r.MaxWaterTime, r.ManualWater)
}

type SprinklerSetStateResponse struct {
	State   SprinklerSetStateResponseState   `json:"state"`
	Setting SprinklerSetStateResponseSetting `json:"setting"`
	Version string                           `json:"version"`
	Tz      int                              `json:"tz"`
}

func (r SprinklerSetStateResponse) String() string {
	return fmt.Sprintf("{State:%v Setting:%v Version:%v Tz:%v}", r.State, r.Setting, r.Version, r.Tz)
}

// SetState Set Sprinkler's State
func (device *Sprinkler) SetState(params SprinklerSetStateParams) (SprinklerSetStateResponse, error) {
	var response SprinklerSetStateResponse
	err := device.Call("Sprinkler.setState", params, &response)
	return response, err
}

func (device *Sprinkler) SetStateAsync(params SprinklerSetStateParams) <-chan controller.AsyncResult[SprinklerSetStateResponse] {
	return controller.DecodeAsync[SprinklerSetStateResponse](device.CallAsync("Sprinkler.setState", params))
}

type SprinklerSetManualWaterParams struct {
	State types.SprinklerCommand `json:"state"` // ['start','stop']
}

func (r SprinklerSetManualWaterParams) String() string {
	return fmt.Sprintf("{State:%v}", r.State)
}

// SetManualWater Start/stop manual watering
func (device *Sprinkler) SetManualWater(params SprinklerSetManualWaterParams) error {
	return device.Call("Sprinkler.setManualWater", params, nil)
}

func (device *Sprinkler) SetManualWaterAsync(params SprinklerSetManualWaterParams) <-chan controller.AsyncResult[any] {
	return controller.DecodeAsync[any](device.CallAsync("Sprinkler.setManualWater", params))
}

type SprinklerGetSchedulesResponseSchesItemPlansItem struct {
	Time  string `json:"time"` // Start time h:m:s
	Zones []int  `json:"zones"`
}

func (r SprinklerGetSchedulesResponseSchesItemPlansItem) String() string {
	return fmt.Sprintf("{Time:%v Zones:%v}", r.Time, r.Zones)
}

type SprinklerGetSchedulesResponseSchesItem struct {
	Date     string                                            `json:"date"`     // Session start date M-d
	Weekmask int                                               `json:"weekmask"` // Enabled weekdays mask
	Plans    []SprinklerGetSchedulesResponseSchesItemPlansItem `json:"plans"`
}

func (r SprinklerGetSchedulesResponseSchesItem) String() string {
	return fmt.Sprintf("{Date:%v Weekmask:%v Plans:%v}", r.Date, r.Weekmask, r.Plans)
}

type SprinklerGetSchedulesResponse struct {
	Sches []SprinklerGetSchedulesResponseSchesItem `json:"sches"`
}

func (r SprinklerGetSchedulesResponse) String() string {
	return fmt.Sprintf("{Sches:%v}", r.Sches)
}

// GetSchedules Get Schedule List
func (device *Sprinkler) GetSchedules() (SprinklerGetSchedulesResponse, error) {
	var response SprinklerGetSchedulesResponse
	err := device.Call("Sprinkler.getSchedules", nil, &response)
	return response, err
}

func (device *Sprinkler) GetSchedulesAsync() <-chan controller.AsyncResult[SprinklerGetSchedulesResponse] {
	return controller.DecodeAsync[SprinklerGetSchedulesResponse](device.CallAsync("Sprinkler.getSchedules", nil))
}

type SprinklerSetSchedulesParamsSchesItemPlansItem struct {
	Time  string `json:"time"` // h:m:s
	Zones []int  `json:"zones"`
}

func (r SprinklerSetSchedulesParamsSchesItemPlansItem) String() string {
	return fmt.Sprintf("{Time:%v Zones:%v}", r.Time, r.Zones)
}

type SprinklerSetSchedulesParamsSchesItem struct {
	Date     string                                          `json:"date"` // M-d
	Weekmask int                                             `json:"weekmask"`
	Plans    []SprinklerSetSchedulesParamsSchesItemPlansItem `json:"plans"`
}

func (r SprinklerSetSchedulesParamsSchesItem) String() string {
	return fmt.Sprintf("{Date:%v Weekmask:%v Plans:%v}", r.Date, r.Weekmask, r.Plans)
}

type SprinklerSetSchedulesParams struct {
	Sches []SprinklerSetSchedulesParamsSchesItem `json:"sches"`
}

func (r SprinklerSetSchedulesParams) String() string {
	return fmt.Sprintf("{Sches:%v}", r.Sches)
}

type SprinklerSetSchedulesResponseSchesItemPlansItem struct {
	Time  string `json:"time"` // Start time h:m:s
	Zones []int  `json:"zones"`
}

func (r SprinklerSetSchedulesResponseSchesItemPlansItem) String() string {
	return fmt.Sprintf("{Time:%v Zones:%v}", r.Time, r.Zones)
}

type SprinklerSetSchedulesResponseSchesItem struct {
	Date     string                                            `json:"date"`     // Session start date M-d
	Weekmask int                                               `json:"weekmask"` // Enabled weekdays mask
	Plans    []SprinklerSetSchedulesResponseSchesItemPlansItem `json:"plans"`
}

func (r SprinklerSetSchedulesResponseSchesItem) String() string {
	return fmt.Sprintf("{Date:%v Weekmask:%v Plans:%v}", r.Date, r.Weekmask, r.Plans)
}

type SprinklerSetSchedulesResponse struct {
	Sches []SprinklerSetSchedulesResponseSchesItem `json:"sches"`
}

func (r SprinklerSetSchedulesResponse) String() string {
	return fmt.Sprintf("{Sches:%v}", r.Sches)
}

// SetSchedules Set Schedule
func (device *Sprinkler) SetSchedules(params SprinklerSetSchedulesParams) (SprinklerSetSchedulesResponse, error) {
	var response SprinklerSetSchedulesResponse
	err := device.Call("Sprinkler.setSchedules", params, &response)
	return response, err
}

func (device *Sprinkler) SetSchedulesAsync(params SprinklerSetSchedulesParams) <-chan controller.AsyncResult[SprinklerSetSchedulesResponse] {
	return controller.DecodeAsync[SprinklerSetSchedulesResponse](device.CallAsync("Sprinkler.setSchedules", params))
}

type SprinklerGetVersionResponseNewVersion struct {
	VersionId   *string `json:"versionId,omitempty"`
	VersionCode *string `json:"versionCode,omitempty"`
	FileSize    *string `json:"fileSize,omitempty"`
}

func (r SprinklerGetVersionResponseNewVersion) String() string {
	var ptr0 any = "<nil>"
	if r.VersionId != nil {
		ptr0 = fmt.Sprint(*r.VersionId)
	}
	var ptr1 any = "<nil>"
	if r.VersionCode != nil {
		ptr1 = fmt.Sprint(*r.VersionCode)
	}
	var ptr2 any = "<nil>"
	if r.FileSize != nil {
		ptr2 = fmt.Sprint(*r.FileSize)
	}
	return fmt.Sprintf("{VersionId:%v VersionCode:%v FileSize:%v}", ptr0, ptr1, ptr2)
}

type SprinklerGetVersionResponse struct {
	Version    string                                `json:"version"`
	NewVersion SprinklerGetVersionResponseNewVersion `json:"newVersion"`
}

func (r SprinklerGetVersionResponse) String() string {
	return fmt.Sprintf("{Version:%v NewVersion:%v}", r.Version, r.NewVersion)
}

// GetVersion Get firmware info
func (device *Sprinkler) GetVersion() (SprinklerGetVersionResponse, error) {
	var response SprinklerGetVersionResponse
	err := device.Call("Sprinkler.getVersion", nil, &response)
	return response, err
}

func (device *Sprinkler) GetVersionAsync() <-chan controller.AsyncResult[SprinklerGetVersionResponse] {
	return controller.DecodeAsync[SprinklerGetVersionResponse](device.CallAsync("Sprinkler.getVersion", nil))
}

type SprinklerStartUpgradeParams struct {
	VersionId string `json:"versionId"`
}

func (r SprinklerStartUpgradeParams) String() string {
	return fmt.Sprintf("{VersionId:%v}", r.VersionId)
}

type SprinklerStartUpgradeResponse struct {
	IsStarted bool `json:"isStarted"`
}

func (r SprinklerStartUpgradeResponse) String() string {
	return fmt.Sprintf("{IsStarted:%v}", r.IsStarted)
}

// StartUpgrade Start firmware upgrade
func (device *Sprinkler) StartUpgrade(params SprinklerStartUpgradeParams) (SprinklerStartUpgradeResponse, error) {
	var response SprinklerStartUpgradeResponse
	err := device.Call("Sprinkler.startUpgrade", params, &response)
	return response, err
}

func (device *Sprinkler) StartUpgradeAsync(params SprinklerStartUpgradeParams) <-chan controller.AsyncResult[SprinklerStartUpgradeResponse] {
	return controller.DecodeAsync[SprinklerStartUpgradeResponse](device.CallAsync("Sprinkler.startUpgrade", params))
}

type SprinklerReportResponseWatering struct {
	Zone  *int `json:"zone,omitempty"`  // Current watering zone index
	Total *int `json:"total,omitempty"` // Total watering time minutes
	Left  *int `json:"left,omitempty"`  // Remaining watering time minutes
}

func (r SprinklerReportResponseWatering) String() string {
	var ptr0 any = "<nil>"
	if r.Zone != nil {
		ptr0 = fmt.Sprint(*r.Zone)
	}
	var ptr1 any = "<nil>"
	if r.Total != nil {
		ptr1 = fmt.Sprint(*r.Total)
	}
	var ptr2 any = "<nil>"
	if r.Left != nil {
		ptr2 = fmt.Sprint(*r.Left)
	}
	return fmt.Sprintf("{Zone:%v Total:%v Left:%v}", ptr0, ptr1, ptr2)
}

type SprinklerReportResponse struct {
	Mode     types.SprinklerMode             `json:"mode"`     // ['auto','manual','off']
	ZoneSize int                             `json:"zoneSize"` // Number of zones
	Delay    int                             `json:"delay"`    // Minutes to delay
	Watering SprinklerReportResponseWatering `json:"watering"`
	LoraInfo *types.LoraInfo                 `json:"loraInfo,omitempty"`
}

func (r SprinklerReportResponse) String() string {
	var ptr0 any = "<nil>"
	if r.LoraInfo != nil {
		ptr0 = fmt.Sprint(*r.LoraInfo)
	}
	return fmt.Sprintf("{Mode:%v ZoneSize:%v Delay:%v Watering:%v LoraInfo:%v}", r.Mode, r.ZoneSize, r.Delay, r.Watering, ptr0)
}

type SprinklerAlertResponseWatering struct {
	Zone  *int `json:"zone,omitempty"`  // Current watering zone index
	Total *int `json:"total,omitempty"` // Total watering time minutes
	Left  *int `json:"left,omitempty"`  // Remaining watering time minutes
}

func (r SprinklerAlertResponseWatering) String() string {
	var ptr0 any = "<nil>"
	if r.Zone != nil {
		ptr0 = fmt.Sprint(*r.Zone)
	}
	var ptr1 any = "<nil>"
	if r.Total != nil {
		ptr1 = fmt.Sprint(*r.Total)
	}
	var ptr2 any = "<nil>"
	if r.Left != nil {
		ptr2 = fmt.Sprint(*r.Left)
	}
	return fmt.Sprintf("{Zone:%v Total:%v Left:%v}", ptr0, ptr1, ptr2)
}

type SprinklerAlertResponse struct {
	Mode           types.SprinklerMode            `json:"mode"`     // ['auto','manual','off']
	ZoneSize       int                            `json:"zoneSize"` // Number of zones
	Delay          int                            `json:"delay"`    // Minutes to delay
	Watering       SprinklerAlertResponseWatering `json:"watering"`
	LoraInfo       *types.LoraInfo                `json:"loraInfo,omitempty"`
	StateChangedAt *types.Timestamp               `json:"stateChangedAt,omitempty"`
}

func (r SprinklerAlertResponse) String() string {
	var ptr0 any = "<nil>"
	if r.LoraInfo != nil {
		ptr0 = fmt.Sprint(*r.LoraInfo)
	}
	var ptr1 any = "<nil>"
	if r.StateChangedAt != nil {
		ptr1 = fmt.Sprint(*r.StateChangedAt)
	}
	return fmt.Sprintf("{Mode:%v ZoneSize:%v Delay:%v Watering:%v LoraInfo:%v StateChangedAt:%v}", r.Mode, r.ZoneSize, r.Delay, r.Watering, ptr0, ptr1)
}

func (device *Sprinkler) ParseEvent(message controller.MqttMessage) (controller.Report, bool) {
	report, ok := device.Device.ParseEvent(message) // base impl decodes event + raw data
	if !ok {
		return report, false
	}
	report.Device = device                        // attribute the report to this concrete device
	data := report.Data.(controller.Unknown).Json // raw payload, re-typed below
	switch report.Event {
	case "Sprinkler.getState":
		var response SprinklerGetStateResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "Sprinkler.setState":
		var response SprinklerSetStateResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "Sprinkler.getSchedules":
		var response SprinklerGetSchedulesResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "Sprinkler.setSchedules":
		var response SprinklerSetSchedulesResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "Sprinkler.getVersion":
		var response SprinklerGetVersionResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "Sprinkler.startUpgrade":
		var response SprinklerStartUpgradeResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "Sprinkler.Report":
		var response SprinklerReportResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "Sprinkler.Alert":
		var response SprinklerAlertResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	}
	return report, true
}
