// Code generated by scripts/gen_device_types.py; DO NOT EDIT.
package devices

import (
	"encoding/json"
	"fmt"

	"github.com/tyandl/homelink/pkg/yolink/controller"
	"github.com/tyandl/homelink/pkg/yolink/types"
)

type SprinklerV2 struct{ *controller.Device }

func init() {
	controller.RegisterDeviceFactory("SprinklerV2", func(device *controller.Device) controller.DeviceController {
		return &SprinklerV2{Device: device}
	})
}

type SprinklerV2GetStateResponseState struct {
	Running            bool `json:"running"` // Current watering status
	NoWaterWhenRunning bool `json:"noWaterWhenRunning"`
}

func (r SprinklerV2GetStateResponseState) String() string {
	return fmt.Sprintf("{Running:%v NoWaterWhenRunning:%v}", r.Running, r.NoWaterWhenRunning)
}

type SprinklerV2GetStateResponseAttributesManualWater struct {
	Type  types.SprinklerWaterType `json:"type"` // ['duration','amount']
	Value int                      `json:"value"`
}

func (r SprinklerV2GetStateResponseAttributesManualWater) String() string {
	return fmt.Sprintf("{Type:%v Value:%v}", r.Type, r.Value)
}

type SprinklerV2GetStateResponseAttributesWaterDelay struct {
	Type     string `json:"type"`     // ['manual']
	Duration int    `json:"duration"` // Delay minutes
}

func (r SprinklerV2GetStateResponseAttributesWaterDelay) String() string {
	return fmt.Sprintf("{Type:%v Duration:%v}", r.Type, r.Duration)
}

type SprinklerV2GetStateResponseAttributes struct {
	MeterUnit       types.MeterUnit                                  `json:"meterUnit"`       // 0=GAL,1=CCF,2=M3,3=L
	MeterStepFactor int                                              `json:"meterStepFactor"` // Measurement accuracy
	ManualWater     SprinklerV2GetStateResponseAttributesManualWater `json:"manualWater"`
	WaterDelay      SprinklerV2GetStateResponseAttributesWaterDelay  `json:"waterDelay"`
}

func (r SprinklerV2GetStateResponseAttributes) String() string {
	return fmt.Sprintf("{MeterUnit:%v MeterStepFactor:%v ManualWater:%v WaterDelay:%v}", r.MeterUnit, r.MeterStepFactor, r.ManualWater, r.WaterDelay)
}

type SprinklerV2GetStateResponseRunningTotal struct {
	Type  types.SprinklerWaterType `json:"type"` // ['duration','amount']
	Value int                      `json:"value"`
}

func (r SprinklerV2GetStateResponseRunningTotal) String() string {
	return fmt.Sprintf("{Type:%v Value:%v}", r.Type, r.Value)
}

type SprinklerV2GetStateResponseRunning struct {
	Mode     types.WaterMode                         `json:"mode"` // ['manual','schedule']
	Total    SprinklerV2GetStateResponseRunningTotal `json:"total"`
	Progress int                                     `json:"progress"`
}

func (r SprinklerV2GetStateResponseRunning) String() string {
	return fmt.Sprintf("{Mode:%v Total:%v Progress:%v}", r.Mode, r.Total, r.Progress)
}

type SprinklerV2GetStateResponse struct {
	State      SprinklerV2GetStateResponseState      `json:"state"`
	WaterMode  types.WaterMode                       `json:"waterMode"` // ['manual','schedule']
	Attributes SprinklerV2GetStateResponseAttributes `json:"attributes"`
	Running    SprinklerV2GetStateResponseRunning    `json:"running"`
	Battery    types.BatteryLevel                    `json:"battery"` // [0-4]
	Version    string                                `json:"version"`
	Tz         int                                   `json:"tz"`
}

func (r SprinklerV2GetStateResponse) String() string {
	return fmt.Sprintf("{State:%v WaterMode:%v Attributes:%v Running:%v Battery:%v Version:%v Tz:%v}", r.State, r.WaterMode, r.Attributes, r.Running, r.Battery, r.Version, r.Tz)
}

// GetState Get Current State
func (device *SprinklerV2) GetState() (SprinklerV2GetStateResponse, error) {
	var response SprinklerV2GetStateResponse
	err := device.Call("SprinklerV2.getState", nil, &response)
	return response, err
}

func (device *SprinklerV2) GetStateAsync() <-chan controller.AsyncResult[SprinklerV2GetStateResponse] {
	return controller.DecodeAsync[SprinklerV2GetStateResponse](device.CallAsync("SprinklerV2.getState", nil))
}

type SprinklerV2SetStateParams struct {
	Running   *bool            `json:"running,omitempty"`   // Start/stop watering
	WaterMode *types.WaterMode `json:"waterMode,omitempty"` // ['schedule','manual']
}

func (r SprinklerV2SetStateParams) String() string {
	var ptr0 any = "<nil>"
	if r.Running != nil {
		ptr0 = fmt.Sprint(*r.Running)
	}
	var ptr1 any = "<nil>"
	if r.WaterMode != nil {
		ptr1 = fmt.Sprint(*r.WaterMode)
	}
	return fmt.Sprintf("{Running:%v WaterMode:%v}", ptr0, ptr1)
}

type SprinklerV2SetStateResponseState struct {
	Running            bool `json:"running"`
	NoWaterWhenRunning bool `json:"noWaterWhenRunning"`
}

func (r SprinklerV2SetStateResponseState) String() string {
	return fmt.Sprintf("{Running:%v NoWaterWhenRunning:%v}", r.Running, r.NoWaterWhenRunning)
}

type SprinklerV2SetStateResponse struct {
	State     SprinklerV2SetStateResponseState `json:"state"`
	WaterMode types.WaterMode                  `json:"waterMode"`
}

func (r SprinklerV2SetStateResponse) String() string {
	return fmt.Sprintf("{State:%v WaterMode:%v}", r.State, r.WaterMode)
}

// SetState Set Sprinkler State
func (device *SprinklerV2) SetState(params SprinklerV2SetStateParams) (SprinklerV2SetStateResponse, error) {
	var response SprinklerV2SetStateResponse
	err := device.Call("SprinklerV2.setState", params, &response)
	return response, err
}

func (device *SprinklerV2) SetStateAsync(params SprinklerV2SetStateParams) <-chan controller.AsyncResult[SprinklerV2SetStateResponse] {
	return controller.DecodeAsync[SprinklerV2SetStateResponse](device.CallAsync("SprinklerV2.setState", params))
}

type SprinklerV2SetAttributesParamsManualWater struct {
	Type  *types.SprinklerWaterType `json:"type,omitempty"` // ['duration','amount']
	Value *int                      `json:"value,omitempty"`
}

func (r SprinklerV2SetAttributesParamsManualWater) String() string {
	var ptr0 any = "<nil>"
	if r.Type != nil {
		ptr0 = fmt.Sprint(*r.Type)
	}
	var ptr1 any = "<nil>"
	if r.Value != nil {
		ptr1 = fmt.Sprint(*r.Value)
	}
	return fmt.Sprintf("{Type:%v Value:%v}", ptr0, ptr1)
}

type SprinklerV2SetAttributesParamsWaterDelay struct {
	Type     *string `json:"type,omitempty"`     // ['manual']
	Duration *int    `json:"duration,omitempty"` // Delay minutes
}

func (r SprinklerV2SetAttributesParamsWaterDelay) String() string {
	var ptr0 any = "<nil>"
	if r.Type != nil {
		ptr0 = fmt.Sprint(*r.Type)
	}
	var ptr1 any = "<nil>"
	if r.Duration != nil {
		ptr1 = fmt.Sprint(*r.Duration)
	}
	return fmt.Sprintf("{Type:%v Duration:%v}", ptr0, ptr1)
}

type SprinklerV2SetAttributesParams struct {
	ManualWater SprinklerV2SetAttributesParamsManualWater `json:"manualWater"`
	WaterDelay  SprinklerV2SetAttributesParamsWaterDelay  `json:"waterDelay"`
}

func (r SprinklerV2SetAttributesParams) String() string {
	return fmt.Sprintf("{ManualWater:%v WaterDelay:%v}", r.ManualWater, r.WaterDelay)
}

type SprinklerV2SetAttributesResponseAttributesManualWater struct {
	Type  string `json:"type"`
	Value int    `json:"value"`
}

func (r SprinklerV2SetAttributesResponseAttributesManualWater) String() string {
	return fmt.Sprintf("{Type:%v Value:%v}", r.Type, r.Value)
}

type SprinklerV2SetAttributesResponseAttributesWaterDelay struct {
	Type     string `json:"type"`
	Duration int    `json:"duration"`
}

func (r SprinklerV2SetAttributesResponseAttributesWaterDelay) String() string {
	return fmt.Sprintf("{Type:%v Duration:%v}", r.Type, r.Duration)
}

type SprinklerV2SetAttributesResponseAttributes struct {
	MeterUnit   types.MeterUnit                                       `json:"meterUnit"`
	ManualWater SprinklerV2SetAttributesResponseAttributesManualWater `json:"manualWater"`
	WaterDelay  SprinklerV2SetAttributesResponseAttributesWaterDelay  `json:"waterDelay"`
}

func (r SprinklerV2SetAttributesResponseAttributes) String() string {
	return fmt.Sprintf("{MeterUnit:%v ManualWater:%v WaterDelay:%v}", r.MeterUnit, r.ManualWater, r.WaterDelay)
}

type SprinklerV2SetAttributesResponse struct {
	Attributes SprinklerV2SetAttributesResponseAttributes `json:"attributes"`
}

func (r SprinklerV2SetAttributesResponse) String() string {
	return fmt.Sprintf("{Attributes:%v}", r.Attributes)
}

// SetAttributes Set Sprinkler attributes
func (device *SprinklerV2) SetAttributes(params SprinklerV2SetAttributesParams) (SprinklerV2SetAttributesResponse, error) {
	var response SprinklerV2SetAttributesResponse
	err := device.Call("SprinklerV2.setAttributes", params, &response)
	return response, err
}

func (device *SprinklerV2) SetAttributesAsync(params SprinklerV2SetAttributesParams) <-chan controller.AsyncResult[SprinklerV2SetAttributesResponse] {
	return controller.DecodeAsync[SprinklerV2SetAttributesResponse](device.CallAsync("SprinklerV2.setAttributes", params))
}

type SprinklerV2GetSchedulesParams struct {
	Offset int `json:"offset"` // Pagination offset
}

func (r SprinklerV2GetSchedulesParams) String() string {
	return fmt.Sprintf("{Offset:%v}", r.Offset)
}

type SprinklerV2GetSchedulesResponseSchedulesItemWaterDelay struct {
	Type  types.SprinklerWaterType `json:"type"` // ['duration','amount']
	Value int                      `json:"value"`
}

func (r SprinklerV2GetSchedulesResponseSchedulesItemWaterDelay) String() string {
	return fmt.Sprintf("{Type:%v Value:%v}", r.Type, r.Value)
}

type SprinklerV2GetSchedulesResponseSchedulesItemDays struct {
	Type  types.SprinklerDaysType `json:"type"` // ['weekly','even_days','odd_days','every_few_days']
	Value int                     `json:"value"`
}

func (r SprinklerV2GetSchedulesResponseSchedulesItemDays) String() string {
	return fmt.Sprintf("{Type:%v Value:%v}", r.Type, r.Value)
}

type SprinklerV2GetSchedulesResponseSchedulesItem struct {
	Index      int                                                    `json:"index"`
	StartDate  string                                                 `json:"startDate"` // M-d
	EndDate    string                                                 `json:"endDate"`   // M-d
	Time       string                                                 `json:"time"`      // h:m
	WaterDelay SprinklerV2GetSchedulesResponseSchedulesItemWaterDelay `json:"waterDelay"`
	Days       SprinklerV2GetSchedulesResponseSchedulesItemDays       `json:"days"`
	Valid      bool                                                   `json:"valid"`
}

func (r SprinklerV2GetSchedulesResponseSchedulesItem) String() string {
	return fmt.Sprintf("{Index:%v StartDate:%v EndDate:%v Time:%v WaterDelay:%v Days:%v Valid:%v}", r.Index, r.StartDate, r.EndDate, r.Time, r.WaterDelay, r.Days, r.Valid)
}

type SprinklerV2GetSchedulesResponse struct {
	Total     int                                            `json:"total"`
	Count     int                                            `json:"count"`
	Offset    int                                            `json:"offset"`
	Schedules []SprinklerV2GetSchedulesResponseSchedulesItem `json:"schedules"`
}

func (r SprinklerV2GetSchedulesResponse) String() string {
	return fmt.Sprintf("{Total:%v Count:%v Offset:%v Schedules:%v}", r.Total, r.Count, r.Offset, r.Schedules)
}

// GetSchedules Get Schedule List (paginated)
func (device *SprinklerV2) GetSchedules(params SprinklerV2GetSchedulesParams) (SprinklerV2GetSchedulesResponse, error) {
	var response SprinklerV2GetSchedulesResponse
	err := device.Call("SprinklerV2.getSchedules", params, &response)
	return response, err
}

func (device *SprinklerV2) GetSchedulesAsync(params SprinklerV2GetSchedulesParams) <-chan controller.AsyncResult[SprinklerV2GetSchedulesResponse] {
	return controller.DecodeAsync[SprinklerV2GetSchedulesResponse](device.CallAsync("SprinklerV2.getSchedules", params))
}

type SprinklerV2SetSchedulesParamsSchedulesItemWaterDelay struct {
	Type  string `json:"type"`
	Value int    `json:"value"`
}

func (r SprinklerV2SetSchedulesParamsSchedulesItemWaterDelay) String() string {
	return fmt.Sprintf("{Type:%v Value:%v}", r.Type, r.Value)
}

type SprinklerV2SetSchedulesParamsSchedulesItemDays struct {
	Type  string `json:"type"`
	Value int    `json:"value"`
}

func (r SprinklerV2SetSchedulesParamsSchedulesItemDays) String() string {
	return fmt.Sprintf("{Type:%v Value:%v}", r.Type, r.Value)
}

type SprinklerV2SetSchedulesParamsSchedulesItem struct {
	Index      int                                                  `json:"index"`
	StartDate  string                                               `json:"startDate"` // M-d
	EndDate    string                                               `json:"endDate"`   // M-d
	Time       string                                               `json:"time"`      // h:m
	WaterDelay SprinklerV2SetSchedulesParamsSchedulesItemWaterDelay `json:"waterDelay"`
	Days       SprinklerV2SetSchedulesParamsSchedulesItemDays       `json:"days"`
	Valid      bool                                                 `json:"valid"`
}

func (r SprinklerV2SetSchedulesParamsSchedulesItem) String() string {
	return fmt.Sprintf("{Index:%v StartDate:%v EndDate:%v Time:%v WaterDelay:%v Days:%v Valid:%v}", r.Index, r.StartDate, r.EndDate, r.Time, r.WaterDelay, r.Days, r.Valid)
}

type SprinklerV2SetSchedulesParams struct {
	Schedules []SprinklerV2SetSchedulesParamsSchedulesItem `json:"schedules"`
}

func (r SprinklerV2SetSchedulesParams) String() string {
	return fmt.Sprintf("{Schedules:%v}", r.Schedules)
}

type SprinklerV2SetSchedulesResponseSchedulesItemWaterDelay struct {
	Type  types.SprinklerWaterType `json:"type"` // ['duration','amount']
	Value int                      `json:"value"`
}

func (r SprinklerV2SetSchedulesResponseSchedulesItemWaterDelay) String() string {
	return fmt.Sprintf("{Type:%v Value:%v}", r.Type, r.Value)
}

type SprinklerV2SetSchedulesResponseSchedulesItemDays struct {
	Type  types.SprinklerDaysType `json:"type"` // ['weekly','even_days','odd_days','every_few_days']
	Value int                     `json:"value"`
}

func (r SprinklerV2SetSchedulesResponseSchedulesItemDays) String() string {
	return fmt.Sprintf("{Type:%v Value:%v}", r.Type, r.Value)
}

type SprinklerV2SetSchedulesResponseSchedulesItem struct {
	Index      int                                                    `json:"index"`
	StartDate  string                                                 `json:"startDate"` // M-d
	EndDate    string                                                 `json:"endDate"`   // M-d
	Time       string                                                 `json:"time"`      // h:m
	WaterDelay SprinklerV2SetSchedulesResponseSchedulesItemWaterDelay `json:"waterDelay"`
	Days       SprinklerV2SetSchedulesResponseSchedulesItemDays       `json:"days"`
	Valid      bool                                                   `json:"valid"`
}

func (r SprinklerV2SetSchedulesResponseSchedulesItem) String() string {
	return fmt.Sprintf("{Index:%v StartDate:%v EndDate:%v Time:%v WaterDelay:%v Days:%v Valid:%v}", r.Index, r.StartDate, r.EndDate, r.Time, r.WaterDelay, r.Days, r.Valid)
}

type SprinklerV2SetSchedulesResponse struct {
	Total     int                                            `json:"total"`
	Count     int                                            `json:"count"`
	Offset    int                                            `json:"offset"`
	Schedules []SprinklerV2SetSchedulesResponseSchedulesItem `json:"schedules"`
}

func (r SprinklerV2SetSchedulesResponse) String() string {
	return fmt.Sprintf("{Total:%v Count:%v Offset:%v Schedules:%v}", r.Total, r.Count, r.Offset, r.Schedules)
}

// SetSchedules Set Schedule
func (device *SprinklerV2) SetSchedules(params SprinklerV2SetSchedulesParams) (SprinklerV2SetSchedulesResponse, error) {
	var response SprinklerV2SetSchedulesResponse
	err := device.Call("SprinklerV2.setSchedules", params, &response)
	return response, err
}

func (device *SprinklerV2) SetSchedulesAsync(params SprinklerV2SetSchedulesParams) <-chan controller.AsyncResult[SprinklerV2SetSchedulesResponse] {
	return controller.DecodeAsync[SprinklerV2SetSchedulesResponse](device.CallAsync("SprinklerV2.setSchedules", params))
}

type SprinklerV2ReportResponse struct {
	Running            bool            `json:"running"` // Current watering status
	NoWaterWhenRunning bool            `json:"noWaterWhenRunning"`
	LoraInfo           *types.LoraInfo `json:"loraInfo,omitempty"`
}

func (r SprinklerV2ReportResponse) String() string {
	var ptr0 any = "<nil>"
	if r.LoraInfo != nil {
		ptr0 = fmt.Sprint(*r.LoraInfo)
	}
	return fmt.Sprintf("{Running:%v NoWaterWhenRunning:%v LoraInfo:%v}", r.Running, r.NoWaterWhenRunning, ptr0)
}

type SprinklerV2AlertResponse struct {
	Running            bool             `json:"running"` // Current watering status
	NoWaterWhenRunning bool             `json:"noWaterWhenRunning"`
	LoraInfo           *types.LoraInfo  `json:"loraInfo,omitempty"`
	StateChangedAt     *types.Timestamp `json:"stateChangedAt,omitempty"`
}

func (r SprinklerV2AlertResponse) String() string {
	var ptr0 any = "<nil>"
	if r.LoraInfo != nil {
		ptr0 = fmt.Sprint(*r.LoraInfo)
	}
	var ptr1 any = "<nil>"
	if r.StateChangedAt != nil {
		ptr1 = fmt.Sprint(*r.StateChangedAt)
	}
	return fmt.Sprintf("{Running:%v NoWaterWhenRunning:%v LoraInfo:%v StateChangedAt:%v}", r.Running, r.NoWaterWhenRunning, ptr0, ptr1)
}

func (device *SprinklerV2) ParseEvent(message controller.MqttMessage) (controller.Report, bool) {
	report, ok := device.Device.ParseEvent(message) // base impl decodes event + raw data
	if !ok {
		return report, false
	}
	report.Device = device                        // attribute the report to this concrete device
	data := report.Data.(controller.Unknown).Json // raw payload, re-typed below
	switch report.Event {
	case "SprinklerV2.getState":
		var response SprinklerV2GetStateResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "SprinklerV2.setState":
		var response SprinklerV2SetStateResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "SprinklerV2.setAttributes":
		var response SprinklerV2SetAttributesResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "SprinklerV2.getSchedules":
		var response SprinklerV2GetSchedulesResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "SprinklerV2.setSchedules":
		var response SprinklerV2SetSchedulesResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "SprinklerV2.Report":
		var response SprinklerV2ReportResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "SprinklerV2.Alert":
		var response SprinklerV2AlertResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	}
	return report, true
}
