// Code generated by scripts/gen_device_types.py; DO NOT EDIT.
package devices

import (
	"encoding/json"
	"fmt"
	"time"

	"github.com/tyandl/homelink/pkg/yolink/controller"
	"github.com/tyandl/homelink/pkg/yolink/types"
)

type Switch struct{ *controller.Device }

func init() {
	controller.RegisterDeviceFactory("Switch", func(device *controller.Device) controller.DeviceController {
		return &Switch{Device: device}
	})
}

type SwitchGetStateResponseDelay struct {
	On  int `json:"on"`  // Remain Delay ON minutes
	Off int `json:"off"` // Remain Delay OFF minutes
}

func (r SwitchGetStateResponseDelay) String() string {
	return fmt.Sprintf("{On:%v Off:%v}", r.On, r.Off)
}

type SwitchGetStateResponse struct {
	State   types.SwitchState           `json:"state"` // ['closed','open']
	Delay   SwitchGetStateResponseDelay `json:"delay"`
	Version string                      `json:"version"`
	Tz      int                         `json:"tz"`
}

func (r SwitchGetStateResponse) String() string {
	return fmt.Sprintf("{State:%v Delay:%v Version:%v Tz:%v}", r.State, r.Delay, r.Version, r.Tz)
}

// GetState Get Current State
func (device *Switch) GetState() (SwitchGetStateResponse, error) {
	var response SwitchGetStateResponse
	err := device.Call("Switch.getState", nil, &response)
	return response, err
}

func (device *Switch) GetStateAsync() <-chan controller.AsyncResult[SwitchGetStateResponse] {
	return controller.DecodeAsync[SwitchGetStateResponse](device.CallAsync("Switch.getState", nil))
}

type SwitchSetStateParams struct {
	State types.SwitchCommand `json:"state"` // ['close','open']
}

func (r SwitchSetStateParams) String() string {
	return fmt.Sprintf("{State:%v}", r.State)
}

type SwitchSetStateResponse struct {
	State types.SwitchState `json:"state"` // ['closed','open']
}

func (r SwitchSetStateResponse) String() string {
	return fmt.Sprintf("{State:%v}", r.State)
}

// SetState Set Switch's State
func (device *Switch) SetState(params SwitchSetStateParams) (SwitchSetStateResponse, error) {
	var response SwitchSetStateResponse
	err := device.Call("Switch.setState", params, &response)
	return response, err
}

func (device *Switch) SetStateAsync(params SwitchSetStateParams) <-chan controller.AsyncResult[SwitchSetStateResponse] {
	return controller.DecodeAsync[SwitchSetStateResponse](device.CallAsync("Switch.setState", params))
}

type SwitchSetDelayParams struct {
	DelayOn  *int `json:"delayOn,omitempty"`  // Delay ON minutes; 0=cancel
	DelayOff *int `json:"delayOff,omitempty"` // Delay OFF minutes; 0=cancel
}

func (r SwitchSetDelayParams) String() string {
	var ptr0 any = "<nil>"
	if r.DelayOn != nil {
		ptr0 = fmt.Sprint(*r.DelayOn)
	}
	var ptr1 any = "<nil>"
	if r.DelayOff != nil {
		ptr1 = fmt.Sprint(*r.DelayOff)
	}
	return fmt.Sprintf("{DelayOn:%v DelayOff:%v}", ptr0, ptr1)
}

type SwitchSetDelayResponseDelay struct {
	On  int `json:"on"`
	Off int `json:"off"`
}

func (r SwitchSetDelayResponseDelay) String() string {
	return fmt.Sprintf("{On:%v Off:%v}", r.On, r.Off)
}

type SwitchSetDelayResponse struct {
	Delay SwitchSetDelayResponseDelay `json:"delay"`
}

func (r SwitchSetDelayResponse) String() string {
	return fmt.Sprintf("{Delay:%v}", r.Delay)
}

// SetDelay Set delay to turn on/off Switch
func (device *Switch) SetDelay(params SwitchSetDelayParams) (SwitchSetDelayResponse, error) {
	var response SwitchSetDelayResponse
	err := device.Call("Switch.setDelay", params, &response)
	return response, err
}

func (device *Switch) SetDelayAsync(params SwitchSetDelayParams) <-chan controller.AsyncResult[SwitchSetDelayResponse] {
	return controller.DecodeAsync[SwitchSetDelayResponse](device.CallAsync("Switch.setDelay", params))
}

type SwitchGetSchedulesResponse = []struct {
	IsValid bool    `json:"isValid"`
	Index   int     `json:"index"`
	On      *string `json:"on,omitempty"`  // HH:mm
	Off     *string `json:"off,omitempty"` // HH:mm
	Week    int     `json:"week"`          // Weekday mask
}

// GetSchedules Get Schedule List
func (device *Switch) GetSchedules() (SwitchGetSchedulesResponse, error) {
	var response SwitchGetSchedulesResponse
	err := device.Call("Switch.getSchedules", nil, &response)
	return response, err
}

func (device *Switch) GetSchedulesAsync() <-chan controller.AsyncResult[SwitchGetSchedulesResponse] {
	return controller.DecodeAsync[SwitchGetSchedulesResponse](device.CallAsync("Switch.getSchedules", nil))
}

type SwitchSetSchedulesParamsSchesItem struct {
	IsValid bool   `json:"isValid"`
	Index   int    `json:"index"`
	On      string `json:"on"`   // HH:mm
	Off     string `json:"off"`  // HH:mm
	Week    int    `json:"week"` // Weekday mask
}

func (r SwitchSetSchedulesParamsSchesItem) String() string {
	return fmt.Sprintf("{IsValid:%v Index:%v On:%v Off:%v Week:%v}", r.IsValid, r.Index, r.On, r.Off, r.Week)
}

type SwitchSetSchedulesParams struct {
	Sches []SwitchSetSchedulesParamsSchesItem `json:"sches"`
}

func (r SwitchSetSchedulesParams) String() string {
	return fmt.Sprintf("{Sches:%v}", r.Sches)
}

type SwitchSetSchedulesResponse = []struct {
	IsValid bool    `json:"isValid"`
	Index   int     `json:"index"`
	On      *string `json:"on,omitempty"`  // HH:mm
	Off     *string `json:"off,omitempty"` // HH:mm
	Week    int     `json:"week"`          // Weekday mask
}

// SetSchedules Set Schedule (index 0-5)
func (device *Switch) SetSchedules(params SwitchSetSchedulesParams) (SwitchSetSchedulesResponse, error) {
	var response SwitchSetSchedulesResponse
	err := device.Call("Switch.setSchedules", params, &response)
	return response, err
}

func (device *Switch) SetSchedulesAsync(params SwitchSetSchedulesParams) <-chan controller.AsyncResult[SwitchSetSchedulesResponse] {
	return controller.DecodeAsync[SwitchSetSchedulesResponse](device.CallAsync("Switch.setSchedules", params))
}

type SwitchGetVersionResponseNewVersion struct {
	VersionId   *string `json:"versionId,omitempty"`
	VersionCode *string `json:"versionCode,omitempty"`
	FileSize    *string `json:"fileSize,omitempty"`
}

func (r SwitchGetVersionResponseNewVersion) String() string {
	var ptr0 any = "<nil>"
	if r.VersionId != nil {
		ptr0 = fmt.Sprint(*r.VersionId)
	}
	var ptr1 any = "<nil>"
	if r.VersionCode != nil {
		ptr1 = fmt.Sprint(*r.VersionCode)
	}
	var ptr2 any = "<nil>"
	if r.FileSize != nil {
		ptr2 = fmt.Sprint(*r.FileSize)
	}
	return fmt.Sprintf("{VersionId:%v VersionCode:%v FileSize:%v}", ptr0, ptr1, ptr2)
}

type SwitchGetVersionResponse struct {
	Version    string                             `json:"version"`
	NewVersion SwitchGetVersionResponseNewVersion `json:"newVersion"`
}

func (r SwitchGetVersionResponse) String() string {
	return fmt.Sprintf("{Version:%v NewVersion:%v}", r.Version, r.NewVersion)
}

// GetVersion Get firmware info
func (device *Switch) GetVersion() (SwitchGetVersionResponse, error) {
	var response SwitchGetVersionResponse
	err := device.Call("Switch.getVersion", nil, &response)
	return response, err
}

func (device *Switch) GetVersionAsync() <-chan controller.AsyncResult[SwitchGetVersionResponse] {
	return controller.DecodeAsync[SwitchGetVersionResponse](device.CallAsync("Switch.getVersion", nil))
}

type SwitchSetDeviceAttributesParamsLed struct {
	Status *string `json:"status,omitempty"` // ['on','off']
}

func (r SwitchSetDeviceAttributesParamsLed) String() string {
	var ptr0 any = "<nil>"
	if r.Status != nil {
		ptr0 = fmt.Sprint(*r.Status)
	}
	return fmt.Sprintf("{Status:%v}", ptr0)
}

type SwitchSetDeviceAttributesParams struct {
	Led SwitchSetDeviceAttributesParamsLed `json:"led"`
}

func (r SwitchSetDeviceAttributesParams) String() string {
	return fmt.Sprintf("{Led:%v}", r.Led)
}

type SwitchSetDeviceAttributesResponseLed struct {
	Status string `json:"status"` // ['on','off']
}

func (r SwitchSetDeviceAttributesResponseLed) String() string {
	return fmt.Sprintf("{Status:%v}", r.Status)
}

type SwitchSetDeviceAttributesResponse struct {
	Led SwitchSetDeviceAttributesResponseLed `json:"led"`
}

func (r SwitchSetDeviceAttributesResponse) String() string {
	return fmt.Sprintf("{Led:%v}", r.Led)
}

// SetDeviceAttributes Set device's attributes
func (device *Switch) SetDeviceAttributes(params SwitchSetDeviceAttributesParams) (SwitchSetDeviceAttributesResponse, error) {
	var response SwitchSetDeviceAttributesResponse
	err := device.Call("Switch.setDeviceAttributes", params, &response)
	return response, err
}

func (device *Switch) SetDeviceAttributesAsync(params SwitchSetDeviceAttributesParams) <-chan controller.AsyncResult[SwitchSetDeviceAttributesResponse] {
	return controller.DecodeAsync[SwitchSetDeviceAttributesResponse](device.CallAsync("Switch.setDeviceAttributes", params))
}

type SwitchStartUpgradeParams struct {
	VersionId string `json:"versionId"`
}

func (r SwitchStartUpgradeParams) String() string {
	return fmt.Sprintf("{VersionId:%v}", r.VersionId)
}

type SwitchStartUpgradeResponse struct {
	IsStarted bool `json:"isStarted"`
}

func (r SwitchStartUpgradeResponse) String() string {
	return fmt.Sprintf("{IsStarted:%v}", r.IsStarted)
}

// StartUpgrade Start firmware upgrade
func (device *Switch) StartUpgrade(params SwitchStartUpgradeParams) (SwitchStartUpgradeResponse, error) {
	var response SwitchStartUpgradeResponse
	err := device.Call("Switch.startUpgrade", params, &response)
	return response, err
}

func (device *Switch) StartUpgradeAsync(params SwitchStartUpgradeParams) <-chan controller.AsyncResult[SwitchStartUpgradeResponse] {
	return controller.DecodeAsync[SwitchStartUpgradeResponse](device.CallAsync("Switch.startUpgrade", params))
}

type SwitchGetActivityLogsParamsSearch struct {
	StartDate *string `json:"startDate,omitempty"` // YYYY-MM-DD
	EndDate   *string `json:"endDate,omitempty"`   // YYYY-MM-DD
}

func (r SwitchGetActivityLogsParamsSearch) String() string {
	var ptr0 any = "<nil>"
	if r.StartDate != nil {
		ptr0 = fmt.Sprint(*r.StartDate)
	}
	var ptr1 any = "<nil>"
	if r.EndDate != nil {
		ptr1 = fmt.Sprint(*r.EndDate)
	}
	return fmt.Sprintf("{StartDate:%v EndDate:%v}", ptr0, ptr1)
}

type SwitchGetActivityLogsParams struct {
	Search       SwitchGetActivityLogsParamsSearch `json:"search"`
	RetrievalKey *string                           `json:"retrievalKey,omitempty"`
}

func (r SwitchGetActivityLogsParams) String() string {
	var ptr0 any = "<nil>"
	if r.RetrievalKey != nil {
		ptr0 = fmt.Sprint(*r.RetrievalKey)
	}
	return fmt.Sprintf("{Search:%v RetrievalKey:%v}", r.Search, ptr0)
}

type SwitchGetActivityLogsResponseLogsItem struct {
	Id   string      `json:"id"`
	Time time.Time   `json:"time"`
	Data interface{} `json:"data"`
}

func (r SwitchGetActivityLogsResponseLogsItem) String() string {
	return fmt.Sprintf("{Id:%v Time:%v Data:%v}", r.Id, r.Time, r.Data)
}

type SwitchGetActivityLogsResponseRetrievalKeys struct {
	Next *interface{} `json:"next,omitempty"`
}

func (r SwitchGetActivityLogsResponseRetrievalKeys) String() string {
	var ptr0 any = "<nil>"
	if r.Next != nil {
		ptr0 = fmt.Sprint(*r.Next)
	}
	return fmt.Sprintf("{Next:%v}", ptr0)
}

type SwitchGetActivityLogsResponse struct {
	Logs          []SwitchGetActivityLogsResponseLogsItem    `json:"logs"`
	RetrievalKeys SwitchGetActivityLogsResponseRetrievalKeys `json:"retrievalKeys"`
}

func (r SwitchGetActivityLogsResponse) String() string {
	return fmt.Sprintf("{Logs:%v RetrievalKeys:%v}", r.Logs, r.RetrievalKeys)
}

// GetActivityLogs Retrieve device activity records. Requires DEVICE.HISTORICAL_DATA.READ permission.
func (device *Switch) GetActivityLogs(params SwitchGetActivityLogsParams) (SwitchGetActivityLogsResponse, error) {
	var response SwitchGetActivityLogsResponse
	err := device.Call("Switch.getActivityLogs", params, &response)
	return response, err
}

func (device *Switch) GetActivityLogsAsync(params SwitchGetActivityLogsParams) <-chan controller.AsyncResult[SwitchGetActivityLogsResponse] {
	return controller.DecodeAsync[SwitchGetActivityLogsResponse](device.CallAsync("Switch.getActivityLogs", params))
}

type SwitchReportResponseDelay struct {
	On  int `json:"on"`  // Remain Delay ON minutes
	Off int `json:"off"` // Remain Delay OFF minutes
}

func (r SwitchReportResponseDelay) String() string {
	return fmt.Sprintf("{On:%v Off:%v}", r.On, r.Off)
}

type SwitchReportResponse struct {
	State    types.SwitchState         `json:"state"` // ['closed','open']
	Delay    SwitchReportResponseDelay `json:"delay"`
	Version  string                    `json:"version"`
	Tz       int                       `json:"tz"`
	LoraInfo *types.LoraInfo           `json:"loraInfo,omitempty"`
}

func (r SwitchReportResponse) String() string {
	var ptr0 any = "<nil>"
	if r.LoraInfo != nil {
		ptr0 = fmt.Sprint(*r.LoraInfo)
	}
	return fmt.Sprintf("{State:%v Delay:%v Version:%v Tz:%v LoraInfo:%v}", r.State, r.Delay, r.Version, r.Tz, ptr0)
}

type SwitchAlertResponseDelay struct {
	On  int `json:"on"`  // Remain Delay ON minutes
	Off int `json:"off"` // Remain Delay OFF minutes
}

func (r SwitchAlertResponseDelay) String() string {
	return fmt.Sprintf("{On:%v Off:%v}", r.On, r.Off)
}

type SwitchAlertResponse struct {
	State          types.SwitchState        `json:"state"` // ['closed','open']
	Delay          SwitchAlertResponseDelay `json:"delay"`
	Version        string                   `json:"version"`
	Tz             int                      `json:"tz"`
	LoraInfo       *types.LoraInfo          `json:"loraInfo,omitempty"`
	StateChangedAt *types.Timestamp         `json:"stateChangedAt,omitempty"`
}

func (r SwitchAlertResponse) String() string {
	var ptr0 any = "<nil>"
	if r.LoraInfo != nil {
		ptr0 = fmt.Sprint(*r.LoraInfo)
	}
	var ptr1 any = "<nil>"
	if r.StateChangedAt != nil {
		ptr1 = fmt.Sprint(*r.StateChangedAt)
	}
	return fmt.Sprintf("{State:%v Delay:%v Version:%v Tz:%v LoraInfo:%v StateChangedAt:%v}", r.State, r.Delay, r.Version, r.Tz, ptr0, ptr1)
}

func (device *Switch) ParseEvent(message controller.MqttMessage) (controller.Report, bool) {
	report, ok := device.Device.ParseEvent(message) // base impl decodes event + raw data
	if !ok {
		return report, false
	}
	report.Device = device                        // attribute the report to this concrete device
	data := report.Data.(controller.Unknown).Json // raw payload, re-typed below
	switch report.Event {
	case "Switch.getState":
		var response SwitchGetStateResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "Switch.setState":
		var response SwitchSetStateResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "Switch.setDelay":
		var response SwitchSetDelayResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "Switch.getSchedules":
		var response SwitchGetSchedulesResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "Switch.setSchedules":
		var response SwitchSetSchedulesResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "Switch.getVersion":
		var response SwitchGetVersionResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "Switch.setDeviceAttributes":
		var response SwitchSetDeviceAttributesResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "Switch.startUpgrade":
		var response SwitchStartUpgradeResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "Switch.getActivityLogs":
		var response SwitchGetActivityLogsResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "Switch.Report":
		var response SwitchReportResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "Switch.Alert":
		var response SwitchAlertResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	}
	return report, true
}
