// Code generated by scripts/gen_device_types.py; DO NOT EDIT.
package devices

import (
	"encoding/json"
	"fmt"
	"time"

	"github.com/tyandl/homelink/pkg/yolink/controller"
	"github.com/tyandl/homelink/pkg/yolink/types"
)

type THSensor struct{ *controller.Device }

func init() {
	controller.RegisterDeviceFactory("THSensor", func(device *controller.Device) controller.DeviceController {
		return &THSensor{Device: device}
	})
}

type THSensorGetStateResponseStateAlarm struct {
	LowBattery   bool `json:"lowBattery"`
	LowTemp      bool `json:"lowTemp"`
	HighTemp     bool `json:"highTemp"`
	LowHumidity  bool `json:"lowHumidity"`
	HighHumidity bool `json:"highHumidity"`
	Period       bool `json:"period"`
}

func (r THSensorGetStateResponseStateAlarm) String() string {
	return fmt.Sprintf("{LowBattery:%v LowTemp:%v HighTemp:%v LowHumidity:%v HighHumidity:%v Period:%v}", r.LowBattery, r.LowTemp, r.HighTemp, r.LowHumidity, r.HighHumidity, r.Period)
}

type THSensorGetStateResponseStateTempLimit struct {
	Max types.Temperature `json:"max"`
	Min types.Temperature `json:"min"`
}

func (r THSensorGetStateResponseStateTempLimit) String() string {
	return fmt.Sprintf("{Max:%v Min:%v}", r.Max, r.Min)
}

type THSensorGetStateResponseStateHumidityLimit struct {
	Max float32 `json:"max"`
	Min float32 `json:"min"`
}

func (r THSensorGetStateResponseStateHumidityLimit) String() string {
	return fmt.Sprintf("{Max:%v Min:%v}", r.Max, r.Min)
}

type THSensorGetStateResponseState struct {
	Alarm              THSensorGetStateResponseStateAlarm         `json:"alarm"`
	State              types.AlarmState                           `json:"state"`       // ['normal','alert']
	Battery            types.BatteryLevel                         `json:"battery"`     // 0-4
	Mode               types.TemperatureUnit                      `json:"mode"`        // Display unit ['c','f']
	BatteryType        string                                     `json:"batteryType"` // ['Li']
	Interval           *int                                       `json:"interval,omitempty"`
	Temperature        types.Temperature                          `json:"temperature"`
	Humidity           float32                                    `json:"humidity"`
	TempLimit          THSensorGetStateResponseStateTempLimit     `json:"tempLimit"`
	HumidityLimit      THSensorGetStateResponseStateHumidityLimit `json:"humidityLimit"`
	TempCorrection     types.Temperature                          `json:"tempCorrection"`
	HumidityCorrection float32                                    `json:"humidityCorrection"`
	Version            string                                     `json:"version"`
}

func (r THSensorGetStateResponseState) String() string {
	var ptr0 any = "<nil>"
	if r.Interval != nil {
		ptr0 = fmt.Sprint(*r.Interval)
	}
	return fmt.Sprintf("{Alarm:%v State:%v Battery:%v Mode:%v BatteryType:%v Interval:%v Temperature:%v Humidity:%v TempLimit:%v HumidityLimit:%v TempCorrection:%v HumidityCorrection:%v Version:%v}", r.Alarm, r.State, r.Battery, r.Mode, r.BatteryType, ptr0, r.Temperature, r.Humidity, r.TempLimit, r.HumidityLimit, r.TempCorrection, r.HumidityCorrection, r.Version)
}

type THSensorGetStateResponse struct {
	Online   bool                          `json:"online"`
	State    THSensorGetStateResponseState `json:"state"`
	ReportAt time.Time                     `json:"reportAt"`
	DeviceId string                        `json:"deviceId"`
}

func (r THSensorGetStateResponse) String() string {
	return fmt.Sprintf("{Online:%v State:%v ReportAt:%v DeviceId:%v}", r.Online, r.State, r.ReportAt, r.DeviceId)
}

// GetState Get T&H Sensor's State
func (device *THSensor) GetState() (THSensorGetStateResponse, error) {
	var response THSensorGetStateResponse
	err := device.Call("THSensor.getState", nil, &response)
	return response, err
}

func (device *THSensor) GetStateAsync() <-chan controller.AsyncResult[THSensorGetStateResponse] {
	return controller.DecodeAsync[THSensorGetStateResponse](device.CallAsync("THSensor.getState", nil))
}

type THSensorGetActivityLogsParamsSearch struct {
	StartDate *string `json:"startDate,omitempty"` // YYYY-MM-DD
	EndDate   *string `json:"endDate,omitempty"`   // YYYY-MM-DD
}

func (r THSensorGetActivityLogsParamsSearch) String() string {
	var ptr0 any = "<nil>"
	if r.StartDate != nil {
		ptr0 = fmt.Sprint(*r.StartDate)
	}
	var ptr1 any = "<nil>"
	if r.EndDate != nil {
		ptr1 = fmt.Sprint(*r.EndDate)
	}
	return fmt.Sprintf("{StartDate:%v EndDate:%v}", ptr0, ptr1)
}

type THSensorGetActivityLogsParams struct {
	Search       THSensorGetActivityLogsParamsSearch `json:"search"`
	RetrievalKey *string                             `json:"retrievalKey,omitempty"`
}

func (r THSensorGetActivityLogsParams) String() string {
	var ptr0 any = "<nil>"
	if r.RetrievalKey != nil {
		ptr0 = fmt.Sprint(*r.RetrievalKey)
	}
	return fmt.Sprintf("{Search:%v RetrievalKey:%v}", r.Search, ptr0)
}

type THSensorGetActivityLogsResponseLogsItem struct {
	Id   string      `json:"id"`
	Time time.Time   `json:"time"`
	Data interface{} `json:"data"`
}

func (r THSensorGetActivityLogsResponseLogsItem) String() string {
	return fmt.Sprintf("{Id:%v Time:%v Data:%v}", r.Id, r.Time, r.Data)
}

type THSensorGetActivityLogsResponseRetrievalKeys struct {
	Next *interface{} `json:"next,omitempty"`
}

func (r THSensorGetActivityLogsResponseRetrievalKeys) String() string {
	var ptr0 any = "<nil>"
	if r.Next != nil {
		ptr0 = fmt.Sprint(*r.Next)
	}
	return fmt.Sprintf("{Next:%v}", ptr0)
}

type THSensorGetActivityLogsResponse struct {
	Logs          []THSensorGetActivityLogsResponseLogsItem    `json:"logs"`
	RetrievalKeys THSensorGetActivityLogsResponseRetrievalKeys `json:"retrievalKeys"`
}

func (r THSensorGetActivityLogsResponse) String() string {
	return fmt.Sprintf("{Logs:%v RetrievalKeys:%v}", r.Logs, r.RetrievalKeys)
}

// GetActivityLogs Retrieve device activity records. Requires DEVICE.HISTORICAL_DATA.READ permission.
func (device *THSensor) GetActivityLogs(params THSensorGetActivityLogsParams) (THSensorGetActivityLogsResponse, error) {
	var response THSensorGetActivityLogsResponse
	err := device.Call("THSensor.getActivityLogs", params, &response)
	return response, err
}

func (device *THSensor) GetActivityLogsAsync(params THSensorGetActivityLogsParams) <-chan controller.AsyncResult[THSensorGetActivityLogsResponse] {
	return controller.DecodeAsync[THSensorGetActivityLogsResponse](device.CallAsync("THSensor.getActivityLogs", params))
}

type THSensorGetMetricsLogsParamsSearch struct {
	StartDate *string `json:"startDate,omitempty"` // YYYY-MM-DD
	EndDate   *string `json:"endDate,omitempty"`   // YYYY-MM-DD
}

func (r THSensorGetMetricsLogsParamsSearch) String() string {
	var ptr0 any = "<nil>"
	if r.StartDate != nil {
		ptr0 = fmt.Sprint(*r.StartDate)
	}
	var ptr1 any = "<nil>"
	if r.EndDate != nil {
		ptr1 = fmt.Sprint(*r.EndDate)
	}
	return fmt.Sprintf("{StartDate:%v EndDate:%v}", ptr0, ptr1)
}

type THSensorGetMetricsLogsParams struct {
	Search THSensorGetMetricsLogsParamsSearch `json:"search"`
}

func (r THSensorGetMetricsLogsParams) String() string {
	return fmt.Sprintf("{Search:%v}", r.Search)
}

type THSensorGetMetricsLogsResponseLogsItem struct {
	Time time.Time `json:"time"`
}

func (r THSensorGetMetricsLogsResponseLogsItem) String() string {
	return fmt.Sprintf("{Time:%v}", r.Time)
}

type THSensorGetMetricsLogsResponse struct {
	Logs []THSensorGetMetricsLogsResponseLogsItem `json:"logs"`
}

func (r THSensorGetMetricsLogsResponse) String() string {
	return fmt.Sprintf("{Logs:%v}", r.Logs)
}

// GetMetricsLogs Retrieve device metrics logs. Requires DEVICE.HISTORICAL_DATA.READ permission.
func (device *THSensor) GetMetricsLogs(params THSensorGetMetricsLogsParams) (THSensorGetMetricsLogsResponse, error) {
	var response THSensorGetMetricsLogsResponse
	err := device.Call("THSensor.getMetricsLogs", params, &response)
	return response, err
}

func (device *THSensor) GetMetricsLogsAsync(params THSensorGetMetricsLogsParams) <-chan controller.AsyncResult[THSensorGetMetricsLogsResponse] {
	return controller.DecodeAsync[THSensorGetMetricsLogsResponse](device.CallAsync("THSensor.getMetricsLogs", params))
}

type THSensorReportResponseAlarm struct {
	LowBattery   bool `json:"lowBattery"`
	LowTemp      bool `json:"lowTemp"`
	HighTemp     bool `json:"highTemp"`
	LowHumidity  bool `json:"lowHumidity"`
	HighHumidity bool `json:"highHumidity"`
	Period       bool `json:"period"`
	Code         int  `json:"code"`
}

func (r THSensorReportResponseAlarm) String() string {
	return fmt.Sprintf("{LowBattery:%v LowTemp:%v HighTemp:%v LowHumidity:%v HighHumidity:%v Period:%v Code:%v}", r.LowBattery, r.LowTemp, r.HighTemp, r.LowHumidity, r.HighHumidity, r.Period, r.Code)
}

type THSensorReportResponseTempLimit struct {
	Max float32 `json:"max"`
	Min float32 `json:"min"`
}

func (r THSensorReportResponseTempLimit) String() string {
	return fmt.Sprintf("{Max:%v Min:%v}", r.Max, r.Min)
}

type THSensorReportResponseHumidityLimit struct {
	Max int `json:"max"`
	Min int `json:"min"`
}

func (r THSensorReportResponseHumidityLimit) String() string {
	return fmt.Sprintf("{Max:%v Min:%v}", r.Max, r.Min)
}

type THSensorReportResponse struct {
	State              types.AlarmState                    `json:"state"`
	Alarm              THSensorReportResponseAlarm         `json:"alarm"`
	Battery            types.BatteryLevel                  `json:"battery"`
	Mode               string                              `json:"mode"` // f | c
	Interval           int                                 `json:"interval"`
	Temperature        float32                             `json:"temperature"`
	Humidity           float32                             `json:"humidity"`
	TempLimit          THSensorReportResponseTempLimit     `json:"tempLimit"`
	HumidityLimit      THSensorReportResponseHumidityLimit `json:"humidityLimit"`
	TempCorrection     float32                             `json:"tempCorrection"`
	HumidityCorrection float32                             `json:"humidityCorrection"`
	Version            string                              `json:"version"`
	BatteryType        *string                             `json:"batteryType,omitempty"`
	LoraInfo           *types.LoraInfo                     `json:"loraInfo,omitempty"`
}

func (r THSensorReportResponse) String() string {
	var ptr0 any = "<nil>"
	if r.BatteryType != nil {
		ptr0 = fmt.Sprint(*r.BatteryType)
	}
	var ptr1 any = "<nil>"
	if r.LoraInfo != nil {
		ptr1 = fmt.Sprint(*r.LoraInfo)
	}
	return fmt.Sprintf("{State:%v Alarm:%v Battery:%v Mode:%v Interval:%v Temperature:%v Humidity:%v TempLimit:%v HumidityLimit:%v TempCorrection:%v HumidityCorrection:%v Version:%v BatteryType:%v LoraInfo:%v}", r.State, r.Alarm, r.Battery, r.Mode, r.Interval, r.Temperature, r.Humidity, r.TempLimit, r.HumidityLimit, r.TempCorrection, r.HumidityCorrection, r.Version, ptr0, ptr1)
}

type THSensorAlertResponseAlarm struct {
	LowBattery   bool `json:"lowBattery"`
	LowTemp      bool `json:"lowTemp"`
	HighTemp     bool `json:"highTemp"`
	LowHumidity  bool `json:"lowHumidity"`
	HighHumidity bool `json:"highHumidity"`
	Period       bool `json:"period"`
	Code         int  `json:"code"`
}

func (r THSensorAlertResponseAlarm) String() string {
	return fmt.Sprintf("{LowBattery:%v LowTemp:%v HighTemp:%v LowHumidity:%v HighHumidity:%v Period:%v Code:%v}", r.LowBattery, r.LowTemp, r.HighTemp, r.LowHumidity, r.HighHumidity, r.Period, r.Code)
}

type THSensorAlertResponse struct {
	State       types.AlarmState           `json:"state"`
	Alarm       THSensorAlertResponseAlarm `json:"alarm"`
	Battery     types.BatteryLevel         `json:"battery"`
	Mode        string                     `json:"mode"` // f | c
	Temperature float32                    `json:"temperature"`
	Humidity    float32                    `json:"humidity"`
	Version     string                     `json:"version"`
	LoraInfo    *types.LoraInfo            `json:"loraInfo,omitempty"`
}

func (r THSensorAlertResponse) String() string {
	var ptr0 any = "<nil>"
	if r.LoraInfo != nil {
		ptr0 = fmt.Sprint(*r.LoraInfo)
	}
	return fmt.Sprintf("{State:%v Alarm:%v Battery:%v Mode:%v Temperature:%v Humidity:%v Version:%v LoraInfo:%v}", r.State, r.Alarm, r.Battery, r.Mode, r.Temperature, r.Humidity, r.Version, ptr0)
}

func (device *THSensor) ParseEvent(message controller.MqttMessage) (controller.Report, bool) {
	report, ok := device.Device.ParseEvent(message) // base impl decodes event + raw data
	if !ok {
		return report, false
	}
	report.Device = device                        // attribute the report to this concrete device
	data := report.Data.(controller.Unknown).Json // raw payload, re-typed below
	switch report.Event {
	case "THSensor.getState":
		var response THSensorGetStateResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "THSensor.getActivityLogs":
		var response THSensorGetActivityLogsResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "THSensor.getMetricsLogs":
		var response THSensorGetMetricsLogsResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "THSensor.Report":
		var response THSensorReportResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "THSensor.Alert":
		var response THSensorAlertResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	}
	return report, true
}
