// Code generated by scripts/gen_device_types.py; DO NOT EDIT.
package devices

import (
	"encoding/json"
	"fmt"
	"time"

	"github.com/tyandl/homelink/pkg/yolink/controller"
	"github.com/tyandl/homelink/pkg/yolink/types"
)

type Thermostat struct{ *controller.Device }

func init() {
	controller.RegisterDeviceFactory("Thermostat", func(device *controller.Device) controller.DeviceController {
		return &Thermostat{Device: device}
	})
}

type ThermostatGetStateResponseStateOther struct {
	AuxiliaryHeat *bool `json:"auxiliaryHeat,omitempty"`
	SecondStage   *bool `json:"secondStage,omitempty"`
	DrRunning     *bool `json:"drRunning,omitempty"`
}

func (r ThermostatGetStateResponseStateOther) String() string {
	var ptr0 any = "<nil>"
	if r.AuxiliaryHeat != nil {
		ptr0 = fmt.Sprint(*r.AuxiliaryHeat)
	}
	var ptr1 any = "<nil>"
	if r.SecondStage != nil {
		ptr1 = fmt.Sprint(*r.SecondStage)
	}
	var ptr2 any = "<nil>"
	if r.DrRunning != nil {
		ptr2 = fmt.Sprint(*r.DrRunning)
	}
	return fmt.Sprintf("{AuxiliaryHeat:%v SecondStage:%v DrRunning:%v}", ptr0, ptr1, ptr2)
}

type ThermostatGetStateResponseState struct {
	TempMode    types.TemperatureUnit                `json:"tempMode"`    // ['c','f']
	Temperature types.Temperature                    `json:"temperature"` // Current temp (Celsius)
	Humidity    float32                              `json:"humidity"`    // Current humidity %RH
	LowTemp     types.Temperature                    `json:"lowTemp"`     // Lower setpoint Celsius
	HighTemp    types.Temperature                    `json:"highTemp"`    // Upper setpoint Celsius
	Mode        types.ThermostatMode                 `json:"mode"`        // ['cool','heat','auto','off']
	Fan         types.FanMode                        `json:"fan"`         // ['on','auto']
	Sche        types.ThermostatSchedule             `json:"sche"`        // ['run','hold']
	Running     types.ThermostatRunning              `json:"running"`     // ['cool','heat','idle']
	Sensor1     *float32                             `json:"sensor1,omitempty"`
	Sensor2     *float32                             `json:"sensor2,omitempty"`
	Other       ThermostatGetStateResponseStateOther `json:"other"`
}

func (r ThermostatGetStateResponseState) String() string {
	var ptr0 any = "<nil>"
	if r.Sensor1 != nil {
		ptr0 = fmt.Sprint(*r.Sensor1)
	}
	var ptr1 any = "<nil>"
	if r.Sensor2 != nil {
		ptr1 = fmt.Sprint(*r.Sensor2)
	}
	return fmt.Sprintf("{TempMode:%v Temperature:%v Humidity:%v LowTemp:%v HighTemp:%v Mode:%v Fan:%v Sche:%v Running:%v Sensor1:%v Sensor2:%v Other:%v}", r.TempMode, r.Temperature, r.Humidity, r.LowTemp, r.HighTemp, r.Mode, r.Fan, r.Sche, r.Running, ptr0, ptr1, r.Other)
}

type ThermostatGetStateResponseProperties struct {
	MinRuntime interface{} `json:"minRuntime"`
	CoolLimit  interface{} `json:"coolLimit"`
	HeatLimit  interface{} `json:"heatLimit"`
	Mute       *bool       `json:"mute,omitempty"`
	MenuLock   *bool       `json:"menuLock,omitempty"`
}

func (r ThermostatGetStateResponseProperties) String() string {
	var ptr0 any = "<nil>"
	if r.Mute != nil {
		ptr0 = fmt.Sprint(*r.Mute)
	}
	var ptr1 any = "<nil>"
	if r.MenuLock != nil {
		ptr1 = fmt.Sprint(*r.MenuLock)
	}
	return fmt.Sprintf("{MinRuntime:%v CoolLimit:%v HeatLimit:%v Mute:%v MenuLock:%v}", r.MinRuntime, r.CoolLimit, r.HeatLimit, ptr0, ptr1)
}

type ThermostatGetStateResponse struct {
	State      ThermostatGetStateResponseState      `json:"state"`
	Properties ThermostatGetStateResponseProperties `json:"properties"`
	Eco        interface{}                          `json:"eco"`
	Version    string                               `json:"version"`
	Tz         int                                  `json:"tz"`
}

func (r ThermostatGetStateResponse) String() string {
	return fmt.Sprintf("{State:%v Properties:%v Eco:%v Version:%v Tz:%v}", r.State, r.Properties, r.Eco, r.Version, r.Tz)
}

// GetState Get Current State
func (device *Thermostat) GetState() (ThermostatGetStateResponse, error) {
	var response ThermostatGetStateResponse
	err := device.Call("Thermostat.getState", nil, &response)
	return response, err
}

func (device *Thermostat) GetStateAsync() <-chan controller.AsyncResult[ThermostatGetStateResponse] {
	return controller.DecodeAsync[ThermostatGetStateResponse](device.CallAsync("Thermostat.getState", nil))
}

type ThermostatSetStateParams struct {
	LowTemp  *types.Temperature        `json:"lowTemp,omitempty"`  // Lower setpoint Celsius
	HighTemp *types.Temperature        `json:"highTemp,omitempty"` // Upper setpoint Celsius
	Mode     *types.ThermostatMode     `json:"mode,omitempty"`     // ['cool','heat','auto','off']
	Fan      *types.FanMode            `json:"fan,omitempty"`      // ['on','auto']
	Sche     *types.ThermostatSchedule `json:"sche,omitempty"`     // ['run','hold']
}

func (r ThermostatSetStateParams) String() string {
	var ptr0 any = "<nil>"
	if r.LowTemp != nil {
		ptr0 = fmt.Sprint(*r.LowTemp)
	}
	var ptr1 any = "<nil>"
	if r.HighTemp != nil {
		ptr1 = fmt.Sprint(*r.HighTemp)
	}
	var ptr2 any = "<nil>"
	if r.Mode != nil {
		ptr2 = fmt.Sprint(*r.Mode)
	}
	var ptr3 any = "<nil>"
	if r.Fan != nil {
		ptr3 = fmt.Sprint(*r.Fan)
	}
	var ptr4 any = "<nil>"
	if r.Sche != nil {
		ptr4 = fmt.Sprint(*r.Sche)
	}
	return fmt.Sprintf("{LowTemp:%v HighTemp:%v Mode:%v Fan:%v Sche:%v}", ptr0, ptr1, ptr2, ptr3, ptr4)
}

type ThermostatSetStateResponse struct {
	State string `json:"state"`
}

func (r ThermostatSetStateResponse) String() string {
	return fmt.Sprintf("{State:%v}", r.State)
}

// SetState Set Thermostat's State
func (device *Thermostat) SetState(params ThermostatSetStateParams) (ThermostatSetStateResponse, error) {
	var response ThermostatSetStateResponse
	err := device.Call("Thermostat.setState", params, &response)
	return response, err
}

func (device *Thermostat) SetStateAsync(params ThermostatSetStateParams) <-chan controller.AsyncResult[ThermostatSetStateResponse] {
	return controller.DecodeAsync[ThermostatSetStateResponse](device.CallAsync("Thermostat.setState", params))
}

type ThermostatGetSchedulesResponseSchesItem struct {
	Time     string            `json:"time"` // HH:MM
	LowTemp  types.Temperature `json:"lowTemp"`
	HighTemp types.Temperature `json:"highTemp"`
}

func (r ThermostatGetSchedulesResponseSchesItem) String() string {
	return fmt.Sprintf("{Time:%v LowTemp:%v HighTemp:%v}", r.Time, r.LowTemp, r.HighTemp)
}

type ThermostatGetSchedulesResponse struct {
	Sches []ThermostatGetSchedulesResponseSchesItem `json:"sches"` // Weekday schedules Mon-Sat
}

func (r ThermostatGetSchedulesResponse) String() string {
	return fmt.Sprintf("{Sches:%v}", r.Sches)
}

// GetSchedules Get Schedule List
func (device *Thermostat) GetSchedules() (ThermostatGetSchedulesResponse, error) {
	var response ThermostatGetSchedulesResponse
	err := device.Call("Thermostat.getSchedules", nil, &response)
	return response, err
}

func (device *Thermostat) GetSchedulesAsync() <-chan controller.AsyncResult[ThermostatGetSchedulesResponse] {
	return controller.DecodeAsync[ThermostatGetSchedulesResponse](device.CallAsync("Thermostat.getSchedules", nil))
}

type ThermostatSetSchedulesParamsSchesItem struct {
	Time     string            `json:"time"` // HH:MM
	LowTemp  types.Temperature `json:"lowTemp"`
	HighTemp types.Temperature `json:"highTemp"`
}

func (r ThermostatSetSchedulesParamsSchesItem) String() string {
	return fmt.Sprintf("{Time:%v LowTemp:%v HighTemp:%v}", r.Time, r.LowTemp, r.HighTemp)
}

type ThermostatSetSchedulesParams struct {
	Sches []ThermostatSetSchedulesParamsSchesItem `json:"sches[weekday]"`
}

func (r ThermostatSetSchedulesParams) String() string {
	return fmt.Sprintf("{Sches:%v}", r.Sches)
}

type ThermostatSetSchedulesResponseSchesItem struct {
	Time     string            `json:"time"` // HH:MM
	LowTemp  types.Temperature `json:"lowTemp"`
	HighTemp types.Temperature `json:"highTemp"`
}

func (r ThermostatSetSchedulesResponseSchesItem) String() string {
	return fmt.Sprintf("{Time:%v LowTemp:%v HighTemp:%v}", r.Time, r.LowTemp, r.HighTemp)
}

type ThermostatSetSchedulesResponse struct {
	Sches []ThermostatSetSchedulesResponseSchesItem `json:"sches"` // Weekday schedules Mon-Sat
}

func (r ThermostatSetSchedulesResponse) String() string {
	return fmt.Sprintf("{Sches:%v}", r.Sches)
}

// SetSchedules Set Schedule (4 points per day, Mon-Sat)
func (device *Thermostat) SetSchedules(params ThermostatSetSchedulesParams) (ThermostatSetSchedulesResponse, error) {
	var response ThermostatSetSchedulesResponse
	err := device.Call("Thermostat.setSchedules", params, &response)
	return response, err
}

func (device *Thermostat) SetSchedulesAsync(params ThermostatSetSchedulesParams) <-chan controller.AsyncResult[ThermostatSetSchedulesResponse] {
	return controller.DecodeAsync[ThermostatSetSchedulesResponse](device.CallAsync("Thermostat.setSchedules", params))
}

type ThermostatSetTimeZoneParams struct {
	Tz int `json:"tz"` // Timezone -12~+12
}

func (r ThermostatSetTimeZoneParams) String() string {
	return fmt.Sprintf("{Tz:%v}", r.Tz)
}

type ThermostatSetTimeZoneResponse struct {
	Tz int `json:"tz"`
}

func (r ThermostatSetTimeZoneResponse) String() string {
	return fmt.Sprintf("{Tz:%v}", r.Tz)
}

// SetTimeZone Set Timezone
func (device *Thermostat) SetTimeZone(params ThermostatSetTimeZoneParams) (ThermostatSetTimeZoneResponse, error) {
	var response ThermostatSetTimeZoneResponse
	err := device.Call("Thermostat.setTimeZone", params, &response)
	return response, err
}

func (device *Thermostat) SetTimeZoneAsync(params ThermostatSetTimeZoneParams) <-chan controller.AsyncResult[ThermostatSetTimeZoneResponse] {
	return controller.DecodeAsync[ThermostatSetTimeZoneResponse](device.CallAsync("Thermostat.setTimeZone", params))
}

type ThermostatSetECOParams struct {
	Mode     *types.ThermostatSwitch `json:"mode,omitempty"`     // ['on','off']
	LowTemp  *types.Temperature      `json:"lowTemp,omitempty"`  // ECO lower adjustment 0-5 Celsius
	HighTemp *types.Temperature      `json:"highTemp,omitempty"` // ECO upper adjustment 0-5 Celsius
}

func (r ThermostatSetECOParams) String() string {
	var ptr0 any = "<nil>"
	if r.Mode != nil {
		ptr0 = fmt.Sprint(*r.Mode)
	}
	var ptr1 any = "<nil>"
	if r.LowTemp != nil {
		ptr1 = fmt.Sprint(*r.LowTemp)
	}
	var ptr2 any = "<nil>"
	if r.HighTemp != nil {
		ptr2 = fmt.Sprint(*r.HighTemp)
	}
	return fmt.Sprintf("{Mode:%v LowTemp:%v HighTemp:%v}", ptr0, ptr1, ptr2)
}

type ThermostatSetECOResponse struct {
	Eco interface{} `json:"eco"`
}

func (r ThermostatSetECOResponse) String() string {
	return fmt.Sprintf("{Eco:%v}", r.Eco)
}

// SetECO Set ECO mode settings
func (device *Thermostat) SetECO(params ThermostatSetECOParams) (ThermostatSetECOResponse, error) {
	var response ThermostatSetECOResponse
	err := device.Call("Thermostat.setECO", params, &response)
	return response, err
}

func (device *Thermostat) SetECOAsync(params ThermostatSetECOParams) <-chan controller.AsyncResult[ThermostatSetECOResponse] {
	return controller.DecodeAsync[ThermostatSetECOResponse](device.CallAsync("Thermostat.setECO", params))
}

type ThermostatSetPropertiesParams struct {
	MinRuntime      *int                    `json:"minRuntime,omitempty"`
	CoolLimit       *float32                `json:"coolLimit,omitempty"`
	HeatLimit       *float32                `json:"heatLimit,omitempty"`
	Mute            *bool                   `json:"mute,omitempty"`
	MenuLock        *bool                   `json:"menuLock,omitempty"`
	AuxStandby      *int                    `json:"auxStandby,omitempty"`
	AuxMaxSpan      *int                    `json:"auxMaxSpan,omitempty"`
	AuxThreshold    *float32                `json:"auxThreshold,omitempty"`
	Stage2Standby   *int                    `json:"stage2Standby,omitempty"`
	Stage2MaxSpan   *int                    `json:"stage2MaxSpan,omitempty"`
	Stage2Threshold *float32                `json:"stage2Threshold,omitempty"`
	Master          *types.ThermostatMaster `json:"master,omitempty"` // ['local','sensor1','sensor2']
}

func (r ThermostatSetPropertiesParams) String() string {
	var ptr0 any = "<nil>"
	if r.MinRuntime != nil {
		ptr0 = fmt.Sprint(*r.MinRuntime)
	}
	var ptr1 any = "<nil>"
	if r.CoolLimit != nil {
		ptr1 = fmt.Sprint(*r.CoolLimit)
	}
	var ptr2 any = "<nil>"
	if r.HeatLimit != nil {
		ptr2 = fmt.Sprint(*r.HeatLimit)
	}
	var ptr3 any = "<nil>"
	if r.Mute != nil {
		ptr3 = fmt.Sprint(*r.Mute)
	}
	var ptr4 any = "<nil>"
	if r.MenuLock != nil {
		ptr4 = fmt.Sprint(*r.MenuLock)
	}
	var ptr5 any = "<nil>"
	if r.AuxStandby != nil {
		ptr5 = fmt.Sprint(*r.AuxStandby)
	}
	var ptr6 any = "<nil>"
	if r.AuxMaxSpan != nil {
		ptr6 = fmt.Sprint(*r.AuxMaxSpan)
	}
	var ptr7 any = "<nil>"
	if r.AuxThreshold != nil {
		ptr7 = fmt.Sprint(*r.AuxThreshold)
	}
	var ptr8 any = "<nil>"
	if r.Stage2Standby != nil {
		ptr8 = fmt.Sprint(*r.Stage2Standby)
	}
	var ptr9 any = "<nil>"
	if r.Stage2MaxSpan != nil {
		ptr9 = fmt.Sprint(*r.Stage2MaxSpan)
	}
	var ptr10 any = "<nil>"
	if r.Stage2Threshold != nil {
		ptr10 = fmt.Sprint(*r.Stage2Threshold)
	}
	var ptr11 any = "<nil>"
	if r.Master != nil {
		ptr11 = fmt.Sprint(*r.Master)
	}
	return fmt.Sprintf("{MinRuntime:%v CoolLimit:%v HeatLimit:%v Mute:%v MenuLock:%v AuxStandby:%v AuxMaxSpan:%v AuxThreshold:%v Stage2Standby:%v Stage2MaxSpan:%v Stage2Threshold:%v Master:%v}", ptr0, ptr1, ptr2, ptr3, ptr4, ptr5, ptr6, ptr7, ptr8, ptr9, ptr10, ptr11)
}

type ThermostatSetPropertiesResponse struct {
	MinRuntime interface{} `json:"minRuntime"`
	CoolLimit  interface{} `json:"coolLimit"`
	HeatLimit  interface{} `json:"heatLimit"`
}

func (r ThermostatSetPropertiesResponse) String() string {
	return fmt.Sprintf("{MinRuntime:%v CoolLimit:%v HeatLimit:%v}", r.MinRuntime, r.CoolLimit, r.HeatLimit)
}

// SetProperties Set running properties
func (device *Thermostat) SetProperties(params ThermostatSetPropertiesParams) (ThermostatSetPropertiesResponse, error) {
	var response ThermostatSetPropertiesResponse
	err := device.Call("Thermostat.setProperties", params, &response)
	return response, err
}

func (device *Thermostat) SetPropertiesAsync(params ThermostatSetPropertiesParams) <-chan controller.AsyncResult[ThermostatSetPropertiesResponse] {
	return controller.DecodeAsync[ThermostatSetPropertiesResponse](device.CallAsync("Thermostat.setProperties", params))
}

type ThermostatGetVersionResponseNewVersion struct {
	VersionId   *string `json:"versionId,omitempty"`
	VersionCode *string `json:"versionCode,omitempty"`
	FileSize    *string `json:"fileSize,omitempty"`
}

func (r ThermostatGetVersionResponseNewVersion) String() string {
	var ptr0 any = "<nil>"
	if r.VersionId != nil {
		ptr0 = fmt.Sprint(*r.VersionId)
	}
	var ptr1 any = "<nil>"
	if r.VersionCode != nil {
		ptr1 = fmt.Sprint(*r.VersionCode)
	}
	var ptr2 any = "<nil>"
	if r.FileSize != nil {
		ptr2 = fmt.Sprint(*r.FileSize)
	}
	return fmt.Sprintf("{VersionId:%v VersionCode:%v FileSize:%v}", ptr0, ptr1, ptr2)
}

type ThermostatGetVersionResponse struct {
	Version    string                                 `json:"version"`
	NewVersion ThermostatGetVersionResponseNewVersion `json:"newVersion"`
}

func (r ThermostatGetVersionResponse) String() string {
	return fmt.Sprintf("{Version:%v NewVersion:%v}", r.Version, r.NewVersion)
}

// GetVersion Get firmware info
func (device *Thermostat) GetVersion() (ThermostatGetVersionResponse, error) {
	var response ThermostatGetVersionResponse
	err := device.Call("Thermostat.getVersion", nil, &response)
	return response, err
}

func (device *Thermostat) GetVersionAsync() <-chan controller.AsyncResult[ThermostatGetVersionResponse] {
	return controller.DecodeAsync[ThermostatGetVersionResponse](device.CallAsync("Thermostat.getVersion", nil))
}

type ThermostatStartUpgradeParams struct {
	VersionId string `json:"versionId"`
}

func (r ThermostatStartUpgradeParams) String() string {
	return fmt.Sprintf("{VersionId:%v}", r.VersionId)
}

type ThermostatStartUpgradeResponse struct {
	IsStarted bool `json:"isStarted"`
}

func (r ThermostatStartUpgradeResponse) String() string {
	return fmt.Sprintf("{IsStarted:%v}", r.IsStarted)
}

// StartUpgrade Start firmware upgrade
func (device *Thermostat) StartUpgrade(params ThermostatStartUpgradeParams) (ThermostatStartUpgradeResponse, error) {
	var response ThermostatStartUpgradeResponse
	err := device.Call("Thermostat.startUpgrade", params, &response)
	return response, err
}

func (device *Thermostat) StartUpgradeAsync(params ThermostatStartUpgradeParams) <-chan controller.AsyncResult[ThermostatStartUpgradeResponse] {
	return controller.DecodeAsync[ThermostatStartUpgradeResponse](device.CallAsync("Thermostat.startUpgrade", params))
}

type ThermostatGetActivityLogsParamsSearch struct {
	StartDate *string `json:"startDate,omitempty"` // YYYY-MM-DD
	EndDate   *string `json:"endDate,omitempty"`   // YYYY-MM-DD
}

func (r ThermostatGetActivityLogsParamsSearch) String() string {
	var ptr0 any = "<nil>"
	if r.StartDate != nil {
		ptr0 = fmt.Sprint(*r.StartDate)
	}
	var ptr1 any = "<nil>"
	if r.EndDate != nil {
		ptr1 = fmt.Sprint(*r.EndDate)
	}
	return fmt.Sprintf("{StartDate:%v EndDate:%v}", ptr0, ptr1)
}

type ThermostatGetActivityLogsParams struct {
	Search       ThermostatGetActivityLogsParamsSearch `json:"search"`
	RetrievalKey *string                               `json:"retrievalKey,omitempty"`
}

func (r ThermostatGetActivityLogsParams) String() string {
	var ptr0 any = "<nil>"
	if r.RetrievalKey != nil {
		ptr0 = fmt.Sprint(*r.RetrievalKey)
	}
	return fmt.Sprintf("{Search:%v RetrievalKey:%v}", r.Search, ptr0)
}

type ThermostatGetActivityLogsResponseLogsItem struct {
	Id   string      `json:"id"`
	Time time.Time   `json:"time"`
	Data interface{} `json:"data"`
}

func (r ThermostatGetActivityLogsResponseLogsItem) String() string {
	return fmt.Sprintf("{Id:%v Time:%v Data:%v}", r.Id, r.Time, r.Data)
}

type ThermostatGetActivityLogsResponseRetrievalKeys struct {
	Next *interface{} `json:"next,omitempty"`
}

func (r ThermostatGetActivityLogsResponseRetrievalKeys) String() string {
	var ptr0 any = "<nil>"
	if r.Next != nil {
		ptr0 = fmt.Sprint(*r.Next)
	}
	return fmt.Sprintf("{Next:%v}", ptr0)
}

type ThermostatGetActivityLogsResponse struct {
	Logs          []ThermostatGetActivityLogsResponseLogsItem    `json:"logs"`
	RetrievalKeys ThermostatGetActivityLogsResponseRetrievalKeys `json:"retrievalKeys"`
}

func (r ThermostatGetActivityLogsResponse) String() string {
	return fmt.Sprintf("{Logs:%v RetrievalKeys:%v}", r.Logs, r.RetrievalKeys)
}

// GetActivityLogs Retrieve device activity records. Requires DEVICE.HISTORICAL_DATA.READ permission.
func (device *Thermostat) GetActivityLogs(params ThermostatGetActivityLogsParams) (ThermostatGetActivityLogsResponse, error) {
	var response ThermostatGetActivityLogsResponse
	err := device.Call("Thermostat.getActivityLogs", params, &response)
	return response, err
}

func (device *Thermostat) GetActivityLogsAsync(params ThermostatGetActivityLogsParams) <-chan controller.AsyncResult[ThermostatGetActivityLogsResponse] {
	return controller.DecodeAsync[ThermostatGetActivityLogsResponse](device.CallAsync("Thermostat.getActivityLogs", params))
}

type ThermostatSetCorrectionParams struct {
	Temperature *types.Temperature `json:"temperature,omitempty"` // Correction value +/-5.0 Celsius
	Humidity    *float32           `json:"humidity,omitempty"`    // Correction value +/-10 percent
}

func (r ThermostatSetCorrectionParams) String() string {
	var ptr0 any = "<nil>"
	if r.Temperature != nil {
		ptr0 = fmt.Sprint(*r.Temperature)
	}
	var ptr1 any = "<nil>"
	if r.Humidity != nil {
		ptr1 = fmt.Sprint(*r.Humidity)
	}
	return fmt.Sprintf("{Temperature:%v Humidity:%v}", ptr0, ptr1)
}

type ThermostatSetCorrectionResponse struct {
	Temperature *types.Temperature `json:"temperature,omitempty"`
	Humidity    *float32           `json:"humidity,omitempty"`
}

func (r ThermostatSetCorrectionResponse) String() string {
	var ptr0 any = "<nil>"
	if r.Temperature != nil {
		ptr0 = fmt.Sprint(*r.Temperature)
	}
	var ptr1 any = "<nil>"
	if r.Humidity != nil {
		ptr1 = fmt.Sprint(*r.Humidity)
	}
	return fmt.Sprintf("{Temperature:%v Humidity:%v}", ptr0, ptr1)
}

// SetCorrection Set temperature and humidity correction of local sensor
func (device *Thermostat) SetCorrection(params ThermostatSetCorrectionParams) (ThermostatSetCorrectionResponse, error) {
	var response ThermostatSetCorrectionResponse
	err := device.Call("Thermostat.setCorrection", params, &response)
	return response, err
}

func (device *Thermostat) SetCorrectionAsync(params ThermostatSetCorrectionParams) <-chan controller.AsyncResult[ThermostatSetCorrectionResponse] {
	return controller.DecodeAsync[ThermostatSetCorrectionResponse](device.CallAsync("Thermostat.setCorrection", params))
}

type ThermostatReportResponseOther struct {
	AuxiliaryHeat *bool `json:"auxiliaryHeat,omitempty"`
	SecondStage   *bool `json:"secondStage,omitempty"`
	DrRunning     *bool `json:"drRunning,omitempty"`
}

func (r ThermostatReportResponseOther) String() string {
	var ptr0 any = "<nil>"
	if r.AuxiliaryHeat != nil {
		ptr0 = fmt.Sprint(*r.AuxiliaryHeat)
	}
	var ptr1 any = "<nil>"
	if r.SecondStage != nil {
		ptr1 = fmt.Sprint(*r.SecondStage)
	}
	var ptr2 any = "<nil>"
	if r.DrRunning != nil {
		ptr2 = fmt.Sprint(*r.DrRunning)
	}
	return fmt.Sprintf("{AuxiliaryHeat:%v SecondStage:%v DrRunning:%v}", ptr0, ptr1, ptr2)
}

type ThermostatReportResponse struct {
	TempMode    types.TemperatureUnit         `json:"tempMode"`    // ['c','f']
	Temperature types.Temperature             `json:"temperature"` // Current temp (Celsius)
	Humidity    float32                       `json:"humidity"`    // Current humidity %RH
	LowTemp     types.Temperature             `json:"lowTemp"`     // Lower setpoint Celsius
	HighTemp    types.Temperature             `json:"highTemp"`    // Upper setpoint Celsius
	Mode        types.ThermostatMode          `json:"mode"`        // ['cool','heat','auto','off']
	Fan         types.FanMode                 `json:"fan"`         // ['on','auto']
	Sche        types.ThermostatSchedule      `json:"sche"`        // ['run','hold']
	Running     types.ThermostatRunning       `json:"running"`     // ['cool','heat','idle']
	Sensor1     *float32                      `json:"sensor1,omitempty"`
	Sensor2     *float32                      `json:"sensor2,omitempty"`
	Other       ThermostatReportResponseOther `json:"other"`
	LoraInfo    *types.LoraInfo               `json:"loraInfo,omitempty"`
}

func (r ThermostatReportResponse) String() string {
	var ptr0 any = "<nil>"
	if r.Sensor1 != nil {
		ptr0 = fmt.Sprint(*r.Sensor1)
	}
	var ptr1 any = "<nil>"
	if r.Sensor2 != nil {
		ptr1 = fmt.Sprint(*r.Sensor2)
	}
	var ptr2 any = "<nil>"
	if r.LoraInfo != nil {
		ptr2 = fmt.Sprint(*r.LoraInfo)
	}
	return fmt.Sprintf("{TempMode:%v Temperature:%v Humidity:%v LowTemp:%v HighTemp:%v Mode:%v Fan:%v Sche:%v Running:%v Sensor1:%v Sensor2:%v Other:%v LoraInfo:%v}", r.TempMode, r.Temperature, r.Humidity, r.LowTemp, r.HighTemp, r.Mode, r.Fan, r.Sche, r.Running, ptr0, ptr1, r.Other, ptr2)
}

type ThermostatAlertResponseOther struct {
	AuxiliaryHeat *bool `json:"auxiliaryHeat,omitempty"`
	SecondStage   *bool `json:"secondStage,omitempty"`
	DrRunning     *bool `json:"drRunning,omitempty"`
}

func (r ThermostatAlertResponseOther) String() string {
	var ptr0 any = "<nil>"
	if r.AuxiliaryHeat != nil {
		ptr0 = fmt.Sprint(*r.AuxiliaryHeat)
	}
	var ptr1 any = "<nil>"
	if r.SecondStage != nil {
		ptr1 = fmt.Sprint(*r.SecondStage)
	}
	var ptr2 any = "<nil>"
	if r.DrRunning != nil {
		ptr2 = fmt.Sprint(*r.DrRunning)
	}
	return fmt.Sprintf("{AuxiliaryHeat:%v SecondStage:%v DrRunning:%v}", ptr0, ptr1, ptr2)
}

type ThermostatAlertResponse struct {
	TempMode       types.TemperatureUnit        `json:"tempMode"`    // ['c','f']
	Temperature    types.Temperature            `json:"temperature"` // Current temp (Celsius)
	Humidity       float32                      `json:"humidity"`    // Current humidity %RH
	LowTemp        types.Temperature            `json:"lowTemp"`     // Lower setpoint Celsius
	HighTemp       types.Temperature            `json:"highTemp"`    // Upper setpoint Celsius
	Mode           types.ThermostatMode         `json:"mode"`        // ['cool','heat','auto','off']
	Fan            types.FanMode                `json:"fan"`         // ['on','auto']
	Sche           types.ThermostatSchedule     `json:"sche"`        // ['run','hold']
	Running        types.ThermostatRunning      `json:"running"`     // ['cool','heat','idle']
	Sensor1        *float32                     `json:"sensor1,omitempty"`
	Sensor2        *float32                     `json:"sensor2,omitempty"`
	Other          ThermostatAlertResponseOther `json:"other"`
	LoraInfo       *types.LoraInfo              `json:"loraInfo,omitempty"`
	StateChangedAt *types.Timestamp             `json:"stateChangedAt,omitempty"`
}

func (r ThermostatAlertResponse) String() string {
	var ptr0 any = "<nil>"
	if r.Sensor1 != nil {
		ptr0 = fmt.Sprint(*r.Sensor1)
	}
	var ptr1 any = "<nil>"
	if r.Sensor2 != nil {
		ptr1 = fmt.Sprint(*r.Sensor2)
	}
	var ptr2 any = "<nil>"
	if r.LoraInfo != nil {
		ptr2 = fmt.Sprint(*r.LoraInfo)
	}
	var ptr3 any = "<nil>"
	if r.StateChangedAt != nil {
		ptr3 = fmt.Sprint(*r.StateChangedAt)
	}
	return fmt.Sprintf("{TempMode:%v Temperature:%v Humidity:%v LowTemp:%v HighTemp:%v Mode:%v Fan:%v Sche:%v Running:%v Sensor1:%v Sensor2:%v Other:%v LoraInfo:%v StateChangedAt:%v}", r.TempMode, r.Temperature, r.Humidity, r.LowTemp, r.HighTemp, r.Mode, r.Fan, r.Sche, r.Running, ptr0, ptr1, r.Other, ptr2, ptr3)
}

func (device *Thermostat) ParseEvent(message controller.MqttMessage) (controller.Report, bool) {
	report, ok := device.Device.ParseEvent(message) // base impl decodes event + raw data
	if !ok {
		return report, false
	}
	report.Device = device                        // attribute the report to this concrete device
	data := report.Data.(controller.Unknown).Json // raw payload, re-typed below
	switch report.Event {
	case "Thermostat.getState":
		var response ThermostatGetStateResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "Thermostat.setState":
		var response ThermostatSetStateResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "Thermostat.getSchedules":
		var response ThermostatGetSchedulesResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "Thermostat.setSchedules":
		var response ThermostatSetSchedulesResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "Thermostat.setTimeZone":
		var response ThermostatSetTimeZoneResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "Thermostat.setECO":
		var response ThermostatSetECOResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "Thermostat.setProperties":
		var response ThermostatSetPropertiesResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "Thermostat.getVersion":
		var response ThermostatGetVersionResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "Thermostat.startUpgrade":
		var response ThermostatStartUpgradeResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "Thermostat.getActivityLogs":
		var response ThermostatGetActivityLogsResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "Thermostat.setCorrection":
		var response ThermostatSetCorrectionResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "Thermostat.Report":
		var response ThermostatReportResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "Thermostat.Alert":
		var response ThermostatAlertResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	}
	return report, true
}
