// Code generated by scripts/gen_device_types.py; DO NOT EDIT.
package devices

import (
	"encoding/json"
	"fmt"
	"time"

	"github.com/tyandl/homelink/pkg/yolink/controller"
	"github.com/tyandl/homelink/pkg/yolink/types"
)

type VibrationSensor struct{ *controller.Device }

func init() {
	controller.RegisterDeviceFactory("VibrationSensor", func(device *controller.Device) controller.DeviceController {
		return &VibrationSensor{Device: device}
	})
}

type VibrationSensorGetStateResponseState struct {
	Online           bool               `json:"online"`
	State            types.AlarmState   `json:"state"`   // ['normal','alert']
	Battery          types.BatteryLevel `json:"battery"` // 0-4
	AlertInterval    *int               `json:"alertInterval,omitempty"`
	NoVibrationDelay *int               `json:"noVibrationDelay,omitempty"` // Time to enter no-vibration state
	Version          string             `json:"version"`
}

func (r VibrationSensorGetStateResponseState) String() string {
	var ptr0 any = "<nil>"
	if r.AlertInterval != nil {
		ptr0 = fmt.Sprint(*r.AlertInterval)
	}
	var ptr1 any = "<nil>"
	if r.NoVibrationDelay != nil {
		ptr1 = fmt.Sprint(*r.NoVibrationDelay)
	}
	return fmt.Sprintf("{Online:%v State:%v Battery:%v AlertInterval:%v NoVibrationDelay:%v Version:%v}", r.Online, r.State, r.Battery, ptr0, ptr1, r.Version)
}

type VibrationSensorGetStateResponse struct {
	State    VibrationSensorGetStateResponseState `json:"state"`
	ReportAt time.Time                            `json:"reportAt"`
	DeviceId string                               `json:"deviceId"`
}

func (r VibrationSensorGetStateResponse) String() string {
	return fmt.Sprintf("{State:%v ReportAt:%v DeviceId:%v}", r.State, r.ReportAt, r.DeviceId)
}

// GetState Get Vibration Sensor's State
func (device *VibrationSensor) GetState() (VibrationSensorGetStateResponse, error) {
	var response VibrationSensorGetStateResponse
	err := device.Call("VibrationSensor.getState", nil, &response)
	return response, err
}

func (device *VibrationSensor) GetStateAsync() <-chan controller.AsyncResult[VibrationSensorGetStateResponse] {
	return controller.DecodeAsync[VibrationSensorGetStateResponse](device.CallAsync("VibrationSensor.getState", nil))
}

type VibrationSensorReportResponse struct {
	Online           bool               `json:"online"`
	State            types.AlarmState   `json:"state"`   // ['normal','alert']
	Battery          types.BatteryLevel `json:"battery"` // 0-4
	AlertInterval    *int               `json:"alertInterval,omitempty"`
	NoVibrationDelay *int               `json:"noVibrationDelay,omitempty"` // Time to enter no-vibration state
	Version          string             `json:"version"`
	LoraInfo         *types.LoraInfo    `json:"loraInfo,omitempty"`
}

func (r VibrationSensorReportResponse) String() string {
	var ptr0 any = "<nil>"
	if r.AlertInterval != nil {
		ptr0 = fmt.Sprint(*r.AlertInterval)
	}
	var ptr1 any = "<nil>"
	if r.NoVibrationDelay != nil {
		ptr1 = fmt.Sprint(*r.NoVibrationDelay)
	}
	var ptr2 any = "<nil>"
	if r.LoraInfo != nil {
		ptr2 = fmt.Sprint(*r.LoraInfo)
	}
	return fmt.Sprintf("{Online:%v State:%v Battery:%v AlertInterval:%v NoVibrationDelay:%v Version:%v LoraInfo:%v}", r.Online, r.State, r.Battery, ptr0, ptr1, r.Version, ptr2)
}

type VibrationSensorAlertResponse struct {
	Online           bool               `json:"online"`
	State            types.AlarmState   `json:"state"`   // ['normal','alert']
	Battery          types.BatteryLevel `json:"battery"` // 0-4
	AlertInterval    *int               `json:"alertInterval,omitempty"`
	NoVibrationDelay *int               `json:"noVibrationDelay,omitempty"` // Time to enter no-vibration state
	Version          string             `json:"version"`
	LoraInfo         *types.LoraInfo    `json:"loraInfo,omitempty"`
	StateChangedAt   *types.Timestamp   `json:"stateChangedAt,omitempty"`
}

func (r VibrationSensorAlertResponse) String() string {
	var ptr0 any = "<nil>"
	if r.AlertInterval != nil {
		ptr0 = fmt.Sprint(*r.AlertInterval)
	}
	var ptr1 any = "<nil>"
	if r.NoVibrationDelay != nil {
		ptr1 = fmt.Sprint(*r.NoVibrationDelay)
	}
	var ptr2 any = "<nil>"
	if r.LoraInfo != nil {
		ptr2 = fmt.Sprint(*r.LoraInfo)
	}
	var ptr3 any = "<nil>"
	if r.StateChangedAt != nil {
		ptr3 = fmt.Sprint(*r.StateChangedAt)
	}
	return fmt.Sprintf("{Online:%v State:%v Battery:%v AlertInterval:%v NoVibrationDelay:%v Version:%v LoraInfo:%v StateChangedAt:%v}", r.Online, r.State, r.Battery, ptr0, ptr1, r.Version, ptr2, ptr3)
}

func (device *VibrationSensor) ParseEvent(message controller.MqttMessage) (controller.Report, bool) {
	report, ok := device.Device.ParseEvent(message) // base impl decodes event + raw data
	if !ok {
		return report, false
	}
	report.Device = device                        // attribute the report to this concrete device
	data := report.Data.(controller.Unknown).Json // raw payload, re-typed below
	switch report.Event {
	case "VibrationSensor.getState":
		var response VibrationSensorGetStateResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "VibrationSensor.Report":
		var response VibrationSensorReportResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "VibrationSensor.Alert":
		var response VibrationSensorAlertResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	}
	return report, true
}
