// Code generated by scripts/gen_device_types.py; DO NOT EDIT.
package devices

import (
	"encoding/json"
	"fmt"

	"github.com/tyandl/homelink/pkg/yolink/controller"
	"github.com/tyandl/homelink/pkg/yolink/types"
)

type WaterLeakController struct{ *controller.Device }

func init() {
	controller.RegisterDeviceFactory("WaterLeakController", func(device *controller.Device) controller.DeviceController {
		return &WaterLeakController{Device: device}
	})
}

type WaterLeakControllerGetStateResponseState struct {
	Valve                types.SwitchCommand `json:"valve"`                // ['close','open']
	WaterTemp            types.Temperature   `json:"waterTemp"`            // Water temp Celsius
	WaterFlowingDuration bool                `json:"waterFlowingDuration"` // Duration of single water usage
}

func (r WaterLeakControllerGetStateResponseState) String() string {
	return fmt.Sprintf("{Valve:%v WaterTemp:%v WaterFlowingDuration:%v}", r.Valve, r.WaterTemp, r.WaterFlowingDuration)
}

type WaterLeakControllerGetStateResponseAlarm struct {
	Leak                bool `json:"leak"`
	NoWaterError        bool `json:"noWaterError"` // Dry pipe alarm
	FreezeError         bool `json:"freezeError"`
	DurationOverrun     bool `json:"durationOverrun"`
	Reminder            bool `json:"reminder"`
	OpenReminder        bool `json:"openReminder"`
	SensorDetectorError bool `json:"sensorDetectorError"`
	ValveDetectorError  bool `json:"valveDetectorError"`
}

func (r WaterLeakControllerGetStateResponseAlarm) String() string {
	return fmt.Sprintf("{Leak:%v NoWaterError:%v FreezeError:%v DurationOverrun:%v Reminder:%v OpenReminder:%v SensorDetectorError:%v ValveDetectorError:%v}", r.Leak, r.NoWaterError, r.FreezeError, r.DurationOverrun, r.Reminder, r.OpenReminder, r.SensorDetectorError, r.ValveDetectorError)
}

type WaterLeakControllerGetStateResponseValveDelay struct {
	On  *int `json:"on,omitempty"`
	Off *int `json:"off,omitempty"`
}

func (r WaterLeakControllerGetStateResponseValveDelay) String() string {
	var ptr0 any = "<nil>"
	if r.On != nil {
		ptr0 = fmt.Sprint(*r.On)
	}
	var ptr1 any = "<nil>"
	if r.Off != nil {
		ptr1 = fmt.Sprint(*r.Off)
	}
	return fmt.Sprintf("{On:%v Off:%v}", ptr0, ptr1)
}

type WaterLeakControllerGetStateResponseAttributesLeakDetector struct {
	DryPipeTemp types.Temperature `json:"dryPipeTemp"` // Celsius
}

func (r WaterLeakControllerGetStateResponseAttributesLeakDetector) String() string {
	return fmt.Sprintf("{DryPipeTemp:%v}", r.DryPipeTemp)
}

type WaterLeakControllerGetStateResponseAttributes struct {
	OpenReminder          int                                                       `json:"openReminder"`       // Open remind minutes
	AlertInterval         int                                                       `json:"alertInterval"`      // Alert interval minutes
	LeakPlan              types.WaterLeakPlan                                       `json:"leakPlan"`           // ['Manual','Auto','AwayAuto']
	MaxOverrunDuration    int                                                       `json:"maxOverrunDuration"` // Max continuous usage minutes
	MaxOverrunSensivity   int                                                       `json:"maxOverrunSensivity"`
	MaxOverrunCloseValve  bool                                                      `json:"maxOverrunCloseValve"`
	AwayDuration          int                                                       `json:"awayDuration"`
	AwayCloseValve        bool                                                      `json:"awayCloseValve"`
	Mute                  bool                                                      `json:"mute"`
	MuteDuration          int                                                       `json:"muteDuration"`
	WaterTemperatureLevel types.WaterTemperatureLevel                               `json:"waterTemperatureLevel"` // 0=cold,1=hot
	FreezeACVEnable       bool                                                      `json:"freezeACVEnable"`
	LeakDetector          WaterLeakControllerGetStateResponseAttributesLeakDetector `json:"leakDetector"`
}

func (r WaterLeakControllerGetStateResponseAttributes) String() string {
	return fmt.Sprintf("{OpenReminder:%v AlertInterval:%v LeakPlan:%v MaxOverrunDuration:%v MaxOverrunSensivity:%v MaxOverrunCloseValve:%v AwayDuration:%v AwayCloseValve:%v Mute:%v MuteDuration:%v WaterTemperatureLevel:%v FreezeACVEnable:%v LeakDetector:%v}", r.OpenReminder, r.AlertInterval, r.LeakPlan, r.MaxOverrunDuration, r.MaxOverrunSensivity, r.MaxOverrunCloseValve, r.AwayDuration, r.AwayCloseValve, r.Mute, r.MuteDuration, r.WaterTemperatureLevel, r.FreezeACVEnable, r.LeakDetector)
}

type WaterLeakControllerGetStateResponse struct {
	State                    WaterLeakControllerGetStateResponseState      `json:"state"`
	Alarm                    WaterLeakControllerGetStateResponseAlarm      `json:"alarm"`
	Battery                  types.BatteryLevel                            `json:"battery"`     // 0-4
	PowerSupply              types.PowerSupply                             `json:"powerSupply"` // ['battery','PowerLine']
	ValveDelay               WaterLeakControllerGetStateResponseValveDelay `json:"valveDelay"`
	Attributes               WaterLeakControllerGetStateResponseAttributes `json:"attributes"`
	MuteRemaining            int                                           `json:"muteRemaining"` // Remaining mute minutes
	HeaterTemp               types.Temperature                             `json:"heaterTemp"`
	WaterTemperatureVariance float32                                       `json:"waterTemperatureVariance"`
	Version                  string                                        `json:"version"`
	Tz                       int                                           `json:"tz"`
}

func (r WaterLeakControllerGetStateResponse) String() string {
	return fmt.Sprintf("{State:%v Alarm:%v Battery:%v PowerSupply:%v ValveDelay:%v Attributes:%v MuteRemaining:%v HeaterTemp:%v WaterTemperatureVariance:%v Version:%v Tz:%v}", r.State, r.Alarm, r.Battery, r.PowerSupply, r.ValveDelay, r.Attributes, r.MuteRemaining, r.HeaterTemp, r.WaterTemperatureVariance, r.Version, r.Tz)
}

// GetState Get the state of Water Leak Controller
func (device *WaterLeakController) GetState() (WaterLeakControllerGetStateResponse, error) {
	var response WaterLeakControllerGetStateResponse
	err := device.Call("WaterLeakController.getState", nil, &response)
	return response, err
}

func (device *WaterLeakController) GetStateAsync() <-chan controller.AsyncResult[WaterLeakControllerGetStateResponse] {
	return controller.DecodeAsync[WaterLeakControllerGetStateResponse](device.CallAsync("WaterLeakController.getState", nil))
}

type WaterLeakControllerSetStateParams struct {
	Valve types.SwitchCommand `json:"valve"` // ['close','open']
}

func (r WaterLeakControllerSetStateParams) String() string {
	return fmt.Sprintf("{Valve:%v}", r.Valve)
}

// SetState Set valve state
func (device *WaterLeakController) SetState(params WaterLeakControllerSetStateParams) error {
	return device.Call("WaterLeakController.setState", params, nil)
}

func (device *WaterLeakController) SetStateAsync(params WaterLeakControllerSetStateParams) <-chan controller.AsyncResult[any] {
	return controller.DecodeAsync[any](device.CallAsync("WaterLeakController.setState", params))
}

type WaterLeakControllerSetAttributesParamsAttributesLeakDetector struct {
	DryPipeTemp *types.Temperature `json:"dryPipeTemp,omitempty"`
}

func (r WaterLeakControllerSetAttributesParamsAttributesLeakDetector) String() string {
	var ptr0 any = "<nil>"
	if r.DryPipeTemp != nil {
		ptr0 = fmt.Sprint(*r.DryPipeTemp)
	}
	return fmt.Sprintf("{DryPipeTemp:%v}", ptr0)
}

type WaterLeakControllerSetAttributesParamsAttributes struct {
	OpenReminder          *int                                                         `json:"openReminder,omitempty"`
	AlertInterval         *int                                                         `json:"alertInterval,omitempty"`
	LeakPlan              *types.WaterLeakPlan                                         `json:"leakPlan,omitempty"` // ['Manual','Auto','AwayAuto']
	MaxOverrunDuration    *int                                                         `json:"maxOverrunDuration,omitempty"`
	MaxOverrunSensivity   *int                                                         `json:"maxOverrunSensivity,omitempty"`
	MaxOverrunCloseValve  *bool                                                        `json:"maxOverrunCloseValve,omitempty"`
	AwayDuration          *int                                                         `json:"awayDuration,omitempty"`
	AwayCloseValve        *bool                                                        `json:"awayCloseValve,omitempty"`
	Mute                  *bool                                                        `json:"mute,omitempty"`
	MuteDuration          *int                                                         `json:"muteDuration,omitempty"`
	WaterTemperatureLevel *types.WaterTemperatureLevel                                 `json:"waterTemperatureLevel,omitempty"`
	FreezeACVEnable       *bool                                                        `json:"freezeACVEnable,omitempty"`
	LeakDetector          WaterLeakControllerSetAttributesParamsAttributesLeakDetector `json:"leakDetector"`
}

func (r WaterLeakControllerSetAttributesParamsAttributes) String() string {
	var ptr0 any = "<nil>"
	if r.OpenReminder != nil {
		ptr0 = fmt.Sprint(*r.OpenReminder)
	}
	var ptr1 any = "<nil>"
	if r.AlertInterval != nil {
		ptr1 = fmt.Sprint(*r.AlertInterval)
	}
	var ptr2 any = "<nil>"
	if r.LeakPlan != nil {
		ptr2 = fmt.Sprint(*r.LeakPlan)
	}
	var ptr3 any = "<nil>"
	if r.MaxOverrunDuration != nil {
		ptr3 = fmt.Sprint(*r.MaxOverrunDuration)
	}
	var ptr4 any = "<nil>"
	if r.MaxOverrunSensivity != nil {
		ptr4 = fmt.Sprint(*r.MaxOverrunSensivity)
	}
	var ptr5 any = "<nil>"
	if r.MaxOverrunCloseValve != nil {
		ptr5 = fmt.Sprint(*r.MaxOverrunCloseValve)
	}
	var ptr6 any = "<nil>"
	if r.AwayDuration != nil {
		ptr6 = fmt.Sprint(*r.AwayDuration)
	}
	var ptr7 any = "<nil>"
	if r.AwayCloseValve != nil {
		ptr7 = fmt.Sprint(*r.AwayCloseValve)
	}
	var ptr8 any = "<nil>"
	if r.Mute != nil {
		ptr8 = fmt.Sprint(*r.Mute)
	}
	var ptr9 any = "<nil>"
	if r.MuteDuration != nil {
		ptr9 = fmt.Sprint(*r.MuteDuration)
	}
	var ptr10 any = "<nil>"
	if r.WaterTemperatureLevel != nil {
		ptr10 = fmt.Sprint(*r.WaterTemperatureLevel)
	}
	var ptr11 any = "<nil>"
	if r.FreezeACVEnable != nil {
		ptr11 = fmt.Sprint(*r.FreezeACVEnable)
	}
	return fmt.Sprintf("{OpenReminder:%v AlertInterval:%v LeakPlan:%v MaxOverrunDuration:%v MaxOverrunSensivity:%v MaxOverrunCloseValve:%v AwayDuration:%v AwayCloseValve:%v Mute:%v MuteDuration:%v WaterTemperatureLevel:%v FreezeACVEnable:%v LeakDetector:%v}", ptr0, ptr1, ptr2, ptr3, ptr4, ptr5, ptr6, ptr7, ptr8, ptr9, ptr10, ptr11, r.LeakDetector)
}

type WaterLeakControllerSetAttributesParams struct {
	Attributes WaterLeakControllerSetAttributesParamsAttributes `json:"attributes"`
}

func (r WaterLeakControllerSetAttributesParams) String() string {
	return fmt.Sprintf("{Attributes:%v}", r.Attributes)
}

// SetAttributes Set attributes for Water Leak Controller
func (device *WaterLeakController) SetAttributes(params WaterLeakControllerSetAttributesParams) error {
	return device.Call("WaterLeakController.setAttributes", params, nil)
}

func (device *WaterLeakController) SetAttributesAsync(params WaterLeakControllerSetAttributesParams) <-chan controller.AsyncResult[any] {
	return controller.DecodeAsync[any](device.CallAsync("WaterLeakController.setAttributes", params))
}

type WaterLeakControllerGetValveSchedulesResponse = []struct {
	IsValid bool    `json:"isValid"`
	Index   int     `json:"index"`
	On      *string `json:"on,omitempty"`  // HH:mm
	Off     *string `json:"off,omitempty"` // HH:mm
	Week    int     `json:"week"`          // Weekday mask
}

// GetValveSchedules Get valve schedules
func (device *WaterLeakController) GetValveSchedules() (WaterLeakControllerGetValveSchedulesResponse, error) {
	var response WaterLeakControllerGetValveSchedulesResponse
	err := device.Call("WaterLeakController.getValveSchedules", nil, &response)
	return response, err
}

func (device *WaterLeakController) GetValveSchedulesAsync() <-chan controller.AsyncResult[WaterLeakControllerGetValveSchedulesResponse] {
	return controller.DecodeAsync[WaterLeakControllerGetValveSchedulesResponse](device.CallAsync("WaterLeakController.getValveSchedules", nil))
}

type WaterLeakControllerSetValveSchedulesParamsSchesItem struct {
	IsValid bool   `json:"isValid"`
	Index   int    `json:"index"`
	On      string `json:"on"`  // HH:mm
	Off     string `json:"off"` // HH:mm
	Week    int    `json:"week"`
}

func (r WaterLeakControllerSetValveSchedulesParamsSchesItem) String() string {
	return fmt.Sprintf("{IsValid:%v Index:%v On:%v Off:%v Week:%v}", r.IsValid, r.Index, r.On, r.Off, r.Week)
}

type WaterLeakControllerSetValveSchedulesParams struct {
	Sches []WaterLeakControllerSetValveSchedulesParamsSchesItem `json:"sches"`
}

func (r WaterLeakControllerSetValveSchedulesParams) String() string {
	return fmt.Sprintf("{Sches:%v}", r.Sches)
}

type WaterLeakControllerSetValveSchedulesResponse = []struct {
	IsValid bool    `json:"isValid"`
	Index   int     `json:"index"`
	On      *string `json:"on,omitempty"`  // HH:mm
	Off     *string `json:"off,omitempty"` // HH:mm
	Week    int     `json:"week"`          // Weekday mask
}

// SetValveSchedules Set valve schedules (index 0-5; isValid=false & week=0 to remove)
func (device *WaterLeakController) SetValveSchedules(params WaterLeakControllerSetValveSchedulesParams) (WaterLeakControllerSetValveSchedulesResponse, error) {
	var response WaterLeakControllerSetValveSchedulesResponse
	err := device.Call("WaterLeakController.setValveSchedules", params, &response)
	return response, err
}

func (device *WaterLeakController) SetValveSchedulesAsync(params WaterLeakControllerSetValveSchedulesParams) <-chan controller.AsyncResult[WaterLeakControllerSetValveSchedulesResponse] {
	return controller.DecodeAsync[WaterLeakControllerSetValveSchedulesResponse](device.CallAsync("WaterLeakController.setValveSchedules", params))
}

type WaterLeakControllerGetLeakSchedulesResponse = []struct {
	IsValid    bool    `json:"isValid"`
	Index      int     `json:"index"`
	On         *string `json:"on,omitempty"`  // HH:mm
	Off        *string `json:"off,omitempty"` // HH:mm
	Week       int     `json:"week"`
	StandBy    int     `json:"standBy"`   // Leak duration before alarm
	Sensivity  int     `json:"sensivity"` // Sensitivity (Deprecated)
	CloseValve bool    `json:"closeValve"`
}

// GetLeakSchedules Get leak detection schedules
func (device *WaterLeakController) GetLeakSchedules() (WaterLeakControllerGetLeakSchedulesResponse, error) {
	var response WaterLeakControllerGetLeakSchedulesResponse
	err := device.Call("WaterLeakController.getLeakSchedules", nil, &response)
	return response, err
}

func (device *WaterLeakController) GetLeakSchedulesAsync() <-chan controller.AsyncResult[WaterLeakControllerGetLeakSchedulesResponse] {
	return controller.DecodeAsync[WaterLeakControllerGetLeakSchedulesResponse](device.CallAsync("WaterLeakController.getLeakSchedules", nil))
}

type WaterLeakControllerSetLeakSchedulesParamsSchesItem struct {
	IsValid    bool   `json:"isValid"`
	Index      int    `json:"index"`
	On         string `json:"on"`  // HH:mm
	Off        string `json:"off"` // HH:mm
	Week       int    `json:"week"`
	StandBy    int    `json:"standBy"`   // Leak alarm delay minutes
	Sensivity  int    `json:"sensivity"` // (Deprecated)
	CloseValve bool   `json:"closeValve"`
}

func (r WaterLeakControllerSetLeakSchedulesParamsSchesItem) String() string {
	return fmt.Sprintf("{IsValid:%v Index:%v On:%v Off:%v Week:%v StandBy:%v Sensivity:%v CloseValve:%v}", r.IsValid, r.Index, r.On, r.Off, r.Week, r.StandBy, r.Sensivity, r.CloseValve)
}

type WaterLeakControllerSetLeakSchedulesParams struct {
	Sches []WaterLeakControllerSetLeakSchedulesParamsSchesItem `json:"sches"`
}

func (r WaterLeakControllerSetLeakSchedulesParams) String() string {
	return fmt.Sprintf("{Sches:%v}", r.Sches)
}

type WaterLeakControllerSetLeakSchedulesResponse = []struct {
	IsValid    bool    `json:"isValid"`
	Index      int     `json:"index"`
	On         *string `json:"on,omitempty"`  // HH:mm
	Off        *string `json:"off,omitempty"` // HH:mm
	Week       int     `json:"week"`
	StandBy    int     `json:"standBy"`   // Leak duration before alarm
	Sensivity  int     `json:"sensivity"` // Sensitivity (Deprecated)
	CloseValve bool    `json:"closeValve"`
}

// SetLeakSchedules Set leak detection schedules (index 0-5)
func (device *WaterLeakController) SetLeakSchedules(params WaterLeakControllerSetLeakSchedulesParams) (WaterLeakControllerSetLeakSchedulesResponse, error) {
	var response WaterLeakControllerSetLeakSchedulesResponse
	err := device.Call("WaterLeakController.setLeakSchedules", params, &response)
	return response, err
}

func (device *WaterLeakController) SetLeakSchedulesAsync(params WaterLeakControllerSetLeakSchedulesParams) <-chan controller.AsyncResult[WaterLeakControllerSetLeakSchedulesResponse] {
	return controller.DecodeAsync[WaterLeakControllerSetLeakSchedulesResponse](device.CallAsync("WaterLeakController.setLeakSchedules", params))
}

type WaterLeakControllerReportResponse struct {
	Valve                types.SwitchCommand `json:"valve"`                // ['close','open']
	WaterTemp            types.Temperature   `json:"waterTemp"`            // Water temp Celsius
	WaterFlowingDuration bool                `json:"waterFlowingDuration"` // Duration of single water usage
	LoraInfo             *types.LoraInfo     `json:"loraInfo,omitempty"`
}

func (r WaterLeakControllerReportResponse) String() string {
	var ptr0 any = "<nil>"
	if r.LoraInfo != nil {
		ptr0 = fmt.Sprint(*r.LoraInfo)
	}
	return fmt.Sprintf("{Valve:%v WaterTemp:%v WaterFlowingDuration:%v LoraInfo:%v}", r.Valve, r.WaterTemp, r.WaterFlowingDuration, ptr0)
}

type WaterLeakControllerAlertResponse struct {
	Valve                types.SwitchCommand `json:"valve"`                // ['close','open']
	WaterTemp            types.Temperature   `json:"waterTemp"`            // Water temp Celsius
	WaterFlowingDuration bool                `json:"waterFlowingDuration"` // Duration of single water usage
	LoraInfo             *types.LoraInfo     `json:"loraInfo,omitempty"`
	StateChangedAt       *types.Timestamp    `json:"stateChangedAt,omitempty"`
}

func (r WaterLeakControllerAlertResponse) String() string {
	var ptr0 any = "<nil>"
	if r.LoraInfo != nil {
		ptr0 = fmt.Sprint(*r.LoraInfo)
	}
	var ptr1 any = "<nil>"
	if r.StateChangedAt != nil {
		ptr1 = fmt.Sprint(*r.StateChangedAt)
	}
	return fmt.Sprintf("{Valve:%v WaterTemp:%v WaterFlowingDuration:%v LoraInfo:%v StateChangedAt:%v}", r.Valve, r.WaterTemp, r.WaterFlowingDuration, ptr0, ptr1)
}

func (device *WaterLeakController) ParseEvent(message controller.MqttMessage) (controller.Report, bool) {
	report, ok := device.Device.ParseEvent(message) // base impl decodes event + raw data
	if !ok {
		return report, false
	}
	report.Device = device                        // attribute the report to this concrete device
	data := report.Data.(controller.Unknown).Json // raw payload, re-typed below
	switch report.Event {
	case "WaterLeakController.getState":
		var response WaterLeakControllerGetStateResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "WaterLeakController.getValveSchedules":
		var response WaterLeakControllerGetValveSchedulesResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "WaterLeakController.setValveSchedules":
		var response WaterLeakControllerSetValveSchedulesResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "WaterLeakController.getLeakSchedules":
		var response WaterLeakControllerGetLeakSchedulesResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "WaterLeakController.setLeakSchedules":
		var response WaterLeakControllerSetLeakSchedulesResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "WaterLeakController.Report":
		var response WaterLeakControllerReportResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "WaterLeakController.Alert":
		var response WaterLeakControllerAlertResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	}
	return report, true
}
