// Code generated by scripts/gen_device_types.py; DO NOT EDIT.
package devices

import (
	"encoding/json"
	"fmt"

	"github.com/tyandl/homelink/pkg/yolink/controller"
	"github.com/tyandl/homelink/pkg/yolink/types"
)

type WaterMeterController struct{ *controller.Device }

func init() {
	controller.RegisterDeviceFactory("WaterMeterController", func(device *controller.Device) controller.DeviceController {
		return &WaterMeterController{Device: device}
	})
}

type WaterMeterControllerGetStateResponseState struct {
	Valve        types.SwitchCommand `json:"valve"` // ['close','open']
	Meter        int                 `json:"meter"` // Meter reading
	WaterFlowing bool                `json:"waterFlowing"`
}

func (r WaterMeterControllerGetStateResponseState) String() string {
	return fmt.Sprintf("{Valve:%v Meter:%v WaterFlowing:%v}", r.Valve, r.Meter, r.WaterFlowing)
}

type WaterMeterControllerGetStateResponseAlarm struct {
	OpenReminder    bool `json:"openReminder"`
	Leak            bool `json:"leak"`
	AmountOverrun   bool `json:"amountOverrun"`
	DurationOverrun bool `json:"durationOverrun"`
	ValveError      bool `json:"valveError"`
	Reminder        bool `json:"reminder"`
	FreezeError     bool `json:"freezeError"`
}

func (r WaterMeterControllerGetStateResponseAlarm) String() string {
	return fmt.Sprintf("{OpenReminder:%v Leak:%v AmountOverrun:%v DurationOverrun:%v ValveError:%v Reminder:%v FreezeError:%v}", r.OpenReminder, r.Leak, r.AmountOverrun, r.DurationOverrun, r.ValveError, r.Reminder, r.FreezeError)
}

type WaterMeterControllerGetStateResponseValveDelay struct {
	On  *int `json:"on,omitempty"`
	Off *int `json:"off,omitempty"`
}

func (r WaterMeterControllerGetStateResponseValveDelay) String() string {
	var ptr0 any = "<nil>"
	if r.On != nil {
		ptr0 = fmt.Sprint(*r.On)
	}
	var ptr1 any = "<nil>"
	if r.Off != nil {
		ptr1 = fmt.Sprint(*r.Off)
	}
	return fmt.Sprintf("{On:%v Off:%v}", ptr0, ptr1)
}

type WaterMeterControllerGetStateResponseAttributes struct {
	OpenReminder       int                      `json:"openReminder"` // Open remind minutes
	MeterUnit          types.MeterUnit          `json:"meterUnit"`    // 0=GAL,1=CCF,2=M3,3=L
	AlertInterval      int                      `json:"alertInterval"`
	MeterStepFactor    int                      `json:"meterStepFactor"`
	LeakLimit          float32                  `json:"leakLimit"`
	AutoCloseValve     bool                     `json:"autoCloseValve"`
	OverrunAmountACV   bool                     `json:"overrunAmountACV"`
	OverrunDurationACV bool                     `json:"overrunDurationACV"`
	LeakPlan           types.WaterMeterLeakPlan `json:"leakPlan"` // ['on','off','schedule']
	OverrunAmount      float32                  `json:"overrunAmount"`
	OverrunDuration    int                      `json:"overrunDuration"`
	FreezeTemp         types.Temperature        `json:"freezeTemp"`
}

func (r WaterMeterControllerGetStateResponseAttributes) String() string {
	return fmt.Sprintf("{OpenReminder:%v MeterUnit:%v AlertInterval:%v MeterStepFactor:%v LeakLimit:%v AutoCloseValve:%v OverrunAmountACV:%v OverrunDurationACV:%v LeakPlan:%v OverrunAmount:%v OverrunDuration:%v FreezeTemp:%v}", r.OpenReminder, r.MeterUnit, r.AlertInterval, r.MeterStepFactor, r.LeakLimit, r.AutoCloseValve, r.OverrunAmountACV, r.OverrunDurationACV, r.LeakPlan, r.OverrunAmount, r.OverrunDuration, r.FreezeTemp)
}

type WaterMeterControllerGetStateResponseRecentUsage struct {
	Amount   int `json:"amount"`
	Duration int `json:"duration"`
}

func (r WaterMeterControllerGetStateResponseRecentUsage) String() string {
	return fmt.Sprintf("{Amount:%v Duration:%v}", r.Amount, r.Duration)
}

type WaterMeterControllerGetStateResponse struct {
	State       WaterMeterControllerGetStateResponseState       `json:"state"`
	Alarm       WaterMeterControllerGetStateResponseAlarm       `json:"alarm"`
	Battery     types.BatteryLevel                              `json:"battery"`     // 0-4
	PowerSupply types.PowerSupply                               `json:"powerSupply"` // ['battery','PowerLine']
	ValveDelay  WaterMeterControllerGetStateResponseValveDelay  `json:"valveDelay"`
	Attributes  WaterMeterControllerGetStateResponseAttributes  `json:"attributes"`
	RecentUsage WaterMeterControllerGetStateResponseRecentUsage `json:"recentUsage"`
	DailyUsage  int                                             `json:"dailyUsage"`
	Temperature types.Temperature                               `json:"temperature"`
	Version     string                                          `json:"version"`
	Tz          int                                             `json:"tz"`
}

func (r WaterMeterControllerGetStateResponse) String() string {
	return fmt.Sprintf("{State:%v Alarm:%v Battery:%v PowerSupply:%v ValveDelay:%v Attributes:%v RecentUsage:%v DailyUsage:%v Temperature:%v Version:%v Tz:%v}", r.State, r.Alarm, r.Battery, r.PowerSupply, r.ValveDelay, r.Attributes, r.RecentUsage, r.DailyUsage, r.Temperature, r.Version, r.Tz)
}

// GetState Get the state of Water Meter Controller
func (device *WaterMeterController) GetState() (WaterMeterControllerGetStateResponse, error) {
	var response WaterMeterControllerGetStateResponse
	err := device.Call("WaterMeterController.getState", nil, &response)
	return response, err
}

func (device *WaterMeterController) GetStateAsync() <-chan controller.AsyncResult[WaterMeterControllerGetStateResponse] {
	return controller.DecodeAsync[WaterMeterControllerGetStateResponse](device.CallAsync("WaterMeterController.getState", nil))
}

type WaterMeterControllerSetStateParams struct {
	Valve types.SwitchCommand `json:"valve"` // ['close','open']
}

func (r WaterMeterControllerSetStateParams) String() string {
	return fmt.Sprintf("{Valve:%v}", r.Valve)
}

// SetState Set valve state
func (device *WaterMeterController) SetState(params WaterMeterControllerSetStateParams) error {
	return device.Call("WaterMeterController.setState", params, nil)
}

func (device *WaterMeterController) SetStateAsync(params WaterMeterControllerSetStateParams) <-chan controller.AsyncResult[any] {
	return controller.DecodeAsync[any](device.CallAsync("WaterMeterController.setState", params))
}

type WaterMeterControllerSetMeterAttributesParamsAttributes struct {
	OpenReminder       *int                      `json:"openReminder,omitempty"`
	MeterUnit          *types.MeterUnit          `json:"meterUnit,omitempty"` // 0=GAL,1=CCF,2=M3,3=L
	AlertInterval      *int                      `json:"alertInterval,omitempty"`
	MeterStepFactor    *int                      `json:"meterStepFactor,omitempty"`
	LeakLimit          *float32                  `json:"leakLimit,omitempty"`
	AutoCloseValve     *bool                     `json:"autoCloseValve,omitempty"`
	OverrunAmountACV   *bool                     `json:"overrunAmountACV,omitempty"`
	OverrunDurationACV *bool                     `json:"overrunDurationACV,omitempty"`
	LeakPlan           *types.WaterMeterLeakPlan `json:"leakPlan,omitempty"` // ['on','off','schedule']
	OverrunAmount      *float32                  `json:"overrunAmount,omitempty"`
	OverrunDuration    *int                      `json:"overrunDuration,omitempty"`
	FreezeTemp         *types.Temperature        `json:"freezeTemp,omitempty"`
}

func (r WaterMeterControllerSetMeterAttributesParamsAttributes) String() string {
	var ptr0 any = "<nil>"
	if r.OpenReminder != nil {
		ptr0 = fmt.Sprint(*r.OpenReminder)
	}
	var ptr1 any = "<nil>"
	if r.MeterUnit != nil {
		ptr1 = fmt.Sprint(*r.MeterUnit)
	}
	var ptr2 any = "<nil>"
	if r.AlertInterval != nil {
		ptr2 = fmt.Sprint(*r.AlertInterval)
	}
	var ptr3 any = "<nil>"
	if r.MeterStepFactor != nil {
		ptr3 = fmt.Sprint(*r.MeterStepFactor)
	}
	var ptr4 any = "<nil>"
	if r.LeakLimit != nil {
		ptr4 = fmt.Sprint(*r.LeakLimit)
	}
	var ptr5 any = "<nil>"
	if r.AutoCloseValve != nil {
		ptr5 = fmt.Sprint(*r.AutoCloseValve)
	}
	var ptr6 any = "<nil>"
	if r.OverrunAmountACV != nil {
		ptr6 = fmt.Sprint(*r.OverrunAmountACV)
	}
	var ptr7 any = "<nil>"
	if r.OverrunDurationACV != nil {
		ptr7 = fmt.Sprint(*r.OverrunDurationACV)
	}
	var ptr8 any = "<nil>"
	if r.LeakPlan != nil {
		ptr8 = fmt.Sprint(*r.LeakPlan)
	}
	var ptr9 any = "<nil>"
	if r.OverrunAmount != nil {
		ptr9 = fmt.Sprint(*r.OverrunAmount)
	}
	var ptr10 any = "<nil>"
	if r.OverrunDuration != nil {
		ptr10 = fmt.Sprint(*r.OverrunDuration)
	}
	var ptr11 any = "<nil>"
	if r.FreezeTemp != nil {
		ptr11 = fmt.Sprint(*r.FreezeTemp)
	}
	return fmt.Sprintf("{OpenReminder:%v MeterUnit:%v AlertInterval:%v MeterStepFactor:%v LeakLimit:%v AutoCloseValve:%v OverrunAmountACV:%v OverrunDurationACV:%v LeakPlan:%v OverrunAmount:%v OverrunDuration:%v FreezeTemp:%v}", ptr0, ptr1, ptr2, ptr3, ptr4, ptr5, ptr6, ptr7, ptr8, ptr9, ptr10, ptr11)
}

type WaterMeterControllerSetMeterAttributesParams struct {
	Attributes WaterMeterControllerSetMeterAttributesParamsAttributes `json:"attributes"`
}

func (r WaterMeterControllerSetMeterAttributesParams) String() string {
	return fmt.Sprintf("{Attributes:%v}", r.Attributes)
}

// SetMeterAttributes Set attributes for Water Meter Controller
func (device *WaterMeterController) SetMeterAttributes(params WaterMeterControllerSetMeterAttributesParams) error {
	return device.Call("WaterMeterController.setMeterAttributes", params, nil)
}

func (device *WaterMeterController) SetMeterAttributesAsync(params WaterMeterControllerSetMeterAttributesParams) <-chan controller.AsyncResult[any] {
	return controller.DecodeAsync[any](device.CallAsync("WaterMeterController.setMeterAttributes", params))
}

type WaterMeterControllerGetValveSchedulesResponse = []struct {
	IsValid bool    `json:"isValid"`
	Index   int     `json:"index"`
	On      *string `json:"on,omitempty"`  // HH:mm
	Off     *string `json:"off,omitempty"` // HH:mm
	Week    int     `json:"week"`
}

// GetValveSchedules Get valve schedules
func (device *WaterMeterController) GetValveSchedules() (WaterMeterControllerGetValveSchedulesResponse, error) {
	var response WaterMeterControllerGetValveSchedulesResponse
	err := device.Call("WaterMeterController.getValveSchedules", nil, &response)
	return response, err
}

func (device *WaterMeterController) GetValveSchedulesAsync() <-chan controller.AsyncResult[WaterMeterControllerGetValveSchedulesResponse] {
	return controller.DecodeAsync[WaterMeterControllerGetValveSchedulesResponse](device.CallAsync("WaterMeterController.getValveSchedules", nil))
}

type WaterMeterControllerSetValveSchedulesParamsSchesItem struct {
	IsValid bool   `json:"isValid"`
	Index   int    `json:"index"`
	On      string `json:"on"`  // HH:mm
	Off     string `json:"off"` // HH:mm
	Week    int    `json:"week"`
}

func (r WaterMeterControllerSetValveSchedulesParamsSchesItem) String() string {
	return fmt.Sprintf("{IsValid:%v Index:%v On:%v Off:%v Week:%v}", r.IsValid, r.Index, r.On, r.Off, r.Week)
}

type WaterMeterControllerSetValveSchedulesParams struct {
	Sches []WaterMeterControllerSetValveSchedulesParamsSchesItem `json:"sches"`
}

func (r WaterMeterControllerSetValveSchedulesParams) String() string {
	return fmt.Sprintf("{Sches:%v}", r.Sches)
}

type WaterMeterControllerSetValveSchedulesResponse = []struct {
	IsValid bool    `json:"isValid"`
	Index   int     `json:"index"`
	On      *string `json:"on,omitempty"`  // HH:mm
	Off     *string `json:"off,omitempty"` // HH:mm
	Week    int     `json:"week"`
}

// SetValveSchedules Set valve schedules (index 0-5)
func (device *WaterMeterController) SetValveSchedules(params WaterMeterControllerSetValveSchedulesParams) (WaterMeterControllerSetValveSchedulesResponse, error) {
	var response WaterMeterControllerSetValveSchedulesResponse
	err := device.Call("WaterMeterController.setValveSchedules", params, &response)
	return response, err
}

func (device *WaterMeterController) SetValveSchedulesAsync(params WaterMeterControllerSetValveSchedulesParams) <-chan controller.AsyncResult[WaterMeterControllerSetValveSchedulesResponse] {
	return controller.DecodeAsync[WaterMeterControllerSetValveSchedulesResponse](device.CallAsync("WaterMeterController.setValveSchedules", params))
}

type WaterMeterControllerGetLeakSchedulesResponse = []struct {
	IsValid   bool    `json:"isValid"`
	Index     int     `json:"index"`
	On        *string `json:"on,omitempty"`  // HH:mm
	Off       *string `json:"off,omitempty"` // HH:mm
	Week      int     `json:"week"`
	LeakLimit int     `json:"leakLimit"` // Leak limit in meter unit
}

// GetLeakSchedules Get leak schedules
func (device *WaterMeterController) GetLeakSchedules() (WaterMeterControllerGetLeakSchedulesResponse, error) {
	var response WaterMeterControllerGetLeakSchedulesResponse
	err := device.Call("WaterMeterController.getLeakSchedules", nil, &response)
	return response, err
}

func (device *WaterMeterController) GetLeakSchedulesAsync() <-chan controller.AsyncResult[WaterMeterControllerGetLeakSchedulesResponse] {
	return controller.DecodeAsync[WaterMeterControllerGetLeakSchedulesResponse](device.CallAsync("WaterMeterController.getLeakSchedules", nil))
}

type WaterMeterControllerSetLeakSchedulesParamsSchesItem struct {
	IsValid   bool   `json:"isValid"`
	Index     int    `json:"index"`
	On        string `json:"on"`  // HH:mm
	Off       string `json:"off"` // HH:mm
	Week      int    `json:"week"`
	LeakLimit *int   `json:"leakLimit,omitempty"`
}

func (r WaterMeterControllerSetLeakSchedulesParamsSchesItem) String() string {
	var ptr0 any = "<nil>"
	if r.LeakLimit != nil {
		ptr0 = fmt.Sprint(*r.LeakLimit)
	}
	return fmt.Sprintf("{IsValid:%v Index:%v On:%v Off:%v Week:%v LeakLimit:%v}", r.IsValid, r.Index, r.On, r.Off, r.Week, ptr0)
}

type WaterMeterControllerSetLeakSchedulesParams struct {
	Sches []WaterMeterControllerSetLeakSchedulesParamsSchesItem `json:"sches"`
}

func (r WaterMeterControllerSetLeakSchedulesParams) String() string {
	return fmt.Sprintf("{Sches:%v}", r.Sches)
}

type WaterMeterControllerSetLeakSchedulesResponse = []struct {
	IsValid   bool    `json:"isValid"`
	Index     int     `json:"index"`
	On        *string `json:"on,omitempty"`  // HH:mm
	Off       *string `json:"off,omitempty"` // HH:mm
	Week      int     `json:"week"`
	LeakLimit int     `json:"leakLimit"` // Leak limit in meter unit
}

// SetLeakSchedules Set leak schedules (index 0-5)
func (device *WaterMeterController) SetLeakSchedules(params WaterMeterControllerSetLeakSchedulesParams) (WaterMeterControllerSetLeakSchedulesResponse, error) {
	var response WaterMeterControllerSetLeakSchedulesResponse
	err := device.Call("WaterMeterController.setLeakSchedules", params, &response)
	return response, err
}

func (device *WaterMeterController) SetLeakSchedulesAsync(params WaterMeterControllerSetLeakSchedulesParams) <-chan controller.AsyncResult[WaterMeterControllerSetLeakSchedulesResponse] {
	return controller.DecodeAsync[WaterMeterControllerSetLeakSchedulesResponse](device.CallAsync("WaterMeterController.setLeakSchedules", params))
}

type WaterMeterControllerReportResponse struct {
	Valve        types.SwitchCommand `json:"valve"` // ['close','open']
	Meter        int                 `json:"meter"` // Meter reading
	WaterFlowing bool                `json:"waterFlowing"`
	LoraInfo     *types.LoraInfo     `json:"loraInfo,omitempty"`
}

func (r WaterMeterControllerReportResponse) String() string {
	var ptr0 any = "<nil>"
	if r.LoraInfo != nil {
		ptr0 = fmt.Sprint(*r.LoraInfo)
	}
	return fmt.Sprintf("{Valve:%v Meter:%v WaterFlowing:%v LoraInfo:%v}", r.Valve, r.Meter, r.WaterFlowing, ptr0)
}

type WaterMeterControllerAlertResponse struct {
	Valve          types.SwitchCommand `json:"valve"` // ['close','open']
	Meter          int                 `json:"meter"` // Meter reading
	WaterFlowing   bool                `json:"waterFlowing"`
	LoraInfo       *types.LoraInfo     `json:"loraInfo,omitempty"`
	StateChangedAt *types.Timestamp    `json:"stateChangedAt,omitempty"`
}

func (r WaterMeterControllerAlertResponse) String() string {
	var ptr0 any = "<nil>"
	if r.LoraInfo != nil {
		ptr0 = fmt.Sprint(*r.LoraInfo)
	}
	var ptr1 any = "<nil>"
	if r.StateChangedAt != nil {
		ptr1 = fmt.Sprint(*r.StateChangedAt)
	}
	return fmt.Sprintf("{Valve:%v Meter:%v WaterFlowing:%v LoraInfo:%v StateChangedAt:%v}", r.Valve, r.Meter, r.WaterFlowing, ptr0, ptr1)
}

func (device *WaterMeterController) ParseEvent(message controller.MqttMessage) (controller.Report, bool) {
	report, ok := device.Device.ParseEvent(message) // base impl decodes event + raw data
	if !ok {
		return report, false
	}
	report.Device = device                        // attribute the report to this concrete device
	data := report.Data.(controller.Unknown).Json // raw payload, re-typed below
	switch report.Event {
	case "WaterMeterController.getState":
		var response WaterMeterControllerGetStateResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "WaterMeterController.getValveSchedules":
		var response WaterMeterControllerGetValveSchedulesResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "WaterMeterController.setValveSchedules":
		var response WaterMeterControllerSetValveSchedulesResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "WaterMeterController.getLeakSchedules":
		var response WaterMeterControllerGetLeakSchedulesResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "WaterMeterController.setLeakSchedules":
		var response WaterMeterControllerSetLeakSchedulesResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "WaterMeterController.Report":
		var response WaterMeterControllerReportResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "WaterMeterController.Alert":
		var response WaterMeterControllerAlertResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	}
	return report, true
}
