// Code generated by scripts/gen_device_types.py; DO NOT EDIT.
package devices

import (
	"encoding/json"
	"fmt"
	"time"

	"github.com/tyandl/homelink/pkg/yolink/controller"
	"github.com/tyandl/homelink/pkg/yolink/types"
)

type WaterDepthSensor struct{ *controller.Device }

func init() {
	controller.RegisterDeviceFactory("WaterDepthSensor", func(device *controller.Device) controller.DeviceController {
		return &WaterDepthSensor{Device: device}
	})
}

type WaterDepthSensorGetStateResponseStateAlarm struct {
	HighAlarm     bool `json:"highAlarm"`     // Water depth above threshold
	LowAlarm      bool `json:"lowAlarm"`      // Water depth below threshold
	DetectorError bool `json:"detectorError"` // Probe abnormal
}

func (r WaterDepthSensorGetStateResponseStateAlarm) String() string {
	return fmt.Sprintf("{HighAlarm:%v LowAlarm:%v DetectorError:%v}", r.HighAlarm, r.LowAlarm, r.DetectorError)
}

type WaterDepthSensorGetStateResponseStateAlarmSettings struct {
	Standby  int `json:"standby"`  // Standby seconds [0-7200]
	Interval int `json:"interval"` // Alarm interval minutes [10-240]
	High     int `json:"high"`     // High threshold [0-1000] per-thousand of range
	Low      int `json:"low"`      // Low threshold [0-1000] per-thousand of range
}

func (r WaterDepthSensorGetStateResponseStateAlarmSettings) String() string {
	return fmt.Sprintf("{Standby:%v Interval:%v High:%v Low:%v}", r.Standby, r.Interval, r.High, r.Low)
}

type WaterDepthSensorGetStateResponseState struct {
	Online         bool                                               `json:"online"`
	Alarm          WaterDepthSensorGetStateResponseStateAlarm         `json:"alarm"`
	AlarmSettings  WaterDepthSensorGetStateResponseStateAlarmSettings `json:"alarmSettings"`
	Battery        types.BatteryLevel                                 `json:"battery"`        // 0-4
	WaterDepth     int                                                `json:"waterDepth"`     // Water depth percentage x10
	ReportInterval int                                                `json:"reportInterval"` // Report interval minutes [10-240]
	Version        string                                             `json:"version"`
}

func (r WaterDepthSensorGetStateResponseState) String() string {
	return fmt.Sprintf("{Online:%v Alarm:%v AlarmSettings:%v Battery:%v WaterDepth:%v ReportInterval:%v Version:%v}", r.Online, r.Alarm, r.AlarmSettings, r.Battery, r.WaterDepth, r.ReportInterval, r.Version)
}

type WaterDepthSensorGetStateResponse struct {
	State    WaterDepthSensorGetStateResponseState `json:"state"`
	ReportAt time.Time                             `json:"reportAt"`
	DeviceId string                                `json:"deviceId"`
}

func (r WaterDepthSensorGetStateResponse) String() string {
	return fmt.Sprintf("{State:%v ReportAt:%v DeviceId:%v}", r.State, r.ReportAt, r.DeviceId)
}

// GetState Get the state of Water Depth Sensor. Water depth formula: (range * (waterDepth / 1000)) / density
func (device *WaterDepthSensor) GetState() (WaterDepthSensorGetStateResponse, error) {
	var response WaterDepthSensorGetStateResponse
	err := device.Call("WaterDepthSensor.getState", nil, &response)
	return response, err
}

func (device *WaterDepthSensor) GetStateAsync() <-chan controller.AsyncResult[WaterDepthSensorGetStateResponse] {
	return controller.DecodeAsync[WaterDepthSensorGetStateResponse](device.CallAsync("WaterDepthSensor.getState", nil))
}

type WaterDepthSensorSetAttributesParamsAlarmSettings struct {
	Standby  int `json:"standby"`  // [0-7200] seconds
	Interval int `json:"interval"` // [10-240] minutes
	High     int `json:"high"`     // [0-1000]
	Low      int `json:"low"`      // [0-1000]
}

func (r WaterDepthSensorSetAttributesParamsAlarmSettings) String() string {
	return fmt.Sprintf("{Standby:%v Interval:%v High:%v Low:%v}", r.Standby, r.Interval, r.High, r.Low)
}

type WaterDepthSensorSetAttributesParams struct {
	AlarmSettings WaterDepthSensorSetAttributesParamsAlarmSettings `json:"alarmSettings"`
}

func (r WaterDepthSensorSetAttributesParams) String() string {
	return fmt.Sprintf("{AlarmSettings:%v}", r.AlarmSettings)
}

// SetAttributes Set attributes for water depth sensor
func (device *WaterDepthSensor) SetAttributes(params WaterDepthSensorSetAttributesParams) error {
	return device.Call("WaterDepthSensor.setAttributes", params, nil)
}

func (device *WaterDepthSensor) SetAttributesAsync(params WaterDepthSensorSetAttributesParams) <-chan controller.AsyncResult[any] {
	return controller.DecodeAsync[any](device.CallAsync("WaterDepthSensor.setAttributes", params))
}

type WaterDepthSensorReportResponseAlarm struct {
	HighAlarm     bool `json:"highAlarm"`     // Water depth above threshold
	LowAlarm      bool `json:"lowAlarm"`      // Water depth below threshold
	DetectorError bool `json:"detectorError"` // Probe abnormal
}

func (r WaterDepthSensorReportResponseAlarm) String() string {
	return fmt.Sprintf("{HighAlarm:%v LowAlarm:%v DetectorError:%v}", r.HighAlarm, r.LowAlarm, r.DetectorError)
}

type WaterDepthSensorReportResponseAlarmSettings struct {
	Standby  int `json:"standby"`  // Standby seconds [0-7200]
	Interval int `json:"interval"` // Alarm interval minutes [10-240]
	High     int `json:"high"`     // High threshold [0-1000] per-thousand of range
	Low      int `json:"low"`      // Low threshold [0-1000] per-thousand of range
}

func (r WaterDepthSensorReportResponseAlarmSettings) String() string {
	return fmt.Sprintf("{Standby:%v Interval:%v High:%v Low:%v}", r.Standby, r.Interval, r.High, r.Low)
}

type WaterDepthSensorReportResponse struct {
	Online         bool                                        `json:"online"`
	Alarm          WaterDepthSensorReportResponseAlarm         `json:"alarm"`
	AlarmSettings  WaterDepthSensorReportResponseAlarmSettings `json:"alarmSettings"`
	Battery        types.BatteryLevel                          `json:"battery"`        // 0-4
	WaterDepth     int                                         `json:"waterDepth"`     // Water depth percentage x10
	ReportInterval int                                         `json:"reportInterval"` // Report interval minutes [10-240]
	Version        string                                      `json:"version"`
	LoraInfo       *types.LoraInfo                             `json:"loraInfo,omitempty"`
}

func (r WaterDepthSensorReportResponse) String() string {
	var ptr0 any = "<nil>"
	if r.LoraInfo != nil {
		ptr0 = fmt.Sprint(*r.LoraInfo)
	}
	return fmt.Sprintf("{Online:%v Alarm:%v AlarmSettings:%v Battery:%v WaterDepth:%v ReportInterval:%v Version:%v LoraInfo:%v}", r.Online, r.Alarm, r.AlarmSettings, r.Battery, r.WaterDepth, r.ReportInterval, r.Version, ptr0)
}

type WaterDepthSensorAlertResponseAlarm struct {
	HighAlarm     bool `json:"highAlarm"`     // Water depth above threshold
	LowAlarm      bool `json:"lowAlarm"`      // Water depth below threshold
	DetectorError bool `json:"detectorError"` // Probe abnormal
}

func (r WaterDepthSensorAlertResponseAlarm) String() string {
	return fmt.Sprintf("{HighAlarm:%v LowAlarm:%v DetectorError:%v}", r.HighAlarm, r.LowAlarm, r.DetectorError)
}

type WaterDepthSensorAlertResponseAlarmSettings struct {
	Standby  int `json:"standby"`  // Standby seconds [0-7200]
	Interval int `json:"interval"` // Alarm interval minutes [10-240]
	High     int `json:"high"`     // High threshold [0-1000] per-thousand of range
	Low      int `json:"low"`      // Low threshold [0-1000] per-thousand of range
}

func (r WaterDepthSensorAlertResponseAlarmSettings) String() string {
	return fmt.Sprintf("{Standby:%v Interval:%v High:%v Low:%v}", r.Standby, r.Interval, r.High, r.Low)
}

type WaterDepthSensorAlertResponse struct {
	Online         bool                                       `json:"online"`
	Alarm          WaterDepthSensorAlertResponseAlarm         `json:"alarm"`
	AlarmSettings  WaterDepthSensorAlertResponseAlarmSettings `json:"alarmSettings"`
	Battery        types.BatteryLevel                         `json:"battery"`        // 0-4
	WaterDepth     int                                        `json:"waterDepth"`     // Water depth percentage x10
	ReportInterval int                                        `json:"reportInterval"` // Report interval minutes [10-240]
	Version        string                                     `json:"version"`
	LoraInfo       *types.LoraInfo                            `json:"loraInfo,omitempty"`
	StateChangedAt *types.Timestamp                           `json:"stateChangedAt,omitempty"`
}

func (r WaterDepthSensorAlertResponse) String() string {
	var ptr0 any = "<nil>"
	if r.LoraInfo != nil {
		ptr0 = fmt.Sprint(*r.LoraInfo)
	}
	var ptr1 any = "<nil>"
	if r.StateChangedAt != nil {
		ptr1 = fmt.Sprint(*r.StateChangedAt)
	}
	return fmt.Sprintf("{Online:%v Alarm:%v AlarmSettings:%v Battery:%v WaterDepth:%v ReportInterval:%v Version:%v LoraInfo:%v StateChangedAt:%v}", r.Online, r.Alarm, r.AlarmSettings, r.Battery, r.WaterDepth, r.ReportInterval, r.Version, ptr0, ptr1)
}

func (device *WaterDepthSensor) ParseEvent(message controller.MqttMessage) (controller.Report, bool) {
	report, ok := device.Device.ParseEvent(message) // base impl decodes event + raw data
	if !ok {
		return report, false
	}
	report.Device = device                        // attribute the report to this concrete device
	data := report.Data.(controller.Unknown).Json // raw payload, re-typed below
	switch report.Event {
	case "WaterDepthSensor.getState":
		var response WaterDepthSensorGetStateResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "WaterDepthSensor.Report":
		var response WaterDepthSensorReportResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	case "WaterDepthSensor.Alert":
		var response WaterDepthSensorAlertResponse
		if err := json.Unmarshal(data, &response); err == nil {
			report.Data = response
		}
	}
	return report, true
}
